objects/Account.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_Division__c</fullName>
        <inlineHelpText>For domestic sales, select “Domestic”. For international sales, select “Export”. For transfers between centers or warehouses, select “Intercompany”.</inlineHelpText>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Domestic</fullName>
                </value>
                <value>
                    <fullName>Export</fullName>
                </value>
                <value>
                    <fullName>Intercompany</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_ProcessSwitches__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This Custom Setting is for implementing bypass framework for triggers, flows, integrations and validation rules.</description>
    <fields>
        <fullName>PMC_BypassValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to bypass the validation rules</description>
        <label>Bypass Validation Rule</label>
        <type>Checkbox</type>
    </fields>
    <label>Process Switches</label>
</CustomObject>

objects/PMC_SS_AccountSalesAreaRelationship__c.object
<CustomObject>
    <description>Junction Object to relate Account and Sales Areas</description>
    <fields>
        <fullName>PMC_SS_Account__c</fullName>
        <description>Master Detail relationship between Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>AccountSalesAreRelationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SalesArea__c</fullName>
        <description>Master Detail relationship to Sales Area</description>
        <label>Sales Area</label>
        <referenceTo>PMC_SS_SalesArea__c</referenceTo>
        <relationshipName>AccountSalesAreRelationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Sales Area Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Sales Area Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PMC_SS_SalesArea__c.object
<CustomObject>
    <description>Sales Area Object</description>
    <fields>
        <fullName>PMC_CPQ_SAPSalesOrganization__c</fullName>
        <description>Field to uniquely identify SAP Sales Organization</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SAP Sales Organization</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PMC_DH_SalesArea__c</fullName>
        <formula>TEXT(PMC_SS_SalesOrganization__c)&amp;&quot; &quot; &amp;  
CASE( TEXT(PMC_SS_Division__c),
					&quot;10&quot;,&quot;Domestic&quot;,
					&quot;20&quot;,&quot;Export&quot;,
					&quot;30&quot;,&quot;Intercompany&quot;,&quot;&quot;) &amp;&quot; &quot;
					&amp; CASE( TEXT(PMC_SS_DistributionChannel__c),
					&quot;0&quot;,&quot;Common&quot;,
					&quot;00&quot;,&quot;Common&quot;,
					&quot;&quot;)</formula>
        <label>Sales Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SS_DistributionChannel__c</fullName>
        <description>Specifies the Distribution Channel</description>
        <label>Distribution Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>00</fullName>
                    <label>Common</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_Division__c</fullName>
        <description>Specifies the Division</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>10</fullName>
                    <label>Domestic</label>
                </value>
                <value>
                    <fullName>20</fullName>
                    <label>Export</label>
                </value>
                <value>
                    <fullName>30</fullName>
                    <label>Intercompany</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_SalesOrganization__c</fullName>
        <description>Specifies the Sales Organization</description>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fospar SA</fullName>
                </value>
                <value>
                    <fullName>Comp. Minera Miski Mayo</fullName>
                    <label>Minera Miski Mayo</label>
                </value>
                <value>
                    <fullName>Mos. Sulphur Partner</fullName>
                </value>
                <value>
                    <fullName>Mos Ag Innovation Sol,LLC</fullName>
                    <label>Mosaic Ag Innov Sol</label>
                </value>
                <value>
                    <fullName>Mosaic Potash Colonsay UL</fullName>
                    <label>Mosaic CA Colonsay</label>
                </value>
                <value>
                    <fullName>Mosaic CA Crop Nutrit, LP</fullName>
                    <label>Mosaic CA Crop Nutri</label>
                </value>
                <value>
                    <fullName>Mosaic Potash Esterhazy</fullName>
                    <label>Mosaic CA Esterhazy</label>
                </value>
                <value>
                    <fullName>Mosaic Canada ULC (BP)</fullName>
                    <label>Mosaic CA ULC (BP)</label>
                </value>
                <value>
                    <fullName>Mosaic Crop Nutrition LLC</fullName>
                    <label>Mosaic CN Fertilizer</label>
                </value>
                <value>
                    <fullName>Mosaic Fertilizers (HK) L</fullName>
                    <label>Mosaic Fert. (HK)</label>
                </value>
                <value>
                    <fullName>Mosaic Fertilizantes Ltd.</fullName>
                    <label>Mosaic Fert Bahamas</label>
                </value>
                <value>
                    <fullName>Mosaic Fertilizers (BJ)</fullName>
                    <label>Mosaic Fert BMF</label>
                </value>
                <value>
                    <fullName>Mosaic Fertilizantes do B</fullName>
                    <label>Mosaic Fert Brasil</label>
                </value>
                <value>
                    <fullName>Mosaic Fertilizer LLC</fullName>
                    <label>Mosaic Fertilizer</label>
                </value>
                <value>
                    <fullName>Mosaic Fertz Paraguay SRL</fullName>
                    <label>Mosaic Fert Paraguay</label>
                </value>
                <value>
                    <fullName>Mosaic Fertilizers (QHD)</fullName>
                    <label>Mosaic Fert QMF</label>
                </value>
                <value>
                    <fullName>Mosaic Fertilizers (YT)</fullName>
                    <label>Mosaic Fert YMF</label>
                </value>
                <value>
                    <fullName>Mosaic Global Sales LLC</fullName>
                    <label>Mosaic Global Sales</label>
                </value>
                <value>
                    <fullName>Mosaic India Private Ltd.</fullName>
                    <label>Mosaic India Pvt Ltd</label>
                </value>
                <value>
                    <fullName>Mosaic Potash Carlsbad In</fullName>
                    <label>Mosaic Potash Carlsb</label>
                </value>
                <value>
                    <fullName>Mosaic Potássio Mineração</fullName>
                    <label>Mosaic Potássio Mine</label>
                </value>
                <value>
                    <fullName>Tampa Port Services, LLC</fullName>
                    <label>Tampa Port Services</label>
                </value>
                <value>
                    <fullName>Mosaic Fertilizantes P&amp;K</fullName>
                    <label>Mosaic Fert P&amp;K</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Area</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Region__c</fullName>
        <description>To identify which product belongs to which region so that the product selection can be done accurately. Avoiding cross-region sales. etc,</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CPQ_SalesArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Area</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SBQQ__Account__c</field>
                <operation>equals</operation>
                <valueField>PMC_SS_AccountSalesAreaRelationship__c.PMC_SS_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_SS_AccountSalesAreaRelationship__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>Account for which this quote has been created.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__PriceBook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Price Book associated with this Quote.</description>
        <inlineHelpText>Price Book associated with this Quote.</inlineHelpText>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>PMC_CPQ_SalesArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Area</label>
        <referenceTo>PMC_SS_AccountSalesAreaRelationship__c</referenceTo>
        <relationshipLabel>CPQ Quote Lines</relationshipLabel>
        <relationshipName>PMC_CPQ_CPQQuoteLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_SalesArea__c</fullName>
        <description>The Sales Areas associated with the user from which the record type and product will be configured.</description>
        <label>Sales Area</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_SalesAreaUser</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SalesRegion__c</fullName>
        <label>Sales Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/PMC_CPQ_Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
        <isActive>false</isActive>
        <label>Argentina</label>
    </customValue>
    <customValue>
        <fullName>Paraguay</fullName>
        <isActive>false</isActive>
        <label>Paraguay</label>
    </customValue>
    <customValue>
        <fullName>Peru</fullName>
        <isActive>false</isActive>
        <label>Peru</label>
    </customValue>
    <description>This Global Value Set stores/handles values of Region</description>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

classes/PMC_CPQ_GenerateContractTest.cls
@isTest
private class PMC_CPQ_GenerateContractTest {
    @TestSetup
    static void setup() {
        List<String>lstProfileNames = New List<String>{'System Administrator','Sales User'};
        List<userRole> userRoleName= [SELECT Id FROM userRole WHERE Name = 'Service Director'];
        List<String>lstPermissionNames = New List<String>{'PMC_Administrator_Permission_Set_Group','PMC_SLS_Permission_Set_Group'};
        Map<String,Id>mapOfProfiles = PMC_TestUtilityClass.getProfiles(lstProfileNames);
        Map<String,PermissionSetGroup>mapOfPermissionGrp = PMC_TestUtilityClass.getPemissionsetGroups(lstPermissionNames);
        Integer intuserCount =0;
        User objSystemAdminUser;  
        User objSalesUser;
        List<User> lstUser = PMC_TestUtilityClass.createUser(2);
        for(User objUser : lstUser) {
            If(intuserCount==0){
                objUser.LastName = 'Admin User Test';
                objUser.ProfileId = mapOfProfiles.get('System Administrator'); 
                objUser.FederationIdentifier = objUser.Username + 'Admin';
                objUser.UserRoleId=userRoleName[0].id;
            }else if(intuserCount==1){
                objUser.LastName = 'Sales User Test PMC_CPQ_GenerateContractTest';
                objUser.ProfileId = mapOfProfiles.get('Sales User'); 
                objUser.FederationIdentifier = objUser.Username + 'Sales';
            }
            objUser.PMC_CPQ_SalesArea__c = 'Mosaic Global Sales LLC Export Common';
            objUser.PMC_CPQ_SalesRegion__c = 'Brazil';
            objUser.isActive = true;                
            objUser.MobilePhone = '1234567890';
            objUser.UserPermissionsKnowledgeUser =true;
            objUser.LanguageLocaleKey = 'en_US';
            intuserCount = intuserCount + 1;
        }            
        insert lstUser;
        objSystemAdminUser = lstUser[0];
        objSalesUser = lstUser[1];
        PMC_TestUtilityClass.assignPermissionSetGroupToUsers(new List<User>{objSystemAdminUser}, mapOfPermissionGrp.get('PMC_Administrator_Permission_Set_Group'));
        PMC_TestUtilityClass.assignPermissionSetGroupToUsers(new List<User>{objSalesUser}, mapOfPermissionGrp.get('PMC_SLS_Permission_Set_Group'));  
        
        //     User adminUser = [SELECT Id FROM User WHERE Name = 'Copado Integration' LIMIT 1];
            
        //     // Bypass validation rule using custom setting
        System.runAs(objSystemAdminUser) {
            PMC_ProcessSwitches__c bypassSetting = PMC_ProcessSwitches__c.getOrgDefaults();
            bypassSetting.PMC_BypassValidationRule__c = true;
            upsert bypassSetting;
            
            // Run remaining setup as test user to bypass validation rules
            
            Account acc = new Account (Name = 'Test Account',BillingCity ='toronto',BillingStreet='tor');
            insert acc;
            
            PMC_SS_SalesArea__c salesArea = new PMC_SS_SalesArea__c(
            Name = 'Brazil Area',
            PMC_CPQ_SAPSalesOrganization__c = '40000010',
                PMC_SS_SalesOrganization__c='Mosaic Global Sales LLC',
                PMC_SS_DistributionChannel__c = '0',
                PMC_SS_Division__c = '20'
            );
            insert salesArea; // PMC_DH_SalesArea__c = Mosaic Global Sales LLC Export

            //Create sales Area Assignment
            PMC_SS_AccountSalesAreaRelationship__c salesAreaAssignment = new PMC_SS_AccountSalesAreaRelationship__c(
            Name = 'Test Sales Area Assignment',
            PMC_SS_Account__c = acc.Id , 
            PMC_SS_SalesArea__c = salesArea.Id
            );
            insert salesAreaAssignment;
                    system.debug ('sales Area Assignment outcome : ' + salesAreaAssignment);

            Product2 product = new Product2(
            Name = 'Test Product',
            IsActive = true
            );
            insert product;
            
            PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id = product.Id,
            UnitPrice = 100,
            IsActive = true,
            UseStandardPrice = false
            );
            insert pbe;
            // Create common test data
            SBQQ__Quote__c validQuote = new SBQQ__Quote__c(
                SBQQ__Account__c = acc.Id,
                SBQQ__PriceBook__c = Test.getStandardPricebookId(),
                SBQQ__Primary__c = true,
                PMC_CPQ_SalesArea__c = salesAreaAssignment.Id,
                PMC_CPQ_Region__c = 'Brazil',
                PMC_CPQ_ContractLanguage__c = 'Portuguese',
                PMC_CPQ_ContractShippingInstructions__c = 'Test Shipping Instructions',
                PMC_CPQ_AccountManager__c = objSalesUser.Id
            );
            insert validQuote;
            
            SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c(
                SBQQ__Quote__c = validQuote.Id,
                SBQQ__Product__c = product.Id,
                SBQQ__PricebookEntryId__c = Pbe.Id,
                SBQQ__Quantity__c = 1,
                SBQQ__NetPrice__c = 100,
                PMC_CPQ_EstFreightPrice__c = 10,
                PMC_CPQ_QuoteRecordType__c = 'Domestic SA',
                PMC_CPQ_QuoteRecordSubType__c = 'B2C - Fertilizer',
                PMC_CPQ_Incoterms1__c = 'CIF'
            );
            insert quoteLine;
        }
    }
    
    // Test valid scenario - Portuguese contract
        @isTest
    static void testValidPortugueseContract() {

        User testUser = [SELECT Id, Name FROM User Where LastName='Sales User Test PMC_CPQ_GenerateContractTest' WITH SECURITY_ENFORCED LIMIT 1];
        SBQQ__Quote__c quote = [SELECT Id,Name,PMC_CLM_Region__c,PMC_CPQ_ContractLanguage__c FROM SBQQ__Quote__c LIMIT 1];
        System.runAs(testUser) {
            Map<String,String> orgToAid = new Map<String,String>{
                'devp1' => '98018',
                'qa' => '116096',
                'uat' => '102552'
            };
                String expectedAid = EnvironmentChecker.getValueBySandboxAlias('31298',orgToAid);
            String expectedParam = 'aid='+expectedAid;
            Test.startTest();
            quote.PMC_CPQ_Region__c = 'Brazil';
            quote.PMC_CPQ_ContractLanguage__c = 'Portuguese';
            update quote;
            String result = PMC_CPQ_GenerateContract.generateContract(quote.Id);
            Test.stopTest();
            System.assert(result.contains(expectedParam), 'Should generate Portuguese contract URL' +expectedParam+'\nActual result:'+ result);
        }
    }
    // Test valid scenario - Spanish contract
    @isTest
    static void testValidSpanishContract() {
        User testUser = [SELECT Id, Name FROM User Where LastName='Admin User Test' WITH SECURITY_ENFORCED LIMIT 1];
        SBQQ__Quote__c quote = [SELECT Id,Name,PMC_CLM_Region__c,PMC_CPQ_ContractLanguage__c FROM SBQQ__Quote__c LIMIT 1];
        System.runAs(testUser) {
             Map<String,String> orgToAid = new Map<String,String>{
                'devp1' => '98018',
                'qa' => '116096',
                'uat' => '102552'
            };
                String expectedAid = EnvironmentChecker.getValueBySandboxAlias('31298',orgToAid);
            String expectedParam = 'aid='+expectedAid;
            quote.PMC_CPQ_Region__c = 'Brazil';
            quote.PMC_CPQ_ContractLanguage__c = 'Spanish';
            update quote;
            Test.startTest();
            String result = PMC_CPQ_GenerateContract.generateContract(quote.Id);
            Test.stopTest();
            System.assert(result.contains(expectedParam), 'Should generate Spanish contract URL' +expectedParam+'\nActual result:'+ result);
        }
    }
    
    // Test missing shipping instructions
    @isTest
    static void testMissingShippingInstructions() {
        SBQQ__Quote__c quote = [SELECT Id,PMC_CPQ_ContractShippingInstructions__c FROM SBQQ__Quote__c LIMIT 1];
        quote.PMC_CPQ_ContractShippingInstructions__c = null;
        update quote;
        
        Test.startTest();
        try {
            PMC_CPQ_GenerateContract.generateContract(quote.Id);
            System.assert(false, 'Expected exception not thrown');
        } catch (CustomException e) {
            System.assertEquals('Shipping Instructions field is empty. Please fill it before generating the contract.', e.getMessage());
        }
        Test.stopTest();
    }
    
    // Test invalid region
    @isTest
    static void testInvalidRegion() {
        PMC_SS_SalesArea__c salesArea = [SELECT Id,PMC_SS_Division__c,PMC_SS_SalesOrganization__c,PMC_CPQ_SAPSalesOrganization__c FROM PMC_SS_SalesArea__c LIMIT 1];
        salesArea.PMC_CPQ_SAPSalesOrganization__c = '123';
        salesArea.PMC_SS_SalesOrganization__c='Mosaic Global Sales LLC';
        salesArea.PMC_SS_Division__c = '20';
        update salesArea;
        
        Test.startTest();
         try {
            PMC_CPQ_GenerateContract.generateContract([SELECT Id FROM SBQQ__Quote__c LIMIT 1].Id);
            System.assert(false, 'Expected exception not thrown');
         } 
        catch (CustomException e) {
             System.assertEquals('Contract generation is only available for Brazil region.', e.getMessage());
         }
        Test.stopTest();
    }
    
    // Test invalid language
    @isTest
    static void testInvalidLanguage() {
        SBQQ__Quote__c quote = [SELECT Id,Name,PMC_CPQ_Region__c,PMC_CPQ_ContractLanguage__c FROM SBQQ__Quote__c LIMIT 1];
        quote.PMC_CPQ_Region__c = 'Brazil';
        quote.PMC_CPQ_ContractLanguage__c = 'English';
        
        Test.startTest();
        try {
            update quote;
            PMC_CPQ_GenerateContract.generateContract(quote.Id);
            System.assert(false, 'Expected exception not thrown');
        } 
        catch (DMLException e) {
            System.assert(e.getMessage().contains('INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST, bad value for restricted picklist field: English: [PMC_CPQ_ContractLanguage__c]'));
        } 
         /* catch (AuraHandledException e) {
             System.assertEquals('Invalid language for Brazil region.', e.getMessage());
         }*/
        Test.stopTest();
    }
    
    // Test quote not found
    @isTest
    static void testQuoteNotFound() {
        try {
            Test.startTest();
            PMC_CPQ_GenerateContract.generateContract('invalidId');
            Test.stopTest();
            System.assert(false, 'Expected exception not thrown');
        } catch (CustomException e) {
            System.assertEquals('Quote not found or access denied.', e.getMessage());
        }
    }
}