objects/Account.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_RegionalManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>States the Regional Manager</description>
        <label>Regional Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SAPCustomerNumber__c</fullName>
        <description>The SAP Generated Customer Number</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SAP Customer Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>PMC_SS_Customer</fullName>
        <active>true</active>
        <description>This record type will be used to create Account records of Customer record types</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CartItem.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_DeliveryMode__c</fullName>
        <label>Delivery Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Barge</fullName>
                </value>
                <value>
                    <fullName>Truck</fullName>
                </value>
                <value>
                    <fullName>Rail</fullName>
                </value>
                <value>
                    <fullName>Vessel</fullName>
                </value>
                <value>
                    <fullName>Inventory Transfer</fullName>
                </value>
                <value>
                    <fullName>Container</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_Incoterms__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Incoterms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_PlantShipFrom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship From</label>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Cart Items (Ship From)</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_DH_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_LatestQuote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts (Latest Quote)</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_RegionalManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Regional Manager of the Lead</description>
        <label>Regional Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_CPQ_ProductLocation__c.object
<CustomObject>
    <description>This object is created as a part of  story to capture product and location data.</description>
    <label>Product Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product.This is as per the  US GCPM 1064</description>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <infoMessage>Select Product Location Columns Link to add appropriate Locations</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>CPQ Quotes</relationshipLabel>
        <relationshipName>CPQ_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Type__c</fullName>
        <description>Indicates the type of quote.</description>
        <inlineHelpText>Indicates the type of quote.(New,Amend,Renew)</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                    <default>true</default>
                    <label>Quote</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Re-Quote</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product.</description>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SBQQ__Product__c</field>
                <operation>equals</operation>
                <valueField>PMC_CPQ_ProductLocation__c.PMC_CPQ_ProductName__c</valueField>
            </filterItems>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SBQQ__Product__c</field>
                <operation>equals</operation>
                <valueField>PMC_CPQ_ProductLocation__c.PMC_CPQ_ProductName__c</valueField>
            </filterItems>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract that governs this subscription.</description>
        <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this subscription.</description>
        <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_RegionalManager__c</fullName>
        <description>Field used to store the Regional Manager of the user</description>
        <label>Regional Manager</label>
        <relationshipName>Regional_Managers</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PMC_DH_ContractUtilTest.cls
/**
* @description : Test class for PMC_DH_ContractUtil
* @author      : Rohan Undale
* @userStory   : GDASF-142 & GDASF-8927 
* @last modified by Rohan Undale
* @last modified on 06-29-2023
**/
@isTest
public with sharing class PMC_DH_ContractUtilTest {
    /**
* @description Method for getting test data from PMC_DH_TestDataFactoryClass
* @param: none
* @return: void
* @author Rohan
*/
    @testSetup  static void setup()
    {
        
       //Account acc=PMC_DH_TestDataFactoryClass.createParentTestAccount();
         Account acc = new Account();
        acc.Name='Parent Test Account';
        acc.AccountNumber='Test002';
        acc.PMC_SS_RegionalManager__c = UserInfo.getUserId();
        acc.PMC_SS_SAPCustomerNumber__c = '12346785';
        acc.Type = 'Sold-to';
         acc.BillingCountry='United States';
        acc.CurrencyIsoCode='USD';
        acc.BillingState='California';
        acc.BillingStreet='fsvc';
        acc.BillingCity='San Francisco';
        acc.BillingPostalCode= '94001';
        Id recordTypeId = Schema.SObjectType.Account.getrecordtypeinfosbydevelopername().get('PMC_SS_Customer').getRecordTypeId();
        acc.RecordTypeId=recordTypeId;
        insert acc;
        
        Profile profile = [SELECT Id FROM Profile WHERE Name =: PMC_DH_ConstantClass.PROFILE_NAME LIMIT 1];
        PMC_DH_TestDataFactoryClass.createTestUser(acc.Id,profile.Id);
        
        User user=[SELECT id FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
        
        Id lstPermSet2=[select id from PermissionSet where Name ='PMC_DH_CPQ_PermissionSetLicense'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(user.Id,lstPermSet2);
        Id lstPermSet=[select id from PermissionSet where Name ='SteelBrickDHCPQPartnerUser'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(user.Id,lstPermSet);
        Id lstPermSet1=[select id from PermissionSet where Name ='PMC_DH_SuperBuyer'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(user.Id,lstPermSet1);
        Id lstPermSet3=[select id from PermissionSet where Name ='PMC_DH_AccountCRE'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(user.Id,lstPermSet3);
        
        WebStore webStore=PMC_DH_TestDataFactoryClass.createTestWebStore();
        system.runAs(user){
            WebCart cartObj=PMC_DH_TestDataFactoryClass.buildCart(webStore.Id,acc.Id);
            insert cartObj;
            Product2 prod = PMC_DH_TestDataFactoryClass.createProduct();
            insert prod;
            CartDeliveryGroup testCartDeliveryGroup=PMC_DH_TestDataFactoryClass.buildCartDeliveryGroup(cartObj.id);
            insert testCartDeliveryGroup;
            CartItem cartItem=PMC_DH_TestDataFactoryClass.buildCartItem(cartObj.id, prod.id,testCartDeliveryGroup.Id);
            insert cartItem;
            Test.startTest();
            Account shipToAcc=PMC_DH_TestDataFactoryClass.createShipToTestAccount(acc);
            Schema.Location loc = PMC_DH_TestDataFactoryClass.createLocation();
            PMC_CPQ_ProductLocation__c prodLocation = PMC_DH_TestDataFactoryClass.createProductLocation(prod, loc);
            PMC_DH_TestDataFactoryClass.CartItemObject objCartItem=new PMC_DH_TestDataFactoryClass.CartItemObject();
            objCartItem.strCartId=cartObj.id;
            objCartItem.strProductId=prod.id;
            objCartItem.strDeliveryGroupId=testCartDeliveryGroup.id;
            objCartItem.strShipToAccId=shipToAcc.id;
            objCartItem.strShipFromId=prodLocation.id;
            CartItem cartItem1=PMC_DH_TestDataFactoryClass.buildCartItem1(objCartItem); 
            insert cartItem1;
            PMC_DH_TestDataFactoryClass.createSubscription(objCartItem);
            Test.stopTest();
        }
    }
    
    /**
* @description Test Method for addCartItems
* @param: none
* @return: void
* @author Rohan
*/  
    @isTest
    public static void addCartItemsTest()
    {
        Test.startTest();
        User user=[SELECT id FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
        String strCartId=[SELECT id FROM WebCart WHERE Name='Test Web Cart'][0].id;
        
        CartItem cartItems =[select id,Product2.Name,Product2Id,Product2.StockKeepingUnit, PMC_DH_ShipTo__c, PMC_DH_PlantShipFrom__c, PMC_DH_DeliveryMode__c, PMC_DH_Incoterms__c, Type, CartDeliveryGroupId, Quantity from CartItem where cartid=:strCartId and Name='Test Cart Item1'];
        List<PMC_DH_RequestToDeliverWrapper.CartItemWrapper> lstCartItemWrap = new List<PMC_DH_RequestToDeliverWrapper.CartItemWrapper>();
        PMC_DH_RequestToDeliverWrapper.CartItemWrapper cartItemWrap = new PMC_DH_RequestToDeliverWrapper.CartItemWrapper();
        cartItemWrap.strCartItemId = cartItems.id;
        cartItemWrap.intQuantity = integer.valueOf(PMC_DH_ConstantClass.PRODUCT_QUANTITY);
        cartItemWrap.strShipTo = cartItems.PMC_DH_ShipTo__c;
        cartItemWrap.strIncoterms =cartItems.PMC_DH_Incoterms__c;
        cartItemWrap.strDeliveryMode =cartItems.PMC_DH_DeliveryMode__c;
        cartItemWrap.strShipFrom =cartItems.PMC_DH_PlantShipFrom__c;
        cartItemWrap.strSource ='RTD';
        lstCartItemWrap.add(cartItemWrap);
        
        List<PMC_DH_RequestToDeliverWrapper.CartWrapper> lstCartWrapper = new List<PMC_DH_RequestToDeliverWrapper.CartWrapper>();
        PMC_DH_RequestToDeliverWrapper.CartWrapper objCartWrapper = new PMC_DH_RequestToDeliverWrapper.CartWrapper();
        objCartWrapper.lstCartItems = lstCartItemWrap;
        objCartWrapper.strProductId = cartItems.Product2Id;
        objCartWrapper.strProductName = cartItems.Product2.Name;
        lstCartWrapper.add(objCartWrapper);
        system.runAs(user){
            PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper result=PMC_DH_ContractUtil.addCartItems(strCartId, lstCartWrapper);
            PMC_DH_ContractUtil.isNumericOrDecimal('20.00');
            system.assert(result!=null,'success');
        }
        Test.stopTest();
    }
    
    /**
* @description Test Method for addCartItems
* @param: none
* @return: void
* @author Rohan
*/  
    @isTest
    public static void addCartItemsExceptionTest()
    {
        Test.startTest();
        User user=[SELECT id FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
        String strCartId=[SELECT id FROM WebCart WHERE Name='Test Web Cart'][0].id;
        
        CartItem cartItems =[select id,Product2.Name,Product2Id,Product2.StockKeepingUnit, PMC_DH_ShipTo__c, PMC_DH_PlantShipFrom__c, PMC_DH_DeliveryMode__c, PMC_DH_Incoterms__c, Type, CartDeliveryGroupId, Quantity from CartItem where cartid=:strCartId and Name='Test Cart Item1'];
        List<PMC_DH_RequestToDeliverWrapper.CartItemWrapper> lstCartItemWrap = new List<PMC_DH_RequestToDeliverWrapper.CartItemWrapper>();
        PMC_DH_RequestToDeliverWrapper.CartItemWrapper cartItemWrap = new PMC_DH_RequestToDeliverWrapper.CartItemWrapper();
        cartItemWrap.strCartItemId = cartItems.id;
        cartItemWrap.intQuantity = integer.valueOf(PMC_DH_ConstantClass.PRODUCT_QUANTITY);
        cartItemWrap.strShipTo = cartItems.PMC_DH_ShipTo__c;
        cartItemWrap.strIncoterms =cartItems.PMC_DH_Incoterms__c;
        cartItemWrap.strDeliveryMode =cartItems.PMC_DH_DeliveryMode__c;
        cartItemWrap.strShipFrom =cartItems.PMC_DH_PlantShipFrom__c;
        cartItemWrap.strSource ='RTD';
        lstCartItemWrap.add(cartItemWrap);
        
        List<PMC_DH_RequestToDeliverWrapper.CartWrapper> lstCartWrapper = new List<PMC_DH_RequestToDeliverWrapper.CartWrapper>();
        PMC_DH_RequestToDeliverWrapper.CartWrapper objCartWrapper = new PMC_DH_RequestToDeliverWrapper.CartWrapper();
        objCartWrapper.lstCartItems = lstCartItemWrap;
        objCartWrapper.strProductId = cartItems.Product2Id;
        objCartWrapper.strProductName = cartItems.Product2.Name;
        lstCartWrapper.add(objCartWrapper);
        system.runAs(user){
            Boolean exceptionOccurred;
            PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper result=new PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper();
            try{
                PMC_DH_DigitalHubB2BUtils.throwTestException = true;
                result=PMC_DH_ContractUtil.addCartItems(strCartId, lstCartWrapper);
            }catch(Exception ex){
                exceptionOccurred = true;
            }
            System.assertEquals(result.strStatusCode,'100','success');
        }
        Test.stopTest();
        
    }
    
    /**
* @description Test Method for contract summary
* @param: none
* @return: void
* @author Ajeet 
*/  
    @isTest
    public static void getContractSummaryTest(){
        User usr=[SELECT id FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
        Account acc = new Account();
        acc.Name='Parent Test Account222';
        acc.AccountNumber='Test002';
        acc.PMC_SS_RegionalManager__c = UserInfo.getUserId();
        acc.PMC_SS_SAPCustomerNumber__c = '1295222';
        acc.Type = 'Sold-to';
         acc.BillingCountry='United States';
        acc.CurrencyIsoCode='USD';
        acc.BillingState='California';
        acc.BillingStreet='fsvc';
        acc.BillingCity='San Francisco';
        acc.BillingPostalCode= '94001';
        Id recordTypeId = Schema.SObjectType.Account.getrecordtypeinfosbydevelopername().get('PMC_SS_Customer').getRecordTypeId();
        acc.RecordTypeId=recordTypeId;
        insert acc;
        acc.PMC_SS_SAPCustomerNumber__c='1234224';
        update acc;
        Contact con = PMC_DH_TestDataFactoryClass.createContact(acc.Id);
           
            Opportunity opp = PMC_DH_TestDataFactoryClass.createOpportunity(acc);
            SBQQ__Quote__c quot = PMC_DH_TestDataFactoryClass.createQuote(acc,con.Id,opp);
            Product2 prod1 = [Select id from Product2 where StockKeepingUnit='1234' limit 1];
            SBQQ__QuoteLine__c testQuoteLine = PMC_DH_TestDataFactoryClass.creatQuoteLine(quot,prod1);
            Test.startTest();
            Contract cont1 = PMC_DH_TestDataFactoryClass.createContract(quot.Id,acc.Id);
            cont1.Status='Activated';
            SBQQ__Subscription__c sub1 = [Select Id, SBQQ__Contract__c from SBQQ__Subscription__c Limit 1];
            sub1.SBQQ__Contract__c = cont1.Id;
            sub1.SBQQ__QuoteLine__c = testQuoteLine.Id;
            update sub1;
            update cont1;
            Test.stopTest();
            System.runAs(usr){
               // PMC_DH_RequestToDeliverWrapper.ContractSummaryWrapper contResult = PMC_DH_ContractUtil.getContractSummary(cont1.Id);
               
            }
    }

       /**
* @description Test Method for contract summary for amendment
* @param: none
* @return: void
*/  
@isTest
public static void getContractSummaryTest2(){
    User usr=[SELECT id FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
     Account acc = new Account();
        acc.Name='Parent Test Accounts';
        acc.AccountNumber='Test002';
        acc.PMC_SS_RegionalManager__c = UserInfo.getUserId();
        acc.PMC_SS_SAPCustomerNumber__c = '12346785s';
        acc.Type = 'Sold-to';
         acc.BillingCountry='United States';
        acc.CurrencyIsoCode='USD';
        acc.BillingState='California';
        acc.BillingStreet='fsvc';
        acc.BillingCity='San Francisco';
        acc.BillingPostalCode= '94001';
        Id recordTypeId = Schema.SObjectType.Account.getrecordtypeinfosbydevelopername().get('PMC_SS_Customer').getRecordTypeId();
        acc.RecordTypeId=recordTypeId;
        insert acc;
    acc.PMC_SS_SAPCustomerNumber__c='123434322';
    update acc;
    Contact con = PMC_DH_TestDataFactoryClass.createContact(acc.Id);
       
        Opportunity opp = PMC_DH_TestDataFactoryClass.createOpportunity(acc);
        SBQQ__Quote__c quot = PMC_DH_TestDataFactoryClass.createQuote(acc,con.Id,opp);
        quot.SBQQ__Type__c  = 'Amendment';
        update quot;

        Product2 prod1 = [Select id from Product2 where StockKeepingUnit='1234' limit 1];
        SBQQ__QuoteLine__c testQuoteLine = PMC_DH_TestDataFactoryClass.creatQuoteLine(quot,prod1);
        Test.startTest();
        Contract cont1 = PMC_DH_TestDataFactoryClass.createContract(quot.Id,acc.Id);
        cont1.PMC_CPQ_LatestQuote__c=quot.Id;
        cont1.Status='Activated';
        SBQQ__Subscription__c sub1 = [Select Id, SBQQ__Contract__c from SBQQ__Subscription__c Limit 1];
        sub1.SBQQ__Contract__c = cont1.Id;
        sub1.SBQQ__QuoteLine__c = testQuoteLine.Id;
        update sub1;
        update cont1;
        Test.stopTest();
        System.runAs(usr){
           // PMC_DH_RequestToDeliverWrapper.ContractSummaryWrapper contResult = PMC_DH_ContractUtil.getContractSummary(cont1.Id);
           
        }
}



    

}