objects/Account.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_AccountExternalID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Account External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PMC_SS_SAPCustomerNumber__c</fullName>
        <description>The SAP Generated Customer Number</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SAP Customer Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_ContractType__c</fullName>
        <description>This field will be used to indicate the Contract Type wrt to the Mode to Transportation (Rail, Truck, Barge) and FPD/Priced/CCC</description>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Priced Contract Barge</fullName>
                </value>
                <value>
                    <fullName>Priced Contract Truck</fullName>
                </value>
                <value>
                    <fullName>Priced Contract Rail</fullName>
                </value>
                <value>
                    <fullName>FPD Contract Barge</fullName>
                </value>
                <value>
                    <fullName>FPD Contract Rail</fullName>
                </value>
                <value>
                    <fullName>FPD Contract Truck</fullName>
                </value>
                <value>
                    <fullName>CCC Contract Truck</fullName>
                </value>
                <value>
                    <fullName>Third Party Delivery</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_SAPOrderNumber__c</fullName>
        <description>This field captures the order number in SAP.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Reference Order Number in SAP.</inlineHelpText>
        <label>SAP Order Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_ContractType__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>CCC</fullName>
                </value>
                <value>
                    <fullName>FPD</fullName>
                </value>
                <value>
                    <fullName>FPD Ex-Space</fullName>
                </value>
                <value>
                    <fullName>Priced</fullName>
                </value>
                <value>
                    <fullName>Priced Ex-Space</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contract of the subscription that is created from this order product.</description>
        <inlineHelpText>The contract of the subscription that is created from this order product.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>OrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote line where this order product is created from.</description>
        <inlineHelpText>The quote line where this order product is created from.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>OrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subscription created from this order product</description>
        <inlineHelpText>Subscription created from this order product</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>SubscriptionOrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_SAPProductCode__c</fullName>
        <description>This field captures the product code in SAP system for the product.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Product code in SAP system.</inlineHelpText>
        <label>SAP Product Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>PMC_CPQ_Brazil</fullName>
        <active>true</active>
        <description>This Record Type was created as a part of story to have different functionalities for different Record Types</description>
        <label>Brazil</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CPQ_ContractType__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Annual</fullName>
                    <isActive>false</isActive>
                    <label>Annual</label>
                </value>
                <value>
                    <fullName>CCC</fullName>
                </value>
                <value>
                    <fullName>FPD</fullName>
                </value>
                <value>
                    <fullName>FPD Ex-Space</fullName>
                    <isActive>false</isActive>
                    <label>FPD Ex-Space</label>
                </value>
                <value>
                    <fullName>Priced</fullName>
                </value>
                <value>
                    <fullName>Priced Ex-Space</fullName>
                    <isActive>false</isActive>
                    <label>Priced Ex-Space</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_QuoteRecordType__c</fullName>
        <label>Quote Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Domestic NA</fullName>
                </value>
                <value>
                    <fullName>Domestic BR</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>International Distribution</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>PMC_CPQ_ContractType__c</fullName>
        <description>This field is created  to check the contract type associated to the SBQQ Quote line item.</description>
        <inlineHelpText>This field captures the Contract Type</inlineHelpText>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PMC_CPQ_QuoteRecordType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CCC</fullName>
                </value>
                <value>
                    <fullName>FPD</fullName>
                </value>
                <value>
                    <fullName>Priced</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                    <isActive>false</isActive>
                    <label>Annual</label>
                </value>
                <value>
                    <fullName>FPD Ex-Space</fullName>
                    <isActive>false</isActive>
                    <label>FPD Ex-Space</label>
                </value>
                <value>
                    <fullName>Priced Ex-Space</fullName>
                    <isActive>false</isActive>
                    <label>Priced Ex-Space</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_QuoteRecordType__c</fullName>
        <description>This picklist will hold the record type of Quote and will be used as a controlling field for many other picklist fields.</description>
        <label>Quote Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Domestic NA</fullName>
                </value>
                <value>
                    <fullName>Domestic SA</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>International Distribution</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>PMC_CPQ_ContractType__c</fullName>
        <description>Twin Field to copy over QLI data</description>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CCC</fullName>
                </value>
                <value>
                    <fullName>FPD</fullName>
                </value>
                <value>
                    <fullName>Priced</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                    <isActive>false</isActive>
                    <label>Annual</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_QuoteRecordType__c</fullName>
        <label>Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Domestic NA</fullName>
                </value>
                <value>
                    <fullName>Domestic SA</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>International Distribution</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this subscription.</description>
        <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PMC_CPQ_FPDMassUpdateControllerTest.cls
/*
* This class is the test class for PMC_CPQ_FPDMassUpdateController.
* @author Ridhu Varshini M
* @storynumber GDASF-12110
*/
@isTest(seeAllData=false)
public with sharing class PMC_CPQ_FPDMassUpdateControllerTest {
    
    /*
* This Method will be used to setup the data for the test class execution.
*/    
    @TestSetup
    private static void testSetup(){
        List<Order> lstOrders = PMC_CPQ_OrderIntegrationTest.createOrders(1);
        User objU = [select Id from User where LastName = 'System Administrator Test' LIMIT 1 ];
        List<String>lstPermissionNames = New List<String>{'PMC_SLS_Permission_Set_Group'};
        User objUserAM = PMC_CPQ_CPIRemoteCalloutUtilityTest.createCPQTestUser('Sales User',lstPermissionNames);
        System.runAs(objU){ 
        List<Opportunity> lstOpty = PMC_TestUtilityClass.createOpportunity(1,'Master');
        List<Account> lstAcct = [select Id,PMC_SS_AccountExternalID__c,PMC_SS_SAPCustomerNumber__c from Account where Id =: lstOpty[0].AccountId];
        lstAcct[0].PMC_SS_AccountExternalID__c = '2378651345';
        lstAcct[0].PMC_SS_SAPCustomerNumber__c = '2378651345';
        update lstAcct;
        List<Contact> lstCont = PMC_TestUtilityClass.createContact(1,'Master');
        List<Product2> lstProduct = PMC_TestUtilityClass.createProduct(1,'PMC_CPQ_Brazil');
        lstProduct[0].PMC_CPQ_SAPProductCode__c = '';
        update lstProduct;
        List<SBQQ__Quote__c> lstQuotes = PMC_TestUtilityClass.createCPQQuotes(1,lstOpty , lstCont);
        SBQQ__QuoteLine__c objQL1 = new SBQQ__QuoteLine__c(SBQQ__Quote__c = lstQuotes.get(0).Id,  SBQQ__Product__c = lstProduct.get(0).Id, PMC_CPQ_QuoteRecordType__c = 'Domestic NA', PMC_CPQ_ContractType__c = 'FPD');
        insert objQL1;
        lstOrders[0].PMC_CPQ_SAPOrderNumber__c = '30008758';
        lstOrders[0].OwnerId = objUserAM.Id;
        update lstOrders;
        List<Contract> lstContract = PMC_TestUtilityClass.createContract(lstAcct,lstOpty);
        SBQQ__Subscription__c objSub = new SBQQ__Subscription__c();
        objSub.SBQQ__Contract__c = lstContract[0].Id;
        objSub.SBQQ__Account__c = lstAcct[0].Id;
        objSub.SBQQ__Quantity__c = 1;
        objSub.SBQQ__QuoteLine__c = objQL1.Id;
        insert objSub;
        OrderItem objOP = new OrderItem(OrderId = lstOrders[0].Id, SBQQ__QuoteLine__c = objQL1.Id,SBQQ__Subscription__c =objSub.Id, Product2Id = lstProduct.get(0).Id, Quantity=1, ListPrice=100, PMC_CPQ_ListPrice__c = 100, UnitPrice = 100,PMC_CPQ_ContractType__c = 'FPD', PMC_CPQ_ShipTo__c = lstOpty.get(0).AccountId);
        insert objOP;
        }
    }
    /* 
* This method will be used to cover the getOPDetails and getDefaultOrderLines methods of the class PMC_CPQ_FPDMassUpdateController.
*/     
    @isTest
    public static void testFPD() {
        Test.startTest();
        Opportunity objOp = [select Id, AccountId from Opportunity LIMIT 1];
        Order objOrder = [select Id,PMC_CPQ_SAPOrderNumber__c, OwnerId from Order LIMIT 1];
        User objUser = [select Id from User where Id =: objOrder.OwnerId LIMIT 1];
        Product2 objProd = [select Id from Product2];
        OrderItem objOL = [select Id,PMC_CPQ_ShipTo__c from OrderItem LIMIT 1];
        system.runAs(objUser){
            PMC_CPQ_FPDMassUpdateController.GetOPDetailsParams paramsWrap = new PMC_CPQ_FPDMassUpdateController.GetOPDetailsParams();
            paramsWrap.acctId = objOp.AccountId;
            paramsWrap.userId = objUser.Id;
            paramsWrap.prodId = objProd.Id;
            paramsWrap.shipId = objOL.PMC_CPQ_ShipTo__c;
            paramsWrap.ordId = objOrder.Id;
            String jsonString = JSON.serialize(paramsWrap);
            
            PMC_CPQ_FPDMassUpdateController.GetOPDetailsParams paramsWrap1 = new PMC_CPQ_FPDMassUpdateController.GetOPDetailsParams();
            paramsWrap1.userId = objUser.Id;
            String jsonString1 = JSON.serialize(paramsWrap1);
            
            PMC_CPQ_FPDMassUpdateController.GetOPDetailsParams paramsWrap2 = new PMC_CPQ_FPDMassUpdateController.GetOPDetailsParams();
            paramsWrap2.acctId = objOp.AccountId;
            String jsonString2 = JSON.serialize(paramsWrap2);
            
            PMC_CPQ_FPDMassUpdateController.GetOPDetailsParams paramsWrap3 = new PMC_CPQ_FPDMassUpdateController.GetOPDetailsParams();
            String jsonString3 = JSON.serialize(paramsWrap3);
            
            PMC_CPQ_FPDMassUpdateController.GetOPDetailsParams paramsWrap4 = new PMC_CPQ_FPDMassUpdateController.GetOPDetailsParams();
            paramsWrap4.ordId = objOrder.Id;
            String jsonString4 = JSON.serialize(paramsWrap4);
            String result7;
            try{
            PMC_CPQ_FPDMassUpdateController.GetOPDetailsParams paramsWrap5 = new PMC_CPQ_FPDMassUpdateController.GetOPDetailsParams();
            paramsWrap5.ordId = objOrder.PMC_CPQ_SAPOrderNumber__c;
            String jsonString5 = JSON.serialize(paramsWrap5);
            result7 = PMC_CPQ_FPDMassUpdateController.getOPDetails(jsonString5);
            }
            catch(Exception e){
                PMC_ErrorLogClass.processException(e);
            }
            
            String result1 = PMC_CPQ_FPDMassUpdateController.getOPDetails(jsonString);
            String result2 = PMC_CPQ_FPDMassUpdateController.getOPDetails(jsonString1);
            String result3 = PMC_CPQ_FPDMassUpdateController.getOPDetails(jsonString2);
            String result4 = PMC_CPQ_FPDMassUpdateController.getOPDetails(jsonString3);
            String result5 = PMC_CPQ_FPDMassUpdateController.getDefaultOrderLines();
            String result6 = PMC_CPQ_FPDMassUpdateController.getOPDetails(jsonString4);
            Assert.isNotNull(result1,'Result should not be null');
            Assert.isNotNull(result2,'Result should not be null');
            Assert.isNotNull(result3,'Result should not be null');
            Assert.isNotNull(result4,'Result should not be null');
            Assert.isNotNull(result5,'Result should not be null');
            Assert.isNotNull(result6,'Result should not be null');
            Assert.isNull(result7,'Result should be null');
        }
        Test.stopTest();
    }
}