objects/Account.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_SAPCustomerNumber__c</fullName>
        <description>The SAP Generated Customer Number</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SAP Customer Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/BuyerAccount.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_isBuyerProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Buyer Processed</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CommerceEntitlementPolicy.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_SAPCustomerNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SAP Customer Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CommerceEntitlementProduct.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_SoldTo_SKU__c</fullName>
        <description>This will have Sold to Account Id along with SKU</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Sold To SKU</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PMC_CPQ_ProductSalesArea__c.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>ProductSalesAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Sales_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Area</label>
        <referenceTo>PMC_SS_SalesArea__c</referenceTo>
        <relationshipName>ProductSalesAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Sales Area</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Product Sales Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Sales Areas</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PMC_DH_CommerceEntitlementSalesArea__c.object
<CustomObject>
    <description>This Object is used by Mosaic Direct to associate customer specific entitlement products to their corresponding sales area.</description>
    <fields>
        <fullName>PMC_DH_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AccountEntitlementProdSalesAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_DH_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>AccountEntitlementProdSalesAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commerce Entitlement Sales Area</label>
    <nameField>
        <displayFormat>CES-{0000000000}</displayFormat>
        <label>CommerceEntSalesArea</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commerce Entitlement Sales Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_ProductSalesArea__c</fullName>
        <label>Product Sales Area</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_SalesAreaUser</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PMC_DH_NewAccountOnboardingBatchUtil.cls
/**
* @description       : Batch Util Class for New Account Onboarding
* @created on        : 12-24-2023
* @author            : Rohan Undale
* @last modified on  : 
* @last modified by  : 
**/
public with sharing class PMC_DH_NewAccountOnboardingBatchUtil {
    private static final String ENTITLEMENTPOLICY = 'Entitlement Policy';
    private static final String DELIMITER = '-';
    /**
    * @description create Commerce Entitlement SalesArea and Commerce Entitlement Product 
    * @author Mosaic Direct | Dev Team | 12-03-2023 
    * @param strCombinedAccIdSalesAreaId
    * @param lstProductSalesArea
    * @param setAccIdProductId 
    * @return List<CommerceEntitlementProduct>
    **/
    public static List<CommerceEntitlementProduct> createCommerceEntitlementSalesArea(String strCombinedAccIdSalesAreaId, List<PMC_CPQ_ProductSalesArea__c> lstProductSalesArea, Set<String> setAccIdProductId){
        String accId = strCombinedAccIdSalesAreaId.split(DELIMITER)[0];
        String salesAreaId = strCombinedAccIdSalesAreaId.split(DELIMITER)[1];
        List<CommerceEntitlementProduct> lstCommerceEntitlementProduct = new List<CommerceEntitlementProduct>();
        for(PMC_CPQ_ProductSalesArea__c psa : lstProductSalesArea){
            if(salesAreaId == psa.PMC_CPQ_Sales_Area__c  && !setAccIdProductId.contains(accId+''+psa.PMC_CPQ_Product__c)){
                CommerceEntitlementProduct cep = new CommerceEntitlementProduct();
                cep.PolicyId = PMC_DH_NewAccountOnboardingBatch.mapAccountIdPolicyId.get(accId);
                cep.ProductId = psa.PMC_CPQ_Product__c;
                cep.PMC_DH_SoldTo_SKU__c =  PMC_DH_NewAccountOnboardingBatch.mapAccSFNumber.get(accId) + DELIMITER +  psa.PMC_CPQ_Product__r.StockKeepingUnit;
                lstCommerceEntitlementProduct.add(cep);
                setAccIdProductId.add(accId+''+psa.PMC_CPQ_Product__c);
                //System.debug('==PMC_DH_SoldTo_SKU__c=='+cep.PMC_DH_SoldTo_SKU__c);
            }
        }

        return lstCommerceEntitlementProduct;
    }

    /**
    * @description get Account Id Product Id Set 
    * @author Mosaic Direct | Dev Team | 12-03-2023 
    * @param setAccId
    * @return Set<String> 
    **/
    public static Set<String> getAccountIdProductIdSet(Set<Id> setAccId){
        Set<String> setAccIdProductId = new Set<String>();
        for(PMC_DH_CommerceEntitlementSalesArea__c cesa : [SELECT Id, PMC_DH_Account__c, PMC_DH_Product__c
                                                            FROM PMC_DH_CommerceEntitlementSalesArea__c
                                                            WHERE PMC_DH_Account__c IN: setAccId
                                                            WITH USER_MODE])
        {
            setAccIdProductId.add(cesa.PMC_DH_Account__c+''+cesa.PMC_DH_Product__c);
        }
        return setAccIdProductId;
    }

    /**
    * @description get Account Id Product Id Set 
    * @author Mosaic Direct | Dev Team | 12-03-2023 
    * @param lstBuyerAccount
    * @return Map<Id, Id> 
    **/
    public static Map<Id, Id> getAccountIdPolicyIdMap(List<BuyerAccount> lstBuyerAccount){
        Map<Id, Id> mapAccountIdPolicyId = new Map<Id, Id>();
        Map<String, Id> mapPolicyNameAccountId = new Map<String, Id>();
        for(BuyerAccount ba : lstBuyerAccount)
        {
            mapPolicyNameAccountId.put(ENTITLEMENTPOLICY+ DELIMITER + ba.Buyer.Name + DELIMITER + ba.Buyer.AccountNumber, ba.BuyerId);
        }
        for(CommerceEntitlementPolicy cep : [SELECT Id, Name
                                            FROM CommerceEntitlementPolicy
                                            WHERE Name IN : mapPolicyNameAccountId.keySet()
                                            WITH USER_MODE])
        {
            if(mapPolicyNameAccountId.containsKey(cep.Name)){
                mapAccountIdPolicyId.put(mapPolicyNameAccountId.get(cep.Name), cep.Id);
            }
        }
        return mapAccountIdPolicyId;
    }

    /**
    * @description getAccountIdSAPnumberMap 
    * @author Mosaic Direct | Dev Team | 12-03-2023 
    * @param lstBuyerAccount
    * @return Map<String, String>
    **/
    
    public static Map<String, String> getAccountIdSAPnumberMap(List<BuyerAccount> lstBuyerAccount){
        Map<String,String> accountIdSAPNumbermap = new Map<String,String>();
        for(BuyerAccount ba : lstBuyerAccount ){
            accountIdSAPNumbermap.put(ba.BuyerId,ba.Buyer.PMC_SS_SAPCustomerNumber__c);
        }
        return accountIdSAPNumbermap;
    }

    /**
    * @description Checks for the Account to Sales Area Relationship 
    * @author Mosaic Direct | Dev Team | 12-03-2023 
    * @param lstCommerceEntitlementProductAll 
    **/
    public static void insertCommerceEntitlementProduct(List<CommerceEntitlementProduct> lstCommerceEntitlementProductAll){
        if(!lstCommerceEntitlementProductAll.isEmpty() && Schema.sObjectType.CommerceEntitlementProduct.isCreateable()){
            	Database.insert(lstCommerceEntitlementProductAll, false);
        }
    }

    /**
     * @description 
     * @author Mosaic Direct | Dev Team | 12-03-2023 
     * @param lstBuyerAccount
     **/
    public static void updateBuyerAccount(List<BuyerAccount> lstBuyerAccount){
        for(BuyerAccount objBuyerAccount : lstBuyerAccount){
            objBuyerAccount.PMC_DH_isBuyerProcessed__c = true;
        }
        if(Schema.sObjectType.BuyerAccount.isUpdateable()){
            Database.update(lstBuyerAccount, false);
        }
    }

    /**
    * @description associate the entitlement record with the buyer group
    * @author Mosaic Direct | Dev Team | 12-03-2023 
    * @param lstBuyerAccount
    * @param isFirstChunk
    * @return Map<String, CommerceEntitlementPolicy> 
    **/
    public static Map<String, CommerceEntitlementPolicy> getAccountIdExistingPolicyMap(List<BuyerAccount> lstBuyerAccount, Boolean isFirstChunk){
        Map<String, String> accountIdSAPnumberMap = getAccountIdSAPnumberMap(lstBuyerAccount);
        Map<String, CommerceEntitlementPolicy> mapAccountIdExistingPolicy = new Map<String, CommerceEntitlementPolicy>();
        for(CommerceEntitlementPolicy cep : [SELECT Id,CreatedDate,LastModifiedDate,PMC_DH_SAPCustomerNumber__c FROM CommerceEntitlementPolicy Where PMC_DH_SAPCustomerNumber__c IN : accountIdSAPnumberMap.Values() WITH SYSTEM_MODE]){
            if(isFirstChunk){
                mapAccountIdExistingPolicy.put(cep.PMC_DH_SAPCustomerNumber__c, cep);
            }else if(cep.CreatedDate != cep.LastModifiedDate){
                mapAccountIdExistingPolicy.put(cep.PMC_DH_SAPCustomerNumber__c, cep);
            }
        }
        return mapAccountIdExistingPolicy;
    }
    

   /**
    * @description associate the entitlement record with the buyer group
    * @author Mosaic Direct | Dev Team | 12-03-2023 
    * @param mapAccountIdPolicy 
    * @param results
    * @return list<String>
    **/
    /*public static list<String> getupdatedSKUIds(Map<Id, CommerceEntitlementPolicy> mapAccountIdPolicy, Database.UpsertResult[] results ){
        List<String> updatedAccIds = new List<String>();
        for(Integer i = 0; i < results.size(); i++) {
            //System.debug('=results='+results);
            //System.debug('==mapAccountIdPolicy.values()=='+mapAccountIdPolicy.values());
           if(results[i].isSuccess() &&  !results[i].isCreated()) {
               //System.debug('=results updated='+mapAccountIdPolicy.values()[i].PMC_DH_SAPCustomerNumber__c);
                updatedAccIds.add(mapAccountIdPolicy.values()[i].PMC_DH_SAPCustomerNumber__c);
            }
        }
        return updatedAccIds;
    }*/
    
}