objects/Account.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_Division__c</fullName>
        <inlineHelpText>For domestic sales, select “Domestic”. For international sales, select “Export”. For transfers between centers or warehouses, select “Intercompany”.</inlineHelpText>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Domestic</fullName>
                </value>
                <value>
                    <fullName>Export</fullName>
                </value>
                <value>
                    <fullName>Intercompany</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CPQ_PO__c</fullName>
        <description>This field captures the unique Purchase order #</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter the unique identification code assigned to this purchase order.</inlineHelpText>
        <label>Customer Purchase Order #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SalesOrg__c</fullName>
        <description>Pull the Sales Org Value from Opportunity/Account/SalesOrg Object</description>
        <formula>LEFT( PMC_CPQ_SalesArea__r.PMC_SS_SalesArea__r.PMC_CPQ_SAPSalesOrganization__c ,4)</formula>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>End date for subscriptions in this group.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>End date for subscriptions in this group.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>PMC_CPQ_HarvestPeriod__c</fullName>
        <description>This field is created to check Harvest period.</description>
        <label>Harvest Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Future</fullName>
                </value>
                <value>
                    <fullName>Present</fullName>
                </value>
                <value>
                    <fullName>Special</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SalesOrg__c</fullName>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_SalesOrgValue_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>Date the service represented by this line item will end (only applies if product is a subscription).</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date the service represented by this line item will end (only applies if product is a subscription).</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Test_Vignesh_2__mdt.object
<CustomObject>
    <fields>
        <fullName>Attribute_Name__c</fullName>
        <label>Attribute_Name</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_API_Name__c</fullName>
        <label>SF_API_Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Test_Vignesh_2</label>
    <pluralLabel>Test_Vignesh_2</pluralLabel>
</CustomObject>

objects/Test_Vignesh__mdt.object
<CustomObject>
    <description>Testing - Do not delete</description>
    <fields>
        <fullName>Attribute_Name__c</fullName>
        <label>Attribute_Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_API_Name__c</fullName>
        <label>SF_API_Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Test_Vignesh</label>
    <pluralLabel>Test_Vignesh</pluralLabel>
</CustomObject>

classes/TestVignesh.cls
//This class is created by Vignesh and for testing - DO NOT USE or DELETE
public class TestVignesh {

    public TestVignesh(ApexPages.StandardController controller) {

    }

    
    Account acc = new Account();
    SBQQ__Quote__c quo = new SBQQ__Quote__c();
    List<SBQQ__QuoteLine__c> qlis = new List<SBQQ__QuoteLine__c>();
    Public String jsonString {get;set;}
    Public String gen3{get;set;}
    public TestVignesh(){
        /*acc = [select id,name,phone,billingcity,billingstate,billingpostalcode,billingcountry,
            shippingcity,shippingstate,shippingcountry,shippingpostalcode,type,website,
            PMC_SS_Division__c from Account where id ='001DT000013bKhhYAE'];
    
        jsonString = JSON.Serialize(acc);
        */
        
        //PMC_CPQ_Parent_Transaction_Id__c,
        //Removed PMC_CPQ_PO__c from the below query as a cleanup
        quo = [Select id,name,PMC_CPQ_SalesOrg__c,RecordType.Name,PMC_CPQ_PO__c,
                SBQQ__StartDate__c,SBQQ__EndDate__c,currencyISOCode from SBQQ__Quote__c where id='a3CDT000001SsZW2A0'];
        
        qlis = [Select id,name,SBQQ__Product__c,PMC_CPQ_HarvestPeriod__c,SBQQ__Quantity__c from SBQQ__QuoteLine__c where SBQQ__Quote__c =: quo.id];
        
        //Generate the JSON that we are sending to the endpoint
        JSONGenerator gen = JSON.createGenerator(false);
        gen.writeStartObject();
        gen.writeStringField('Transaction_Id',quo.name);
        //if(quo.PMC_CPQ_Parent_Transaction_Id__c != null) { gen.writeStringField('Reference_Transaction_Id', quo.PMC_CPQ_Parent_Transaction_Id__c); }
        //gen.writeStringField('SALES_ORG',quo.PMC_CPQ_SalesOrg__c);
        gen.writeStringField('DIVISION',quo.Recordtype.name);
        //gen.writeStringField('PURCH_NO',quo.PMC_CPQ_PO__c);
        //gen.writeStringField('QT_VALID_F',quo.SBQQ__StartDate__c.format());
        //gen.writeStringField('QT_VALID_T',quo.SBQQ__EndDate__c.format());
        gen.writeFieldName('LineItemList');
        gen.writeStartArray();
        for(SBQQ__QuoteLine__c each: qlis) {
            gen.writeStartObject();
            gen.writeStringField('ITM_NUMBER', each.Id);
            gen.writeStringField('MATERIAL', each.SBQQ__Product__c);
            //gen.writeStringField('PURCH_NO_C', each.PMC_CPQ_HarvestPeriod__c);
            gen.writeStringField('REQ_QTY', String.valueOf(each.SBQQ__Quantity__c));
            gen.writeEndObject();
        }
        gen.writeEndArray();
        gen.writeEndObject();
        System.debug(gen.getAsString());
        
        
        //Dynamic json generation using custom metadata
        List<Test_Vignesh__mdt> testMDT = new List<Test_Vignesh__mdt>();
        testMDT = [Select Attribute_Name__c,SF_API_Name__c from Test_Vignesh__mdt];
        
        List<Test_Vignesh_2__mdt> testMDT2 = new List<Test_Vignesh_2__mdt>();
        testMDT2 = [Select Attribute_Name__c,SF_API_Name__c from Test_Vignesh_2__mdt];
        
        JSONGenerator gen2 = JSON.createGenerator(false);
        gen2.writeStartObject();
        for(Test_Vignesh__mdt each: testMDT) {
        system.debug('!!!'+each.SF_API_Name__c);
            String[] fieldPath = each.SF_API_Name__c.split('\\.');
            Object referencedValue = null;            
            if (fieldPath.size() > 1) {
             // It is a reference
             SObject sobReference = quo.getSObject(fieldPath[0]);
             referencedValue = sobReference.get(fieldPath[1]);
              } else {
                 referencedValue = quo.get(fieldPath[0]);
              }
              if(referencedValue == null) {
                  referencedValue ='';
              }

            gen2.writeStringField(each.Attribute_Name__c, String.valueOf(referencedValue));
        }
        
        
        gen2.writeFieldName('LineItemList');
        gen2.writeStartArray();
        for(SBQQ__QuoteLine__c each: qlis) {
            gen2.writeStartObject();
            for(Test_Vignesh_2__mdt eachMDT: testMDT2) {
                String[] fieldPath = eachMDT.SF_API_Name__c.split('\\.');
                Object referencedValue = null;            
                if (fieldPath.size() > 1) {
                 // It is a reference
                 SObject sobReference = each.getSObject(fieldPath[0]);
                 referencedValue = sobReference.get(fieldPath[1]);
                  } else {
                     referencedValue = each.get(fieldPath[0]);
                  }
                  if(referencedValue == null) {
                      referencedValue ='';
                  }
    
                gen2.writeStringField(eachMDT.Attribute_Name__c, String.valueOf(referencedValue));
            }
            gen2.writeEndObject();
        }
        gen2.writeEndArray();
        gen2.writeEndObject();
        System.debug(gen2.getAsString());
        gen3 = gen2.getAsString();
    }

}