objects/Account.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_SAPCustomerNumber__c</fullName>
        <description>The SAP Generated Customer Number</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SAP Customer Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>PMC_SS_Customer</fullName>
        <active>true</active>
        <description>This record type will be used to create Account records of Customer record types</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>PMC_SS_Prospect</fullName>
        <active>true</active>
        <description>This record type will be used to create Account records of Prospect record types</description>
        <label>Prospect</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Location</label>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/PMC_CPQ_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_OriginalAmount__c</fullName>
        <label>Original Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_CPQ_ProductLocation__c.object
<CustomObject>
    <description>This object is created as a part of  story to capture product and location data.</description>
    <label>Product Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PMC_SS_AccountPartnerRelationships__c.object
<CustomObject>
    <description>This junction object is used to store Partner relationships related to the Account.</description>
    <fields>
        <fullName>PMC_SS_Account__c</fullName>
        <description>This field is used to look up to sold-to master</description>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Sold-to</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Partner Accounts</relationshipLabel>
        <relationshipName>PMC_SS_RelatedSoldToAccounts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PMC_SS_RelatedAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to related Bill-to, Ship-to and Payer to Sold-to accounts</description>
        <inlineHelpText>Junction Object will be renamed to Related Account’s name on save</inlineHelpText>
        <label>Related Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Ship-to</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Sold-to</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Bill-to</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Payer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Partner Relationships (Related Account)</relationshipLabel>
        <relationshipName>PMC_SS_RelatedPartnerAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Partner Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Partner Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Partner Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PMC_SS_AccountSalesAreaRelationship__c.object
<CustomObject>
    <description>Junction Object to relate Account and Sales Areas</description>
    <fields>
        <fullName>PMC_SS_Account__c</fullName>
        <description>Master Detail relationship between Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>AccountSalesAreRelationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SalesArea__c</fullName>
        <description>Master Detail relationship to Sales Area</description>
        <label>Sales Area</label>
        <referenceTo>PMC_SS_SalesArea__c</referenceTo>
        <relationshipName>AccountSalesAreRelationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Sales Area Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Sales Area Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PMC_SS_SalesArea__c.object
<CustomObject>
    <description>Sales Area Object</description>
    <label>Sales Area</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <recordTypes>
        <fullName>PMC_CPQ_Brazil</fullName>
        <active>true</active>
        <description>This Record Type was created as a part of story to have different functionalities for different Record Types</description>
        <label>Brazil</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesAgreement.object
<CustomObject>
    <recordTypes>
        <fullName>PMC_SS_BusinessPartnerAgreement</fullName>
        <active>true</active>
        <description>North America Business Partner Agreement</description>
        <label>Business Partner Agreement</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product.This is as per the  US GCPM 1064</description>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <infoMessage>Select Product Location Columns Link to add appropriate Locations</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>CPQ Quotes</relationshipLabel>
        <relationshipName>CPQ_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Shipment.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_VehicleID__c</fullName>
        <description>This field captures the vehicle Vehicle ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ShipmentItem.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Location</label>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Delivery Lines</relationshipLabel>
        <relationshipName>Delivery_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_VehicleID__c</fullName>
        <description>This field captures the vehicle Vehicle ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PMC_TestUtilityClassTest.cls
/**
 * @description This test class will be used to cover all the methods of PMC_TestUtilityClass.
 * @author Kailas Shimpi
 * @storynumber GPSSM-1224
 */

 @isTest(seeAllData=false)
 public class PMC_TestUtilityClassTest {
     /**
     * @description This method will be use to cover createUser of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreateUser() {
         Test.startTest();
         List<User> lstUsers = PMC_TestUtilityClass.createUser(1);
         System.assert(lstUsers.size() != 0,'User records were not created, test method-testCreateUser');
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover the negative scenario of createTestUserRecords of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreateUserNull() {
         Test.startTest();
         try {
             List<User> lstUsers = PMC_TestUtilityClass.createUser(null);
             System.assert(lstUsers.size() != 0, 'User records were not created, test method-testCreateUserNull');
         }catch(Exception e) {
             system.assertEquals(e.getMessage(), 'Attempt to de-reference a null object','Expected a NullPointerException');
         }
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover createTestAccountRecords of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreateAccount() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         System.runAs(objUser) {
             Account objAccount = PMC_TestUtilityClass.createAccount('The Mosaic Company 1','PMC_SS_Prospect');
             System.assert(objAccount != null, 'Account records were not created.');
         }
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover createTestContactRecords of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreateContact() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         System.runAs(objUser) {
             List<Contact> lstContacts = PMC_TestUtilityClass.createContact(1,'Master');
             System.assert(lstContacts.size() != 0, 'Contact records were not created.');
         }
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover createOpportunity of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreateLead() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         System.runAs(objUser) {
             List<Lead> lstLeads = PMC_TestUtilityClass.createLead(1,'Master');
             System.assert(lstLeads.size() != 0, 'Lead records were not created.');
         }
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover createOpportunity of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreateOpportunity() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         System.runAs(objUser) {
             List<Opportunity> lstOpportunities = PMC_TestUtilityClass.createOpportunity(1,'Master');
             System.assert(lstOpportunities.size() != 0, 'Opportunity records were not created.');
         }        
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover createOpportunityContactRoles of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreateOpportunityContactRoles() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         System.runAs(objUser) {
             List<Opportunity> lstOpportunities = PMC_TestUtilityClass.createOpportunity(1,'Master');
             List<Contact> lstContacts = PMC_TestUtilityClass.createContact(1,'Master');
             List<OpportunityContactRole> lstOpportunityContactRoles = PMC_TestUtilityClass.createOpportunityContactRoles(lstContacts,lstOpportunities);
             System.assert(lstOpportunityContactRoles.size() != 0, 'OpportunityContactRole records were not created.');
         }        
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover createOpportunityTeamMember of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreateOpportunityTeamMember() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         System.runAs(objUser) {
             List<User> lstUser = PMC_TestUtilityClass.createUser(1);
             List<Opportunity> lstOpportunities = PMC_TestUtilityClass.createOpportunity(1,'Master');
             List<OpportunityTeamMember> lstOppTeamMembers = PMC_TestUtilityClass.createOpportunityTeamMember(lstUser, lstOpportunities);
             System.assert(lstOppTeamMembers.size() != 0, 'OpportunityTeamMember records were not created.');
         }        
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover createProduct of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreateProduct() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         System.runAs(objUser) {
             List<Product2> lstProducts = PMC_TestUtilityClass.createProduct(1,'PMC_CPQ_Brazil');
             System.assert(lstProducts.size() != 0, 'Product records were not created.');
         }        
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover createPriceBookEntry of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreatePriceBookEntry() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         System.runAs(objUser) {
             List<Product2> lstProducts = PMC_TestUtilityClass.createProduct(1,'PMC_CPQ_Brazil');
             Id idPriceBook = Test.getStandardPricebookId();
             List<PricebookEntry> lstProceBookEntry = PMC_TestUtilityClass.createPriceBookEntry(lstProducts,idPriceBook);
             System.assert(lstProceBookEntry.size() != 0, 'PriceBookEntry records were not created.');
         }        
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover createOpportunityLineItem of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreateOpportunityLineItem() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         System.runAs(objUser) {
             List<Opportunity> lstOpportunities = PMC_TestUtilityClass.createOpportunity(1,'Master');
             List<Product2> lstProducts = PMC_TestUtilityClass.createProduct(1,'PMC_CPQ_Brazil');
             Id idPriceBook = Test.getStandardPricebookId();
             List<PricebookEntry> lstProceBookEntry = PMC_TestUtilityClass.createPriceBookEntry(lstProducts,idPriceBook);
             List<OpportunityLineItem> lstOpportunityLineItem = PMC_TestUtilityClass.createOpportunityLineItem(lstProceBookEntry,lstOpportunities);
             System.assert(lstOpportunityLineItem.size() != 0, 'OpportunityLineItem records were not created.');
         }        
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover createContract of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreateContract() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         List<Account> lstAccounts = new List<Account>();
         System.runAs(objUser) {
             List<Opportunity> lstOpportunities = PMC_TestUtilityClass.createOpportunity(1,'Master');
             Account objAccount = PMC_TestUtilityClass.createAccount('The Mosaic Company 2','PMC_SS_Prospect');
             lstAccounts.add(objAccount);
             //List<Account> lstAccounts = PMC_TestUtilityClass.createAccount(1,'Master');
             List<Contract> lstContracts = PMC_TestUtilityClass.createContract(lstAccounts,lstOpportunities);
             System.assert(lstContracts.size() != 0, 'Contract records were not created.');
         }        
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover createQuotes of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreateQuotes() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         System.runAs(objUser) {
             List<Opportunity> lstOpportunities = PMC_TestUtilityClass.createOpportunity(1,'Master');
             List<Quote> lstQuotes = PMC_TestUtilityClass.createQuotes(1, lstOpportunities);
             System.assert(lstQuotes.size() != 0, 'Quote records were not created.');
         }        
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover createCPQQuotes of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreateCPQQuotes() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         System.runAs(objUser) {
             List<Opportunity> lstOpportunities = PMC_TestUtilityClass.createOpportunity(1,'Master');
             List<Contact> lstContacts = PMC_TestUtilityClass.createContact(1,'Master');
             List<SBQQ__Quote__c> lstQuotes = PMC_TestUtilityClass.createCPQQuotes(1, lstOpportunities, lstContacts);
             System.assert(lstQuotes.size() != 0, 'Quote records were not created.');
         }        
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover createOrders of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreateOrders() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         System.runAs(objUser) {
             List<Account> lstAccount = new List<Account>(); 
             Account objAccount = PMC_TestUtilityClass.createAccount('The Mosaic Company 3','PMC_SS_Prospect');
             lstAccount.add(objAccount);
             List<Order> lstOrders = PMC_TestUtilityClass.createOrders(1, lstAccount);
             System.assert(lstOrders.size() != 0, 'Order records were not created.');
         }        
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover createOrders of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreateOrderProducts() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];  
         System.runAs(objUser) {
             List<Account> lstAccount = new List<Account>(); 
             Account objAccount = PMC_TestUtilityClass.createAccount('The Mosaic Company 4','PMC_SS_Prospect');
             lstAccount.add(objAccount);
             List<Order> lstOrders = PMC_TestUtilityClass.createOrders(1, lstAccount);
             List<OrderItem> lstOrderProducts = PMC_TestUtilityClass.createOrderProducts(1, lstOrders);
             System.assert(lstOrderProducts.size() != 0, 'Order records were not created.');
         }        
         Test.stopTest();
     }


     /**
     * @description This method will be use to cover createSalesArea of PMC_TestUtilityClass.
     */
    @isTest 
    private static void testCreateSalesArea() {
        Test.startTest();
        User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
        System.runAs(objUser) {
            List<PMC_SS_SalesArea__c> lstSalesAreas = PMC_TestUtilityClass.createSalesArea(1,'Master');
            System.assert(lstSalesAreas.size() != 0, 'Sales Area records were not created.');
        }
        Test.stopTest();
    }
     
    /**
     * @description This method will be use to cover createAccountSalesAreaRelationship of PMC_TestUtilityClass.
     */
    @isTest 
    private static void testCreateAccountSalesAreaRelationship() {
        Test.startTest();
        User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
		List<Account> lstAccounts = new List<Account>();
        System.runAs(objUser) {
			Account objAccountToCreate = PMC_TestUtilityClass.createAccount('Google','PMC_SS_Prospect');
            lstAccounts.add(objAccountToCreate);
            List<PMC_SS_SalesArea__c> lstSalesAreas = PMC_TestUtilityClass.createSalesArea(1,'Master');
            List<PMC_SS_AccountSalesAreaRelationship__c> lstAccountSalesAreaRelationships = PMC_TestUtilityClass.createAccountSalesAreaRelationship(lstAccounts, lstSalesAreas);
            System.assert(lstAccountSalesAreaRelationships.size() != 0, 'Account sales area relationship records were not created.');
        }
        Test.stopTest();
    }
     
    /**
     * @description This method will be use to cover createLeadObjectWrapper of PMC_TestUtilityClass.
     */
    @isTest 
    private static void testCreateLeadObjectWrapper() {
        Test.startTest();
        Lead objLead  = PMC_TestUtilityClass.createLeadObjectWrapper('LastName', 'lead@lead.lead', 'Sulphur');
        Test.stopTest();
        System.assertEquals('Test.COM', objLead.Company, 'Expected Company to be populated');
        System.assertEquals('Test.COM', objLead.Website, 'Expected website to be populated');
        System.assertEquals('New', objLead.Status, 'Expected status to be new');
    }
     
     /**
     * @description This method will be use to cover createCase of PMC_TestUtilityClass.
     */
    @isTest 
     private static void testCreateCase() {
         Schema.Location objLocation= PMC_TestUtilityClass.createLocation('Test Location');
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         BusinessHours objBusinessHrs = [SELECT Id, Name FROM BusinessHours WHERE isDefault = True AND IsActive = True]; 
         System.runAs(objUser) {
             
             Account objAccountToCreate = PMC_TestUtilityClass.createAccount('Google','PMC_SS_Prospect');
             Case objCase = PMC_TestUtilityClass.createCase(objBusinessHrs.Id, objAccountToCreate.Id, objUser.Id,objLocation.Id);
             System.assertEquals(objCase.Subject, 'Test Subject', 'Case has been created with the subject - Test Subject');

             //List<Contact> lstContacts = PMC_TestUtilityClass.createContact(1, '');
             //Case objCase1 = PMC_TestUtilityClass.createCaseWithContact(objBusinessHrs.Id, lstContacts[0].Id, objUser.Id);
             //System.assertEquals(objCase1.ContactId, lstContacts[0].Id, 'Case has been created with the subject - Test Subject');
         }
         Test.stopTest();
     }
     
        
     /**
     * @description This method will be use to cover createCase of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreateContactWithPhoneNo() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         System.runAs(objUser) {
             Contact objContactToCreate = PMC_TestUtilityClass.createContactWithPhone();
             System.assertEquals(objContactToCreate.Phone, '0101010101', 'Contact Phone Check');
         }
         
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover createPortalUser of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreatePortalUser() {
         Test.startTest();
         Profile objProfile = [SELECT Id FROM Profile WHERE Name = 'Digital Hub Buyer' LIMIT 1];
         List<User> lstPortalUsers = PMC_TestUtilityClass.createPortalUser(1, objProfile);
         System.assert(lstPortalUsers.size() != 0,'Portal User records were not created, test method-testCreatePortalUser');
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover the negative scenario of createPortalUser of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreatePortalUserNull() {
         Test.startTest();
         try {
             Profile objProfile = [SELECT Id FROM Profile WHERE Name = 'Digital Hub Buyer' LIMIT 1];
             List<User> lstPortalUsers = PMC_TestUtilityClass.createPortalUser(null, objProfile);
             System.assert(lstPortalUsers.size() != 0, 'User records were not created, test method-testCreateUserNull');
         }catch(Exception e) {
             system.assertEquals(e.getMessage(), 'Attempt to de-reference a null object','Expected a NullPointerException');
         }
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover assignPermissionSetGroupToUsers of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testAssignPermissionSetGroupToUsers() {
         Test.startTest();
         Profile objProfile = [SELECT Id FROM Profile WHERE Name = 'Digital Hub Buyer' LIMIT 1];
         List<User> lstPortalUsers = PMC_TestUtilityClass.createPortalUser(1, objProfile);
         PermissionSetGroup perSetGrp = [SELECT Id, Status FROM PermissionSetGroup LIMIT 1];
         if (perSetGrp.Status != 'Updated') {
                Test.calculatePermissionSetGroup(perSetGrp.id);
          }
         PMC_TestUtilityClass.assignPermissionSetGroupToUsers(lstPortalUsers, perSetGrp);
         List<PermissionSetAssignment> lstPermSetAssignmentsCreated = [SELECT Id FROM PermissionSetAssignment WHERE PermissionSetGroupId = :perSetGrp.Id ]; 
         System.assertEquals(true,lstPermSetAssignmentsCreated.size()>=0,'Permission set is not created');
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover CreateLocation of PMC_TestUtilityClass.
     */
     @isTest
     private static void testCreateLocation() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         System.runAs(objUser) {
             Schema.Location objLocation = PMC_TestUtilityClass.createLocation('Test Schema.Location 1');
             System.assertEquals(objLocation.Name, 'Test Schema.Location 1', 'Location Name Check');
         }
         
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover CreateProductLocation of PMC_TestUtilityClass.
     */
     @isTest
     private static void testCreateProductLocation() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         System.runAs(objUser) {
             Schema.Location objLocation = PMC_TestUtilityClass.createLocation('Test Schema.Location 2');
             PMC_CPQ_ProductLocation__c objPrdLocation = PMC_TestUtilityClass.createProductLocation('Test Product Location 2', objLocation);
             System.assertEquals(objPrdLocation.Name, 'Test Product Location 2', 'Product Location Name Check');
         }
         
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover createDelivery of PMC_TestUtilityClass.
     */
     @isTest
     private static void testCreateDelivery() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         System.runAs(objUser) {
             Account objAccount = PMC_TestUtilityClass.createAccount('The Mosaic Company 5','PMC_SS_Prospect');
             List<Order> lstOrders = PMC_TestUtilityClass.createOrders(1, new List<Account>{objAccount});
             Shipment objShipment = PMC_TestUtilityClass.createDelivery('Test Delivery', lstOrders[0]);
             System.assertEquals(objShipment.ShipToName, 'Test Delivery', 'Shipment Name Check');
         }
         
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover CreateDeliveryItem of PMC_TestUtilityClass.
     */
     @isTest
     private static void testCreateDeliveryItem() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         System.runAs(objUser) {
             Account objAccount = PMC_TestUtilityClass.createAccount('The Mosaic Company 6','PMC_SS_Prospect');
             List<Order> lstOrders = PMC_TestUtilityClass.createOrders(1, new List<Account>{objAccount});
             Shipment objShipment = PMC_TestUtilityClass.createDelivery('Test Delivery', lstOrders[0]);
             OrderItem objOrderItem = PMC_TestUtilityClass.createOrderProducts(1, new List<Order>{lstOrders[0]})[0];
             ShipmentItem objShipmentItem = PMC_TestUtilityClass.createDeliveryItem(objShipment, objOrderItem);
             System.assertEquals(objShipmentItem.PMC_CPQ_VehicleID__c, 'Test Vehicle', 'ShipmentItem Vehicle Check');
         }
         
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover createInvoice of PMC_TestUtilityClass.
     */
     @isTest
     private static void testCreateInvoice() {
         Test.startTest();
         User objUser = [SELECT Id, Name FROM User where isActive=true LIMIT 1];
         System.runAs(objUser) {
             Account objAccount = PMC_TestUtilityClass.createAccount('The Mosaic Company 7','PMC_SS_Prospect');
             List<Order> lstOrders = PMC_TestUtilityClass.createOrders(1, new List<Account>{objAccount});
             Shipment objShipment = PMC_TestUtilityClass.createDelivery('Test Delivery', lstOrders[0]);
             Contact objContact = PMC_TestUtilityClass.createContact(1, '')[0];
             PMC_CPQ_Invoice__c objInvoice = PMC_TestUtilityClass.createInvoice(objShipment, lstOrders[0], objContact);
             System.assertEquals(objInvoice.PMC_CPQ_OriginalAmount__c, 1000.0, 'Original Amount Check');
         }
         
         Test.stopTest();
     }
     
     /**
     * @description This method will be use to cover CreateSalesAgreement of PMC_TestUtilityClass.
     */
    @isTest
    private static void testCreateSalesAgreement() {
        Test.startTest();
        List<Profile> lstSalesProfile = [SELECT Id FROM Profile WHERE Name = 'Sales User'];
        List<User> lstUser;
        if(lstSalesProfile != null && !lstSalesProfile.isEmpty()) {
             lstUser = PMC_TestUtilityClass.createUser(1);
             if(lstUser != null && !lstUser.isEmpty()) {
                 lstUser[0].ProfileId = lstSalesProfile[0].Id;
                 lstUser[0].isActive = true;
             }
             insert lstUser;
        }
        PermissionSetLicense psl=[SELECT Id FROM PermissionSetLicense WHERE DeveloperName = 'ManufacturingSalesAgreementsPsl'];
        insert new PermissionSetLicenseAssign(AssigneeId = lstUser[0].Id, PermissionSetLicenseId = psl.Id);
        PermissionSet objPermSet = [SELECT Id FROM PermissionSet WHERE Name = 'PMC_CRESalesAgreement' ];
        insert new PermissionSetAssignment(AssigneeId = lstUser[0].Id, PermissionSetId = objPermSet.Id);
        PermissionSetGroup objPerSetGrp = [SELECT Id, Status FROM PermissionSetGroup WHERE DeveloperName = 'PMC_SLS_Permission_Set_Group'];
        if (objPerSetGrp.Status != 'Updated') {
                Test.calculatePermissionSetGroup(objPerSetGrp.id);
                }
        insert new PermissionSetAssignment(AssigneeId = lstUser[0].Id, PermissionSetGroupId = objPerSetGrp.Id);
        System.runAs(lstUser[0]) {
            List<SalesAgreement> lstSalesAgreement = PMC_TestUtilityClass.createSalesAgreement(1,'PMC_SS_BusinessPartnerAgreement');
            System.assert(lstSalesAgreement.size() != 0, 'Sales Agreement records were not created.');
        }
        Test.stopTest();
    }
     
     /**
     * @description This method will be use to cover createSalesAgreementProduct of PMC_TestUtilityClass.
     */
    @isTest
    private static void testCreateSalesAgreementProduct() {
        Test.startTest();
        List<Profile> lstSalesProfile = [SELECT Id FROM Profile WHERE Name = 'Sales User'];
         List<User> lstUser;
         if(lstSalesProfile != null && !lstSalesProfile.isEmpty()) {
             lstUser = PMC_TestUtilityClass.createUser(1);
             if(lstUser != null && !lstUser.isEmpty()) {
                 lstUser[0].ProfileId = lstSalesProfile[0].Id;
                 lstUser[0].isActive = true;
             }
             insert lstUser;
         }
        PermissionSetLicense psl=[SELECT Id FROM PermissionSetLicense WHERE DeveloperName = 'ManufacturingSalesAgreementsPsl'];
        insert new PermissionSetLicenseAssign(AssigneeId = lstUser[0].Id, PermissionSetLicenseId = psl.Id);
        PermissionSet objPermSet = [SELECT Id FROM PermissionSet WHERE Name = 'PMC_CPQ_CRED_Pricebook' ];
        insert new PermissionSetAssignment(AssigneeId = lstUser[0].Id, PermissionSetId = objPermSet.Id);
        PermissionSetGroup objPerSetGrp = [SELECT Id, Status FROM PermissionSetGroup WHERE DeveloperName = 'PMC_SLS_Permission_Set_Group'];
        if (objPerSetGrp.Status != 'Updated') {
                Test.calculatePermissionSetGroup(objPerSetGrp.id);
                }
        insert new PermissionSetAssignment(AssigneeId = lstUser[0].Id, PermissionSetGroupId = objPerSetGrp.Id);
        System.runAs(lstUser[0]) {
            List<SalesAgreement> lstSalesAgreement = PMC_TestUtilityClass.createSalesAgreement(1,'PMC_SS_BusinessPartnerAgreement');
            System.assert(lstSalesAgreement.size() != 0, 'Sales Agreement records were not created.');
            List<SalesAgreementProduct> lstSalesAgreementProducts = PMC_TestUtilityClass.createSalesAgreementProduct(1,lstSalesAgreement);
            System.assert(lstSalesAgreementProducts.size() != 0, 'Sales Agreement Product records were not created.');
        }
        Test.stopTest();
    }
     
  
     
     
     
    /**
     * @description This method will be use to cover createSoldToShipToAccountJunctionObjectWrapper of PMC_TestUtilityClass.
     */
     @isTest 
     private static void testCreateCaseWithContact() {
        Test.startTest();
        List<Contact> lstContact = PMC_TestUtilityClass.createContact(1, 'Master');
        BusinessHours objBusinessHour = [Select Id From BusinessHours Where Name = 'Default' LIMIT 1];
        User objUser = [Select Id From User LIMIT 1];
        
        Case objCase = PMC_TestUtilityClass.createCaseWithContact(objBusinessHour.Id, lstContact.get(0).Id, objUser.Id );
        Test.stopTest();
        System.assert(objCase != NUll , 'Expected case to be created');
    }
     
     
     /**
     * @description This method will be use to cover createPartnerObjectWrapper of PMC_TestUtilityClass.
     */
    @isTest 
    private static void createPartnerObjectWrapper() {
        Test.startTest();
         List<User> lstUser = new List<User>();
        PermissionSetGroup perSetGrpAdmin = [SELECT Id FROM PermissionSetGroup WHERE DeveloperName = 'PMC_Administrator_Permission_Set_Group'];
        Profile objUserProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        if(objUserProfile != null) {
            lstUser = PMC_TestUtilityClass.createUser(1);
            if(lstUser != null && !lstUser.isEmpty()) {
                lstUser[0].ProfileId = objUserProfile.Id;
                lstUser[0].LastName = 'Admin User Test';
                lstUser[0].isActive = true;
            }
            Database.upsert(lstUser) ;
            PMC_TestUtilityClass.assignPermissionSetGroupToUsers(lstUser, perSetGrpAdmin);
        }
        
       User objSystemAdminUser = lstUser[0];
        System.runAs(objSystemAdminUser){
          List<Account> lstAccounts = new List<Account>();
        Account objAccount;
        for(Integer intAccountCount = 0; intAccountCount < 2; intAccountCount++) {
            objAccount = new Account();
            objAccount = PMC_TestUtilityClass.createAccount('Deloitte' + intAccountCount,'PMC_SS_Customer');
            lstAccounts.add(objAccount);
        }
        lstAccounts[1].Type='Ship-to';
        lstAccounts[1].PMC_SS_SAPCustomerNumber__c='1111';
        lstAccounts[0].Type='Sold-to';
        lstAccounts[0].PMC_SS_SAPCustomerNumber__c='112';
        //upsert(lstAccounts);
        List<PMC_SS_AccountPartnerRelationships__c> lstPartners = PMC_TestUtilityClass.createPartnerObjectWrapper(50,lstAccounts[0].Id,lstAccounts[1].Id);
        System.assertEquals('Test Partner', lstPartners[0].Name, 'Expected Name to be populated');
        System.assertEquals(lstAccounts[0].Id, lstPartners[0].PMC_SS_Account__c, 'Expected Account Id to be populated');
		System.assertEquals(lstAccounts[1].Id, lstPartners[0].PMC_SS_RelatedAccount__c, 'Expected Related Account Id to be populated');            
        }
        Test.stopTest();
 
    }
     
     
 
 }