objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>PMC_SS_Customer</fullName>
        <active>true</active>
        <description>This record type will be used to create Account records of Customer record types</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_SalesAgreementSalesAreaRelation__c.object
<CustomObject>
    <description>Junction object to link Sales Agreement with Sales Area.</description>
    <fields>
        <fullName>PMC_SS_SalesAgreement__c</fullName>
        <description>Sales Agreement Master-Detail field</description>
        <label>Sales Agreement</label>
        <referenceTo>SalesAgreement</referenceTo>
        <relationshipLabel>Sales Area</relationshipLabel>
        <relationshipName>PMC_SS_SalesAgreementSalesAreaRel</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SalesArea__c</fullName>
        <description>Sales Area Master-Detail field</description>
        <label>Sales Area</label>
        <referenceTo>PMC_SS_SalesArea__c</referenceTo>
        <relationshipLabel>Sales Agreement Sales Area Relation</relationshipLabel>
        <relationshipName>PMC_SS_SalesAgreementSalesAreaRelation</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Agreement Sales Area Relation</label>
    <nameField>
        <displayFormat>SAR-{00000}</displayFormat>
        <label>Sales Agreement Sales Area Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Agreement Sales Area Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PMC_SS_SalesArea__c.object
<CustomObject>
    <description>Sales Area Object</description>
    <label>Sales Area</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PMC_SS_SalesAgreeSalesAreaRelHandlerTest.cls
/**
 * @description This test class will be used to cover all the methods of PMC_SS_SalesAgreeSalesAreaRelHandler and PMC_SS_SalesAgreeSalesAreaRelHelper.
 * @author Swakeerth Gadda
 */
@isTest
private with sharing class PMC_SS_SalesAgreeSalesAreaRelHandlerTest{

    /**
    * @description This Method will be used to setup the test data for the test class execution.
    */
    
    @testsetup
    private static void setup() {
        
        List<Profile> lstUserProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        
        List<Account> lstAccounts = new List<Account>();
        Account objAccount;
        
        if(lstUserProfile != null && !lstUserProfile.isEmpty()) {
            
            List<User> lstUser = PMC_TestUtilityClass.createUser(2);
            if(lstUser != null && !lstUser.isEmpty()) {
                for(User objUser : lstUser) {
                    objUser.ProfileId = lstUserProfile[0].Id;
                }
            }
            insert lstUser;
            
            for(Integer intAccountCount = 0; intAccountCount < 2; intAccountCount++) {
                objAccount = new Account();
                objAccount = PMC_TestUtilityClass.createAccount('Deloitte' + intAccountCount,'PMC_SS_Customer');
                lstAccounts.add(objAccount);
            }
                  
            List<PMC_SS_SalesArea__c> listSalesArea = PMC_TestUtilityClass.createSalesArea(4, null);
            PMC_TestUtilityClass.createAccountSalesAreaRelationship(lstAccounts, new List<PMC_SS_SalesArea__c>{listSalesArea[0],listSalesArea[1]});
			PMC_TestUtilityClass.createAccountSalesAreaRelationship(lstAccounts, new List<PMC_SS_SalesArea__c>{listSalesArea[2],listSalesArea[3]});
			Pricebook2 priceBook = new Pricebook2();
            priceBook.Name = 'Test';
            priceBook.IsActive = true;
            priceBook.Description = 'Test1';
            insert priceBook;
            SalesAgreement salesAgreement = new SalesAgreement();
            salesAgreement.Name = 'Test Sales Agreement';
            salesAgreement.Status = PMC_SS_ConstantClass.SALES_AGREEMENT_STATUS_DRAFT;
            salesAgreement.StartDate = System.Today();
            salesAgreement.AccountId = [Select Id From Account Where Name = 'Deloitte1' limit 1].Id;
            salesAgreement.ScheduleFrequency = PMC_SS_ConstantClass.SALES_AGREEMENT_SCHEDULEFREQUENCY_WEEKLY;
            salesAgreement.ScheduleCount = 24;
            salesAgreement.CurrencyIsoCode = PMC_SS_ConstantClass.SALES_AGREEMENT_CURRENCYISOCODE_USD;
            salesAgreement.ProductLevel = PMC_SS_ConstantClass.SALES_AGREEMENT_PRODUCTLEVEL_PRODUCT;
            salesAgreement.PricebookId = [Select Id From Pricebook2 Where Name = 'Test' limit 1].Id;
            insert salesAgreement;
        }
    }
    @isTest
    static void validateSalesAgreementSalesAreaInsertTest(){
        string hasErrorMessage;
        PMC_SalesAgreementSalesAreaRelation__c salesAgreeSalesAreaRel = new PMC_SalesAgreementSalesAreaRelation__c();
        salesAgreeSalesAreaRel.PMC_SS_SalesAgreement__c = [Select Id From SalesAgreement Where name = 'Test Sales Agreement'].Id;
        salesAgreeSalesAreaRel.PMC_SS_SalesArea__c = [Select Id From PMC_SS_SalesArea__c Where name = 'test Sales Area Name0'].Id;
        try{
			insert salesAgreeSalesAreaRel;
        }
        catch(exception ex){
            hasErrorMessage = ex.getMessage();
        }
        system.assertEquals(true, hasErrorMessage.contains(Label.PMC_SS_SalesAgreementtoSalesAreaValidationMessage), 'Has validation message for salesarea');
    }
    @isTest
    static void validateSalesAgreementSalesAreaUpdateTest(){
        string hasErrorMessage = '';
        PMC_SalesAgreementSalesAreaRelation__c salesAgreeSalesAreaRel = new PMC_SalesAgreementSalesAreaRelation__c();
        salesAgreeSalesAreaRel.PMC_SS_SalesAgreement__c = [Select Id From SalesAgreement Where name = 'Test Sales Agreement'].Id;
        salesAgreeSalesAreaRel.PMC_SS_SalesArea__c = [Select Id From PMC_SS_SalesArea__c Where name = 'test Sales Area Name1'].Id;
		insert salesAgreeSalesAreaRel;
        try{
			salesAgreeSalesAreaRel.PMC_SS_SalesArea__c = [Select Id From PMC_SS_SalesArea__c Where Name = 'test Sales Area Name0'].Id;
            update salesAgreeSalesAreaRel;
        }
        catch(exception ex){
            hasErrorMessage = ex.getMessage();
        }
        system.assertEquals(true, hasErrorMessage.contains(Label.PMC_SS_SalesAgreementtoSalesAreaValidationMessage), 'Has validation message for salesarea');
    }
    @isTest
    static void validateSalesAgreementSalesAreaBypassInsertTest(){
        string hasErrorMessage = '';
        PMC_SalesAgreementSalesAreaRelation__c salesAgreeSalesAreaRel = new PMC_SalesAgreementSalesAreaRelation__c();
        salesAgreeSalesAreaRel.PMC_SS_SalesAgreement__c = [Select Id From SalesAgreement Where name = 'Test Sales Agreement'].Id;
        salesAgreeSalesAreaRel.PMC_SS_SalesArea__c = [Select Id From PMC_SS_SalesArea__c Where name = 'test Sales Area Name0'].Id;
        try{
            PMC_SS_SalesAgreeSalesAreaRelHandler.boolBypassTriggerLogic = true;
            insert salesAgreeSalesAreaRel;
        }
        catch(exception ex){
            hasErrorMessage = ex.getMessage();
        }
		system.assertEquals(false, hasErrorMessage.contains(Label.PMC_SS_SalesAgreementtoSalesAreaValidationMessage), 'Has no validation message for salesarea');
    }
    @isTest
    static void validateSalesAgreementSalesAreaBypassUpdateTest(){
        string hasErrorMessage = '';
        PMC_SalesAgreementSalesAreaRelation__c salesAgreeSalesAreaRel = new PMC_SalesAgreementSalesAreaRelation__c();
        salesAgreeSalesAreaRel.PMC_SS_SalesAgreement__c = [Select Id From SalesAgreement Where name = 'Test Sales Agreement'].Id;
        salesAgreeSalesAreaRel.PMC_SS_SalesArea__c = [Select Id From PMC_SS_SalesArea__c Where name = 'test Sales Area Name1'].Id;
		insert salesAgreeSalesAreaRel;
        try{
			PMC_SS_SalesAgreeSalesAreaRelHandler.boolBypassTriggerLogic = true;
            update salesAgreeSalesAreaRel;
        }
        catch(exception ex){
            hasErrorMessage = ex.getMessage();
        }
		system.assertEquals(false, hasErrorMessage.contains(Label.PMC_SS_SalesAgreementtoSalesAreaValidationMessage), 'Has no validation message for salesarea');
    }
    @isTest
    static void validateSalesAgreementSalesAreaDeleteTest(){
        string hasErrorMessage = '';
        PMC_SalesAgreementSalesAreaRelation__c salesAgreeSalesAreaRel = new PMC_SalesAgreementSalesAreaRelation__c();
        salesAgreeSalesAreaRel.PMC_SS_SalesAgreement__c = [Select Id From SalesAgreement Where name = 'Test Sales Agreement'].Id;
        salesAgreeSalesAreaRel.PMC_SS_SalesArea__c = [Select Id From PMC_SS_SalesArea__c Where name = 'test Sales Area Name1'].Id;
		insert salesAgreeSalesAreaRel;
        try{
			PMC_SS_SalesAgreeSalesAreaRelHandler.boolBypassTriggerLogic = true;
            delete salesAgreeSalesAreaRel;
        }
        catch(exception ex){
            hasErrorMessage = ex.getMessage();
        }
		system.assertEquals(false, hasErrorMessage.contains(Label.PMC_SS_SalesAgreementtoSalesAreaValidationMessage), 'Has no validation message for salesarea');
    }
    @isTest
    static void validateSalesAgreementSalesAreaUndeleteTest(){
        string hasErrorMessage = '';
        PMC_SalesAgreementSalesAreaRelation__c salesAgreeSalesAreaRel = new PMC_SalesAgreementSalesAreaRelation__c();
        salesAgreeSalesAreaRel.PMC_SS_SalesAgreement__c = [Select Id From SalesAgreement Where name = 'Test Sales Agreement'].Id;
        salesAgreeSalesAreaRel.PMC_SS_SalesArea__c = [Select Id From PMC_SS_SalesArea__c Where name = 'test Sales Area Name1'].Id;
		insert salesAgreeSalesAreaRel;
        delete salesAgreeSalesAreaRel;
        try{
			PMC_SS_SalesAgreeSalesAreaRelHandler.boolBypassTriggerLogic = true;
            undelete salesAgreeSalesAreaRel;
        }
        catch(exception ex){
            hasErrorMessage = ex.getMessage();
        }
		system.assertEquals(false, hasErrorMessage.contains(Label.PMC_SS_SalesAgreementtoSalesAreaValidationMessage), 'Has no validation message for salesarea');
    }
}