objects/Account.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_AccountExternalID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Account External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Location.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Plant__c</fullName>
        <description>Indicates Plant Number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Plant</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CPQ_ContractEnd__c</fullName>
        <description>If Master contract exists - then formula to pull the date from Contract reference</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Quote End Date</inlineHelpText>
        <label>Contract Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ContractStart__c</fullName>
        <description>If Master contract exists - then formula to pull the date from Contract reference</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Quote Start Date</inlineHelpText>
        <label>Contract Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to capture the Primary Contact associated with the quote.</description>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.SBQQ__Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CPQ Quotes (Primary Contact1)</relationshipLabel>
        <relationshipName>CPQ_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>Account for which this quote has been created.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PMC_CPQ_CalloutToGetPricingFromSAPTest.cls
/** @description This class is the test class to test the Apex Class which is called at the Calculate Event in 'Get Price'
 *  @author Prakhar
 *  @storynumber GDASF-6819
 */

@isTest
public class PMC_CPQ_CalloutToGetPricingFromSAPTest {
    @isTest
    static void testPostExternalPricing(){
        test.startTest();
        /*
        Account objAccTest = PMC_TestUtilityClass.createAccount('Test Account',Null);
        //objAccTest.Name = 'Test Account';
        objAccTest.PMC_SS_AccountExternalID__c = 'GDASF-6819';
        insert objAccTest;*/
        
        List<Opportunity> opp = PMC_TestUtilityClass.createOpportunity(1, Null);
        //opp.Name = 'Test Opportunity';
        opp[0].CloseDate = System.today().addDays(10);
        update opp;
        
        List<Contact> objConTest = PMC_TestUtilityClass.createContact(1, Null); 
        update objConTest;
        
        Schema.Location testLoc = new Schema.Location();
        testLoc.Name = 'Test Location';
        testLoc.PMC_CPQ_Plant__c = 'Test Plant';
        insert testLoc;
    
        List<Account> listAccount = [SELECT Id,PMC_SS_AccountExternalID__c from Account];
        listAccount[0].PMC_SS_AccountExternalID__c = 'GDASF-6819';
        update listAccount;
        
        
        List<Opportunity> lstopp = [Select id from Opportunity];
        
        List <Contact> listContacts = [SELECT Id from Contact];
        listContacts.get(0).AccountId = listAccount.get(0).Id;
        update listContacts;
        
        List<SBQQ__Quote__c> quotes = new List<SBQQ__Quote__c>();
        Date dateToday = System.today();
        Date dateLater = dateToday.addDays(3);
        SBQQ__Quote__c curquote = new SBQQ__Quote__c(PMC_CPQ_ContractStart__c = dateToday,PMC_CPQ_ContractEnd__c = dateLater,PMC_CPQ_PrimaryContact__c = listContacts[0].Id,SBQQ__Account__c = listAccount[0].Id,SBQQ__Opportunity2__c
 = lstopp[0].id);
        quotes.add(curquote);
        insert curquote;
        
        
        //List<Product2> testProd = PMC_TestUtilityClass.createProduct(1, Null);
        Product2 testProd = new Product2();
        testProd.Name = 'Test Product';
        testProd.StockKeepingUnit = 'Test SKU';
        
        insert testProd;
        
        
        
        List<SBQQ__Quote__c> quoteList = [SELECT Id, Name from SBQQ__Quote__c];

        List<Product2> listProd = [Select id from Product2];
        
        List<Account> testAcnt = [Select id from Account];
        
        List<Schema.Location> locList = [Select id from Location];

        Map<String, String> testData = new Map<String, String>();
        
        testData.put('Transaction_Id', quoteList[0].Name);
        testData.put('Qline1', ('4*' + listProd[0].Id + '*PO298752897*'+locList[0].Id+'*1*2*1*TestQLId*TestPQID*KG*'+testAcnt[0].Id));
        
        String res = PMC_CPQ_CalloutToGetPricingFromSAPClass.postExternalPricing(testData);
        system.assertEquals('100', res, 'Expected response from Callout Class');
        test.stopTest();
    }
}