objects/Account.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_Division__c</fullName>
        <inlineHelpText>For domestic sales, select “Domestic”. For international sales, select “Export”. For transfers between centers or warehouses, select “Intercompany”.</inlineHelpText>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Domestic</fullName>
                </value>
                <value>
                    <fullName>Export</fullName>
                </value>
                <value>
                    <fullName>Intercompany</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Location.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_ProductName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to check product details</description>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PMC_CPQ_ProductLocation__c.object
<CustomObject>
    <description>This object is created as a part of  story to capture product and location data.</description>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created  to check the location details.</description>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Product Locations</relationshipLabel>
        <relationshipName>ProductLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created as a part of story to check the product details.</description>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Locations</relationshipLabel>
        <relationshipName>ProductLocations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PMC_DH_CommerceEntitlementSalesArea__c.object
<CustomObject>
    <description>This Object is used by Mosaic Direct to associate customer specific entitlement products to their corresponding sales area.</description>
    <fields>
        <fullName>PMC_DH_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AccountEntitlementProdSalesAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_DH_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>AccountEntitlementProdSalesAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_DH_SalesArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Area</label>
        <referenceTo>PMC_SS_SalesArea__c</referenceTo>
        <relationshipName>AccountEntitlementProdSalesAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commerce Entitlement Sales Area</label>
    <nameField>
        <displayFormat>CES-{0000000000}</displayFormat>
        <label>CommerceEntSalesArea</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commerce Entitlement Sales Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PMC_DH_Digital_Hub_Restriction_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_Restricted_Value__c</fullName>
        <label>Restricted Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Digital Hub Restriction Setting</label>
    <pluralLabel>Digital Hub Restriction Settings</pluralLabel>
</CustomObject>

objects/PMC_SS_AccountSalesAreaRelationship__c.object
<CustomObject>
    <description>Junction Object to relate Account and Sales Areas</description>
    <fields>
        <fullName>PMC_SS_Account__c</fullName>
        <description>Master Detail relationship between Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>AccountSalesAreRelationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SalesArea__c</fullName>
        <description>Master Detail relationship to Sales Area</description>
        <label>Sales Area</label>
        <referenceTo>PMC_SS_SalesArea__c</referenceTo>
        <relationshipName>AccountSalesAreRelationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Sales Area Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Sales Area Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PMC_SS_SalesArea__c.object
<CustomObject>
    <description>Sales Area Object</description>
    <fields>
        <fullName>PMC_DH_SalesArea__c</fullName>
        <formula>TEXT(PMC_SS_SalesOrganization__c)&amp;&quot; &quot; &amp;  
CASE( TEXT(PMC_SS_Division__c),
					&quot;10&quot;,&quot;Domestic&quot;,
					&quot;20&quot;,&quot;Export&quot;,
					&quot;30&quot;,&quot;Intercompany&quot;,&quot;&quot;) &amp;&quot; &quot;
					&amp; CASE( TEXT(PMC_SS_DistributionChannel__c),
					&quot;0&quot;,&quot;Common&quot;,
					&quot;00&quot;,&quot;Common&quot;,
					&quot;&quot;)</formula>
        <label>Sales Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SS_Division__c</fullName>
        <description>Specifies the Division</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>10</fullName>
                    <label>Domestic</label>
                </value>
                <value>
                    <fullName>20</fullName>
                    <label>Export</label>
                </value>
                <value>
                    <fullName>30</fullName>
                    <label>Intercompany</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Area</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CPQ_ExpiresOn__c</fullName>
        <description>This field captures the Date and Time this quote will be expired</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Indicates the Date and Time this Quote will expire</inlineHelpText>
        <label>Expiration Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>CPQ Quotes</relationshipLabel>
        <relationshipName>CPQ_Quotes_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PrimaryBusinessType__c</fullName>
        <description>This field is to extract business type from Primary Business Type in Quote to use filter on Add product selection page</description>
        <formula>IF(TEXT(PMC_CPQ_QuoteRecordSubType__c)=&quot;International&quot;,&quot;&quot;, IF(
ISPICKVAL( PMC_CPQ_Region__c, &apos;North America&apos;) ,
IF( RecordType.DeveloperName =&apos;PMC_CPQ_International&apos;,&apos;&apos;,
IF(TEXT(PMC_CPQ_QuoteRecordSubType__c)=&quot;Industrial&quot;,&quot;&quot;,
IF( or(TEXT(PMC_CPQ_QuoteRecordSubType__c)=&apos;Co-Products&apos; ,TEXT(PMC_CPQ_QuoteRecordSubType__c)=&apos;Raw Material&apos;),&apos;Co-Product&apos;,
TEXT(PMC_CPQ_QuoteRecordSubType__c))
)
) ,
IF( OR(TRIM(RIGHT( TEXT( PMC_CPQ_QuoteRecordSubType__c ),LEN(TEXT( PMC_CPQ_QuoteRecordSubType__c ))-6) )=&quot;Potash&quot;,
TRIM(RIGHT( TEXT( PMC_CPQ_QuoteRecordSubType__c ),LEN(TEXT( PMC_CPQ_QuoteRecordSubType__c ))-6) )=&quot;Paraguay&quot;),&quot;&quot;,
if(TEXT(PMC_CPQ_QuoteRecordSubType__c)=&apos;B2B_Specialities&apos;,&apos;Co-Product&apos;,TRIM(RIGHT( TEXT( PMC_CPQ_QuoteRecordSubType__c ),LEN(TEXT( PMC_CPQ_QuoteRecordSubType__c ))-6) )))
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Business Type Extractor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product.This is as per the  US GCPM 1064</description>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <infoMessage>Select Product Location Columns Link to add appropriate Locations</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>CPQ Quotes</relationshipLabel>
        <relationshipName>CPQ_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SalesArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Area</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SBQQ__Account__c</field>
                <operation>equals</operation>
                <valueField>PMC_SS_AccountSalesAreaRelationship__c.PMC_SS_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_SS_AccountSalesAreaRelationship__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_PrimaryBusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PMC_CPQ_SalesRegion__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_QuoteBusinessType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SalesArea__c</fullName>
        <description>The Sales Areas associated with the user from which the record type and product will be configured.</description>
        <label>Sales Area</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_SalesAreaUser</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WebCart.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_DH_SalesArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Area</label>
        <referenceTo>PMC_SS_SalesArea__c</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/PMC_CPQ_QuoteBusinessType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Feed</fullName>
    </customValue>
    <customValue>
        <fullName>Fertilizer</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial</fullName>
    </customValue>
    <customValue>
        <fullName>Raw Material</fullName>
    </customValue>
    <customValue>
        <fullName>Co-Products</fullName>
    </customValue>
    <customValue>
        <fullName>B2C - Fertilizer</fullName>
    </customValue>
    <customValue>
        <fullName>B2B - Feed</fullName>
    </customValue>
    <customValue>
        <fullName>B2B - Fertilizer</fullName>
    </customValue>
    <customValue>
        <fullName>B2B - Specialties</fullName>
    </customValue>
    <customValue>
        <fullName>B2C - Paraguay</fullName>
    </customValue>
    <customValue>
        <fullName>B2B - Potash</fullName>
    </customValue>
    <customValue>
        <fullName>International</fullName>
    </customValue>
    <masterLabel>Quote Business Type</masterLabel>
</GlobalValueSet>

classes/PMC_DH_RequestForQuoteHelper.cls
/**
* @description util class for RFQ
* @author hemant giri goswami
* @since  07-27-2023
*/
public without sharing class PMC_DH_RequestForQuoteHelper {
    Private Static Final Set<String> SETSALESAREADIVISION = new Set<String>{'10'};
    /*************************************************************************
* @method Name  : getQuoteRecordType 
* @description  : Method to create the quote Record type id
* @param       	strUserRegion  
* @return       : String
*****************************************************************************/
    public static String getQuoteRecordType(String strUserRegion){
        String strQuoteRecId='';        
    //strQuoteRecId= Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByName().get(system.label.PMC_DH_DomesticNa).getRecordTypeId();
        strQuoteRecId=[SELECT ID FROM RECORDTYPE WHERE NAME=:PMC_DH_ConstantClass.DOMESTIC_NA AND SobjectType=:PMC_DH_ConstantClass.QUOTE_SOBJECT_TYPE WITH SECURITY_ENFORCED LIMIT 1].id;
        if(strUserRegion=='BR'){
        //  strQuoteRecId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByName().get('Domestic SA').getRecordTypeId();
            strQuoteRecId=[SELECT ID FROM RECORDTYPE WHERE NAME=: PMC_DH_ConstantClass.DOMESTIC_SA AND SobjectType=:PMC_DH_ConstantClass.QUOTE_SOBJECT_TYPE WITH SECURITY_ENFORCED LIMIT 1].id;

        }
        return strQuoteRecId;
    }
    
    /*************************************************************************
* @method Name  : getAccSalesAreaJuncId
* @description  : Method to get the Id of Account Sales Area Relationship junction object
* @param 		  effAccId
* @param		  setSalesArea
* @return       : String
*****************************************************************************/
    public static Id getAccSalesAreaJuncId(String effAccId, set<String> setSalesArea){
        String accSalesAreaJuncId;
        List<PMC_SS_AccountSalesAreaRelationship__c> lstAccSalesAreaJunc = [SELECT Id FROM PMC_SS_AccountSalesAreaRelationship__c
                                                                            WHERE PMC_SS_Account__c =: effAccId
                                                                            AND PMC_SS_SalesArea__r.PMC_DH_SalesArea__c IN: setSalesArea WITH SECURITY_ENFORCED];
        if(!lstAccSalesAreaJunc.isEmpty()){
            accSalesAreaJuncId = lstAccSalesAreaJunc[0].Id;
        }
        return accSalesAreaJuncId;
    }
    
    
    /*************************************************************************
* @method Name  : getExpiryDate
* @description  : Method to get Expiry Date
* @param       	quoteDetails 
*@param 		quoteStatusWrapper
* @return       : PMC_DH_QuoteMgmtActionController.PMC_DH_QuoteStatusWrapper
*****************************************************************************/
    
    public  static  PMC_DH_QuoteMgmtActionController.PMC_DH_QuoteStatusWrapper getExpiryDate(SBQQ__Quote__c quoteDetails,PMC_DH_QuoteMgmtActionController.PMC_DH_QuoteStatusWrapper quoteStatusWrapper)
    {
        PMC_DH_QuoteMgmtActionController.PMC_DH_QuoteStatusWrapper objQuoteWrapper=new PMC_DH_QuoteMgmtActionController.PMC_DH_QuoteStatusWrapper();
        objQuoteWrapper.strProgressIndicatorStatus=quoteStatusWrapper.strProgressIndicatorStatus;
        objQuoteWrapper.strSummaryStatus=quoteStatusWrapper.strSummaryStatus; 
        if(quoteDetails.PMC_CPQ_ExpiresOn__c!=null){
            if((system.now()<quoteDetails.PMC_CPQ_ExpiresOn__c) && (quoteDetails.SBQQ__Status__c==PMC_DH_ConstantClass.PRESENTED)){
                String gmtFormattedStringExp =quoteDetails.PMC_CPQ_ExpiresOn__c.formatGMT(PMC_DH_ConstantClass.GMT_FORMAT);
                objQuoteWrapper.datTExpiresIn=DateTime.valueOfGMT(gmtFormattedStringExp);
                
                String gmtFormattedString =DateTime.now().formatGMT(PMC_DH_ConstantClass.GMT_FORMAT);
                objQuoteWrapper.datTCurrentDateTime= DateTime.valueOfGMT(gmtFormattedString);
            }
            else  if(quoteDetails.SBQQ__Status__c==PMC_DH_ConstantClass.STATUS_EXPIRED) {
                
                objQuoteWrapper.strProgressIndicatorStatus=PMC_DH_ConstantClass.REJECTED;
                objQuoteWrapper.strSummaryStatus=PMC_DH_ConstantClass.ACCOUNT_INACTIVE_STATUS;
            }
        }
        return objQuoteWrapper;
    }
    
    
    /*************************************************************************
* @method Name  : getQuoteRecordTypeName
* @description  : Method to get Recordtype name   
* @return       : String
*****************************************************************************/
    public static String getQuoteRecordTypeName()
    {   String strTemplabel;
        String strTempVar;
        String strUserId=userInfo.getUserId();
        List<User> lstUser=PMC_DH_UserUtil.getUserData(strUserId);
        String strUserRegion = PMC_DH_CommonSystemUtils.getUserRegion(lstUser[0].country);
        String strRecordTypeId = PMC_DH_RequestForQuoteHelper.getQuoteRecordType(strUserRegion);
        String strRecordTypeName = [SELECT Id,name from RecordType WHERE id =: strRecordTypeId][0].Name;
        strTempVar=strRecordTypeName.replace(' ','');
        strTemplabel=System.label.get(null,strRecordTypeName=PMC_DH_ConstantClass.LABEL_HEADER+strTempVar,userinfo.getLocale());// added as fix for translation GPT-29606
        return strTemplabel;
    }  
    /*************************************************************************
* @method Name  : getUserBusinessType
* @description  : Method to get BusinessType name   
* @param effAccId
* @return       : String
*****************************************************************************/
    public static String getUserBusinessType(String effAccId){
        String strBusinessType='';
        String strAMUserId= [SELECT Id,OwnerId FROM Account WHERE Id =: effAccId WITH SYSTEM_MODE LIMIT 1].OwnerId;
        User userAM = [SELECT Id, PMC_CPQ_PrimaryBusinessType__c, PMC_CPQ_SalesArea__c FROM User WHERE Id =: strAMUserId WITH SYSTEM_MODE LIMIT 1]; 
        if(userAM.PMC_CPQ_PrimaryBusinessType__c!=null){
            String strTemp=PMC_DH_ConstantClass.LABEL_HEADER+userAM.PMC_CPQ_PrimaryBusinessType__c.replace('-','').replace(' ','');
            //String strLabelName=PMC_DH_ConstantClass.LABEL_HEADER+strTemp2; // added as fix for translation GPT-29606
            strBusinessType = System.label.get(null,strTemp,userinfo.getLocale());//userAM.PMC_CPQ_PrimaryBusinessType__c;
            //strBusinessType=userAM.PMC_CPQ_PrimaryBusinessType__c;
        }
        return strBusinessType;
        
    }

    
    /**
* @description method to handle validation
* @param lstProductLocation 
* @param mapShipFrom        
* @return                   `Map<String,List<PMC_DH_PicklistWrapper>>`
*/
    public static Map<String,List<PMC_DH_PicklistWrapper>> getShipFromValidation(List<PMC_CPQ_ProductLocation__c> lstProductLocation,Map<String,List<PMC_DH_PicklistWrapper>> mapShipFrom)
    {
        PMC_DH_PicklistWrapper shipFrom;
        if(!lstProductLocation.isEmpty()){
            for(PMC_CPQ_ProductLocation__c loc : lstProductLocation){
                
                shipFrom = new PMC_DH_PicklistWrapper();
                shipFrom.label = loc.PMC_CPQ_Location__r.Name;
                shipFrom.value = loc.Id;
                if(!mapShipFrom.containsKey(loc.PMC_CPQ_ProductName__r.StockKeepingUnit))
                {
                    mapShipFrom.put(loc.PMC_CPQ_ProductName__r.StockKeepingUnit,new List<PMC_DH_PicklistWrapper>());
                }
                mapShipFrom.get(loc.PMC_CPQ_ProductName__r.StockKeepingUnit).add(shipFrom); 
            }
        }
        return mapShipFrom;
    }
    /**
* @description Method to handle restricted rules for incoterms
* @param strCategory
* @return Map<String, Set<String>>
*/
    
    public static Map<String, Set<String>> getRestrictionRulesForIncoterm(String strCategory) {
        Map<String, Set<String>> mapOfIncoterm = new Map<String,Set<String>>();
        List<PMC_DH_Digital_Hub_Restriction_Setting__mdt> lstRules= [SELECT PMC_DH_Category__c, PMC_DH_Type__c, PMC_DH_Restricted_Value__c  FROM PMC_DH_Digital_Hub_Restriction_Setting__mdt WHERE PMC_DH_Category__c=:strCategory WITH SECURITY_ENFORCED ];
        for(PMC_DH_Digital_Hub_Restriction_Setting__mdt key : lstRules){
            if(!mapOfIncoterm.containsKey(key.PMC_DH_Type__c)){
                mapOfIncoterm.put(key.PMC_DH_Type__c, new Set<String>());       
            }
            mapOfIncoterm.get(key.PMC_DH_Type__c).add(key.PMC_DH_Restricted_Value__c);       
        }
        return mapOfIncoterm;
    }
    
    
    /*************************************************************************
* @method Name  : getSalesAreaForCart
* @description  : Method to get the Sales area 
* @param 		  strCartId
* @return       : PMC_DH_SalesAreaForCartWrapper
*****************************************************************************/
    
    public static PMC_DH_SalesAreaForCartWrapper getSalesAreaForCart(String strCartId){
        PMC_DH_SalesAreaForCartWrapper salesAreaCartWrapper=new PMC_DH_SalesAreaForCartWrapper();
        try{
            Set<String> setProdIds = new Set<String>();
            Set<String> setSalesAreaIds = new Set<String>();
            List<Cartitem> lstCartItem = [SELECT Id, Product2Id, Cart.AccountId FROM CartItem WHERE CartId =: strCartId WITH SECURITY_ENFORCED];
            if(!lstCartItem.isEmpty()){
                String accountId = lstCartItem[0].Cart.AccountId;
                for(CartItem ci : lstCartItem){
                    setProdIds.add(ci.Product2Id);
                }
                List<PMC_DH_CommerceEntitlementSalesArea__c> lstCESalesArea = [SELECT Id, PMC_DH_SalesArea__c FROM PMC_DH_CommerceEntitlementSalesArea__c
                                                                            WHERE PMC_DH_Account__c =: accountId 
                                                                            AND PMC_DH_Product__c IN: setProdIds AND PMC_DH_SalesArea__r.PMC_SS_Division__c IN :SETSALESAREADIVISION
                                                                            WITH SECURITY_ENFORCED];
                for(PMC_DH_CommerceEntitlementSalesArea__c cesa : lstCESalesArea){
                    setSalesAreaIds.add(cesa.PMC_DH_SalesArea__c);
                }
                salesAreaCartWrapper.boolIsPriceEnabled=false;
                if(setSalesAreaIds.size()==1)
                {
                    List<String> lstSalesArea = new List<String>(setSalesAreaIds);
                    salesAreaCartWrapper.boolIsPriceEnabled=true;
                    salesAreaCartWrapper.strSalesArea=lstSalesArea.get(0);
                }
            } 
        }
        catch(Exception ex){
            PMC_ErrorLogClass.processException(ex);// MDErrorLog
        }
        return salesAreaCartWrapper;
    }
    
    /**
* @description  wrapper class for Sales Area Info
* @author Humera
* @since 10-10-2023
*/ 
// added with sharing
    public with sharing class PMC_DH_SalesAreaForCartWrapper{
        /**
* @description Sales Area
* @return String
*/
        public string strSalesArea{get;set;}
        /**
* @description Price widget visibility
* @return Boolean
*/
        public Boolean boolIsPriceEnabled{get;set;}
    }
    
/*************************************************************************
* @method Name  : shareRecordWithPortalUser
* @description   :This method is used to share the opportunity record 
* @param 		  strQuoteId
* @return         Boolean
* @author       : Humera
*****************************************************************************/
    public  static Boolean shareRecordWithPortalUser(String strQuoteId){
        Boolean boolIsShared=false;
        try{
            String strOppId =[SELECT SBQQ__Opportunity2__c FROM sbqq__quote__c WHERE ID=:strQuoteId WITH SECURITY_ENFORCED][0].SBQQ__Opportunity2__c;
            If(string.isnotBlank(strOppId)){
                OpportunityShare objOppShare = new OpportunityShare();
                objOppShare.OpportunityId = strOppId;
                objOppShare.UserOrGroupId = UserInfo.getUserId();
                objOppShare.OpportunityAccessLevel = PMC_DH_ConstantClass.EDIT;
                objOppShare.RowCause = Schema.OpportunityShare.RowCause.Manual;
                boolIsShared=PMC_DH_RequestForQuoteUtil.insertOpportunityShare(objOppShare);
            }
        }
        Catch(Exception ex){
            PMC_ErrorLogClass.processException(ex); // MDErrorLog
        }
        return boolIsShared;
    }
    /**
    * @description stampOwner
    * @author Hemant Giri Goswami | hegoswami@deloitte.com | 01-20-2024 
    * @param objQuote 
    * @param objWebCart 
    **/
    public static void stampOwner(SBQQ__Quote__c objQuote,WebCart objWebCart)
    {
        if(Schema.sObjectType.SBQQ__Quote__c.isUpdateable()){
            objQuote.OwnerId = objWebCart.PMC_DH_Account__r.OwnerId;
            update objQuote;
        }
    }
    
    
}