objects/Account.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_isProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a flag field, which will indicate if this account record is already processed or not</description>
        <label>Is Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_SS_Division__c</fullName>
        <inlineHelpText>For domestic sales, select “Domestic”. For international sales, select “Export”. For transfers between centers or warehouses, select “Intercompany”.</inlineHelpText>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Domestic</fullName>
                </value>
                <value>
                    <fullName>Export</fullName>
                </value>
                <value>
                    <fullName>Intercompany</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_CPQ_ProductSalesArea__c.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>ProductSalesAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Sales_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Area</label>
        <referenceTo>PMC_SS_SalesArea__c</referenceTo>
        <relationshipName>ProductSalesAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Sales Area</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Product Sales Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Sales Areas</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PMC_SS_AccountSalesAreaRelationship__c.object
<CustomObject>
    <description>Junction Object to relate Account and Sales Areas</description>
    <fields>
        <fullName>PMC_SS_Account__c</fullName>
        <description>Master Detail relationship between Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>AccountSalesAreRelationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SalesArea__c</fullName>
        <description>Master Detail relationship to Sales Area</description>
        <label>Sales Area</label>
        <referenceTo>PMC_SS_SalesArea__c</referenceTo>
        <relationshipName>AccountSalesAreRelationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Sales Area Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Sales Area Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PMC_SS_SalesArea__c.object
<CustomObject>
    <description>Sales Area Object</description>
    <fields>
        <fullName>PMC_SS_Division__c</fullName>
        <description>Specifies the Division</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>10</fullName>
                    <label>Domestic</label>
                </value>
                <value>
                    <fullName>20</fullName>
                    <label>Export</label>
                </value>
                <value>
                    <fullName>30</fullName>
                    <label>Intercompany</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Area</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Nitrogen__c</fullName>
        <description>This field captures the Nitrogen % for the product.</description>
        <inlineHelpText>This field captures the Nitrogen % for the product.</inlineHelpText>
        <label>Nitrogen %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Phosphorous__c</fullName>
        <description>This field captures the Phosphorous % for the product.</description>
        <inlineHelpText>This field captures the Phosphorous % for the product.</inlineHelpText>
        <label>Phosphorous %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Potassium__c</fullName>
        <description>This field captures the Potassium % for the product.</description>
        <inlineHelpText>This field captures the Potassium % for the product.</inlineHelpText>
        <label>Potassium %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductSalesArea__c</fullName>
        <label>Product Sales Area</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_SalesAreaUser</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_Micronutrients__c</fullName>
        <description>This field was created as part of story to handle/manage value for Micronutrient</description>
        <label>Micronutrient</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Boron</fullName>
                </value>
                <value>
                    <fullName>Chlorine</fullName>
                </value>
                <value>
                    <fullName>Cobalt</fullName>
                </value>
                <value>
                    <fullName>Copper</fullName>
                </value>
                <value>
                    <fullName>Iron</fullName>
                </value>
                <value>
                    <fullName>Manganese</fullName>
                </value>
                <value>
                    <fullName>Molybdenum</fullName>
                </value>
                <value>
                    <fullName>Silicone</fullName>
                </value>
                <value>
                    <fullName>Zinc</fullName>
                </value>
                <value>
                    <fullName>Calcium</fullName>
                </value>
                <value>
                    <fullName>Magnesium</fullName>
                </value>
                <value>
                    <fullName>Sulfur</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_Nitrogen__c</fullName>
        <label>Nitrogen(N)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0-5%</fullName>
                </value>
                <value>
                    <fullName>06-10%</fullName>
                </value>
                <value>
                    <fullName>11-15%</fullName>
                </value>
                <value>
                    <fullName>16-20%</fullName>
                </value>
                <value>
                    <fullName>21-25%</fullName>
                </value>
                <value>
                    <fullName>26-30%</fullName>
                </value>
                <value>
                    <fullName>31-35%</fullName>
                </value>
                <value>
                    <fullName>36-40%</fullName>
                </value>
                <value>
                    <fullName>41-45%</fullName>
                </value>
                <value>
                    <fullName>46-50%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_Phosphorous__c</fullName>
        <label>Phosphorous (P)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0-5%</fullName>
                </value>
                <value>
                    <fullName>06-10%</fullName>
                </value>
                <value>
                    <fullName>11-15%</fullName>
                </value>
                <value>
                    <fullName>16-20%</fullName>
                </value>
                <value>
                    <fullName>21-25%</fullName>
                </value>
                <value>
                    <fullName>26-30%</fullName>
                </value>
                <value>
                    <fullName>31-35%</fullName>
                </value>
                <value>
                    <fullName>36-40%</fullName>
                </value>
                <value>
                    <fullName>41-45%</fullName>
                </value>
                <value>
                    <fullName>46-50%</fullName>
                </value>
                <value>
                    <fullName>51-55%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_Potassium__c</fullName>
        <label>Potassium (K)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0-5%</fullName>
                </value>
                <value>
                    <fullName>06-10%</fullName>
                </value>
                <value>
                    <fullName>11-15%</fullName>
                </value>
                <value>
                    <fullName>16-20%</fullName>
                </value>
                <value>
                    <fullName>21-25%</fullName>
                </value>
                <value>
                    <fullName>26-30%</fullName>
                </value>
                <value>
                    <fullName>31-35%</fullName>
                </value>
                <value>
                    <fullName>36-40%</fullName>
                </value>
                <value>
                    <fullName>41-45%</fullName>
                </value>
                <value>
                    <fullName>46-50%</fullName>
                </value>
                <value>
                    <fullName>51-55%</fullName>
                </value>
                <value>
                    <fullName>56-60%</fullName>
                </value>
                <value>
                    <fullName>61-65%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_isProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a flag field, which will indicate if this product record is already processed or not</description>
        <label>Is Processed</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PMC_DH_ProductOnboardingBatchHelper.cls
/**
* @description       : Batch Helper Class for Product Onboarding
* @author            : Rohan Undale
* @last modified on  : 01-09-2024
* @last modified by  : Hemant Giri Goswami | hegoswami@deloitte.com
**/
public with sharing class PMC_DH_ProductOnboardingBatchHelper {
    private static final Set<String> SETSALESAREADIVISION = new Set<String>{'10'};
    public final static String DEFAULT_IMAGE='Default Product Image';
    /**
    * @description 
    * @author Hemant Giri Goswami | hegoswami@deloitte.com | 10-22-2023 
    * @param lstProducts 
    **/
    public static void executeHelper(List<Product2> lstProducts){
        try{
            Set<String> setProductIds = new Set<String>();
            Set<Id> setAllBuyerGroupIds = new Set<Id>();
            Map<Id, Set<Id>> mapAccountProducts = new Map<Id, Set<Id>>();
            Map<Id, Set<Id>> mapBuyerGroupMembers = new Map<Id, Set<Id>>();
            Map<Id, Set<Id>> mapEntitlementBuyerGroups = new Map<Id, Set<Id>>();
            Map<Id,Set<Id>> mapAcctoEntPolicies = new Map<Id,Set<Id>>();
            Map<Id,Set<Id>> mapProdEnableEntPolicies = new Map<Id, Set<Id>>();
            
            Schema.DescribeFieldResult fieldResultNitrogen = Product2.PMC_DH_Nitrogen__c.getDescribe();
            Map<Integer,String> mapPicklistNitrogen = PMC_DH_ProductOnboardingBatchUtil.getPicklistValueMap(fieldResultNitrogen);

            Schema.DescribeFieldResult fieldResultPhosphorous = Product2.PMC_DH_Phosphorous__c.getDescribe();
            Map<Integer,String> mapPicklistPhosphorous = PMC_DH_ProductOnboardingBatchUtil.getPicklistValueMap(fieldResultPhosphorous);

            Schema.DescribeFieldResult fieldResultPotassium = Product2.PMC_DH_Potassium__c.getDescribe();
            Map<Integer,String> mapPicklistPotassium = PMC_DH_ProductOnboardingBatchUtil.getPicklistValueMap(fieldResultPotassium);
            PMC_DH_ProductOnboardingBatchUtil.executeProductProcessing( lstProducts); //to-do have to pass list of prod with category assigned
            //system.debug('categ and media linked:');
            for(Product2 prodItem:lstProducts)
            {
                setProductIds.add(prodItem.Id);
                prodItem.PMC_DH_isProcessed__c = true;
                prodItem.PMC_DH_Nitrogen__c = prodItem.PMC_CPQ_Nitrogen__c != NULL ? PMC_DH_ProductOnboardingBatchUtil.getMatchingPicklistValue(mapPicklistNitrogen, Integer.valueOf(prodItem.PMC_CPQ_Nitrogen__c)) : NULL;
                prodItem.PMC_DH_Phosphorous__c = prodItem.PMC_CPQ_Phosphorous__c != NULL ? PMC_DH_ProductOnboardingBatchUtil.getMatchingPicklistValue(mapPicklistPhosphorous, Integer.valueOf(prodItem.PMC_CPQ_Phosphorous__c)) : NULL;
                prodItem.PMC_DH_Potassium__c = prodItem.PMC_CPQ_Potassium__c != NULL ? PMC_DH_ProductOnboardingBatchUtil.getMatchingPicklistValue(mapPicklistPotassium, Integer.valueOf(prodItem.PMC_CPQ_Potassium__c)) : NULL;
                prodItem.PMC_DH_Micronutrients__c = PMC_DH_ProductOnboardingBatch.populateMicroNutrinents(prodItem);
                
            }
            
            Set<String> setAccountIds = getAccountIdSet(setProductIds, mapAccountProducts);
            mapBuyerGroupMembers = getBuyerGroupMembersMap(setAccountIds, setAllBuyerGroupIds);
            mapEntitlementBuyerGroups = getEntitlementBuyerGroupMap(setAllBuyerGroupIds);
            for(String strAccountId : setAccountIds){
                Set<Id> setAccountEntPolicies = getAccountEntPoliciesIdsSet(mapBuyerGroupMembers, mapEntitlementBuyerGroups, strAccountId);
                mapAcctoEntPolicies.put(strAccountId, setAccountEntPolicies);
            }
            mapProdEnableEntPolicies = getMapProdEnableEntPolicies(mapAcctoEntPolicies, mapAccountProducts);        
            insertProductEntitlementRecords(mapProdEnableEntPolicies);
            
            if(Schema.sObjectType.Product2.isUpdateable()){
                Database.update(lstProducts, false);
            }
        }
        Catch(Exception ex){
            //System.debug(ex.getLineNumber()+ex.getMessage()+ex.getStackTraceString()+ex.getCause());
            throw new AuraHandledException(ex.getMessage());
        }
    }

    /**
    * @description  get Account Id Set
    * @param setProductIds
    * @param mapAccountProducts
    * @return Set<String>
    * @date 2023-09-14
    */ 
    public static Set<String> getAccountIdSet(Set<String> setProductIds, Map<Id, Set<Id>> mapAccountProducts){
        List<PMC_CPQ_ProductSalesArea__c> lstProductSalesArea = [SELECT Id, Name, PMC_CPQ_Product__c, PMC_CPQ_Sales_Area__c
                                                                FROM PMC_CPQ_ProductSalesArea__c
                                                                WHERE PMC_CPQ_Product__c IN :setProductIds
                                                                AND PMC_CPQ_Sales_Area__r.PMC_SS_Division__c IN :SETSALESAREADIVISION
                                                                WITH SYSTEM_MODE];
        List<String> lstSalesArea = new List<String>();
        for(PMC_CPQ_ProductSalesArea__c psa : lstProductSalesArea){
            lstSalesArea.add(psa.PMC_CPQ_Sales_Area__c);
        }
        
        List<PMC_SS_AccountSalesAreaRelationship__c> lstAccountSalesAreaRelationship = [SELECT Id, Name, PMC_SS_Account__c, PMC_SS_SalesArea__c
                                                                                        FROM PMC_SS_AccountSalesAreaRelationship__c
                                                                                        WHERE PMC_SS_SalesArea__c IN :lstSalesArea
                                                                                        AND PMC_SS_Account__r.IsBuyer=TRUE AND PMC_SS_Account__r.Type='Sold-to' //Need review on this
                                                                                        WITH SYSTEM_MODE];
        Set<String> setAccountIds = new Set<String>();
        for(PMC_SS_AccountSalesAreaRelationship__c asar : lstAccountSalesAreaRelationship){
            setAccountIds.add(asar.PMC_SS_Account__c);
            for(PMC_CPQ_ProductSalesArea__c psa : lstProductSalesArea){
                if(asar.PMC_SS_SalesArea__c == psa.PMC_CPQ_Sales_Area__c){
                    if(!mapAccountProducts.containsKey(asar.PMC_SS_Account__c)){
                        mapAccountProducts.put(asar.PMC_SS_Account__c, new Set<Id>());
                    }
                    mapAccountProducts.get(asar.PMC_SS_Account__c).add(psa.PMC_CPQ_Product__c);
                }
            }
        }
        return setAccountIds;
    }

    /**
    * @description  To get the Map Buyer and  BuyerGroup Memeber Map
    * @param setAccountIds
    * @param setAllBuyerGroupIds
    * @return Map<Id, Set<Id>>
    * @date 2023-09-14
    */ 
    public static Map<Id,Set<Id>> getBuyerGroupMembersMap(Set<String> setAccountIds, Set<Id> setAllBuyerGroupIds){
        List<BuyerGroupMember> lstBuyerGroupMembers= [SELECT Id,Name, BuyerGroupId, BuyerId 
                                                      FROM BuyerGroupMember 
                                                      WHERE  BuyerId in: setAccountIds 
                                                      WITH SYSTEM_MODE 
                                                      ORDER BY BuyerGroupId];
        
        Map<Id, Set<Id>> mapBuyerGroupMembers = new Map<Id, Set<Id>>();
        for(BuyerGroupMember objBuyerGroupMem : lstBuyerGroupMembers){
            if(!mapBuyerGroupMembers.containsKey(objBuyerGroupMem.BuyerId)){
                mapBuyerGroupMembers.put(objBuyerGroupMem.BuyerId, new Set<Id>());
            }
            mapBuyerGroupMembers.get(objBuyerGroupMem.BuyerId).add(objBuyerGroupMem.BuyerGroupId);
            setAllBuyerGroupIds.add(objBuyerGroupMem.BuyerGroupId);
        }
        return mapBuyerGroupMembers;
    }

    /**
    * @description get the Entitlement and Buyer Group Map
    * @param setAllBuyerGroupIds
    * @return Map<Id, Set<Id>>
    * @date 2023-09-14
    */
    public static  Map<Id, Set<Id>> getEntitlementBuyerGroupMap(Set<Id> setAllBuyerGroupIds){
        Map<Id, Set<Id>>  mapEntitlementBuyerGroups = new Map<Id, Set<Id>>();
        List<CommerceEntitlementBuyerGroup> lstEntitlementPolicies = [SELECT Id, Name, PolicyId, BuyerGroupId 
                                                                    FROM CommerceEntitlementBuyerGroup 
                                                                    WHERE BuyerGroupId IN:setAllBuyerGroupIds 
                                                                    WITH SYSTEM_MODE  Order BY BuyerGroupId];
        
        for(CommerceEntitlementBuyerGroup objEntitlementBuyerGroups : lstEntitlementPolicies){
            if(!mapEntitlementBuyerGroups.containsKey(objEntitlementBuyerGroups.BuyerGroupId)){
                mapEntitlementBuyerGroups.put(objEntitlementBuyerGroups.BuyerGroupId, new Set<Id>());
            }
            mapEntitlementBuyerGroups.get(objEntitlementBuyerGroups.BuyerGroupId).add(objEntitlementBuyerGroups.PolicyId);
        }
        return mapEntitlementBuyerGroups;
    }

    /**
    * @description  To get the Map Buyer and  BuyerGroup Memeber Map
    * @param mapBuyerGroupMembers
    * @param mapEntitlementBuyerGroups
    * @param strAccountId
    * @return Set<Id>
    * @date 2023-10-25
    */
    public static Set<Id> getAccountEntPoliciesIdsSet(Map<Id, Set<Id>> mapBuyerGroupMembers, Map<Id, Set<Id>> mapEntitlementBuyerGroups, String strAccountId){
        Set<Id> setAccountEntPolicies = new Set<Id>();
        if(mapBuyerGroupMembers.containsKey(strAccountId)){
            for(Id strBuyerGroupId : mapBuyerGroupMembers.get(strAccountId)){
                if(mapEntitlementBuyerGroups.containsKey(strBuyerGroupId)){
                    setAccountEntPolicies.addAll(mapEntitlementBuyerGroups.get(strBuyerGroupId));
                }
            }
        }
        return setAccountEntPolicies;
    }

    /**
    * @description  To get the Map Buyer and  BuyerGroup Memeber Map
    * @param mapAcctoEntPolicies
    * @param mapAccountProducts
    * @return Map<Id,Set<Id>>
    * @date 2023-10-25
    */
    public static Map<Id,Set<Id>> getMapProdEnableEntPolicies(Map<Id,Set<Id>> mapAcctoEntPolicies, Map<Id, Set<Id>> mapAccountProducts){
        Map<Id,Set<Id>> mapProdEnableEntPolicies = new Map<Id, Set<Id>>();
        Set<Id> setAccountIds = mapAcctoEntPolicies.keySet();
        for(String strAccountId : setAccountIds){
            Set<Id> setProductIds = mapAccountProducts.get(strAccountId);
            for(Id prodId : setProductIds){
                if(!mapProdEnableEntPolicies.containsKey(prodId)){
                    mapProdEnableEntPolicies.put(prodId, new Set<Id>());
                }
                mapProdEnableEntPolicies.get(prodId).addAll(mapAcctoEntPolicies.get(strAccountId));
            }
        }
        return mapProdEnableEntPolicies;
    }

    /**
    * @description Insert the Product Entitlement Record
    * @param mapProdEnableEntPolicies
    * @date 2023-10-25
    */
    public static void insertProductEntitlementRecords(Map<Id,Set<Id>> mapProdEnableEntPolicies){
        Map<Id,Set<Id>> mapProdToExistingEntPolicies = new Map<Id,Set<Id>>();
        List<CommerceEntitlementProduct> lstCommEntProdToInsert = new List<CommerceEntitlementProduct>();
        List<CommerceEntitlementProduct> lstCommEntProd = PMC_DH_ProductOnboardingBatchUtil.getEntitlementRecords(mapProdEnableEntPolicies);
        
        for (CommerceEntitlementProduct objEntProd : lstCommEntProd){
            if(!mapProdToExistingEntPolicies.containsKey(objEntProd.ProductId)){
                mapProdToExistingEntPolicies.put(objEntProd.ProductId, new Set<Id>());
            }
            mapProdToExistingEntPolicies.get(objEntProd.ProductId).add(objEntProd.PolicyId);
        }
        
        Map<Id,Set<Id>> mapProdToNonExistingEntPolicies = new Map<Id,Set<Id>>();
        mapProdToNonExistingEntPolicies = PMC_DH_ProductOnboardingBatchUtil.fetchProdToNonExistingEntPoliciesMap(mapProdToExistingEntPolicies, mapProdEnableEntPolicies);
        
        for(String strProdId : mapProdToNonExistingEntPolicies.keySet()){
            for(String strPolicyId : mapProdToNonExistingEntPolicies.get(strProdId)){
                CommerceEntitlementProduct objCommEntProd = new CommerceEntitlementProduct();
                objCommEntProd.PolicyId = strPolicyId;
                objCommEntProd.ProductId = strProdId;
                lstCommEntProdToInsert.add(objCommEntProd);
            }
        }
        
        if( !lstCommEntProdToInsert.isEmpty() && Schema.sObjectType.CommerceEntitlementProduct.isCreateable()){
            Database.insert(lstCommEntProdToInsert, false); 
        }
    }

   /**
    * @description getElectronicMediaId
    * @param strCategory
    * @param mapContentKey
    * @return string
    * @date 2023-10-25
    */
    public static string getElectronicMediaId(String strCategory, Map<String,String> mapContentKey){
        if(mapContentKey.containsKey(strCategory)){
            return mapContentKey.get(strCategory);
        }else{
            return mapContentKey.get(DEFAULT_IMAGE);
        }
    }

}