objects/Account.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_Segmentation__c</fullName>
        <description>Segmentation the Customer belongs to.</description>
        <label>Segmentation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>14</fullName>
                    <label>14 - Base</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>10 - Canal - KAM</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>13 - Core</label>
                </value>
                <value>
                    <fullName>09</fullName>
                    <label>9 - Canal - Basic / Grow</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>3 - EU - KAM Mega Farmer</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>4 - EU - Mega Farmer</label>
                </value>
                <value>
                    <fullName>07</fullName>
                    <label>7 - Canal - Prime</label>
                </value>
                <value>
                    <fullName>06</fullName>
                    <label>6 - EU - Farmer/Mid/Small</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <label>12 - Strategic</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>5 - EU - Top Farmer</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <label>11 - Trader - KAM</label>
                </value>
                <value>
                    <fullName>08</fullName>
                    <label>8 - Canal - Ultra</label>
                </value>
                <value>
                    <fullName>A</fullName>
                    <label>A - Customer</label>
                </value>
                <value>
                    <fullName>B</fullName>
                    <label>B - Customer</label>
                </value>
                <value>
                    <fullName>C</fullName>
                    <label>C - Customer</label>
                </value>
                <value>
                    <fullName>Basic</fullName>
                    <isActive>false</isActive>
                    <label>Canal-Basic/Grow</label>
                </value>
                <value>
                    <fullName>Farmers</fullName>
                    <isActive>false</isActive>
                    <label>Farmers</label>
                </value>
                <value>
                    <fullName>Mid Farmers</fullName>
                    <isActive>false</isActive>
                    <label>Mid Farmers</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_IssueReason__c</fullName>
        <description>Specifies the reason of the issue</description>
        <inlineHelpText>Contract Cancellation, Product request, Credit Request, Financial Solution and Anticipated Billing are for Brazil users ONLY</inlineHelpText>
        <label>Issue Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Account Issues</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Article Request</fullName>
                </value>
                <value>
                    <fullName>Call by Date</fullName>
                </value>
                <value>
                    <fullName>Cambio Exhange</fullName>
                </value>
                <value>
                    <fullName>Change to loading priorities</fullName>
                </value>
                <value>
                    <fullName>Consignment</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                    <label>Contract Cancellation</label>
                </value>
                <value>
                    <fullName>Credit Note Request</fullName>
                </value>
                <value>
                    <fullName>Credit Request</fullName>
                </value>
                <value>
                    <fullName>Data Entry</fullName>
                </value>
                <value>
                    <fullName>Debit Note Request</fullName>
                </value>
                <value>
                    <fullName>Delivery Delay</fullName>
                </value>
                <value>
                    <fullName>Demurrage</fullName>
                </value>
                <value>
                    <fullName>Diversion</fullName>
                </value>
                <value>
                    <fullName>Document Request</fullName>
                </value>
                <value>
                    <fullName>Donation Order/Bonus</fullName>
                </value>
                <value>
                    <fullName>Driver Verification/Change</fullName>
                </value>
                <value>
                    <fullName>Equipment Failure</fullName>
                </value>
                <value>
                    <fullName>Export Documentation</fullName>
                </value>
                <value>
                    <fullName>Export prioritization</fullName>
                </value>
                <value>
                    <fullName>Financial Solution</fullName>
                </value>
                <value>
                    <fullName>Include Script CIF</fullName>
                </value>
                <value>
                    <fullName>Incorrect Destination</fullName>
                </value>
                <value>
                    <fullName>Incorrect Label</fullName>
                </value>
                <value>
                    <fullName>Incorrect Product</fullName>
                </value>
                <value>
                    <fullName>Incorrect UOM</fullName>
                </value>
                <value>
                    <fullName>Incorrect Vehicle ID</fullName>
                </value>
                <value>
                    <fullName>IntelliTrans</fullName>
                </value>
                <value>
                    <fullName>Invoice Adjustments</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_SS_CasePriorityAssignment__mdt.object
<CustomObject>
    <description>This metadata is used to set the Case priority based on Case Type And Account Segmentation.</description>
    <fields>
        <fullName>PMC_SS_IssueReason__c</fullName>
        <label>Issue Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery Delay</fullName>
                </value>
                <value>
                    <fullName>Missing Cargo</fullName>
                </value>
                <value>
                    <fullName>Incorrect Destination</fullName>
                </value>
                <value>
                    <fullName>Ship Date / Scheduling</fullName>
                </value>
                <value>
                    <fullName>Equipment Failure</fullName>
                </value>
                <value>
                    <fullName>Diversion</fullName>
                </value>
                <value>
                    <fullName>Demurrage</fullName>
                </value>
                <value>
                    <fullName>Incorrect UOM</fullName>
                </value>
                <value>
                    <fullName>Driver Verification/Change</fullName>
                </value>
                <value>
                    <fullName>Route / Directions</fullName>
                </value>
                <value>
                    <fullName>Warehouse</fullName>
                </value>
                <value>
                    <fullName>Mode of transportation</fullName>
                </value>
                <value>
                    <fullName>Weight Discrepancy</fullName>
                </value>
                <value>
                    <fullName>Incorrect Product</fullName>
                </value>
                <value>
                    <fullName>Product Concern</fullName>
                </value>
                <value>
                    <fullName>Incorrect Label</fullName>
                </value>
                <value>
                    <fullName>Product Request</fullName>
                </value>
                <value>
                    <fullName>Account Issues</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Document Request</fullName>
                </value>
                <value>
                    <fullName>Data Entry</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Stock Out / Plant Outage</fullName>
                </value>
                <value>
                    <fullName>Article Request</fullName>
                </value>
                <value>
                    <fullName>MDM Verification</fullName>
                </value>
                <value>
                    <fullName>Incorrect Vehicle ID</fullName>
                </value>
                <value>
                    <fullName>Invoice Adjustments</fullName>
                </value>
                <value>
                    <fullName>Order Date</fullName>
                </value>
                <value>
                    <fullName>Destination Change</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                    <default>true</default>
                    <label>High</label>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_Segmentation__c</fullName>
        <label>Segmentation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Strategic</fullName>
                    <default>true</default>
                    <label>Strategic</label>
                </value>
                <value>
                    <fullName>Core</fullName>
                </value>
                <value>
                    <fullName>Base</fullName>
                </value>
                <value>
                    <fullName>Prime</fullName>
                </value>
                <value>
                    <fullName>Ultra</fullName>
                </value>
                <value>
                    <fullName>Grow</fullName>
                </value>
                <value>
                    <fullName>Basic</fullName>
                </value>
                <value>
                    <fullName>Mega Farmers</fullName>
                </value>
                <value>
                    <fullName>Top Farmers</fullName>
                </value>
                <value>
                    <fullName>Farmers</fullName>
                </value>
                <value>
                    <fullName>Mid Farmers</fullName>
                </value>
                <value>
                    <fullName>Small Farmers</fullName>
                </value>
                <value>
                    <fullName>Key</fullName>
                </value>
                <value>
                    <fullName>Canal KAM</fullName>
                    <label>Canal - KAM</label>
                </value>
                <value>
                    <fullName>Trader KAM</fullName>
                    <label>Trader - KAM</label>
                </value>
                <value>
                    <fullName>Mega Farmer KAM</fullName>
                    <label>EU - KAM Mega Farmer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PMC SS Case Priority Assignment</label>
    <pluralLabel>PMC SS Case Priority Assignments</pluralLabel>
</CustomObject>

classes/PMC_CaseTriggerHelperFFLib.cls
/**
* @description This class will be used to handle all triggers on Case object.
* @author Sayali Shinde
* @storynumber GDASF-1941
*/

public without sharing class PMC_CaseTriggerHelperFFLib {

        //Variable to cover the exception part
    @testVisible
    private static Boolean boolThrowException = false;
    
    /**
	* @description Wrapper class to hold & pass the notification related parameters.
	*/
    public class PMC_NotificationWrapper {
        
        Id idNotificationType;
        String strBody; 
        String strTitle;
        /**
		* @description This is wrapper constructor to pass notification related parameters.
		* @param idNotificationType - Custom Notification Type Id
		* @param strBody - Notification Body
		* @param strTitle - Notification Title
		*/
        public PMC_NotificationWrapper(Id idNotificationType, String strBody, String strTitle) {
            this.idNotificationType = idNotificationType;
            this.strBody = strBody; 
            this.strTitle = strTitle;
        }
    }
    
    /**
    * @description This method will be used to update the Case priority on cases.
    * @param lstNewCases - List of triggering case records.
    */
    
    public static void updateCasePriority(List<Case> lstNewCases) {
        
        try {
            
            Set<Id> setAccountIds = new Set<Id>();
            Map<Id, String> mapContactAccountIds = new Map<Id, String>();
            
            for(Case objCase : lstNewCases) {
                
                if(objCase.AccountId != null){
                    setAccountIds.add(objCase.AccountId);
                }
                else if(objCase.ContactId != null) {
                    mapContactAccountIds.put(objCase.ContactId,'');
                }
            }
            
            for(Contact objContact : PMC_ContactSelector.newInstance().getContactsById(mapContactAccountIds.keySet())) {
                mapContactAccountIds.put(objContact.Id, objContact.AccountId);
            }
            
            Map<String, Account> mapAccounts = new Map<String, Account>(PMC_AccountSelector.newInstance().getAccountsById(setAccountIds, mapContactAccountIds.values()));
            
            checkAndAssignPriorityToCase(lstNewCases, mapAccounts, mapContactAccountIds);
        }
        catch(QueryException objQueryException) {
            PMC_ErrorLogClass.processException(objQueryException);
        }
    }

    /**
    * @description This method will be used to check the case type and retrieve the corresponding Case priority on cases.
    * @param lstNewCases - List of triggering case records.
    * @param mapAccounts - Map of Account Id & Account Record
    * @param mapContactAccountIds - Map of Contact Id & associated Account Id
    */

    public static void checkAndAssignPriorityToCase(List<Case> lstNewCases, Map<String, Account> mapAccounts, Map<Id, String> mapContactAccountIds) {

        Map<String, PMC_SS_CasePriorityAssignment__mdt> mapCasePriorityAssignments = getCasePriorityAssignments();

        for(Case objCase : lstNewCases) {
            String strKey = objCase.AccountId != null && mapAccounts.containsKey(objCase.AccountId) ? objCase.Type + '_' + mapAccounts.get(objCase.AccountId).PMC_SS_Segmentation__c : 
            objCase.ContactId != null && mapAccounts.containsKey(mapContactAccountIds.get(objCase.ContactId)) ? objCase.Type + '_' + mapAccounts.get(mapContactAccountIds.get(objCase.ContactId)).PMC_SS_Segmentation__c : '';

            if(objCase.Type == PMC_SS_ConstantClass.INTERNAL_REQUEST && objCase.PMC_SS_IssueReason__c == PMC_SS_ConstantClass.ADDRESS_CREATION_UPDATE) {
                objCase.Priority = PMC_SS_ConstantClass.HIGH;
            }
            else {
                objCase.Priority = mapCasePriorityAssignments.containsKey(strKey) ? mapCasePriorityAssignments.get(strKey).PMC_SS_Priority__c : PMC_SS_ConstantClass.LOW;
            }
        } 

    }
    
    /**
    * @description This method will be used to retrieve Custom Metadata.
    * @return Map<String, PMC_SS_CasePriorityAssignment__mdt> where record's Master Label is key and record is value
    */
    
    public static Map<String, PMC_SS_CasePriorityAssignment__mdt> getCasePriorityAssignments() {
        
        Map<String, PMC_SS_CasePriorityAssignment__mdt> mapCasePriorityAssignments = new Map<String, PMC_SS_CasePriorityAssignment__mdt>();

        for(PMC_SS_CasePriorityAssignment__mdt objCasePriorityDetails : PMC_CasePriorityAssignmentSelector.newInstance().getCasePriorityAssignmentMetadata()) {
            mapCasePriorityAssignments.put(objCasePriorityDetails.MasterLabel, objCasePriorityDetails);
        }
        
        return mapCasePriorityAssignments;
    }
    

    /**
    * @description This method will be used to calculate business days post case closure.
    * @param mapOldCases - Map of old values of case records.
    * @param lstNewCases - List of triggering case records.
    */

    public static void checkBusinessDaysOnCaseReOpen(Map<Id, Case> mapOldCases, List<Case> lstNewCases) {
            
        try {
            BusinessHours objBusinessHrs = PMC_BusinessHoursSelector.newInstance().getDefaultBusinessHour();
            
            for(Case objCase : lstNewCases) {

                if(objCase.Status == PMC_SS_ConstantClass.RE_OPEN && mapOldCases.get(objCase.Id).Status == PMC_SS_ConstantClass.CLOSED) 
                {
                    validateReopenTimeFrame(objCase,mapOldCases.get(objCase.Id),objBusinessHrs);
                }
            }
        }
        catch(QueryException objQueryException) {
            PMC_ErrorLogClass.processException(objQueryException);
        }
    }

    /**
    * @description This method will be used to update the isEscalated flag on cases.
    * @param  objNewCase - Triggering case record.
    * @param  objOldCase - Old Case record values
    * @param  objBusinessHrs - Default Business Hours
    */
    public static  void validateReopenTimeFrame(Case objNewCase, Case objOldCase, BusinessHours objBusinessHrs) {
        Id idBusinessHrs = objNewCase.BusinessHoursId != null ? objNewCase.BusinessHoursId : objBusinessHrs.Id;
                                    
        DateTime dateTimeExpectedReOpenDate = BusinessHours.addGmt(idBusinessHrs, objOldCase.ClosedDate, PMC_SS_ConstantClass.RE_OPEN_DATE_FORMULA);
        
        if(System.now() > dateTimeExpectedReOpenDate || (Test.isRunningTest() && boolThrowException)) {
            objNewCase.addError(Label.PMC_SS_ReopenPeriodForClosedCase);
            return;
        }
        else if(UserInfo.getUserId() != objOldCase.OwnerId) {
            objNewCase.OwnerId = UserInfo.getUserId();
        }
    }
    
    
    /**
    * @description This method will be used to update the isEscalated flag on cases.
    * @param mapOldCases - Map of old values of case records.
    * @param lstNewCases - List of triggering case records.
    */
    
    public static void updateIsEscalatedFlag(Map<Id, Case> mapOldCases, List<Case> lstNewCases) {
            
        for(Case objCase : lstNewCases) {
            
            if(mapOldCases != null) {
               
                if(objCase.Status == PMC_SS_ConstantClass.ESCALATED && mapOldCases.get(objCase.Id).Status != PMC_SS_ConstantClass.ESCALATED) {
                    objCase.IsEscalated = true;
                }
                else if(objCase.Status != PMC_SS_ConstantClass.ESCALATED && mapOldCases.get(objCase.Id).Status == PMC_SS_ConstantClass.ESCALATED) {
                    objCase.IsEscalated = false;
                }
            }
            else {
                objCase.IsEscalated = objCase.Status == PMC_SS_ConstantClass.ESCALATED ? true : false;
            }
        }
    }
}