objects/Account.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_AccountExternalID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Account External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PMC_SS_SAPCustomerNumber__c</fullName>
        <description>The SAP Generated Customer Number</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SAP Customer Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <description>Field which automatically gets updated when a Quote is submitted to approval/ it&apos;s approved/ it&apos;s rejected.</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to capture the Primary Contact associated with the quote.</description>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.SBQQ__Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CPQ Quotes (Primary Contact1)</relationshipLabel>
        <relationshipName>CPQ_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/QuoteExtControllerTests.cls
/**
* @description This is the test class for the controller class for Advanced Approvals on SBQQ__Quote__c
*/
@isTest
public class QuoteExtControllerTests {
    /*
* This Method will be used to setup the data for the test class execution.
*/   
    @TestSetup
    private static void testSetup(){
        List<String>lstPermissionNames = New List<String>{'PMC_SLS_Permission_Set_Group'};
        User objUserAM = PMC_CPQ_CPIRemoteCalloutUtilityTest.createCPQTestUser('Sales User',lstPermissionNames);
        system.runAs(objUserAM){
            List<Contact> lstContacts = PMC_TestUtilityClass.createContact(1,'Master');
            List<Opportunity> lstOpty = PMC_TestUtilityClass.createOpportunity(1,'Master');
            Account objAccount = [select Id from Account where Id =: lstOpty.get(0).AccountId];
            objAccount.PMC_SS_AccountExternalID__c = '5389521474';
            objAccount.PMC_SS_SAPCustomerNumber__c = '5389521474';
            update objAccount;
            List<SBQQ__Quote__c> lstquote = PMC_TestUtilityClass.createCPQQuotes(1,lstOpty,lstContacts);
        }
    }
    /*
* This Method will be used to execute the Submit for Approval Functionality.
*/   
    @istest
    public static void testSubmit() {
        User objUserAM = [select Id from User where LastName = 'Sales User Test' LIMIT 1 ];
        system.runAs(objUserAM){
            List<SBQQ__Quote__c> lstquote = [select Id from SBQQ__Quote__c];
            if(!lstquote.isEmpty()){
                Test.startTest();
                QuoteExtController con = new QuoteExtController(new ApexPages.StandardController(lstquote[0]));
                con.onSubmit();
                SBQQ__Quote__c quote = [SELECT ApprovalStatus__c,PMC_CPQ_PrimaryContact__c FROM SBQQ__Quote__c WHERE Id =: lstquote[0].Id LIMIT 1];
                Test.stopTest();
                System.assertEquals('Approved', quote.ApprovalStatus__c, 'Error in approving Quote');
            }
        }
    }
    
    @isTest
    public static void testRecall() {
        User objUserAM = [select Id from User where LastName = 'Sales User Test' LIMIT 1 ];
        system.runAs(objUserAM){
            List<SBQQ__Quote__c> lstquote = [select Id from SBQQ__Quote__c];
            if(!lstquote.isEmpty()){
                Test.startTest();
                QuoteExtController con = new QuoteExtController(new ApexPages.StandardController(lstquote[0]));
                con.onRecall();
                SBQQ__Quote__c quote = [SELECT ApprovalStatus__c,PMC_CPQ_PrimaryContact__c  FROM SBQQ__Quote__c WHERE Id = :lstquote[0].Id LIMIT 1];
                Test.stopTest();
                System.assertEquals('Recalled', quote.ApprovalStatus__c, 'Error in recalling Quote');
            }
        }
    }
}