objects/Account.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_isProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a flag field, which will indicate if this account record is already processed or not</description>
        <label>Is Processed</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_SS_AccountSalesAreaRelationship__c.object
<CustomObject>
    <description>Junction Object to relate Account and Sales Areas</description>
    <fields>
        <fullName>PMC_SS_SalesArea__c</fullName>
        <description>Master Detail relationship to Sales Area</description>
        <label>Sales Area</label>
        <referenceTo>PMC_SS_SalesArea__c</referenceTo>
        <relationshipName>AccountSalesAreRelationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Sales Area Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Sales Area Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_MaterialGroup__c</fullName>
        <description>This field is created as a part of story to handle/store value of any Product&apos;s Group.</description>
        <label>Product Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BIOSCIENCE</fullName>
                    <label>Bioscience</label>
                </value>
                <value>
                    <fullName>Co-Product</fullName>
                </value>
                <value>
                    <fullName>Nitrogen</fullName>
                    <label>NITROGEN</label>
                </value>
                <value>
                    <fullName>NPK</fullName>
                </value>
                <value>
                    <fullName>Phosphate</fullName>
                </value>
                <value>
                    <fullName>Potash</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                    <label>SERVICES</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Nitrogen__c</fullName>
        <description>This field captures the Nitrogen % for the product.</description>
        <inlineHelpText>This field captures the Nitrogen % for the product.</inlineHelpText>
        <label>Nitrogen %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Phosphorous__c</fullName>
        <description>This field captures the Phosphorous % for the product.</description>
        <inlineHelpText>This field captures the Phosphorous % for the product.</inlineHelpText>
        <label>Phosphorous %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Potassium__c</fullName>
        <description>This field captures the Potassium % for the product.</description>
        <inlineHelpText>This field captures the Potassium % for the product.</inlineHelpText>
        <label>Potassium %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductFamily__c</fullName>
        <description>This field captures the product family for the product.</description>
        <inlineHelpText>This field captures the product family for the product.</inlineHelpText>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ATHOS</fullName>
                </value>
                <value>
                    <fullName>BASICA</fullName>
                </value>
                <value>
                    <fullName>BLENDS</fullName>
                </value>
                <value>
                    <fullName>BORON</fullName>
                </value>
                <value>
                    <fullName>Co-Product</fullName>
                    <label>CO-PRODUCT</label>
                </value>
                <value>
                    <fullName>DAP-MAP</fullName>
                </value>
                <value>
                    <fullName>EXCELLEN</fullName>
                </value>
                <value>
                    <fullName>FEED</fullName>
                </value>
                <value>
                    <fullName>Fluosilic Acid</fullName>
                </value>
                <value>
                    <fullName>GRAVEL</fullName>
                </value>
                <value>
                    <fullName>Gypsum</fullName>
                </value>
                <value>
                    <fullName>K-MAG</fullName>
                </value>
                <value>
                    <fullName>Limestone</fullName>
                </value>
                <value>
                    <fullName>Liquid Fert</fullName>
                </value>
                <value>
                    <fullName>MES</fullName>
                </value>
                <value>
                    <fullName>MES BLENDS</fullName>
                </value>
                <value>
                    <fullName>MICRO</fullName>
                </value>
                <value>
                    <fullName>MKP</fullName>
                </value>
                <value>
                    <fullName>MOP</fullName>
                </value>
                <value>
                    <fullName>MPASTO</fullName>
                </value>
                <value>
                    <fullName>N Blends</fullName>
                </value>
                <value>
                    <fullName>Nitrogen</fullName>
                </value>
                <value>
                    <fullName>NPK</fullName>
                </value>
                <value>
                    <fullName>NPK Blends</fullName>
                </value>
                <value>
                    <fullName>P Blends</fullName>
                </value>
                <value>
                    <fullName>PERFORMA BIO</fullName>
                </value>
                <value>
                    <fullName>PERFORMA BLENDS</fullName>
                </value>
                <value>
                    <fullName>P FERTILIZER</fullName>
                </value>
                <value>
                    <fullName>Phosphoric Acid</fullName>
                </value>
                <value>
                    <fullName>Rock</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductSubFamily__c</fullName>
        <description>This field captures the product sub family for the product</description>
        <inlineHelpText>This field captures the product sub family for the product.</inlineHelpText>
        <label>Product Sub Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMMONIA</fullName>
                </value>
                <value>
                    <fullName>APATITE</fullName>
                </value>
                <value>
                    <fullName>ASPIRE</fullName>
                </value>
                <value>
                    <fullName>ASPIRE FINE</fullName>
                </value>
                <value>
                    <fullName>ATHOS</fullName>
                </value>
                <value>
                    <fullName>BASICA</fullName>
                </value>
                <value>
                    <fullName>BORON</fullName>
                </value>
                <value>
                    <fullName>CFL ROCK</fullName>
                </value>
                <value>
                    <fullName>DAP</fullName>
                </value>
                <value>
                    <fullName>DAP-MAP</fullName>
                </value>
                <value>
                    <fullName>EXCELLEN</fullName>
                </value>
                <value>
                    <fullName>FEED</fullName>
                </value>
                <value>
                    <fullName>FLUOSILIC ACID</fullName>
                </value>
                <value>
                    <fullName>GRAVEL</fullName>
                </value>
                <value>
                    <fullName>GYPSUM</fullName>
                </value>
                <value>
                    <fullName>GYPSUM (AGRICULTURAL)</fullName>
                </value>
                <value>
                    <fullName>GYPSUM (CHEMICAL)</fullName>
                </value>
                <value>
                    <fullName>GYPSUM (CONSTRUCTION)</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>K BLENDS</fullName>
                </value>
                <value>
                    <fullName>KMAG BLENDS</fullName>
                </value>
                <value>
                    <fullName>KMAG GRANULAR</fullName>
                </value>
                <value>
                    <fullName>KMAG PREMIUM</fullName>
                </value>
                <value>
                    <fullName>KMAG SPECIAL</fullName>
                </value>
                <value>
                    <fullName>KMAG STANDARD</fullName>
                </value>
                <value>
                    <fullName>LIMESTONE</fullName>
                </value>
                <value>
                    <fullName>LIQUID FERT</fullName>
                </value>
                <value>
                    <fullName>MAGNETITE</fullName>
                </value>
                <value>
                    <fullName>MAP</fullName>
                </value>
                <value>
                    <fullName>MES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductTypes__c</fullName>
        <description>This will be used to store Product Hiearchy Informaiton.</description>
        <label>Product Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commodity</fullName>
                </value>
                <value>
                    <fullName>Co-Product</fullName>
                </value>
                <value>
                    <fullName>Intermediary</fullName>
                </value>
                <value>
                    <fullName>Performance</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                    <label>SERVICES</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_isProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a flag field, which will indicate if this product record is already processed or not</description>
        <label>Is Processed</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PMC_DH_NewAccountOnboardingBatchTest.cls
/**
 * @description       : Test Class for New Account Onboarding Batch Job
 * @author            : Rohan Undale
 * @created on        : 11-17-2023
 * @group             : Mosaic Direct
 * @last modified on  : 
 * @last modified by  : 
**/
@isTest
public with Sharing class PMC_DH_NewAccountOnboardingBatchTest {
	@TestSetup
    static void testSetup()
    {
        User userAdmin=PMC_DH_TestDataFactoryClass.createAdminUser();
        System.runAs(userAdmin){
            // test class fixes
            Account acc=PMC_DH_TestDataFactoryClass.createParentTestAccount();
            PMC_DH_TestDataFactoryClass.createShipToTestAccount(acc);
            Test.startTest();        
            Product2 prod = PMC_DH_TestDataFactoryClass.createProduct();
            prod.PMC_CPQ_MaterialGroup__c='Feed';
            prod.PMC_CPQ_ProductTypes__c='services';
            prod.PMC_CPQ_ProductFamily__c='MES';
            prod.PMC_CPQ_Potassium__c=17;
            prod.PMC_CPQ_Phosphorous__c=7;
            prod.PMC_CPQ_Nitrogen__c=35;
            prod.PMC_CPQ_ProductSubFamily__c='mes';
            prod.PMC_DH_isProcessed__c=FALSE;
            insert prod;
    
            Product2 prod2 = PMC_DH_TestDataFactoryClass.createProduct();
            prod2.ProductCode='AB-45678';
            prod2.StockKeepingUnit='45678';
            prod2.PMC_CPQ_MaterialGroup__c='gypsum';
            prod2.PMC_CPQ_ProductTypes__c='commodity';
            prod2.PMC_CPQ_ProductFamily__c='MES';
            prod2.PMC_CPQ_Potassium__c=17;
            prod2.PMC_CPQ_Phosphorous__c=7;
            prod2.PMC_CPQ_Nitrogen__c=35;
            prod2.PMC_CPQ_ProductSubFamily__c='mes';
            prod2.PMC_DH_isProcessed__c=FALSE;
            insert prod2; 
    
            ProductCatalog pc=new ProductCatalog(name='mosaic Direct');
            insert pc;
            PMC_SS_SalesArea__c testSalesArea = new PMC_SS_SalesArea__c();
            testSalesArea.PMC_SS_SalesOrganization__c = 'Mosaic Global Sales LLC';
            testSalesArea.PMC_SS_DistributionChannel__c = '0';
            testSalesArea.PMC_SS_Division__c = '10';
            //testSalesArea.PMC_CPQ_MosaicLLP__c= '1002';
            insert testSalesArea;
    
            PMC_CPQ_ProductSalesArea__c tetProSalesArea=new PMC_CPQ_ProductSalesArea__c();
            tetProSalesArea.PMC_CPQ_Product__c=prod.Id;
            tetProSalesArea.PMC_CPQ_Sales_Area__c=testSalesArea.Id;
            insert tetProSalesArea;
    
            PMC_SS_AccountSalesAreaRelationship__c testAccSalesArea=new PMC_SS_AccountSalesAreaRelationship__c();
            testAccSalesArea.PMC_SS_Account__c=acc.Id;
            testAccSalesArea.PMC_SS_SalesArea__c=testSalesArea.Id;
            insert testAccSalesArea;
    
            BuyerAccount buyerAccount = new BuyerAccount();
            buyerAccount.BuyerId = acc.Id;
            buyerAccount.Name = 'Test Buyer Account (BA-AJ)';
            buyerAccount.IsActive = true;
            insert buyerAccount;
            
            ProductCategory productCat=new  ProductCategory(Name='Mes',PMC_DH_Category_ID__c='FEED-SERVICES-MES-MES',catalogid=pc.id,IsNavigational=true);
            insert productCat;
            /*ElectronicMediaGroup elePLP=new ElectronicMediaGroup(name='Product List Image',developername='productListImage',usagetype='Listing');
            insert elePLP;
            ElectronicMediaGroup elePDP=new ElectronicMediaGroup(name='Product Detail Images',developername='productDetailImage',usagetype='Standard');
            insert elePDP;*/
            Pricebook2 objPB = new Pricebook2(Name = 'DH Price Book', IsActive = true);
            insert objPB;
            /**Pricebook2 standardPricebook = new Pricebook2(
                Id = Test.getStandardPricebookId(),
                IsActive = true,
                Name = 'DH Price Book'
            );
            Update standardPricebook;
            **/
            WebStore webStore=PMC_DH_TestDataFactoryClass.createTestWebStore();
            webStore.Name = 'Mosaic Direct';
            update webStore;
        }
    }
    
    /**
    * @description       : Test Class method for New Account Onboarding Batch Job
    * @author            : Rohan Undale
    * @created on        : 11-17-2023
    **/
    @isTest
    public static void testProductOnBoardBatch()
    {
        
        User userAdmin= [SELECT Id,Name from User Where FirstName='Test John' AND IsActive=TRUE LIMIT 1];
        System.runAs(userAdmin){
            try{
            PMC_DH_NewAccountOnboardingBatch batchJob=new PMC_DH_NewAccountOnboardingBatch();
            Datetime datTSystemTime;
            String strCronExpression;
            String strJobId;
            Test.startTest();
            Database.executeBatch(batchJob);
            Test.stopTest();
            CronTrigger objCronTrigg;
            datTSystemTime = System.now().addSeconds(10);
            strCronExpression =  datTSystemTime.second() + ' ' + datTSystemTime.minute() + ' ' + datTSystemTime.hour() + ' ' + datTSystemTime.day() + ' ' + datTSystemTime.month() + ' ? ' + datTSystemTime.year();
            strJobId = System.schedule('New Account Onboarding', strCronExpression, batchJob );
            objCronTrigg = [SELECT Id, CronExpression, TimesTriggered, NextFireTime, State FROM CronTrigger WHERE Id = :strJobId];
            System.assertEquals(strCronExpression, objCronTrigg.CronExpression, 'Cron Expressions are matching');
            System.assertEquals(0, objCronTrigg.TimesTriggered, '0 Times triggered');
            }
            Catch(Exception ex){
                System.assertEquals(ex!=NULL,true,'Cron Expressions');
            }
        }
    }
}