objects/Account.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_AccountExternalID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Account External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Location.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Plant__c</fullName>
        <description>Indicates Plant Number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Plant</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PMC_CPQ_ProductLocation__c.object
<CustomObject>
    <description>This object is created as a part of  story to capture product and location data.</description>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created  to check the location details.</description>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Product Locations</relationshipLabel>
        <relationshipName>ProductLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product</description>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product.</description>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SBQQ__Product__c</field>
                <operation>equals</operation>
                <valueField>PMC_CPQ_ProductLocation__c.PMC_CPQ_ProductName__c</valueField>
            </filterItems>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created  to check the shipping address value of the line item.</description>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Lines (Ship To)</relationshipLabel>
        <relationshipName>Quote_Lines2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product</description>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SBQQ__Product__c</field>
                <operation>equals</operation>
                <valueField>PMC_CPQ_ProductLocation__c.PMC_CPQ_ProductName__c</valueField>
            </filterItems>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to check the shipping address value</description>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions (Ship To)</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract that governs this subscription.</description>
        <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this subscription.</description>
        <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PMC_DH_RequestedOrderHelper.cls
/**
* @description       : 
* @author            : Mosaic Direct | Dev Team
* @group             : 
* @last modified on  : 03-01-2024
* @last modified by  : Hemant Giri Goswami | hegoswami@deloitte.com
**/
public without sharing class PMC_DH_RequestedOrderHelper {
     
    public static boolean throwTestException = false;
     /**
* @description 
* @author Mosaic Direct | Dev Team  | 10-16-2023 
* @param strShipFrom
* @param strShipTo
* @param strContractId
* @return String 
**/
    public static String getShipFrom(String strShipFrom, String strShipTo, String strContractId){
        String strShipFro ='' ;
        try{
            strShipFro = processShipFrom(strShipFrom,strShipTo,strContractId);
        }
        catch(QueryException qe){
            String strTemp = '';
            // Handle inaccessible fields
            Map<String, Set<String>> inaccessible = qe.getInaccessibleFields();
            Set<String> quoteLineFields = inaccessible.get('SBQQ__QuoteLine__c');    
            Set<String> subFields = inaccessible.get('SBQQ__Subscription__c');
            Set<String> prodLocationFields = inaccessible.get('PMC_CPQ_ProductLocation__c');    
            Set<String> accountFields = inaccessible.get('Account');
            Set<String> locationFields = inaccessible.get('Location');
            if(quoteLineFields != Null && subFields != Null && prodLocationFields != Null && accountFields != Null && locationFields != Null ){
                strTemp = 'Inaccessible';
            }
        }        
        return strShipFro;
    }
   
    /**
* @description 
* @author Mosaic Direct | Dev Team  | 10-16-2023 
* @param strShipFrom
* @param strShipTo
* @param strContractId
* @return String 
**/
    public static String processShipFrom(String strShipFrom, String strShipTo, String strContractId){
        String strShipFro ='';
        if(throwTestException && Test.isRunningTest()) {
            throw new QueryException(PMC_DH_ConstantClass.TEST_EXCEPTION_MESSAGE);
        }
        else {
            if(strShipFrom != Null && strShipTo != Null && strContractId != Null){
                List<SBQQ__Subscription__c> lstSubs =[SELECT Id,SBQQ__QuoteLine__r.PMC_CPQ_ShipTo__r.PMC_SS_AccountExternalID__c, SBQQ__QuoteLine__r.PMC_CPQ_ProductLocation__r.PMC_CPQ_Location__r.PMC_CPQ_Plant__c from SBQQ__Subscription__c where SBQQ__QuoteLine__r.PMC_CPQ_ShipTo__c = :strShipTo and SBQQ__QuoteLine__r.PMC_CPQ_ProductLocation__c  = :strShipFrom and SBQQ__Contract__c = :strContractId WITH USER_MODE];
                if(!lstSubs.isEmpty()){
                    strShipFro = lstSubs[0].SBQQ__QuoteLine__r.PMC_CPQ_ProductLocation__r.PMC_CPQ_Location__r.PMC_CPQ_Plant__c;
            }
        }
    }
        return strShipFro;
    }
     /**
* @description 
* @author Mosaic Direct | Dev Team  | 10-16-2023 
* @param strShipFrom
* @param strShipTo
* @param strContractId
* @return String 
**/
    public static String getShipTo(String strShipFrom, String strShipTo, String strContractId){
        String strShipT ='';
        if(strShipFrom != Null && strShipTo != Null && strContractId != Null){
                List<SBQQ__Subscription__c> lstSubs =[SELECT Id,SBQQ__QuoteLine__r.PMC_CPQ_ShipTo__r.PMC_SS_AccountExternalID__c, SBQQ__QuoteLine__r.PMC_CPQ_ProductLocation__r.PMC_CPQ_Location__r.PMC_CPQ_Plant__c from SBQQ__Subscription__c where SBQQ__QuoteLine__r.PMC_CPQ_ShipTo__c = :strShipTo and SBQQ__QuoteLine__r.PMC_CPQ_ProductLocation__c  = :strShipFrom and SBQQ__Contract__c = :strContractId WITH SECURITY_ENFORCED];
                if(!lstSubs.isEmpty()){
                    strShipT= lstSubs[0].SBQQ__QuoteLine__r.PMC_CPQ_ShipTo__r.PMC_SS_AccountExternalID__c;
                    //strShipT = '876578';

                }                
            }  
        return strShipT;
    }
   
}