objects/CartItem.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_EMPTYCONST__c</fullName>
        <defaultValue>&quot;&quot;</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>EMPTYCONST</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_PaymentTerms__c</fullName>
        <formula>IF(AND(!ISNULL(TEXT(( Cart.PMC_DH_PaymentTerms__c ))),! ISBLANK(TEXT(  Cart.PMC_DH_PaymentTerms__c))),TEXT( Cart.PMC_DH_PaymentTerms__c),NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Terms</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_ContractEndDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PMC DH Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_DH_ContractStartDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_CPQ_Integration_Endpoint__mdt.object
<CustomObject>
    <description>This is used to store all External endpoints.</description>
    <fields>
        <fullName>PMC_CPQ_Endpoint__c</fullName>
        <description>This is used to store the Integration endpoint.</description>
        <label>Endpoint</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Integration Endpoint</label>
    <pluralLabel>Integration Endpoints</pluralLabel>
</CustomObject>

objects/PMC_CPQ_IntegrationFieldMap__mdt.object
<CustomObject>
    <description>Store Details for Quote &amp; Quote Line JSON Request Structure</description>
    <fields>
        <fullName>PMC_CPQ_ApexAPIName__c</fullName>
        <label>PMC_CPQ_ApexAPIName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_AttributeKey__c</fullName>
        <label>PMC_CPQ_AttributeKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ErrorMessage__c</fullName>
        <description>Error Message displayed when Mandatory field is missed.</description>
        <label>PMC_CPQ_ErrorMessage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_IsLookup__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PMC_CPQ_IsLookup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_IsMandatory__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to specify if any given field detail is necessary for request generation.</description>
        <inlineHelpText>Specify if the field is mandatory.</inlineHelpText>
        <label>PMC_CPQ_IsMandatory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SFObject__c</fullName>
        <label>PMC_CPQ_SFObject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Field Map</label>
    <pluralLabel>Integration Field Maps</pluralLabel>
</CustomObject>

objects/SalesAgreement.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_SalesAgreementExternalId__c</fullName>
        <description>This field states the Sales Agreement External Id</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Sales Agreement External Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WebCart.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_B2B_B2C_INDICATOR__c</fullName>
        <formula>TEXT(PMC_DH_Account__r.PMC_SS_CustomerType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>B2B_B2C_INDICATOR</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_Cart_Number__c</fullName>
        <displayFormat>C-{00000}</displayFormat>
        <label>Cart Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>PMC_DH_ContractEndDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_DH_ContractStartDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_DH_Currency__c</fullName>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>BRL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_EMPTYCONST__c</fullName>
        <defaultValue>&quot;&quot;</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>EMPTYCONST</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_PaymentTerms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash Against Documents</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 7 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 10 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 15 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 45 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Doc - 60 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 90 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents-120 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents-180 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Prepayment</fullName>
                </value>
                <value>
                    <fullName>Net 1 Day - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 2 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 3 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>05 Days - Document Lock Date</fullName>
                </value>
                <value>
                    <fullName>Net 7 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 10 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 14 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 15 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 17 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 21 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 28 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 29 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 30 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 31 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 35 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 42 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 45 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 60 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 70 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 75 Days - From Invoicing Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_PrepaymentDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Prepayment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_DH_PrimaryBusinessType__c</fullName>
        <formula>IF(AND(!ISNULL(TEXT((PMC_DH_Account__r.Owner.PMC_CPQ_PrimaryBusinessType__c))),! ISBLANK(TEXT( PMC_DH_Account__r.Owner.PMC_CPQ_PrimaryBusinessType__c))),TEXT(PMC_DH_Account__r.Owner.PMC_CPQ_PrimaryBusinessType__c),NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Business Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_SAP_CONSTANT__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SAP CONSTANT</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_SCHED_AGREEMENT__c</fullName>
        <defaultValue>&quot;&quot;</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>SCHED AGREEMENT</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_SalesAgreementEndDate__c</fullName>
        <formula>IF( PMC_DH_SalesAgreement__c!=NULL,  PMC_DH_SalesAgreement__r.EndDate ,  DATEVALUE( CreatedDate )   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Agreement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_DH_SalesAgreementStartDate__c</fullName>
        <formula>IF(PMC_DH_SalesAgreement__c!=NULL, PMC_DH_SalesAgreement__r.StartDate,  DATEVALUE( CreatedDate ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Agreement Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_DH_SalesAgreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Agreement</label>
        <referenceTo>SalesAgreement</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PMC_DH_GetPriceQuoteService.cls
/**
* @description : class for Get Price SAP Integration
* @author      : Humera Rahath
* @params      : None
* @userStory   : GPDH-6862
* */
public without sharing class PMC_DH_GetPriceQuoteService {

     

    
    static List<PMC_CPQ_IntegrationFieldMap__mdt> lstCartFieldMap = new List<PMC_CPQ_IntegrationFieldMap__mdt>();
    static List<PMC_CPQ_IntegrationFieldMap__mdt> lstCartItemFieldMap = new List<PMC_CPQ_IntegrationFieldMap__mdt>();
    static List<PMC_CPQ_IntegrationFieldMap__mdt> lstLookupCartMap = new List<PMC_CPQ_IntegrationFieldMap__mdt>();
    static List<PMC_CPQ_IntegrationFieldMap__mdt> lstLookupCartItemMap = new List<PMC_CPQ_IntegrationFieldMap__mdt>();
   /** 
* @description Method to filter list for integration mapping.
*/
    public static void filterMapValues(){
        List<PMC_CPQ_IntegrationFieldMap__mdt> lstIntegration = [select MasterLabel,PMC_CPQ_ApexAPIName__c,PMC_CPQ_SFObject__c,PMC_CPQ_IsMandatory__c, PMC_CPQ_ErrorMessage__c, PMC_CPQ_AttributeKey__c, PMC_CPQ_IsLookup__c from PMC_CPQ_IntegrationFieldMap__mdt where (PMC_CPQ_ApexAPIName__c != null AND PMC_CPQ_SFObject__c in ('WebCart','CartItem')) WITH SECURITY_ENFORCED order by MasterLabel ASC];
        
        for(PMC_CPQ_IntegrationFieldMap__mdt mapVal: lstIntegration){
            
            if(mapVal.PMC_CPQ_SFObject__c == 'WebCart'){
                if(mapVal.PMC_CPQ_IsLookup__c == false){
                    lstCartFieldMap.add(mapVal);
                    continue;
                }
                lstLookupCartMap.add(mapVal);
            }
            else{
                if(mapVal.PMC_CPQ_IsLookup__c == false){
                    lstCartItemFieldMap.add(mapVal);
                    continue;
                }
                lstLookupCartItemMap.add(mapVal);
            }
        }
    }
    /** 
* @description This class will make a callout to CPI.
* @param lstCarts - List of quotes.
* @return response - HttpResponse Object returned from Endpoint.
*/

    public static HttpResponse makeCallOutRequest(List<WebCart> lstCarts){
        HttpResponse response;
        Map<String, String> mapCartItemDet = new Map<String, String>();
        List<Map<String, String>> lstCtItem = new List<Map<String, String>>();
        Set<String> setCartIds = new Set<String>();
        Integer i = 0;
        Integer j = 0;
        List<Object> lstCartItem = new List<Object>();
        List<Object> lstLookupCartItem = new List<Object>();
        
        filterMapValues();
        setCartIds.add(lstCarts[0].Id);
        String cId = (String)lstCarts[0].Id;
        String queryParam = getQueryParam(lstCartItemFieldMap, null) + ' ,CartId';
        String strLookupQueryParam = getQueryParam(lstLookupCartItemMap, 'Lookup') + ' ,CartId';
        String strLookupGroupByQry = getQueryParam(lstLookupCartItemMap, null) + ' ,CartId';
        strLookupQueryParam = strLookupQueryParam + '*' + strLookupGroupByQry;
        String strLocError = '';
        Map<String, List<Object>> bulkifiedCI = getCartItem(cId, queryParam);
        Map<String, List<Object>> bulkLookupCI = getLookupCartItem(cId, strLookupQueryParam);
        
        String quoteLookupQueryParam = getQueryParam(lstLookupCartMap, 'Lookup');
        String quoteLookupGroupByQuery = getQueryParam(lstLookupCartMap, null);
        quoteLookupQueryParam = quoteLookupQueryParam + '*' + quoteLookupGroupByQuery;
        Map<String,AggregateResult> cartLookupTable = getLookupCarts(cId, quoteLookupQueryParam);
        try{
            JSONGenerator jsonReq = JSON.createGenerator(false);
            jsonReq.writeStartObject();
            WebCart ct = [ 
                SELECT ID,
                PMC_DH_PaymentTerms__c,
                PMC_DH_ContractEndDate__c,
                PMC_DH_ContractStartDate__c,
                PMC_DH_Currency__c,
                PMC_DH_SalesAgreement__c,
                PMC_DH_SalesAgreementEndDate__c,
                PMC_DH_SalesAgreementStartDate__c,PMC_DH_B2B_B2C_INDICATOR__c,
                PMC_DH_SalesAgreement__r.PMC_SS_SalesAgreementExternalId__c,
                PMC_DH_Cart_Number__c,PMC_DH_SAP_CONSTANT__c,PMC_DH_SCHED_AGREEMENT__c,PMC_DH_EMPTYCONST__c,PMC_DH_PrimaryBusinessType__c,PMC_DH_PrepaymentDate__c
                FROM Webcart where Id=:lstCarts[0].Id WITH USER_MODE LIMIT 1];
            i = 0;
            AggregateResult lookupCart = cartLookupTable.get((String)ct.Id);
            lstCartItem = bulkifiedCI.get((String)ct.Id);
            lstLookupCartItem = bulkLookupCI.get((String)ct.Id);
            
            jsonReq = cartJsonGeneration(lstCartFieldMap, ct, jsonReq);
            jsonReq = cartLookupJsonGeneration(lstLookupCartMap, lookupCart, jsonReq);
            for(Object cartItem: lstCartItem){
                j = 0;
                strLocError = '';
                for(PMC_CPQ_IntegrationFieldMap__mdt value: lstLookupCartItemMap){
                    mapCartItemDet.put(value.PMC_CPQ_AttributeKey__c, ('' + ((((AggregateResult)lstLookupCartItem[i]).get(('Lookup'+j)) == null)?'':((AggregateResult)lstLookupCartItem[i]).get(('Lookup'+j)))));
                    
                    j++;
                }
                mapCartItemDet = cartItemJSONGen(lstCartItemFieldMap, cartItem, mapCartItemDet);
                i++;
                lstCtItem.add(mapCartItemDet);
                mapCartItemDet = new Map<String, String>();
            }
            jsonReq.writeFieldName('LineItemList');
            jsonReq.writeObject(lstCtItem);
            jsonReq.writeEndObject();  
            String strInterface = 'ProductsExternalPricing';
            PMC_CPQ_Integration_Endpoint__mdt strIntegrationEndpointRecord = PMC_CPQ_Integration_Endpoint__mdt.getInstance(strInterface); 
            String strEndpoint = strIntegrationEndpointRecord.PMC_CPQ_Endpoint__c;
           
            response = PMC_CPQ_CPIRemoteCalloutUtilityClass.sendCalloutRequest('GET', 'callout:PMC_CPQ_NamedCredential'+strEndpoint,stringProcess(jsonReq.getAsString()));
           }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
        return response;
    }
    /** 
* @description Returns all the quotelines related to the Quote passed in the method
* @param queryCart - Quote for which quote lines has to be fetched
* @param queryParam - Contains part of the query on Quote Line object
* @return qtLines - Returns list of Quote Lines of the quote in argument
*/
    public static Map<String,List<Object>> getCartItem(String queryCart, String queryParam){
        String strCartSet = '(';
        strCartSet = strCartSet + '\'' + queryCart + '\'' + ')';
        Map<String, List<Object>> bulkifiedCI = new Map<String, List<Object>>();
        String cartItemQuery = 'Select ';
        cartItemQuery = cartItemQuery + String.escapeSingleQuotes(queryParam) + ' from CartItem where cartId  in '+ strCartSet ;//' WITH SECURITY_ENFORCED';
        List<CartItem> ciLines = Database.query(cartItemQuery);
        bulkifiedCI.put(queryCart, ciLines);
        return bulkifiedCI;
    }
    /** 
* @description Returns all the quotelines related to the Quote passed in the method
* @param queryCart - Quote for which quote lines has to be fetched
* @param queryParam - Contains part of the query on Quote Line object
* @return qtLines - Returns list of Quote Lines of the quote in argument
*/
    public static Map<String,List<Object>> getLookupCartItem(String queryCart, String queryParam){
        String strCartSet = '(';
        strCartSet = strCartSet + '\'' + queryCart + '\'' + ')';
        
        Map<String, List<Object>> bulkifiedCI = new Map<String, List<Object>>();
        String cartItemQuery = 'Select ';
        cartItemQuery = cartItemQuery + String.escapeSingleQuotes(queryParam.split('\\*')[0]) + ' from CartItem where cartId  in '+ strCartSet + ' group by ' + String.escapeSingleQuotes(queryParam.split('\\*')[1]);
        List<AggregateResult> ciLookupLines = Database.query(cartItemQuery);
        bulkifiedCI.put(queryCart, ciLookupLines);
        return bulkifiedCI;
    }
    /** 
* @description Returns unique set of id of Quote
* @param fieldMap - Fields fetched from External metadata.
* @param filterString - String value which will be added for aliasing. 
* @return queryParam - Returns String value which will be used to query the Database
*/
    public static String getQueryParam(List<PMC_CPQ_IntegrationFieldMap__mdt> fieldMap, String filterString){
        Set<String> cartItemFieldSet = new Set<String>();
        String queryParam = '';
        Integer i = 0;
        
        for(PMC_CPQ_IntegrationFieldMap__mdt keypair: fieldMap){
            cartItemFieldSet.add((String)keypair.PMC_CPQ_ApexAPIName__c);
        }
        for(String s: cartItemFieldSet){
            queryParam = queryParam + s + ((filterString!=null)?(' ' + filterString + i):'') + ',';
            i++;
        }
        queryParam = queryParam + 'Id';
        return queryParam;
    }
    /** 
* @description Returns unique set of id of Quote
* @param queryCart - Unique set of Quote IDS
* @param queryParam - String value for Query 
* @return lookupQuote - Returns String value which will be used to query the Database
*/
    public static Map<String,AggregateResult> getLookupCarts(String queryCart, String queryParam){
        String strCartSet = '(';
        Map<String, AggregateResult> lookupCart = new Map<String, AggregateResult>();
        String cartQuery = 'Select ';
        strCartSet = strCartSet + '\'' + queryCart + '\'' + ')';
        cartQuery = cartQuery + String.escapeSingleQuotes(queryParam.split('\\*')[0]) + ' from WebCart where Id  in '+ strCartSet + ' group by ' + String.escapeSingleQuotes(queryParam.split('\\*')[1]);
        List<AggregateResult> ctLookupLines = Database.query(cartQuery);
        
        for(AggregateResult line: ctLookupLines){
            lookupCart.put(queryCart, line);
        }
        return lookupCart;
    }
    /** 
* @description Returns the JSON Generator Object after adding fields based on if it is a lookup or not.
* @param lstCartFieldMap - Map for all the fields that have to be used in the JSON Request.
* @param cartObject - Argument of type Object that may be of type Quote or Aggregate result all similar to Quote.
* @param jsonReq - Reference of the jsonReq Object that is to have the additional fields that are in the Quote Field Map.
* @return qtLines - Returns list of Quote Lines of the quote in argument
*/
    public static JSONGenerator cartJsonGeneration(List<PMC_CPQ_IntegrationFieldMap__mdt> lstCartFieldMap, Object cartObject, JSONGenerator jsonReq){
        String strPlaceHolderValue = '';
        WebCart cT = (WebCart)cartObject;
        for (PMC_CPQ_IntegrationFieldMap__mdt value: lstCartFieldMap) { 
            jsonReq.writeFieldName(value.PMC_CPQ_AttributeKey__c);
            strPlaceHolderValue = (cT.get(value.PMC_CPQ_ApexAPIName__c) != null)?(''+cT.get(value.PMC_CPQ_ApexAPIName__c)):'';
            
            jsonReq.writeObject(strPlaceHolderValue);
        }
        return jsonReq;
    }
    /** 
* @description Returns the JSON Generator Object after adding fields based on if it is a lookup or not.
* @param lstCartFieldMap - Map for all the fields that have to be used in the JSON Request.
* @param cartObject - Argument of type Object that may be of type Quote or Aggregate result all similar to Quote.
* @param jsonReq - Reference of the jsonReq Object that is to have the additional fields that are in the Quote Field Map.
* @return qtLines - Returns list of Quote Lines of the quote in argument
*/
    public static JSONGenerator cartLookupJsonGeneration(List<PMC_CPQ_IntegrationFieldMap__mdt> lstCartFieldMap, Object cartObject, JSONGenerator jsonReq){
        String strPlaceHolderValue = '';
        Integer j = 0;
        AggregateResult lookupCart = (AggregateResult)cartObject;
        for (PMC_CPQ_IntegrationFieldMap__mdt value: lstCartFieldMap) {
            jsonReq.writeFieldName(value.PMC_CPQ_AttributeKey__c);
            strPlaceHolderValue = (lookupCart.get(('Lookup'+j)) != null)?(''+lookupCart.get(('Lookup'+j))):'';
            jsonReq.writeObject(strPlaceHolderValue);
            j++;
        }
        return jsonReq;
    }
    /** 
* @description Returns the map of quote line after adding fields.
* @param lstCartItemFieldMap - Map for all the fields that have to be used in the JSON Request.
* @param cartItem - Argument of type Object that may be of type Quote or Aggregate result all similar to Quote.
* @param mapCartItemDet - Reference of the jsonReq Object that is to have the additional fields that are in the Quote Field Map.
* @return mapCartItemDet - Returns map after adding values
*/
    public static Map<String, String> cartItemJSONGen(List<PMC_CPQ_IntegrationFieldMap__mdt> lstCartItemFieldMap, Object cartItem, Map<String, String> mapCartItemDet){
        for(PMC_CPQ_IntegrationFieldMap__mdt value: lstCartItemFieldMap){
            mapCartItemDet.put(value.PMC_CPQ_AttributeKey__c, ('' + ((((CartItem)cartItem).get(value.PMC_CPQ_ApexAPIName__c) == null)?'':((CartItem)cartItem).get(value.PMC_CPQ_ApexAPIName__c))));
        }
        return mapCartItemDet;
        
    }
    /** 
* @description Returns unique set of id of Quote
* @param strVal - Object to be converted to String and hit the end point.
* @return strProcessed - Returns String value which can be used to hit the end point.
*/
    public static String stringProcess(Object strVal){
        String strObject = JSON.serialize(strVal);
        String strProcessed = strObject.replace('\\\\','').substringAfter('"').substringBeforeLAst('"');
        strProcessed = strProcessed.replaceAll('\n','');
        strProcessed = strProcessed.replaceAll('\\\\','');
        return strProcessed;
    }


    

}