objects/CartItem.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_DH_DeliveryMode__c</fullName>
        <label>Delivery Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Barge</fullName>
                </value>
                <value>
                    <fullName>Truck</fullName>
                </value>
                <value>
                    <fullName>Rail</fullName>
                </value>
                <value>
                    <fullName>Vessel</fullName>
                </value>
                <value>
                    <fullName>Inventory Transfer</fullName>
                </value>
                <value>
                    <fullName>Container</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RFQ</fullName>
                    <default>true</default>
                    <label>RFQ</label>
                </value>
                <value>
                    <fullName>RTD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_CPQ_ProductLocation__c.object
<CustomObject>
    <description>This object is created as a part of  story to capture product and location data.</description>
    <label>Product Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CPQ_ContractEnd__c</fullName>
        <description>If Master contract exists - then formula to pull the date from Contract reference</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Quote End Date</inlineHelpText>
        <label>Contract Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ContractStart__c</fullName>
        <description>If Master contract exists - then formula to pull the date from Contract reference</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Quote Start Date</inlineHelpText>
        <label>Contract Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product.This is as per the  US GCPM 1064</description>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <infoMessage>Select Product Location Columns Link to add appropriate Locations</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>CPQ Quotes</relationshipLabel>
        <relationshipName>CPQ_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_QuoteShortNameDescription__c</fullName>
        <description>Based on the stanadardized Quote description across all quotes</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Quote Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_PaymentMethod__c</fullName>
        <description>This field is used to capture the method of payment for this quote by the customer</description>
        <inlineHelpText>Type of payment that a customer will use to pay</inlineHelpText>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Payment_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__PaymentTerms__c</fullName>
        <description>Terms that govern payment of the items in this quote.</description>
        <inlineHelpText>Indicates the Terms that govern payment of the items in this quote.</inlineHelpText>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash Against Documents</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 5 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 7 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 10 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 15 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 30 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 45 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Doc - 60 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 90 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 120 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 180 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Prepayment</fullName>
                </value>
                <value>
                    <fullName>Net 1 Day - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 2 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 3 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>05 Days - Document Lock Date</fullName>
                </value>
                <value>
                    <fullName>Net 7 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 10 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 14 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 15 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 17 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 21 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 28 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 29 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 30 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 31 Days - From Invoicing Date</fullName>
                    <label>Net 31 Days -  From Invoicing Date</label>
                </value>
                <value>
                    <fullName>Net 35 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 42 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 45 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 60 Days - From Invoicing Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product.</description>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SBQQ__Product__c</field>
                <operation>equals</operation>
                <valueField>PMC_CPQ_ProductLocation__c.PMC_CPQ_ProductName__c</valueField>
            </filterItems>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SBQQ__Product__c</field>
                <operation>equals</operation>
                <valueField>PMC_CPQ_ProductLocation__c.PMC_CPQ_ProductName__c</valueField>
            </filterItems>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this subscription.</description>
        <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WebCart.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_PaymentMethod__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACH</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>PO</fullName>
                </value>
                <value>
                    <fullName>Open Credit</fullName>
                </value>
                <value>
                    <fullName>Boletos</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PMC_DH_QuoteMgmtRelatedItemsClassTest.cls
/**
* @description : Test class for PMC_DH_QuoteManagementController
* @author      : Humera Rahath
* @userStory   : GDASF-121
* @last modified by Hemant Giri Goswami
* @last modified on 06-07-2023
**/
@isTest
public with sharing class PMC_DH_QuoteMgmtRelatedItemsClassTest {
    
    /**
* @description Method for getting test data from PMC_DH_TestDataFactoryClass
* 
* @param: none
* 
* @return: void
*
* @author Hemant
* 
*/
    @testSetup  
    static void setup()
    {
        Account acc=PMC_DH_TestDataFactoryClass.createParentTestAccount();        
        Profile profile = [SELECT Id FROM Profile WHERE Name =: PMC_DH_ConstantClass.PROFILE_NAME LIMIT 1];
        PMC_DH_TestDataFactoryClass.createTestUser(acc.Id,profile.Id);
        
        
        User userR=[SELECT id FROM User WHERE Email = 'demouser@test.com' limit 1];
        String strContactId=[SELECT contactId FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1][0].contactId;
        Id lstPermSet2=[select id from PermissionSet where Name ='PMC_DH_CPQ_PermissionSetLicense'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(userR.Id,lstPermSet2);
        Id lstPermSet=[select id from PermissionSet where Name ='SteelBrickDHCPQPartnerUser'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(userR.Id,lstPermSet);
        Id lstPermSet1=[select id from PermissionSet where Name ='PMC_DH_SuperBuyer'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(userR.Id,lstPermSet1);
        Id lstPermSet3=[select id from PermissionSet where Name ='PMC_DH_AccountCRE'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(userR.Id,lstPermSet3);
        WebStore webStore=PMC_DH_TestDataFactoryClass.createTestWebStore();
        System.runAs(userR)
        {
    		WebCart cartObj=PMC_DH_TestDataFactoryClass.buildCart(webStore.Id,acc.Id);
            insert cartObj;
            Product2 prod = PMC_DH_TestDataFactoryClass.createProduct();
            insert prod;
            PMC_DH_TestDataFactoryClass.createOpportunity(acc);
            test.startTest();
            SBQQ__Quote__c testQuote=PMC_DH_TestDataFactoryClass.createQuote(acc,strContactId,new Opportunity());
            SBQQ__QuoteLine__c testQuoteLine=PMC_DH_TestDataFactoryClass.creatQuoteLine(testQuote,prod);
            Contract testContract=PMC_DH_TestDataFactoryClass.createContract(testQuote.id,acc.id);
            testContract.Status='Activated';
            testContract.ContractTerm=1;
            update testContract;
            CartDeliveryGroup testCartDeliveryGroup=PMC_DH_TestDataFactoryClass.buildCartDeliveryGroup(cartObj.id);
            insert testCartDeliveryGroup;
            
            Account shipToAcc=PMC_DH_TestDataFactoryClass.createShipToTestAccount(acc);
            Schema.Location loc = PMC_DH_TestDataFactoryClass.createLocation();
            
            PMC_CPQ_ProductLocation__c prodLocation = PMC_DH_TestDataFactoryClass.createProductLocation(prod, loc);
            PMC_DH_TestDataFactoryClass.CartItemObject objCartItem=new PMC_DH_TestDataFactoryClass.CartItemObject();
            objCartItem.strCartId=cartObj.id;
            objCartItem.strProductId=prod.id;
            objCartItem.strDeliveryGroupId=testCartDeliveryGroup.id;
            objCartItem.strShipToAccId=shipToAcc.id;
            objCartItem.strQuoteLineId =testQuoteLine.id;
            objCartItem.strShipFromId=prodLocation.id;
            objCartItem.strContractId = testContract.Id;
            SBQQ__Subscription__c subsc=PMC_DH_TestDataFactoryClass.createSubscription(objCartItem);
            CartItem cartItem1=PMC_DH_TestDataFactoryClass.buildCartItem1(objCartItem);
            cartItem1.PMC_DH_Source__c='RFQ';
            cartItem1.PMC_DH_Subscription__c=subsc.id;
            cartItem1.PMC_DH_Contract__c=testContract.Id;
            cartItem1.PMC_DH_DeliveryMode__c='barge';
            upsert cartItem1;
        }    
    } 
    
    
    
/**
* @description Test Method for getConversationHistory  method
* 
* @param: none
* 
* @return: void
*
* @author Hemant
* 
*/
    
    @isTest
    public static void getConversationHistoryTest(){
        
        User userOR=[SELECT id,name,profile.name FROM User WHERE Email = 'demouser@test.com' limit 1];
        Test.startTest();
        System.runAs(userOR)
        {
        SBQQ__Quote__c objQuote=[SELECT ID,PMC_DH_PaymentMethod__c,PMC_CPQ_ContractStart__c,PMC_CPQ_ContractEnd__c,SBQQ__PaymentTerms__c,
                                CurrencyIsoCode FROM SBQQ__Quote__c WHERE PMC_CPQ_QuoteShortNameDescription__c='TestDH Quote' LIMIT 1];
            List<SBQQ__Quote__History> histList=new List<SBQQ__Quote__History>();
            List<SBQQ__QuoteLine__History> histQList=new List<SBQQ__QuoteLine__History>();
            
            SBQQ__Quote__History hist=new SBQQ__Quote__History(Field='Name');
            histList.add(hist);
            SBQQ__QuoteLine__History histql=new SBQQ__QuoteLine__History(Field='Incoterms');
            histQList.add(histql);
            //added as part of GDASF-19642
            PMC_DH_QuoteMgmtRelatedItemsClass.processConvo(histList,histQList); //added as part of GDASF-19642
    
            //added as part of GDASF-19642
            PMC_DH_QuoteMgmtRelatedItemsClass.PMC_DH_ConversationHistoryWrapper wrpResult = PMC_DH_QuoteMgmtRelatedItemsClass.getConversationHistory(objQuote.id);
            System.assert(wrpResult.lstQtHistory != null,'Success');
        }
        Test.stopTest();
        
    }
    
    
    @isTest
    public static void getExceptiongetShipTos()
    {
        User userOR=[SELECT id,name FROM User WHERE Email = 'demouser@test.com' limit 1];
        Test.startTest();
        System.runAs(userOR)
        {
            PMC_DH_DigitalHubB2BUtils.throwTestException=true;
            map<String,String> strResult=new map<String,String>() ;
            String strIns='';
            try{
                List<SBQQ__QuoteLine__History> lstMock=new List<SBQQ__QuoteLine__History>();
            strResult=PMC_DH_QuoteMgmtRelatedItemsClass.getShipTos(lstMock);
            }
            catch(Exception e){
                strIns='Exception';
            }
            System.assertEquals('Exception',strIns,'Passed');

        }   
        Test.stopTest();
    }
    
    
    @isTest
    public static void getExceptiongetAccountList(){
        User userOR=[SELECT id,name FROM User WHERE Email = 'demouser@test.com' limit 1];
        Test.startTest();
        System.runAs(userOR)
        {
            PMC_DH_DigitalHubB2BUtils.throwTestException=true;
            map<String,String> strResult=new map<String,String>() ;
            String strIns='';
            try{
                set<Id> setId=new set<Id>();
            strResult=PMC_DH_QuoteMgmtRelatedItemsClass.getAccountList(setId);
            }
            catch(Exception e){
                strIns='Exception';
            }
            System.assert(strIns.equals('Exception'),'Passed');

        }
        Test.stopTest();
    }
    
    @isTest
    public static void lstQuoteLineDatabaseException(){
        User userOR=[SELECT id,name FROM User WHERE Email = 'demouser@test.com' limit 1];
        Test.startTest();
        System.runAs(userOR)
        {
            PMC_DH_DigitalHubB2BUtils.throwTestException=true;
            List<SBQQ__QuoteLine__History> lstResult=new List<SBQQ__QuoteLine__History>();
            String strIns='';
            try{
            List<String> lstFL=new List<String>();
            lstResult=PMC_DH_QuoteMgmtRelatedItemsClass.lstQuoteLineDatabase('',lstFL);
            }
            catch(Exception e){
                strIns='Exception';
            }
            System.assert(strIns.equals('Exception'),'Passed');
        }
    Test.stopTest();

    }
    
    @isTest
    public static void lstQuoteDatabaseException(){
        User userOR=[SELECT id,name FROM User WHERE Email = 'demouser@test.com' limit 1];
        Test.startTest();
        System.runAs(userOR)
        {
            PMC_DH_DigitalHubB2BUtils.throwTestException=true;
            List<SBQQ__Quote__History> lstResult=new List<SBQQ__Quote__History>();
            String strIns='';
            try{
                
            lstResult=PMC_DH_QuoteMgmtRelatedItemsClass.lstQuoteDatabase('');
            }
            catch(Exception e){
                strIns='Exception';
            }
            System.assert(strIns.equals('Exception'),'Passed');
        }
    Test.stopTest();

    }
    
    
    @isTest
    public static void processConvoException(){
        User userOR=[SELECT id,name FROM User WHERE Email = 'demouser@test.com' limit 1];
        Test.startTest();
        System.runAs(userOR)
        {
            PMC_DH_DigitalHubB2BUtils.throwTestException=true;
            PMC_DH_QuoteMgmtRelatedItemsClass.PMC_DH_ConversationHistoryWrapper wrpConvHistory = new PMC_DH_QuoteMgmtRelatedItemsClass.PMC_DH_ConversationHistoryWrapper(); 
                List<SBQQ__Quote__History> lstQHis=new List<SBQQ__Quote__History>();
                List<SBQQ__QuoteLine__History> lstQLineHis= new List<SBQQ__QuoteLine__History>();
                wrpConvHistory=PMC_DH_QuoteMgmtRelatedItemsClass.processConvo(lstQHis,lstQLineHis); //added as part of GDASF-19642
            
            System.assert(wrpConvHistory.statusCodeMessage.strStatusCode!='000','Failed due to wrong status code');
        }
    Test.stopTest();

    }
        /**
* @description Test Method for getConversationHistory Exception  method
* 
* @param: none
* 
* @return: void
*
* @author Hemant
* 
*/        
    @isTest
        public static void getConversationHistoryException()
        {
            User userOR=[SELECT id,name FROM User WHERE Email = 'demouser@test.com' limit 1];
        Test.startTest();
        System.runAs(userOR)
        {
            String lstResult;
            lstResult=PMC_DH_QuoteMgmtRelatedItemsClass.getUserPersona('System Admin','efg');
            PMC_DH_QuoteMgmtRelatedItemsClass.getUserPersona(PMC_DH_ConstantClass.PMC_DH_APPNAME,'Sham Zack');
        System.assert(lstResult.equals('Mosaic'),'Success');
            PMC_DH_DigitalHubB2BUtils.throwTestException=true;
            try{
            lstResult=PMC_DH_QuoteMgmtRelatedItemsClass.getUserPersona('digital hub',userOR.name);
            }
            catch(Exception e){
                lstResult='Exception';
            }
            System.assert(lstResult.equals('Exception'),'Passed');
            
        }
            Test.stopTest();
            
        }
    
    
    /**
* @description Test Method for Exception  method
* 
* @param: none
* 
* @return: void
*
* @author Hemant
* 
*/        
    @isTest
        public static void exceptionTest()
        {
            User userOR=[SELECT id FROM User WHERE Email = 'demouser@test.com' limit 1];
        Test.startTest();
        System.runAs(userOR)
        {
            List<PMC_DH_QuoteDetailsWrapper.QuoteHistoryWrapper> lstResult=new List<PMC_DH_QuoteDetailsWrapper.QuoteHistoryWrapper>();
            PMC_DH_DigitalHubB2BUtils.throwTestException=true;
            
            try{
            PMC_DH_QuoteMgmtRelatedItemsClass.getConversationHistory('QId'); //added as part of GDASF-19642
            }
            catch(Exception e){
                lstResult=null;
            }
            System.assert(lstResult==null,'Passed');
        }
        Test.stopTest();  
        }
    
    @isTest
    public static void getConversationHistoryExceptionTest()
    {
        User userOR=[SELECT id FROM User WHERE Email = 'demouser@test.com' limit 1];
        Test.startTest();
        System.runAs(userOR)
        {
            List<PMC_DH_QuoteDetailsWrapper.QuoteHistoryWrapper> lstResult=new List<PMC_DH_QuoteDetailsWrapper.QuoteHistoryWrapper>();
            PMC_DH_DigitalHubB2BUtils.throwTestException=true;
            
            try{
                PMC_DH_QuoteMgmtRelatedItemsClass.getConversationHistory('QId'); //added as part of GDASF-19642
            }
            catch(Exception e){
                lstResult=null;
            }
            System.assert(lstResult==null,'Passed');
        }
        Test.stopTest();  
    }
    
    @istest
    public static void getContractsTest() // GDASF-19663 test class fix
    {
	User userOR=[SELECT id FROM User WHERE Email = 'demouser@test.com' limit 1];
    Test.startTest();
        System.runAs(userOR)
        {	SBQQ__Quote__c objQuote=[SELECT ID,PMC_DH_PaymentMethod__c,PMC_CPQ_ContractStart__c,PMC_CPQ_ContractEnd__c,SBQQ__PaymentTerms__c,
                                CurrencyIsoCode FROM SBQQ__Quote__c WHERE PMC_CPQ_QuoteShortNameDescription__c='TestDH Quote' LIMIT 1];
         String strQuoteId=objQuote.id;
         PMC_DH_QuoteMgmtRelatedItemsClass.PMC_DH_ContractListWrapper conWrr=new PMC_DH_QuoteMgmtRelatedItemsClass.PMC_DH_ContractListWrapper();
         conWrr=PMC_DH_QuoteMgmtRelatedItemsClass.getContracts(strQuoteId);
         System.assert(conWrr!=null,'Passed');
        }
       Test.stopTest();  
    }     
}