objects/CartItem.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_ProtocolIdentifier__c</fullName>
        <description>This field will store the protocol ID for 3rd party scenario in SAP defined from I203 and will be linked to the sales order as part of I066 Interface update.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Protocol Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_RequestNumber__c</fullName>
        <description>This field will be used in I066 and I203 to establish the relation between the request number for scheduling order and sales order</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Request Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote line where this order product is created from.</description>
        <inlineHelpText>The quote line where this order product is created from.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>OrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>PMC_CPQ_CustomerPrice__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_FinalPricePerTonne__c</fullName>
        <description>The Overall Final Price Per Tonne</description>
        <label>Final Price Per Tonne</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_LineTotalPrice__c</fullName>
        <label>Line Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_QuoteRecordType__c</fullName>
        <description>This picklist will hold the record type of Quote and will be used as a controlling field for many other picklist fields.</description>
        <label>Quote Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Domestic NA</fullName>
                </value>
                <value>
                    <fullName>Domestic SA</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>International Distribution</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>PMC_CPQ_CustomerPrice__c</fullName>
        <label>Sales Price Per Ton</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_FinalPricePerTonne__c</fullName>
        <label>Final Price Per Tonne</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_LineTotalPrice__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_QuoteRecordType__c</fullName>
        <label>Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Domestic NA</fullName>
                </value>
                <value>
                    <fullName>Domestic SA</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>International Distribution</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity of this subscription product purchased by the customer.</description>
        <inlineHelpText>Quantity of this subscription product purchased by the customer.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this subscription.</description>
        <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PMC_DH_OrderManagementUtil.cls
/** 
* @description Helper class for Order Management 
* @author Manisha
* @last modified on 2023-Dec-08
* @last modified by Manisha
* Created On       :2023-Dec-08
**/
public without sharing class PMC_DH_OrderManagementUtil {
    
    private static final String NORTH_AMERICA_REGION = 'Domestic NA';
    private static final String SOUTH_AMERICA_REGION = 'Domestic SA';
    
    /*************************************************************************
* @method Name  : getCartItemTotalPrice
* @description : Method to calculate total price of order item
* @param        objPriceQuantityWrapper
* @param        objCartItem
*****************************************************************************/
    public static void getCartItemTotalPrice(PMC_DH_OrderManagementController.PMC_DH_PriceQuantityWrapper objPriceQuantityWrapper,CartItem objCartItem){
        if ((objCartItem.PMC_DH_Subscription__r.SBQQ__QuoteLine__r.PMC_CPQ_QuoteRecordType__c == NORTH_AMERICA_REGION) && (objCartItem.PMC_DH_Subscription__r.SBQQ__QuoteLine__r.PMC_CPQ_CustomerPrice__c != null) && (objCartItem.Quantity != null)) {
            objPriceQuantityWrapper.decPrice = objPriceQuantityWrapper.decPrice + (objCartItem.PMC_DH_Subscription__r.SBQQ__QuoteLine__r.PMC_CPQ_CustomerPrice__c * objCartItem.Quantity.longValue());// GDASF-10697
        }
        if ((objCartItem.PMC_DH_Subscription__r.SBQQ__QuoteLine__r.PMC_CPQ_QuoteRecordType__c == SOUTH_AMERICA_REGION) && (objCartItem.PMC_DH_Subscription__r.SBQQ__QuoteLine__r.PMC_CPQ_FinalPricePerTonne__c != null) && (objCartItem.Quantity != null)) {
            objPriceQuantityWrapper.decPrice = objPriceQuantityWrapper.decPrice + (objCartItem.PMC_DH_Subscription__r.SBQQ__QuoteLine__r.PMC_CPQ_FinalPricePerTonne__c * objCartItem.Quantity.longValue());// GDASF-10697
        }
    }
    
    /*************************************************************************
* @method Name  : getLstQuoteLine
* @description : Method to get list of quote lines
* @param        lstQuoteLine
* @return       List<PMC_DH_PricingDetailWrapper.PMC_DH_QuoteLineWrapper>
*****************************************************************************/
    public static List<PMC_DH_PricingDetailWrapper.PMC_DH_QuoteLineWrapper> getLstQuoteLine(List<SBQQ__QuoteLine__c> lstQuoteLine){
        List<PMC_DH_PricingDetailWrapper.PMC_DH_QuoteLineWrapper> lstCartLineItem = new List<PMC_DH_PricingDetailWrapper.PMC_DH_QuoteLineWrapper>();
        for(SBQQ__QuoteLine__c objQuoteLine : lstQuoteLine){
            PMC_DH_PricingDetailWrapper.PMC_DH_QuoteLineWrapper objCartLineItem = new PMC_DH_PricingDetailWrapper.PMC_DH_QuoteLineWrapper();
            //Added as part of GPT-16862
            if ((objQuoteLine.PMC_CPQ_QuoteRecordType__c =='Domestic NA') && (objQuoteLine.PMC_CPQ_CustomerPrice__c != null)) {
                objCartLineItem.strQuoteLineId = objQuoteLine.Id;
                objCartLineItem.decPrice = objQuoteLine.PMC_CPQ_CustomerPrice__c.setScale(2, RoundingMode.HALF_UP);
            }
            //Added as part of GPT-16862
            if ((objQuoteLine.PMC_CPQ_QuoteRecordType__c =='Domestic SA') && (objQuoteLine.PMC_CPQ_FinalPricePerTonne__c != null)) {
                objCartLineItem.strQuoteLineId = objQuoteLine.Id;
                objCartLineItem.decPrice = objQuoteLine.PMC_CPQ_FinalPricePerTonne__c.setScale(2, RoundingMode.HALF_UP); 
            }
            lstCartLineItem.add(objCartLineItem);
        }
        return lstCartLineItem;
    }
    
    /*************************************************************************
* @method Name  : updatePriceAndQuantity
* @description : Method to update price and quantity fields
* @param        objPriceQuantityWrapper
* @param        objQuoteLine

*****************************************************************************/
    public static void updatePriceAndQuantity(PMC_DH_OrderManagementController.PMC_DH_PriceQuantityWrapper objPriceQuantityWrapper, SBQQ__QuoteLine__c objQuoteLine){
        //Added as part of GPT-16862
        if (objQuoteLine.PMC_CPQ_LineTotalPrice__c != null) {
            objPriceQuantityWrapper.decPrice =objPriceQuantityWrapper.decPrice + objQuoteLine.PMC_CPQ_LineTotalPrice__c; 
        }
        if(objQuoteLine.SBQQ__Quantity__c != null){
            objPriceQuantityWrapper.intQuantity = objPriceQuantityWrapper.intQuantity + objQuoteLine.SBQQ__Quantity__c.longValue();// GDASF-10697    
        }       
    } 
    
    /*************************************************************************
* @method Name  : getProtocolNo
* @description : Method to get Protocol Identifier for orderItem
* @param        order
* @return        String
*****************************************************************************/    
    //GDASF-21528
    public static String getProtocolNo(Order order){
        Set<String> setProtocolNo=new Set<String>();
        for(OrderItem oi:order.orderItems){
            if(oi.PMC_DH_RequestNumber__c!=null && oi.PMC_DH_ProtocolIdentifier__c!=null){
                setProtocolNo.add(oi.PMC_DH_ProtocolIdentifier__c);
            }
        }
        List<String> lstProtocolNo=new List<String>(setProtocolNo);
        if(lstProtocolNo.size()>0) {
            return lstProtocolNo.get(0);
        }
        return '';
    }
    /*************************************************************************
* @method Name  : getRequestNo
* @description : Method to get Request Id for OrderItem
* @param        order
* @return        Set<String>

*****************************************************************************/
    //GDASF-21528
    public static Set<String> getRequestNo(Order order){
        Set<String> setReqIds=new set<String>();
        for(OrderItem oi:order.orderItems){
            if(oi.PMC_DH_RequestNumber__c!=null){
                List<String> lstReqSplit=oi.PMC_DH_RequestNumber__c.split(';');
                if(!lstReqSplit.isEmpty()){
                    for(String strReqId:lstReqSplit){
                        Integer str=strReqId.indexOf('-',strReqId.indexof('-')+1);
                        String strReq=strReqId.substring(0,str);
                        setReqIds.add(strReq);
                    }
                }
              }
        }
        return setReqIds;
    }
}