objects/CartItem.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_ItemNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PMC DH Item Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Incoterms__c</fullName>
        <description>This field captures the user input for Incoterms.</description>
        <inlineHelpText>The rules and terms used in international and domestic trade contracts.</inlineHelpText>
        <label>Incoterms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_Incoterms1</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_ConfirmedQuantity__c</fullName>
        <label>Confirmed Quantity</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Incoterms__c</fullName>
        <description>This field captures the user input for Incoterms.</description>
        <label>Incoterms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_Incoterms1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ModeofTransportation__c</fullName>
        <description>This field captures the Mode of Transportation value.</description>
        <inlineHelpText>Mode of Transportation for this order line</inlineHelpText>
        <label>Mode of Transportation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_MoT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderLineStatus__c</fullName>
        <label>Order Line Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Placed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Completely Shipped</fullName>
                    <isActive>false</isActive>
                    <label>Completely Shipped</label>
                </value>
                <value>
                    <fullName>Partially Shipped</fullName>
                    <isActive>false</isActive>
                    <label>Partially Shipped</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PackageType__c</fullName>
        <description>The Packaging Type of the Product added to the quote.</description>
        <label>Packaging Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_PackagingType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Location</label>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ReasonOfRejectionOfItem__c</fullName>
        <description>This field indicates the Reason of Rejection of the Order</description>
        <label>Reason Of Rejection Of Item</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cust Initiated - Ordering Error</fullName>
                </value>
                <value>
                    <fullName>Cancellation Contract Expired</fullName>
                </value>
                <value>
                    <fullName>Supply/Availability</fullName>
                </value>
                <value>
                    <fullName>Rejected by workflow</fullName>
                </value>
                <value>
                    <fullName>Cust Initiated - Price Dispute</fullName>
                </value>
                <value>
                    <fullName>Volume low by Agronomic adjustments</fullName>
                </value>
                <value>
                    <fullName>CSR Initiated - Order Entry Error</fullName>
                </value>
                <value>
                    <fullName>Credit Management</fullName>
                </value>
                <value>
                    <fullName>Open Acct. vs Pre-Pay</fullName>
                </value>
                <value>
                    <fullName>Contract Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Shipment Diverted - Mosaic Request</fullName>
                </value>
                <value>
                    <fullName>Shipment Diverted - Customer Request</fullName>
                </value>
                <value>
                    <fullName>Carrier change</fullName>
                </value>
                <value>
                    <fullName>DH Cancellation</fullName>
                </value>
                <value>
                    <fullName>B2B Order Rejected</fullName>
                </value>
                <value>
                    <fullName>Canpotex Rejection</fullName>
                </value>
                <value>
                    <fullName>Order cannot be fulfilled</fullName>
                </value>
                <value>
                    <fullName>Reshipment</fullName>
                </value>
                <value>
                    <fullName>Diversion to New Customer</fullName>
                </value>
                <value>
                    <fullName>Deleted from SFDC via Amendment</fullName>
                </value>
                <value>
                    <fullName>Due to Complementary Invoice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RequestedShipDate__c</fullName>
        <description>This field captures the Requested ship date of the order product.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field captures the Requested ship date of the order product.</inlineHelpText>
        <label>Requested Ship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Products (Ship To)</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_DH_ItemNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Item Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_ShippedQuantity__c</fullName>
        <label>Shipped Quantity</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote line where this order product is created from.</description>
        <inlineHelpText>The quote line where this order product is created from.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>OrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subscription created from this order product</description>
        <inlineHelpText>Subscription created from this order product</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>SubscriptionOrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_PackageType__c</fullName>
        <description>This field captures the package type for each product record</description>
        <inlineHelpText>This field captures the package type for each product record</inlineHelpText>
        <label>Packaging Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_PackagingType</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>PMC_CPQ_ModeofTransportation__c</fullName>
        <description>This field is created  to check The mode of transportation</description>
        <inlineHelpText>Select the appropriate mode from the available options to track and manage logistics effectively</inlineHelpText>
        <label>MoT</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PMC_CPQ_QuoteRecordType__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_MoT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PackageType__c</fullName>
        <description>This field captures the package type for the product associated.</description>
        <label>Packaging Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_PackagingType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product.</description>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SBQQ__Product__c</field>
                <operation>equals</operation>
                <valueField>PMC_CPQ_ProductLocation__c.PMC_CPQ_ProductName__c</valueField>
            </filterItems>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created  to check the shipping address value of the line item.</description>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Lines (Ship To)</relationshipLabel>
        <relationshipName>Quote_Lines2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>PMC_CPQ_ModeofTransportation__c</fullName>
        <description>This field is created to check the mode of transportation.</description>
        <label>MoT</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_MoT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PackageType__c</fullName>
        <description>The Packaging Type of the Product added to the quote.</description>
        <label>Packaging Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_PackagingType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SBQQ__Product__c</field>
                <operation>equals</operation>
                <valueField>PMC_CPQ_ProductLocation__c.PMC_CPQ_ProductName__c</valueField>
            </filterItems>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to check the shipping address value</description>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions (Ship To)</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipment.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_ModeofTransportation__c</fullName>
        <inlineHelpText>Select the appropriate mode from the available options to track and manage logistics effectively.</inlineHelpText>
        <label>MOT</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_MoT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deliveries (Ship To)</relationshipLabel>
        <relationshipName>Deliveries2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/PMC_CPQ_Incoterms1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CFR</fullName>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
    </customValue>
    <customValue>
        <fullName>DAP</fullName>
    </customValue>
    <customValue>
        <fullName>DAT</fullName>
    </customValue>
    <customValue>
        <fullName>FCA</fullName>
    </customValue>
    <customValue>
        <fullName>FOB</fullName>
    </customValue>
    <customValue>
        <fullName>FOB/CIFADO</fullName>
    </customValue>
    <customValue>
        <fullName>CPT</fullName>
    </customValue>
    <customValue>
        <fullName>CIFFOB</fullName>
        <isActive>false</isActive>
        <label>CIFFOB</label>
    </customValue>
    <masterLabel>Incoterms 1</masterLabel>
</GlobalValueSet>

globalValueSets/PMC_CPQ_MoT.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Barge</fullName>
    </customValue>
    <customValue>
        <fullName>Container</fullName>
    </customValue>
    <customValue>
        <fullName>Rail</fullName>
    </customValue>
    <customValue>
        <fullName>Truck</fullName>
    </customValue>
    <customValue>
        <fullName>Vessel</fullName>
    </customValue>
    <description>This is created to hold mode of Transportation value sets</description>
    <masterLabel>MoT</masterLabel>
</GlobalValueSet>

globalValueSets/PMC_CPQ_PackagingType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Big Bag 1500 Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Saco 50 Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Saco 50 Kg - Paletizado</fullName>
    </customValue>
    <customValue>
        <fullName>Big Bag 1000 Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Saco 30 Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Saco 25 Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Big Bag 1350 Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Saco 25 Kg - Paletizado</fullName>
    </customValue>
    <customValue>
        <fullName>Transp. Valved NPK</fullName>
    </customValue>
    <customValue>
        <fullName>Transp. Valved Urea</fullName>
    </customValue>
    <customValue>
        <fullName>Braided   Valved</fullName>
    </customValue>
    <customValue>
        <fullName>BagOneWay 90x90x1,30</fullName>
    </customValue>
    <customValue>
        <fullName>BagOneWay 500Kg</fullName>
    </customValue>
    <customValue>
        <fullName>BagOneWay Liner 1,40</fullName>
    </customValue>
    <customValue>
        <fullName>Bag ONE-Way-Liner Urea 99x99x1,40</fullName>
    </customValue>
    <customValue>
        <fullName>Bag One Way Liner 500kg Liner 90X</fullName>
    </customValue>
    <customValue>
        <fullName>Tranç. Nitrog. Laminated</fullName>
    </customValue>
    <customValue>
        <fullName>Tranç. Urea Laminated</fullName>
    </customValue>
    <customValue>
        <fullName>BagOneWayLiner 750kg</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk</fullName>
    </customValue>
    <customValue>
        <fullName>Sifted Bulk</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk - Mosiac Production</fullName>
        <label>Bulk - Mosaic Production</label>
    </customValue>
    <customValue>
        <fullName>Big BagOneWay Liner</fullName>
    </customValue>
    <customValue>
        <fullName>Saco 30 Kg - Paletizado</fullName>
    </customValue>
    <customValue>
        <fullName>1000 KG Bags</fullName>
    </customValue>
    <customValue>
        <fullName>25KG Bags</fullName>
    </customValue>
    <customValue>
        <fullName>50KG Bags</fullName>
    </customValue>
    <customValue>
        <fullName>Trançada com Liner</fullName>
    </customValue>
    <customValue>
        <fullName>test</fullName>
        <isActive>false</isActive>
        <label>test</label>
    </customValue>
    <customValue>
        <fullName>saco 50kg</fullName>
        <isActive>false</isActive>
        <label>saco 50kg</label>
    </customValue>
    <description>The Packaging Type of the Product added to the quote.</description>
    <masterLabel>Packaging Type</masterLabel>
</GlobalValueSet>

classes/PMC_DH_OrderHelper.cls
/** 
* @description Helper class for order
* @author Mosaic Direct Dev 
* Created On       :2023-11-27
**/
public without sharing class PMC_DH_OrderHelper {
    private static final String CONST_VARIABLE_CODE2 = '000'; //GPT-34482
    private static final String CARTITEMS_UPDATE = 'CartItemsUpdate'; //GPT-34482
    private static final String CONST_VARIABLE_CODE = '111'; //GPT-34482
    private static final String DUPLICATE_CARTITEM = 'DuplicateCartItem'; //GPT-34482
	 /*************************************************************************
* @method Name  : getPackType
* @description  : Method to get PackType for shipment Items
* @param        ordItem
* @return       : String
*****************************************************************************/
    public static String getPackType(OrderItem ordItem){
        String strPackType = '';
          if(String.isNotBlank(ordItem.PMC_CPQ_PackageType__c) && ordItem.PMC_CPQ_PackageType__c != Null){
                strPackType = 'Packed';
            }
            else{
               strPackType = 'Bulk';
            }
        return strPackType;
    } 
     
 /*************************************************************************
    * @method Name  : updateSystemCustomerCallPriceDate
    * @author Mosaic Direct Dev 
    * @description  : Method to validate System Customer Call PriceDate
    * @param         lstOrderItemIDs
    * @param         strOrderId
    * @return   List<OrderItem>
    *****************************************************************************/  
    public static List<OrderItem> updateSystemCustomerCallPriceDate(List<String> lstOrderItemIDs, String strOrderId){
        if(!lstOrderItemIDs.isEmpty()){
            PMC_DH_OrderManagementController.validateOrderItemsList(lstOrderItemIDs);    
        }
        List<OrderItem> lstOrderItem =[SELECT Id, PMC_CPQ_RequestedShipDate__c, PMC_DH_ItemNumber__c, PMC_CPQ_ShipTo__c, PMC_CPQ_ShipTo__r.Name, 
                         PMC_CPQ_ShipTo__r.ShippingStreet, PMC_CPQ_ShipTo__r.ShippingCity, PMC_CPQ_ShipTo__r.ShippingState,PMC_CPQ_ReasonOfRejectionOfItem__c, 
                         PMC_CPQ_ShipTo__r.ShippingPostalCode, PMC_CPQ_ProductLocation__c, PMC_CPQ_ProductLocation__r.Name, 
                         PMC_CPQ_ModeofTransportation__c, PMC_CPQ_Incoterms__c, Product2.StockKeepingUnit, Quantity, AvailableQuantity, 
                         PMC_CPQ_ConfirmedQuantity__c, PMC_CPQ_OrderLineStatus__c, LineNumber, PMC_DH_ShippedQuantity__c, 
                         SBQQ__Subscription__r.SBQQ__QuoteLine__r.PMC_CPQ_PriceByDate__c,PMC_DH_CustomerCallPriceDate__c,PMC_CPQ_FPDPricefromPriceFx__c,
                         PMC_CPQ_FinalAgreedPrice__c,PMC_DH_CallPriceRequestedBySystem__c,OrderId, Product2Id
                        FROM OrderItem  WHERE OrderId =:strOrderId WITH SECURITY_ENFORCED];
        return lstOrderItem;
    }

    //GPT-34482
     /*************************************************************************
    * @method       checkNewOrDuplicateCartItems
    * @author       Mosaic Direct Dev 
    * @description  Method to check if cart item(s) are already present in cart
    * @param        lstCartitems 
    * @param        objExistingCartItem 
    * @return       PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper
    *****************************************************************************/  

    public static PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper checkNewOrDuplicateCartItems(List<CartItem> lstCartitems, CartItem objExistingCartItem){
        PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper result = new PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper();
        if(!lstCartitems.isEmpty() && (Schema.sObjectType.CartItem.isCreateable()||Schema.sObjectType.CartItem.isUpdateable())){
            //List<Database.UpsertResult> rt = Database.upsert(lstCartitems, false, AccessLevel.USER_MODE);
            Upsert lstCartitems;
            result = PMC_DH_DigitalHubB2BUtils.getMessageForStatusCode(CONST_VARIABLE_CODE2, CARTITEMS_UPDATE);
        }
        else if(String.isNotBlank(objExistingCartItem.Id)){ 
            result = PMC_DH_DigitalHubB2BUtils.getMessageForStatusCode(CONST_VARIABLE_CODE, DUPLICATE_CARTITEM);
        }
        return result;
    }
    
}