objects/CartItem.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_DH_DeliveryInstructions__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Delivery Instructions</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PMC_DH_DeliveryMode__c</fullName>
        <label>Delivery Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Barge</fullName>
                </value>
                <value>
                    <fullName>Truck</fullName>
                </value>
                <value>
                    <fullName>Rail</fullName>
                </value>
                <value>
                    <fullName>Vessel</fullName>
                </value>
                <value>
                    <fullName>Inventory Transfer</fullName>
                </value>
                <value>
                    <fullName>Container</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_DeliveryPONumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Delivery PO Number</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_Incoterms__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Incoterms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_NotaFiscalDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PMC DH Nota Fiscal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_DH_NotaFiscalNumber__c</fullName>
        <label>PMC DH Nota Fiscal Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_DH_PaymentTerms__c</fullName>
        <formula>IF(AND(!ISNULL(TEXT(( Cart.PMC_DH_PaymentTerms__c ))),! ISBLANK(TEXT(  Cart.PMC_DH_PaymentTerms__c))),TEXT( Cart.PMC_DH_PaymentTerms__c),NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Terms</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_PlantShipFrom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship From</label>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Cart Items (Ship From)</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_DH_RequestedShipmentDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PMC DH Requested Shipment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_DH_SAPRequestReferenceNumber__c</fullName>
        <formula>&quot;MD-&quot;+Cart.PMC_DH_CartReferenceNumber__c +&quot;-&quot;+ TEXT(PMC_DH_GroupReferenceNumber__c) +&quot;-&quot;+ TEXT(PMC_DH_ShipmentReferenceNumber__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Request Reference Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_SellOutPrice__c</fullName>
        <label>PMC DH Sell Out Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_DH_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_DH_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Location.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Plant__c</fullName>
        <description>Indicates Plant Number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Plant</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PMC_CPQ_ProductLocation__c.object
<CustomObject>
    <description>This object is created as a part of  story to capture product and location data.</description>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created  to check the location details.</description>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Product Locations</relationshipLabel>
        <relationshipName>ProductLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>CPQ Quotes</relationshipLabel>
        <relationshipName>CPQ_Quotes_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__PaymentTerms__c</fullName>
        <description>Terms that govern payment of the items in this quote.</description>
        <inlineHelpText>Indicates the Terms that govern payment of the items in this quote.</inlineHelpText>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash Against Documents</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 5 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 7 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 10 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 15 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 30 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 45 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Doc - 60 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 90 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 120 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 180 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Prepayment</fullName>
                </value>
                <value>
                    <fullName>Net 1 Day - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 2 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 3 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>05 Days - Document Lock Date</fullName>
                </value>
                <value>
                    <fullName>Net 7 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 10 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 14 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 15 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 17 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 21 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 28 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 29 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 30 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 31 Days - From Invoicing Date</fullName>
                    <label>Net 31 Days -  From Invoicing Date</label>
                </value>
                <value>
                    <fullName>Net 35 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 42 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 45 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 60 Days - From Invoicing Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>PMC_CPQ_FinalPricePerTonne__c</fullName>
        <description>The Overall Final Price Per Tonne</description>
        <label>Final Price Per Tonne</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product</description>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>PMC_CPQ_FinalPricePerTonne__c</fullName>
        <label>Final Price Per Tonne</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product</description>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SubscriptionNumberIdentifier__c</fullName>
        <description>This field will store the Subscription number(AutoNumber) which will be used as an External Id for 066I.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Subscription Number Identifier</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this subscription.</description>
        <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PMC_DH_CreateOrderRequestAPIUtility.cls
/**
* @description       : 
* @author            : Mosaic Direct | Dev Team
* @group             : 
* @last modified on  : 03-01-2024
* @last modified by  : Hemant Giri Goswami | hegoswami@deloitte.com
**/
public without sharing class PMC_DH_CreateOrderRequestAPIUtility {
    private static final String APP_NAME='Mosaic Direct';
    /**
* @description Request Structure Mapping in Mosaic Direct
* @author siddharth.pradhan@mosaicco.com | Mosaic Direct | 10-07-2023 
* @return String
* @param strCartId 
**/
    public static String createOrderRequestForAPI(Id strCartId) {
        
        // get all the cart item for the web cart specified
        // get webstore id
        // get effective account id
        // get cartId
        PMC_DH_OrderRequestWrapper orderSubWrap= new PMC_DH_OrderRequestWrapper();
        PMC_DH_OrderRequestWrapper.PMC_DH_RequestWrapper reqWrap;
        List<PMC_DH_OrderRequestWrapper.PMC_DH_RequestWrapper> lstReqWrap=new List<PMC_DH_OrderRequestWrapper.PMC_DH_RequestWrapper>();
        List<CartItem> cartItems=PMC_DH_CommerceCartQueryUtilsClass.getCartItemsForSingleCart(strCartId);
        
        for (CartItem ci : cartItems)   {
            {
                reqWrap=new PMC_DH_OrderRequestWrapper.PMC_DH_RequestWrapper();
                reqWrap.strReqId= ci.PMC_DH_SAPRequestReferenceNumber__c;
                reqWrap.strPlant=ci.PMC_DH_PlantShipFrom__r.PMC_CPQ_Location__r.PMC_CPQ_Plant__c;//'4000';
                reqWrap.strCustomerId = PMC_DH_CommerceCartQueryUtilsClass.getAccountExternalId(ci.cart.AccountId);
                reqWrap.strMaterial=ci.Product2.StockKeepingUnit ;//'FFALM';
                reqWrap.strIncoterms=ci.PMC_DH_Incoterms__c;//'FOB';
                reqWrap.strCreatedBy=ci.cart.CreatedBy.Name;
                reqWrap.strCreatedVia=APP_NAME;
                //reqWrap.strCreatedOn=String.valueOf(System.today()); // attribute was removed from SAP
                reqWrap.strNfeCoopCustomer=String.ValueOf(ci.PMC_DH_NotaFiscalNumber__c);//'';
                reqWrap.strNFEBillingDate=ci.PMC_DH_NotaFiscalDate__c != Null?formatRequestedDate(String.ValueOf(ci.PMC_DH_NotaFiscalDate__c)):'';               
                reqWrap.strGenPricePerunit=String.valueOf(ci.PMC_DH_Subscription__r.SBQQ__QuoteLine__r.PMC_CPQ_FinalPricePerTonne__c);  //change log - query update for GPT-28361 | added PMC_CPQ_FinalPricePerTonne__c
                reqWrap.strTotPrice=String.valueOf(ci.Quantity*Decimal.valueOf(reqWrap.strGenPricePerunit));
                reqWrap.strCustomerReqQty=String.ValueOf(ci.Quantity);
                reqWrap.strReqDelDat=ci.PMC_DH_RequestedShipmentDate__c != Null?formatRequestedDate(String.ValueOf(ci.PMC_DH_RequestedShipmentDate__c)):'';
                reqWrap.strContractItemNo=ci.PMC_DH_Subscription__r.PMC_CPQ_SubscriptionNumberIdentifier__c;
                reqWrap.strProtocolPrice=String.valueOf(ci.PMC_DH_SellOutPrice__c);
                reqWrap.strDelInstr=ci.PMC_DH_DeliveryInstructions__c;//'Test Instruction';//Third party scenarios
                reqWrap.strMot=ci.PMC_DH_DeliveryMode__c;
                reqWrap.strPoNo=ci.PMC_DH_DeliveryPONumber__c;
                reqWrap.strPaymentTermsn=ci.PMC_DH_Contract__r.SBQQ__Quote__r.SBQQ__PaymentTerms__c;//ci.cart.PMC_DH_PaymentTerms__c;
                reqWrap.strSelfConsInd='';
                if(( ci.PMC_DH_ShipTo__r.PMC_SS_Channel__c==PMC_DH_ConstantClass.COOPERATIVE_CHNL ||
                    ci.PMC_DH_ShipTo__r.Type==PMC_DH_ConstantClass.SOLD_TO)
                   && ci.PMC_DH_Subscription__r.SBQQ__QuoteLine__r.PMC_CPQ_VCOQuotation__c==true)
                {
                    reqWrap.strSelfConsInd=PMC_DH_ConstantClass.SELF_CONSMPT_X;
                }
                reqWrap.strCutomerMaterial=ci.PMC_DH_ItemNumber__c;
                reqWrap.strContractReq = ci.PMC_DH_Contract__r.PMC_CPQ_ContractNumberIdentifier__c;
                reqWrap.strUnitOfMeasure= ci.PMC_DH_Subscription__r.SBQQ__QuoteLine__r.PMC_CPQ_UnitofMeasure__c;//ci.PMC_DH_UnitofMeasure__c;
                reqWrap.strPackType = '';
                //reqWrap.strShipTo=ci.PMC_DH_ShipTo__r.PMC_SS_AccountExternalID__c;
                if(ci.PMC_DH_Subscription__r.SBQQ__QuoteLine__r.PMC_CPQ_VCOQuotation__c==true) {
                    reqWrap.strProtocolNo = ci.PMC_DH_ProtocolNumber__c;
                    reqWrap.strPackingType = PMC_DH_CommerceCartQueryUtilsClass.getPackOrPackageType(ci.PMC_DH_PackType__c,ci.PMC_DH_PackageType__c);
                    // added as part of GDASF-19767
                    //reqWrap.strShipTo = (getShipToIdOrAccIdentifier(ci)).get('strShipTo');
                    //reqWrap.strAccIdentifier = (getShipToIdOrAccIdentifier(ci)).get('strAccIdentifier');
                    reqWrap = getShipToIdOrAccIdentifier(ci, reqWrap);
                }
                else
                {
                    reqWrap.strShipTo = ci.PMC_DH_ShipTo__r.PMC_SS_AccountExternalID__c;
                    reqWrap.strPackingType = PMC_DH_CommerceCartQueryUtilsClass.getPackOrPackageType(ci.PMC_DH_PackType__c,ci.PMC_DH_Subscription__r.SBQQ__QuoteLine__r.PMC_CPQ_PackageType__c);// Added as part of GDASF-20003
                }
                // end of changes added as part of GDASF-19767
                lstReqWrap.add(reqWrap);
            }
        }
        orderSubWrap.lstResultData=lstReqWrap;
        return Json.serialize(orderSubWrap);
    }

    // GDASF-19767
    private static PMC_DH_OrderRequestWrapper.PMC_DH_RequestWrapper getShipToIdOrAccIdentifier(CartItem ci, PMC_DH_OrderRequestWrapper.PMC_DH_RequestWrapper reqWrap){
        if(ci.PMC_DH_ShipTo__r.PMC_SS_AccountExternalID__c == null)
        {
            if(ci.PMC_DH_ShipTo__r.PMC_SS_CPF__c != null){
                //reqWrap.strAccIdentifier = ci.PMC_DH_ShipTo__r.PMC_SS_CPF__c; //CPF Number
                  //reqWrap.strAccIdentifier = ci.PMC_DH_ShipTo__r.PMC_SS_CPF__c +'-'+ci.PMC_DH_ShipTo__r.PMC_SS_StateTaxNumber__c;
                //Character Limit is 25 
            String strdentifierCPF=ci.PMC_DH_ShipTo__r.PMC_SS_CPF__c +'-'+ci.PMC_DH_ShipTo__r.PMC_SS_StateTaxNumber__c;
           if(strdentifierCPF.length()>25){
            String strdentifierCPF2=   strdentifierCPF.right(25);
            reqWrap.strAccIdentifier =strdentifierCPF2;
           }else{
               reqWrap.strAccIdentifier = ci.PMC_DH_ShipTo__r.PMC_SS_CPF__c +'-'+ci.PMC_DH_ShipTo__r.PMC_SS_StateTaxNumber__c;
           }
            }
            else
            {
                //reqWrap.strAccIdentifier = ci.PMC_DH_ShipTo__r.PMC_SS_TaxIDOrCNPJOrCPF__c; //CNPJ Number
            //reqWrap.strAccIdentifier = ci.PMC_DH_ShipTo__r.PMC_SS_TaxIDOrCNPJOrCPF__c +'-'+ci.PMC_DH_ShipTo__r.PMC_SS_StateTaxNumber__c;
           //Character Limit is 25 
            String strdentifierCNPJ=ci.PMC_DH_ShipTo__r.PMC_SS_TaxIDOrCNPJOrCPF__c +'-'+ci.PMC_DH_ShipTo__r.PMC_SS_StateTaxNumber__c;
             if(strdentifierCNPJ.length()>25){
                        String strdentifierCNPJ2=   strdentifierCNPJ.right(25);
                        reqWrap.strAccIdentifier =strdentifierCNPJ2;
             }else{
                 reqWrap.strAccIdentifier = ci.PMC_DH_ShipTo__r.PMC_SS_TaxIDOrCNPJOrCPF__c +'-'+ci.PMC_DH_ShipTo__r.PMC_SS_StateTaxNumber__c;
             }
            
            }
        }
        else
        {
            reqWrap.strShipTo = ci.PMC_DH_ShipTo__r.PMC_SS_AccountExternalID__c;
     
     }
        return reqWrap;
    }
    
    private static String formatRequestedDate(String strReqDate) {
        List<String> datParamsList;
        String strFormattedDate;
        datParamsList = strReqDate.split('-');
        strFormattedDate=String.ValueOf(datParamsList[2]+'.'+datParamsList[1]+'.'+datParamsList[0]);  
        return strFormattedDate;     
    }
    /**
* @description Request Structure Mapping in Mosaic Direct
* @author  Mosaic Direct Dev 
* @return String
* @param strEffectiveAccountId 
**/
    public static String createRequestForOrderRequestStatus(String strEffectiveAccountId) {
        
        List<Account> lstAccount =[SELECT Id, AccountNumber FROM Account WHERE Id =:strEffectiveAccountId WITH SECURITY_ENFORCED];
        PMC_DH_OrderStatusRequestWrapper ordFetchWrapper = new PMC_DH_OrderStatusRequestWrapper();
        List<PMC_DH_OrderStatusRequestWrapper.PMC_DH_OrderRequestStatusWrapper> ordStatusWrapper = new List<PMC_DH_OrderStatusRequestWrapper.PMC_DH_OrderRequestStatusWrapper>();
        PMC_DH_OrderStatusRequestWrapper.PMC_DH_OrderRequestStatusWrapper wrap = new PMC_DH_OrderStatusRequestWrapper.PMC_DH_OrderRequestStatusWrapper();
        wrap.strAccountNumber = lstAccount[0].AccountNumber;
        ordStatusWrapper.add(wrap);
        /*for(Account acc : lstAccount){
PMC_DH_OrderStatusRequestWrapper.PMC_DH_OrderRequestStatusWrapper wrap = new PMC_DH_OrderStatusRequestWrapper.PMC_DH_OrderRequestStatusWrapper();
wrap.strAccountNumber = acc.AccountNumber;//'002000002'+ i;
ordStatusWrapper.add(wrap);
}*/
        ordFetchWrapper.listData = ordStatusWrapper; 
        return JSON.serialize(ordFetchWrapper);
    }
    
    /**
* @description Request Structure Mapping in Mosaic Direct
* @author Mosaic Direct Dev 
* @param  editWrapper
* @return String
**/
    public static String createOrderRequestForEdit(PMC_DH_RequestedOrderEditController.editRequestWrapper editWrapper) {
        PMC_DH_OrderRequestWrapper ordReqWrapper = new PMC_DH_OrderRequestWrapper();
        PMC_DH_OrderRequestWrapper.PMC_DH_RequestWrapper reqWrap=new PMC_DH_OrderRequestWrapper.PMC_DH_RequestWrapper();
        List<PMC_DH_OrderRequestWrapper.PMC_DH_RequestWrapper> lstReqWrap=new List<PMC_DH_OrderRequestWrapper.PMC_DH_RequestWrapper>();
        List<CartItem> cartItems=PMC_DH_CommerceCartQueryUtilsClass.getSingleCartItem(editWrapper.strOrderLineId);      
        if(!cartItems.isEmpty()){
            PMC_DH_OrderFetchWrapper responseWrapper = (PMC_DH_OrderFetchWrapper)JSON.deserialize(editWrapper.responseData, PMC_DH_OrderFetchWrapper.Class);
            Map<String,PMC_DH_OrderFetchWrapper.PMC_DH_ResponseWrapper> mapLineIdOriginalPayload = getMapLineIdOriginalPayload(responseWrapper.lstData,editWrapper);
            PMC_DH_OrderFetchWrapper.PMC_DH_ResponseWrapper wrapData = mapLineIdOriginalPayload.get(editWrapper.strOrderLineId);
            Map<String,ProductPriceAndSubs> mapOfContractDetails=getContractItemNo(wrapData.strContractFinalized);
            ProductPriceAndSubs wrapProdPriceSub=new ProductPriceAndSubs();
            String strGetKey='';
            if(cartItems[0].PMC_DH_Subscription__r.SBQQ__QuoteLine__r.PMC_CPQ_VCOQuotation__c==true){
                reqWrap.strProtocolNo = cartItems[0].PMC_DH_ProtocolNumber__c;
                strGetKey=wrapData.strMaterial+wrapData.strIncotterms+wrapData.strMot+wrapData.strPlant;
                // added as part of GDASF-19767
                //reqWrap.strShipTo = (getShipToIdOrAccIdentifier(cartItems[0])).get('strShipTo');
                //reqWrap.strAccIdentifier = (getShipToIdOrAccIdentifier(cartItems[0])).get('strAccIdentifier');
                reqWrap = getShipToIdOrAccIdentifier(cartItems[0] ,reqWrap);
            }
            else
            {
                reqWrap.strShipTo = wrapData.strShiptoId; //ci.PMC_DH_ShipTo__r.PMC_SS_AccountExternalID__c;
                strGetKey=wrapData.strMaterial+wrapData.strShiptoId+wrapData.strIncotterms+wrapData.strMot+wrapData.strPlant;
            }
            // end of changes added as part of GDASF-19767
            if(mapOfContractDetails.containsKey(strGetKey)){
                wrapProdPriceSub=mapOfContractDetails.get(strGetKey);
            }//key=SKU+SHIPTO+INCOTERM+MOT+PLANT
            reqWrap.strReqId= editWrapper.strOrderLineId ;
            reqWrap.strPlant= wrapData.strPlant;//'4000';
            reqWrap.strCustomerId = wrapData.strSoldtoId;//ci.cart.PMC_DH_Account__r.PMC_SS_AccountExternalID__c;
            reqWrap.strMaterial=wrapData.strMaterial;//ci.Product2.StockKeepingUnit ;//'FFALM';
            reqWrap.strIncoterms=wrapData.strIncotterms;//ci.PMC_DH_Incoterms__c;//'FOB';
            reqWrap.strCreatedBy=wrapData.strCreateBy;//ci.cart.CreatedBy.Name;
            reqWrap.strCreatedVia=APP_NAME;
            //reqWrap.strCreatedOn=wrapData.strCreatedOn;//String.valueOf(System.today());
            reqWrap.strNfeCoopCustomer=String.ValueOf(cartItems[0].PMC_DH_NotaFiscalNumber__c);//'';
            reqWrap.strNFEBillingDate=cartItems[0].PMC_DH_NotaFiscalDate__c != Null?formatRequestedDate(String.ValueOf(cartItems[0].PMC_DH_NotaFiscalDate__c)):'';
            reqWrap.strGenPricePerunit=String.valueOf(wrapProdPriceSub.decPrice);
            reqWrap.strCustomerReqQty=editWrapper.strReqQty;//String.ValueOf(ci.Quantity);
            reqWrap.strTotPrice=String.valueOf(Double.valueOf(editWrapper.strReqQty)*wrapProdPriceSub.decPrice);//GPT-32983
            reqWrap.strReqDelDat=editWrapper.strReqShipmentDate != Null?formatRequestedDate(String.ValueOf(editWrapper.strReqShipmentDate)):'';
            reqWrap.strContractItemNo=wrapProdPriceSub.strContractItemNumber;//ci.PMC_DH_Subscription__r.Name;
            reqWrap.strProtocolPrice=String.valueOf(cartItems[0].PMC_DH_SellOutPrice__c);//Third party scenarios
            reqWrap.strDelInstr=cartItems[0].PMC_DH_DeliveryInstructions__c;//Third party scenarios
            reqWrap.strMot=wrapData.strMot;//ci.PMC_DH_DeliveryMode__c;
            reqWrap.strPoNo=wrapData.strPoNumber;//ci.PMC_DH_DeliveryPONumber__c;
            reqWrap.strPaymentTermsn=cartItems[0].PMC_DH_Contract__r.SBQQ__Quote__r.SBQQ__PaymentTerms__c;
            reqWrap.strSelfConsInd=selfConsumptionIndicator(cartItems);
            reqWrap.strCutomerMaterial=wrapData.strCustMatnr;
            reqWrap.strContractReq = wrapData.strContractFinalized;
            reqWrap.strUnitOfMeasure= cartItems[0].PMC_DH_Subscription__r.SBQQ__QuoteLine__r.PMC_CPQ_UnitofMeasure__c;
            
            //reqWrap.strShipTo=wrapData.strShiptoId;//ci.PMC_DH_ShipTo__r.PMC_SS_AccountExternalID__c;
            
            reqWrap.strPackingType = wrapData.strPackingType;//(PMC_DH_CommerceCartQueryUtilsClass.getPackOrPackageType(wrapData.strPackType,wrapData.strPackingType)).get('strPackageType');
            reqWrap.strPackType = '';//(PMC_DH_CommerceCartQueryUtilsClass.getPackOrPackageType(wrapData.strPackType,wrapData.strPackingType)).get('strPackType');
        }
        lstReqWrap.add(reqWrap);
        ordReqWrapper.lstResultData = lstReqWrap;
        return JSON.serialize(ordReqWrapper);
    }
    
    private static String selfConsumptionIndicator(List<CartItem> lstCartItem)
    {
        String strIndicator='';
        if( !lstCartItem.isEmpty() && (lstCartItem[0].PMC_DH_ShipTo__r.PMC_SS_Channel__c==PMC_DH_ConstantClass.COOPERATIVE_CHNL ||
                                       lstCartItem[0].PMC_DH_ShipTo__r.Type==PMC_DH_ConstantClass.SOLD_TO)
           && lstCartItem[0].PMC_DH_Subscription__r.SBQQ__QuoteLine__r.PMC_CPQ_VCOQuotation__c==true)
        { 
            strIndicator=PMC_DH_ConstantClass.SELF_CONSMPT_X;
        }
        return strIndicator;
    }
    /**
* @description  method to get map of Contract item number and price per unit cost
* @author  Mosaic Direct Dev 
* @param  strContractNumber
* @return Map<String,ProductPriceAndSubs>
**/ 
    //changelog : GPT-28361 | get price per unit , contract item number
    public static Map<String,ProductPriceAndSubs> getContractItemNo(String strContractNumber){
        Map<String,ProductPriceAndSubs> mapOfProductToPriceAndSubs=new Map<String,ProductPriceAndSubs>(); //key=SKU+SHIPTO+INCOTERM+MOT+PLANT
        List<SBQQ__Subscription__c> lstSubs= [ Select id, PMC_CPQ_SubscriptionNumberIdentifier__c, SBQQ__Contract__r.PMC_CPQ_ContractNumberIdentifier__c,SBQQ__QuoteLine__r.SBQQ__Product__r.StockKeepingUnit,SBQQ__QuoteLine__r.PMC_CPQ_Incoterms1__c,SBQQ__QuoteLine__r.PMC_CPQ_ModeofTransportation__c,
                                              SBQQ__QuoteLine__r.PMC_CPQ_ProductLocation__r.PMC_CPQ_Location__r.PMC_CPQ_Plant__c, SBQQ__QuoteLine__r.PMC_CPQ_ShipTo__r.PMC_SS_SAPCustomerNumber__c,SBQQ__QuoteLine__r.PMC_CPQ_FinalPricePerTonne__c, SBQQ__QuoteLine__r.PMC_CPQ_VCOQuotation__c from SBQQ__Subscription__c 
                                              where SBQQ__Contract__r.PMC_CPQ_ContractNumberIdentifier__c=:strContractNumber WITH SECURITY_ENFORCED];
        
        for (SBQQ__Subscription__c sub : lstSubs) {
            ProductPriceAndSubs wrapProdPriceSub=new ProductPriceAndSubs();
            wrapProdPriceSub.strContractItemNumber=sub.PMC_CPQ_SubscriptionNumberIdentifier__c;
            wrapProdPriceSub.decPrice=sub.SBQQ__QuoteLine__r.PMC_CPQ_FinalPricePerTonne__c;
            String strKey=sub.SBQQ__QuoteLine__r.SBQQ__Product__r.StockKeepingUnit+sub.SBQQ__QuoteLine__r.PMC_CPQ_Incoterms1__c+sub.SBQQ__QuoteLine__r.PMC_CPQ_ModeofTransportation__c+sub.SBQQ__QuoteLine__r.PMC_CPQ_ProductLocation__r.PMC_CPQ_Location__r.PMC_CPQ_Plant__c;
            if(!sub.SBQQ__QuoteLine__r.PMC_CPQ_VCOQuotation__c) {
                strKey=sub.SBQQ__QuoteLine__r.SBQQ__Product__r.StockKeepingUnit+sub.SBQQ__QuoteLine__r.PMC_CPQ_ShipTo__r.PMC_SS_SAPCustomerNumber__c+sub.SBQQ__QuoteLine__r.PMC_CPQ_Incoterms1__c+sub.SBQQ__QuoteLine__r.PMC_CPQ_ModeofTransportation__c+sub.SBQQ__QuoteLine__r.PMC_CPQ_ProductLocation__r.PMC_CPQ_Location__r.PMC_CPQ_Plant__c;
            }
            mapOfProductToPriceAndSubs.put(strKey,wrapProdPriceSub);
        }
        return mapOfProductToPriceAndSubs;
        
    }
    
    /**
* @description  method to get mapLineId Original Payload
* @author  Mosaic Direct Dev 
* @param  responseWrapper
* @param  editWrapper
* @return Map<String,PMC_DH_OrderFetchWrapper.PMC_DH_ResponseWrapper>
**/   
    public static Map<String,PMC_DH_OrderFetchWrapper.PMC_DH_ResponseWrapper> getMapLineIdOriginalPayload(List<PMC_DH_OrderFetchWrapper.PMC_DH_ResponseWrapper> responseWrapper, PMC_DH_RequestedOrderEditController.editRequestWrapper editWrapper){
        
        Map<String,PMC_DH_OrderFetchWrapper.PMC_DH_ResponseWrapper> mapLineIdOriginalPayload = new Map<String,PMC_DH_OrderFetchWrapper.PMC_DH_ResponseWrapper>();
        
        for(PMC_DH_OrderFetchWrapper.PMC_DH_ResponseWrapper responseWrap : responseWrapper){
            if(!mapLineIdOriginalPayload.containsKey(editWrapper.strOrderLineId)){
                mapLineIdOriginalPayload.put(responseWrap.strReqId, responseWrap);
            }
        }
        return mapLineIdOriginalPayload;
    }
    
    /*************************************************************************
* @method Name  : QuoteInfoWrapper
* @description  : Wrapper class for quote Info
*****************************************************************************/
    public with sharing class ProductPriceAndSubs{
        /**
* @description Quote ID
* @return  String 
*/
        public Decimal decPrice{get;set;}
        /**
* @description Quote Number
* @return  String 
*/
        public String strContractItemNumber{get;set;}
    }
}