objects/CartItem.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_DeliveryMode__c</fullName>
        <label>Delivery Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Barge</fullName>
                </value>
                <value>
                    <fullName>Truck</fullName>
                </value>
                <value>
                    <fullName>Rail</fullName>
                </value>
                <value>
                    <fullName>Vessel</fullName>
                </value>
                <value>
                    <fullName>Inventory Transfer</fullName>
                </value>
                <value>
                    <fullName>Container</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_PaymentTerms__c</fullName>
        <formula>IF(AND(!ISNULL(TEXT(( Cart.PMC_DH_PaymentTerms__c ))),! ISBLANK(TEXT(  Cart.PMC_DH_PaymentTerms__c))),TEXT( Cart.PMC_DH_PaymentTerms__c),NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Terms</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CLM_OtherRejectionReason__c</fullName>
        <description>This field will store the explanation for Rejection, when customer Rejects Quote and Reason is Other.
This will be populated through CLM</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Other Cancelled Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_CustomerAcceptanceMethod__c</fullName>
        <description>This fied is used to capture the medium the quote has been accepted</description>
        <inlineHelpText>Medium through which customer communicated</inlineHelpText>
        <label>Customer Acceptance Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SBQQ__Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted by DH Customer</fullName>
                </value>
                <value>
                    <fullName>DocuSign</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>In Person</fullName>
                </value>
                <value>
                    <fullName>Phone Call</fullName>
                </value>
                <value>
                    <fullName>Text/Whatsapp</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RejectedReason__c</fullName>
        <label>Rejected Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SBQQ__Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_RejectedReasons</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WebCart.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_PaymentTerms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash Against Documents</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 7 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 10 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 15 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 45 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Doc - 60 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 90 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents-120 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents-180 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Prepayment</fullName>
                </value>
                <value>
                    <fullName>Net 1 Day - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 2 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 3 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>05 Days - Document Lock Date</fullName>
                </value>
                <value>
                    <fullName>Net 7 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 10 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 14 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 15 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 17 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 21 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 28 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 29 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 30 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 31 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 35 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 42 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 45 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 60 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 70 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 75 Days - From Invoicing Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_PrepaymentDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Prepayment Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/PMC_CPQ_RejectedReasons.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Price not appropriate</fullName>
    </customValue>
    <customValue>
        <fullName>Product not required</fullName>
    </customValue>
    <customValue>
        <fullName>Quote does not meet the requirements</fullName>
    </customValue>
    <customValue>
        <fullName>Shipment Window not appropriate</fullName>
    </customValue>
    <customValue>
        <fullName>Price</fullName>
        <isActive>false</isActive>
        <label>Price</label>
    </customValue>
    <customValue>
        <fullName>Volume</fullName>
        <isActive>false</isActive>
        <label>Volume</label>
    </customValue>
    <customValue>
        <fullName>Shipment Window</fullName>
        <isActive>false</isActive>
        <label>Shipment Window</label>
    </customValue>
    <customValue>
        <fullName>Availability</fullName>
        <isActive>false</isActive>
        <label>Availability</label>
    </customValue>
    <customValue>
        <fullName>Quote Request Denied</fullName>
        <isActive>false</isActive>
        <label>Quote Request Denied</label>
    </customValue>
    <masterLabel>Rejected Reasons</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/PMC_DH_RequestForQuoteUtil.cls
/**
* @description       : 
* @author            : Hemant Giri Goswami | hegoswami@deloitte.com
* @group             : 
* @last modified on  : 04-04-2024
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public without sharing class PMC_DH_RequestForQuoteUtil {
    public static Boolean throwTestException=false;
    
    /**
* @description method to handle validation
* @param businessType            
* @param mapBusinessTypeIncoterm 
* @param mapOfIncoterm           
* @return `List<PMC_DH_PicklistWrapper>`
*/
    public static List<PMC_DH_PicklistWrapper> getRestrcIncoTerms(String businessType, Map<String,List<Schema.PicklistEntry>> mapBusinessTypeIncoterm,  Map<String, Set<String>> mapOfIncoterm)
    {   
        Set<String> setRestrictedIncoterms=new Set<String>();
        List<PMC_DH_PicklistWrapper> lstPicklistWrapper = new List<PMC_DH_PicklistWrapper>();
        PMC_DH_PicklistWrapper picklistWrapper;
        if(mapOfIncoterm.containsKey(businessType)){
            setRestrictedIncoterms=mapOfIncoterm.get(businessType);
        }
        if(mapBusinessTypeIncoterm.containsKey(businessType)){
            for(Schema.PicklistEntry picklistIncotrm: mapBusinessTypeIncoterm.get(businessType)){
                if(!setRestrictedIncoterms.contains(picklistIncotrm.getValue()))
                {
                    picklistWrapper = new PMC_DH_PicklistWrapper();
                    picklistWrapper.label = picklistIncotrm.getLabel();
                    picklistWrapper.value = picklistIncotrm.getValue();
                    lstPicklistWrapper.add(picklistWrapper);
                    
                }
                
            }
        }
        return lstPicklistWrapper;
    }
    
    
    /**
* @description 
* @author Hemant Giri Goswami | hegoswami@deloitte.com | 02-06-2024 
**/
    public static void throwTestIntegrationExceptionForTest(){
        
        if (throwTestException && Test.isRunningTest()) {
            throw new CalloutException(PMC_DH_ConstantClass.TEST_EXCEPTION_MESSAGE);
        }
    }
    
    /*************************************************************************
* @method Name  : insertOpportunityShare
* @description   : to insert opportunity share record
* @param 		  objOppShare
* @return         Boolean
* @author       : Humera
*****************************************************************************/
    Public Static Boolean insertOpportunityShare(OpportunityShare objOppShare){
        Boolean boolIsShared=false; 
        try{
            throwTestIntegrationExceptionForTest();
            if(Schema.sObjectType.OpportunityShare.isCreateable()){
                Database.SaveResult srData = Database.insert(objOppShare, false);
                if(srData.isSuccess()){
                    boolIsShared=true;
                }
            }
        }
        Catch(Exception ex){
            PMC_ErrorLogClass.processException(ex); // MDErrorLog
        }
        return boolIsShared;
    }
/*************************************************************************
* @method Name  : updateAcceptedQuote
* @description   : update accepted Quote
* @param 		  objQuote
* @author       : Humera
*****************************************************************************/
    public static void updateAcceptedQuote(SBQQ__Quote__c objQuote){
        Boolean boolIsShared=PMC_DH_RequestForQuoteHelper.shareRecordWithPortalUser(objQuote.id);
        if(boolIsShared){
            objQuote.SBQQ__Primary__c=true;
            objQuote.PMC_CPQ_CustomerAcceptanceMethod__c='Accepted by DH Customer';
        }
    }
    

    /**
    * @methodName updateRejectedReason
    * @description update Rejected Reason
    * @author Mosaic Direct | Dev Team | 02-09-2024 
    * @param modelWrapper 
    * @param objQuote 
    **/
    public static void updateRejectedReason(PMC_DH_QuoteMgmtActionController.PMC_DH_ModelWrapper modelWrapper,SBQQ__Quote__c objQuote){
        if(modelWrapper.strSelectedReason!='Other'){
            objQuote.PMC_CPQ_RejectedReason__c=modelWrapper.strSelectedReason;
        }
        else{
            objQuote.PMC_CPQ_RejectedReason__c=modelWrapper.strSelectedReason;
            objQuote.PMC_CLM_OtherRejectionReason__c=modelWrapper.strReason;
        }
    }

    
    /*************************************************************************
    * @author : Rohan Undale
    * @method Name  : getPackagingTypeForQuote
    * @description  : Method to get Packaging Type
    * @return       : List<PMC_DH_PicklistWrapper>
    *****************************************************************************/
    public static List<PMC_DH_PicklistWrapper> getModeOfTransportationForCPT(){
        List<PMC_DH_PicklistWrapper> lstDeliveryModesCPT = new List<PMC_DH_PicklistWrapper>();
        List<String> lstDeliveryModes = PMC_DH_CommonSystemUtils.getListStoreConfigbyFeature(PMC_DH_ConstantClass.MOT_FOR_CPT);
        for(String strDeliveryMode : lstDeliveryModes){
            PMC_DH_PicklistWrapper picklistWrapper = new PMC_DH_PicklistWrapper();
            picklistWrapper.label = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(CartItem.PMC_DH_DeliveryMode__c.getDescribe(),strDeliveryMode);
            picklistWrapper.value = strDeliveryMode;
            lstDeliveryModesCPT.add(picklistWrapper);
        }
        return lstDeliveryModesCPT;
    }
     /*************************************************************************
* @method Name  : setPrePaymentDate
* @description   : to set payment date
* @param 		  objectData
* @return         date
* @author       : Lakshmi
*****************************************************************************/
    public static date setPaymentDate(object objectData){
        date returnDate;
        if (objectData instanceof WebCart){
            WebCart wb = (WebCart)objectData;
            returnDate= checkForPaymentTerm(wb.PMC_DH_PaymentTerms__c) ? wb.PMC_DH_PrepaymentDate__c:Date.ValueOf(returnDate);
           
        }
        if (objectData instanceof PMC_DH_QuoteUpdateWrapper){
            PMC_DH_QuoteUpdateWrapper ph = (PMC_DH_QuoteUpdateWrapper)objectData;
            returnDate =  checkForPaymentTerm(ph.strPaymentTerms) ? Date.valueOf(ph.datPrepaymentDate):Date.ValueOf(returnDate);  
        }
        return returnDate;
    }
  /*************************************************************************
* @method Name  : setPrePaymentDate
* @description   : to set payment date
* @param   objWebCart
* @param 	 paymentInfoWrapper 
* @return        date
* @author      Lakshmi
*****************************************************************************/
    public static date setPrePaymentDate(WebCart objWebCart,PMC_DH_PaymentInformationForQuoteWrapper paymentInfoWrapper){
    date returnDate;
    return checkForPaymentTerm(objWebCart.PMC_DH_PaymentTerms__c) ? paymentInfoWrapper.datPrepaymentDate: date.ValueOf(returnDate);
}
/*************************************************************************
* @method Name  : checkForPaymentTerm
* @description   : to check prepayment term
* @param 		  paymentTerm
* @return         boolean
* @author       : Lakshmi
*****************************************************************************/
    public static Boolean checkForPaymentTerm(string paymentTerm){
         Boolean boolisPayterm = PMC_DH_ConstantClass.FIXED_DATE.contains(paymentTerm) || PMC_DH_ConstantClass.PREPAYMENT.contains(paymentTerm);
            return boolisPayterm;
        
    }
/*************************************************************************
* @method Name  : getSalesArea
* @description   : method to get Sales Area
* @param 		  strSalesArea
*  @param         objWebCart
* @return         string
* @author       : Humera
*****************************************************************************/    
    public static string getSalesArea(String strSalesArea , WebCart objWebCart){
        String accSalesAreaJuncId  ;  
    if(strSalesArea!=null){
                    //fix as part of GPT-30638
                    List<String> lstUserSalesArea=strSalesArea.split(';');
                    Set<String> setUserSalesArea =new Set<String>(lstUserSalesArea);
                      // handle the null scenario dont query unless params have value
                    accSalesAreaJuncId = PMC_DH_RequestForQuoteHelper.getAccSalesAreaJuncId(objWebCart.AccountId, setUserSalesArea);
                   
                }
                return accSalesAreaJuncId;
            }
 }