objects/CartItem.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created  to check the shipping address value of the line item.</description>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Lines (Ship To)</relationshipLabel>
        <relationshipName>Quote_Lines2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_VCOQuotation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VCO Quotation</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to check the shipping address value</description>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions (Ship To)</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_VCOQuotation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VCO Quotation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this subscription.</description>
        <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PMC_DH_CartValidationUtil.cls
/**
 * @description       : 
 * @author            : Hemant Giri Goswami | hegoswami@deloitte.com
 * @group             : 
 * @last modified on  : 03-06-2024
 * @last modified by  : Hemant Giri Goswami | hegoswami@deloitte.com
**/
public without sharing class PMC_DH_CartValidationUtil {
    
    /**
    * @description 
    * @author Hemant Giri Goswami | hegoswami@deloitte.com | 11-07-2023 
    * @param wrpDetail 
    * @param wrp 
    * @param lstCartwrp 
    **/
    public static void validateVCO(PMC_DH_CartValidationController.WrapperDetail wrpDetail,PMC_DH_CartValidationController.CartValidationParentWrapper wrp,List<PMC_DH_CartValidationController.CartValidationWrapper> lstCartwrp)
    {
    if(wrpDetail.setVCO.size()==2 && wrpDetail.intFlagCheck==0) 
            { 
                wrpDetail.wrpWarning.hasErrors=TRUE;
                wrpDetail.wrpChild.strCartItemId=wrpDetail.cartItem.Id;
                wrpDetail.wrpChild.strSku=wrpDetail.cartItem.Product2.StockKeepingUnit;
                wrpDetail.wrpChild.strFlow=getDeliveryType(wrpDetail.cartItem.PMC_DH_Subscription__r.SBQQ__QuoteLine__r.PMC_CPQ_VCOQuotation__c);
                wrp.strSubjError=String.ValueOf(Label.PMC_DH_DiffDeliveryErrorMsg);
                wrp.strFooterErr=String.ValueOf(Label.PMC_DH_FooterDiffDelivery);
                wrp.strSource=PMC_DH_ConstantClass.RTD;
                lstCartwrp.add(wrpDetail.wrpChild);
            
            }
    }


private static String getDeliveryType(Boolean boolVCO)
{    String strDelivery=String.ValueOf(Label.PMC_DH_StandardDelivery);
        if(boolVCO)
        {
            strDelivery=String.ValueOf(Label.PMC_DH_ThirdPartyDelivery);
        }
        return strDelivery;
}


/**
* @description prodContractValid
* @author Hemant Giri Goswami | hegoswami@deloitte.com | 01-30-2024 
* @param productSKUContractMap 
* @param cItem 
* @param wrpDetail 
* @return Boolean 
**/
public static Boolean prodContractValid(Map<String,Set<String>> productSKUContractMap,CartItem cItem, PMC_DH_CartValidationController.WrapperDetail wrpDetail )
    {
        return (productSKUContractMap.ContainsKey(cItem.Product2.StockKeepingUnit) && wrpDetail.intFlagCheck!=1 );
    }



    /**
    * @description 
    * @author Hemant Giri Goswami | hegoswami@deloitte.com | 03-06-2024 
    * @param mapShipFrom 
    * @param quoteLineObjRecord 
    **/
    public static void mapCreationShipTo(Map<String,PMC_DH_AddressWrapper.AddressViewDetails> mapShipFrom,SBQQ__QuoteLine__c quoteLineObjRecord)
{
    PMC_DH_AddressWrapper.AddressViewDetails wrpAddress;
    
    if(quoteLineObjRecord != null && !mapShipFrom.containsKey(quoteLineObjRecord.id))
                {
                    wrpAddress=new PMC_DH_AddressWrapper.AddressViewDetails();
                    wrpAddress.strCity=quoteLineObjRecord.PMC_CPQ_Shipto__r.ShippingCity;
                    wrpAddress.strState=quoteLineObjRecord.PMC_CPQ_Shipto__r.ShippingState;
                    mapShipFrom.put(quoteLineObjRecord.PMC_CPQ_Shipto__c,wrpAddress);
                }
            
}
}