objects/Case.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_ActionReason__c</fullName>
        <label>Action Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
                <value>
                    <fullName>Rebill</fullName>
                </value>
                <value>
                    <fullName>Return</fullName>
                </value>
                <value>
                    <fullName>Reverse Shipment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_ApprovalStatus__c</fullName>
        <description>To indicate the approval status of the case</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Auto Approved</fullName>
                </value>
                <value>
                    <fullName>Final Approved</fullName>
                </value>
                <value>
                    <fullName>Level 1 Approved</fullName>
                </value>
                <value>
                    <fullName>Level 2 Approved</fullName>
                </value>
                <value>
                    <fullName>Level 3 Approved</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_CancelAmount__c</fullName>
        <label>Invoice Delta Cancel</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_SS_CaseStatus__c</fullName>
        <formula>CASE( Status , &apos;New&apos;, &apos;Open&apos;, &apos;Working&apos;, &apos;In Progress&apos;,&apos;Pending&apos;, &apos;In Progress&apos;,&apos;Escalated&apos;,&apos;In Progress&apos;,&apos;Re-Open&apos;,&apos;In Progress&apos;,&apos;Rejected&apos;,&apos;Closed&apos;,&apos;Closed&apos;,&apos;Closed&apos;,&apos;Closure Pending&apos;,&apos;Closed&apos;,&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SS_CreditDebitAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Credit/Debit Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_SS_DollarAmount__c</fullName>
        <label>Dollar Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_SS_InvoiceDifference__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Invoice Delta</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_SS_IssueReason__c</fullName>
        <description>Specifies the reason of the issue</description>
        <inlineHelpText>Contract Cancellation, Product request, Credit Request, Financial Solution and Anticipated Billing are for Brazil users ONLY</inlineHelpText>
        <label>Issue Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Account Issues</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Article Request</fullName>
                </value>
                <value>
                    <fullName>Call by Date</fullName>
                </value>
                <value>
                    <fullName>Cambio Exhange</fullName>
                </value>
                <value>
                    <fullName>Change to loading priorities</fullName>
                </value>
                <value>
                    <fullName>Consignment</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                    <label>Contract Cancellation</label>
                </value>
                <value>
                    <fullName>Credit Note Request</fullName>
                </value>
                <value>
                    <fullName>Credit Request</fullName>
                </value>
                <value>
                    <fullName>Data Entry</fullName>
                </value>
                <value>
                    <fullName>Debit Note Request</fullName>
                </value>
                <value>
                    <fullName>Delivery Delay</fullName>
                </value>
                <value>
                    <fullName>Demurrage</fullName>
                </value>
                <value>
                    <fullName>Diversion</fullName>
                </value>
                <value>
                    <fullName>Document Request</fullName>
                </value>
                <value>
                    <fullName>Donation Order/Bonus</fullName>
                </value>
                <value>
                    <fullName>Driver Verification/Change</fullName>
                </value>
                <value>
                    <fullName>Equipment Failure</fullName>
                </value>
                <value>
                    <fullName>Export Documentation</fullName>
                </value>
                <value>
                    <fullName>Export prioritization</fullName>
                </value>
                <value>
                    <fullName>Financial Solution</fullName>
                </value>
                <value>
                    <fullName>Include Script CIF</fullName>
                </value>
                <value>
                    <fullName>Incorrect Destination</fullName>
                </value>
                <value>
                    <fullName>Incorrect Label</fullName>
                </value>
                <value>
                    <fullName>Incorrect Product</fullName>
                </value>
                <value>
                    <fullName>Incorrect UOM</fullName>
                </value>
                <value>
                    <fullName>Incorrect Vehicle ID</fullName>
                </value>
                <value>
                    <fullName>IntelliTrans</fullName>
                </value>
                <value>
                    <fullName>Invoice Adjustments</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_NationalDirector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>National Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_SS_OriginalInvoiceAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Original Invoice Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_SS_RebillAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Invoice Rebill Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_SS_RegionalDirector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_SS_ReturnAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Return Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_SegmentManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_ServiceNowTicketNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ServiceNow Ticket Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_StatusLabel__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Service Now Status Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_Status__c</fullName>
        <label>Service Now Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Awaiting Agronomic and Legal Opinion</fullName>
                </value>
                <value>
                    <fullName>Awaiting analysis of acquittance</fullName>
                </value>
                <value>
                    <fullName>Awaiting Analysis of credit</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting Area Evaluation</fullName>
                </value>
                <value>
                    <fullName>Awaiting Commercial Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting Draft and Power of Attorney</fullName>
                </value>
                <value>
                    <fullName>Awaiting Legal Communication</fullName>
                </value>
                <value>
                    <fullName>Awaiting Legal Validation</fullName>
                </value>
                <value>
                    <fullName>Awaiting Mortgage Protocol</fullName>
                </value>
                <value>
                    <fullName>Awaiting Protocol Drafting</fullName>
                </value>
                <value>
                    <fullName>Awaiting Protocol Signature</fullName>
                </value>
                <value>
                    <fullName>Awaiting Registration</fullName>
                </value>
                <value>
                    <fullName>Awaiting Requester Information</fullName>
                </value>
                <value>
                    <fullName>Awaiting Signature</fullName>
                </value>
                <value>
                    <fullName>Awaiting Stock Valuation</fullName>
                </value>
                <value>
                    <fullName>Awaiting Treatment</fullName>
                </value>
                <value>
                    <fullName>Awaiting Value Approval</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Closed Complete</fullName>
                </value>
                <value>
                    <fullName>Document Validation</fullName>
                </value>
                <value>
                    <fullName>In Analysis</fullName>
                </value>
                <value>
                    <fullName>In Credit Analysis</fullName>
                </value>
                <value>
                    <fullName>In Execution</fullName>
                </value>
                <value>
                    <fullName>In Validation of Documents</fullName>
                </value>
                <value>
                    <fullName>In Warranty Validation</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Request of Notary Documents</fullName>
                </value>
                <value>
                    <fullName>Under Legal Analysis</fullName>
                </value>
                <value>
                    <fullName>Waiting for additional Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_SS_SNOW_StatusMapping__mdt.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_CaseStatus__c</fullName>
        <label>Case Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed</fullName>
                    <default>true</default>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_StatusTranslatedLabel__c</fullName>
        <label>Status Translated Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_Status__c</fullName>
        <label>SNOW Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SNOW Status Mapping</label>
    <pluralLabel>SNOW Status Mapping</pluralLabel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_RegionalDirector__c</fullName>
        <description>Field used to store the Regional Director of the user</description>
        <label>Regional Director</label>
        <relationshipName>Regional_Directors</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PMC_CaseTriggerHelperMethodExtension.cls
/**
* @description This class will be used to handle all triggers on Case object.
* @author Vedashri
* @storynumber GDASF-11309
*/
public with sharing class PMC_CaseTriggerHelperMethodExtension {
    /**
    * @description This method will be used to lock closed case.
    * @param mapOldCases - Map of old values of case records.
    * @param lstNewCases - List of triggering case records.
    */
    public static void lockClosedCase(Map<Id, Case> mapOldCases, List<Case> lstNewCases) {
        System.debug(LoggingLevel.FINE, 'Starting lockClosedCase method');
        try {
            List<Id> lstCaseIdToLock = new List<Id>();
            for(Case objCase: lstNewCases) {
                if(objCase.Status != PMC_SS_ConstantClass.RE_OPEN && mapOldCases.get(objCase.id).Status == PMC_SS_ConstantClass.CLOSED) {
                    lstCaseIdToLock.add(objCase.id);
                }
            }
            System.debug(LoggingLevel.FINE, 'Cases to lock: ' + lstCaseIdToLock);
            if(!lstCaseIdToLock.isEmpty()) {
                Approval.lock(lstCaseIdToLock);
            }
        } catch(Exception objQueryException) {
            System.debug(LoggingLevel.ERROR, 'Exception in lockClosedCase: ' + objQueryException);
            PMC_ErrorLogClass.processException(objQueryException);
        }
    }

    /** 
    * @description This method will be used to calculate invoice difference.
    * @param mapOldCases - Map of old values of case records.
    * @param lstNewCases - List of triggering case records.
    */ 
    public static void updateInvoiceDifference(Map<Id, Case> mapOldCases, List<Case> lstNewCases) {
        System.debug(LoggingLevel.FINE, 'Starting updateInvoiceDifference method');
        for(Case objCase : lstNewCases) {
            if(objCase.Type == PMC_SS_ConstantClass.INVOICE && objCase.PMC_SS_IssueReason__c == PMC_SS_ConstantClass.INVOICE_ADJUSTMENTS && string.isBlank(objCase.PMC_SS_ActionReason__c)) {
               // objCase.PMC_SS_InvoiceDifference__c = objCase.PMC_SS_OriginalInvoiceAmount__c - objCase.PMC_SS_RebillAmount__c;
                objCase.PMC_SS_InvoiceDifference__c = objCase.PMC_SS_RebillAmount__c - objCase.PMC_SS_OriginalInvoiceAmount__c;
   
                System.debug(LoggingLevel.FINE, 'Updated Invoice Difference for Case: ' + objCase.Id + ' to: ' + objCase.PMC_SS_InvoiceDifference__c);
            }
        }
    }

    /**
    * @description This method will be used to lock closed case.
    * @param mapOldCases - Map of old values of case records.
    * @param lstNewCases - List of triggering case records.
    */
    public static void updateStatusForSN(Map<Id, Case> mapOldCases, List<Case> lstNewCases) {
        System.debug(LoggingLevel.FINE, 'Starting updateStatusForSN method');
        try {
            Map<String, PMC_SS_SNOW_StatusMapping__mdt> mapSNStatus = new Map<String, PMC_SS_SNOW_StatusMapping__mdt>();
            for(PMC_SS_SNOW_StatusMapping__mdt objSNStatus : [SELECT Id, PMC_SS_SNOW_Status__c, PMC_SS_CaseStatus__c, PMC_SS_SNOW_StatusTranslatedLabel__c FROM PMC_SS_SNOW_StatusMapping__mdt WITH SECURITY_ENFORCED]) {
                mapSNStatus.put(objSNStatus.PMC_SS_SNOW_Status__c, objSNStatus);
                mapSNStatus.put(objSNStatus.PMC_SS_SNOW_StatusTranslatedLabel__c, objSNStatus);
            }
            System.debug(LoggingLevel.FINE, 'ServiceNow Status Mapping: ' + mapSNStatus);
            for(Case objCase: lstNewCases) {
                if(objCase.PMC_SS_SNOW_ServiceNowTicketNumber__c != null && objCase.PMC_SS_SNOW_StatusLabel__c != mapOldCases.get(objCase.id).PMC_SS_SNOW_StatusLabel__c && mapSNStatus.containsKey(objCase.PMC_SS_SNOW_StatusLabel__c)) {
                    objCase.Status = mapSNStatus.get(objCase.PMC_SS_SNOW_StatusLabel__c).PMC_SS_CaseStatus__c;
                    objCase.PMC_SS_SNOW_Status__c = mapSNStatus.get(objCase.PMC_SS_SNOW_StatusLabel__c).PMC_SS_SNOW_Status__c;
                    System.debug(LoggingLevel.FINE, 'Updated Case Status for Case: ' + objCase.Id + ' to: ' + objCase.Status);
                }
            }
        } catch(Exception objQueryException) {
            System.debug(LoggingLevel.ERROR, 'Exception in updateStatusForSN: ' + objQueryException);
            PMC_ErrorLogClass.processException(objQueryException);
        }
    }   

    /**
    * @description This method will be used to lock closed case.
    * @param lstNewCases - List of triggering case records.
    */
    public static void addAccountTeamMembersToCaseOnInsert(List<Case> lstNewCases) {
        System.debug(LoggingLevel.FINE, 'Starting addAccountTeamMembersToCaseOnInsert method');
        Set<Id> setAccountIds = new Set<Id>(); 
        for(Case objCase: lstNewCases) {
            setAccountIds.add(objCase.AccountId);
        }
        System.debug(LoggingLevel.FINE, 'Account Ids: ' + setAccountIds);
        
        Map<Id, Map<String,Id>> mapAccountWithManagers = new Map<Id, Map<String,Id>>();
        for (AccountTeamMember objAccountteammember : [SELECT Id, TeamMemberRole, AccountId, UserId FROM AccountTeamMember WHERE AccountId IN :setAccountIds WITH SECURITY_ENFORCED]) {
            if(mapAccountWithManagers.containsKey(objAccountteammember.AccountId)) {
                mapAccountWithManagers.get(objAccountteammember.AccountId).put(objAccountteammember.TeamMemberRole, objAccountteammember.UserId);
            } else {
                mapAccountWithManagers.put(objAccountteammember.AccountId, new Map<String,Id>{objAccountteammember.TeamMemberRole => objAccountteammember.UserId});
            }
        }
        System.debug(LoggingLevel.FINE, 'Account Team Members: ' + mapAccountWithManagers);
        PMC_CaseTriggerHelperMethodExtension.updateCasesManagers(lstNewCases, mapAccountWithManagers);
    }

    /**
    * @description This method will be used to lock closed case.
    * @param lstNewCases - List of triggering case records.
    * @param mapAccountWithManagers -  Map of 
    */
    private static void updateCasesManagers(List<Case> lstNewCases, Map<Id, Map<String, Id>> mapAccountWithManagers) {
        System.debug(LoggingLevel.FINE, 'Starting updateCasesManagers method');
        for (Case objCase: lstNewCases) {
            if (objCase.AccountId != null && mapAccountWithManagers.containsKey(objCase.AccountId)) {
                objCase.PMC_SS_NationalDirector__c = mapAccountWithManagers.get(objCase.AccountId).containsKey(PMC_SS_ConstantClass.NATIONAL_DIRECTOR) ? mapAccountWithManagers.get(objCase.AccountId).get('National Director') : objCase.PMC_SS_NationalDirector__c;
                objCase.PMC_SS_RegionalDirector__c = mapAccountWithManagers.get(objCase.AccountId).containsKey(PMC_SS_ConstantClass.REGIONAL_DIRECTOR) ? mapAccountWithManagers.get(objCase.AccountId).get('Regional Director') : objCase.PMC_SS_RegionalDirector__c;
                objCase.PMC_SS_SNOW_SegmentManager__c = mapAccountWithManagers.get(objCase.AccountId).containsKey(PMC_SS_ConstantClass.SEGMENT_MANAGER) ? mapAccountWithManagers.get(objCase.AccountId).get('Segment Manager') : objCase.PMC_SS_SNOW_SegmentManager__c;
                System.debug(LoggingLevel.FINE, 'Updated Managers for Case: ' + objCase.Id);
            }
        }
    }

    /**
    * @description This method will be used to lock closed case.
    * @param mapOldCases - List of triggering case records.
    * @param lstNewCases -  Map of 
    */
    public static void updateCaseToAutoApproved(Map<Id, Case> mapOldCases, List<Case> lstNewCases) { 
        System.debug(LoggingLevel.FINE, 'Starting updateCaseToAutoApproved method');
        Boolean isNAUser = PMC_CaseTriggerHelperMethodExtension.checkForNaUser();
        for(Case objCase : lstNewCases) {
            if(objCase.PMC_SS_ActionReason__c != mapOldCases.get(objCase.Id).PMC_SS_ActionReason__c && objCase.AccountId != null && PMC_CaseTriggerHelperMethodExtension.checkForActionAndAmount(objCase, isNAUser)) {
                objCase.PMC_SS_ApprovalStatus__c = PMC_SS_ConstantClass.AUTOAPPROVED;
                System.debug(LoggingLevel.FINE, 'Case set to Auto Approved for Case: ' + objCase.Id);
            }
        }
    }
    
    /**
    * @description This method will be used to lock closed case.
    * @param objCase - List of triggering case records.
    * @param isNAUser - List of triggering case records.
    * @return isAutoApproval - List of triggering case records.
    */
    private static boolean checkForActionAndAmount(Case objCase, Boolean isNAUser) {
        System.debug(LoggingLevel.FINE, 'Checking for Action and Amount for Case: ' + objCase.Id);
        boolean isAutoApproval = (((objCase.PMC_SS_ActionReason__c == PMC_SS_ConstantClass.CANCEL && objCase.PMC_SS_CancelAmount__c <= PMC_SS_ConstantClass.THOUSAND) || 
                                   (objCase.PMC_SS_ActionReason__c == PMC_SS_ConstantClass.REBILL && objCase.PMC_SS_RebillAmount__c <= PMC_SS_ConstantClass.THOUSAND) || 
                                   (objCase.PMC_SS_ActionReason__c == PMC_SS_ConstantClass.CREDIT && objCase.PMC_SS_CreditDebitAmount__c <= PMC_SS_ConstantClass.THOUSAND) || 
                                   (objCase.PMC_SS_ActionReason__c == PMC_SS_ConstantClass.ACTIONRETURN && objCase.PMC_SS_ReturnAmount__c <= PMC_SS_ConstantClass.THOUSAND) || 
                                   (objCase.PMC_SS_ActionReason__c == PMC_SS_ConstantClass.REVERSESHIPMENT && isNAUser && objCase.PMC_SS_DollarAmount__c <= PMC_SS_ConstantClass.THOUSAND )) && 
                                  objCase.PMC_SS_OriginalInvoiceAmount__c < PMC_SS_ConstantClass.ONEMILLION);
        System.debug(LoggingLevel.FINE, 'Auto Approval Check Result: ' + isAutoApproval);
        return isAutoApproval;
    }

    /**
    * @description This method will be used to lock closed case.
    * @return isNaUser - List of triggering case records.
    */
    private static boolean checkForNaUser() {
        System.debug(LoggingLevel.FINE, 'Checking if user is NA User');
        for(User objUser : [SELECT Id, Name, UserRole.Name FROM User WHERE Id = :UserInfo.getUserId() AND UserRoleId != null WITH SYSTEM_MODE]) {
            if(PMC_SS_ConstantClass.SSR_ROLES.contains(objUser.UserRole.Name)) {
                System.debug(LoggingLevel.FINE, 'User is an NA User');
                return true;
            }
        }
        System.debug(LoggingLevel.FINE, 'User is not an NA User');
        return false;
    }
}