objects/Case.object
<CustomObject>
    <fields>
        <fullName>OrderQuantity__c</fullName>
        <label>Order Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_SS_AtFaultParty__c</fullName>
        <label>At Fault Party</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Carrier</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Logistics Planning</fullName>
                </value>
                <value>
                    <fullName>Plant / Operations</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Supply Planning</fullName>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
                <value>
                    <fullName>Warehouse</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_OrderProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Link to Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_SS_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field stores the look-up to the Order record against which the case is being created</description>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SAPOrderNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SAP Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SS_ShipToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_SS_ShipmentDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SoldToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Sold To)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_SAPOrderNumber__c</fullName>
        <description>This field captures the order number in SAP.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Reference Order Number in SAP.</inlineHelpText>
        <label>SAP Order Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SoldToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture Sold To Account for the Order.</description>
        <inlineHelpText>Sold To Account for the Order.</inlineHelpText>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_RequestedShipDate__c</fullName>
        <description>This field captures the Requested ship date of the order product.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field captures the Requested ship date of the order product.</inlineHelpText>
        <label>Requested Ship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Products (Ship To)</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SoldtoAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Products (Sold to Account)</relationshipLabel>
        <relationshipName>Order_Products1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/OrderLineCasesController.cls
public with sharing class OrderLineCasesController {

    @AuraEnabled(cacheable=true)
    public static List<Case> getRelatedCases(Id orderItemId) {
        return [SELECT Id, CaseNumber, Status, Type, Contact.Name, PMC_SS_AtFaultParty__c, CreatedDate FROM Case WHERE PMC_SS_OrderProduct__c = :orderItemId ORDER BY CreatedDate DESC];
    }
    
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getOrderItemDetails(Id orderItemId) {
        OrderItem ord = [SELECT Id, OrderId, PMC_CPQ_SoldtoAccount__c, Order.Contract.PMC_CPQ_PrimaryContact__c, Order.PMC_CPQ_SAPOrderNumber__c, PMC_CPQ_ShipTo__c, Quantity, PMC_CPQ_RequestedShipDate__c FROM OrderItem WHERE Id = :orderItemId];

        Map<String, Object> result = new Map<String, Object>();
        result.put('AccountId', ord.PMC_CPQ_SoldtoAccount__c);
        result.put('ContactId', ord.Order.Contract.PMC_CPQ_PrimaryContact__c);
        result.put('PMC_SS_Order__c', ord.OrderId);
        result.put('PMC_SS_SAPOrderNumber__c', ord.Order.PMC_CPQ_SAPOrderNumber__c);
        result.put('PMC_SS_SoldToAccount__c', ord.PMC_CPQ_SoldtoAccount__c);
        result.put('PMC_SS_ShipToAccount__c', ord.PMC_CPQ_ShipTo__c);
        result.put('OrderQuantity__c', ord.Quantity);
        result.put('PMC_SS_ShipmentDate__c', ord.PMC_CPQ_RequestedShipDate__c);

        return result;
    }
}