objects/Case.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_ArticleType__c</fullName>
        <label>Article Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>FAQ</fullName>
                </value>
                <value>
                    <fullName>Procedure</fullName>
                </value>
                <value>
                    <fullName>Technical Bulletin/Notice</fullName>
                </value>
                <value>
                    <fullName>Training Document</fullName>
                </value>
                <value>
                    <fullName>Transition Document</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_BadOrder__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if Rail shipping case is a Bad Order</description>
        <label>Bad Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_SS_ContractAmendmentJustificationVal__c</fullName>
        <description>This field is to indicate the Contract Amendment Justification</description>
        <label>Contract Amendment Justification</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PMC_SS_ContractAmendmentType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial Input Error</fullName>
                </value>
                <value>
                    <fullName>Customer Request</fullName>
                </value>
                <value>
                    <fullName>Manufacturing Capacity Restriction</fullName>
                </value>
                <value>
                    <fullName>Quality Restriction</fullName>
                </value>
                <value>
                    <fullName>Raw Material / Product Restriction</fullName>
                </value>
                <value>
                    <fullName>Truck Restriction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_ContractAmendmentType__c</fullName>
        <description>This field is to indicate the Contract Amendment Type</description>
        <label>Contract Amendment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent Code</fullName>
                </value>
                <value>
                    <fullName>Agent’s Commission</fullName>
                </value>
                <value>
                    <fullName>Contract End Date</fullName>
                </value>
                <value>
                    <fullName>Contract Start Date</fullName>
                </value>
                <value>
                    <fullName>Culture Exchange</fullName>
                    <label>Culture</label>
                </value>
                <value>
                    <fullName>Due Date</fullName>
                </value>
                <value>
                    <fullName>Freight Cost</fullName>
                </value>
                <value>
                    <fullName>Incoterm</fullName>
                </value>
                <value>
                    <fullName>Packing</fullName>
                </value>
                <value>
                    <fullName>Plant/Origin</fullName>
                </value>
                <value>
                    <fullName>Price List</fullName>
                </value>
                <value>
                    <fullName>Product Exchange</fullName>
                    <label>Product Exchange;(Different Composition)</label>
                </value>
                <value>
                    <fullName>Sales Office</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
                <value>
                    <fullName>Unit Price</fullName>
                </value>
                <value>
                    <fullName>Volume Change</fullName>
                </value>
                <value>
                    <fullName>Payment Terms</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_ContractCancellationSubReason__c</fullName>
        <label>Contract Cancellation Sub Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PMC_SS_ContractCancellation__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Factory Problems</fullName>
                </value>
                <value>
                    <fullName>Lack of Raw Materials</fullName>
                </value>
                <value>
                    <fullName>Logistic Problems</fullName>
                </value>
                <value>
                    <fullName>Quality Problems</fullName>
                </value>
                <value>
                    <fullName>Unreleased Credit - Constitution of Guarantee</fullName>
                </value>
                <value>
                    <fullName>Unreleased Credit - Delinquency</fullName>
                </value>
                <value>
                    <fullName>Unreleased Credit - Surety</fullName>
                </value>
                <value>
                    <fullName>Unreleased Credit - Unauthorized term</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_ContractCancellation__c</fullName>
        <label>Contract Cancellation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Balance Return to Master Contract</fullName>
                    <isActive>false</isActive>
                    <label>Balance Return to Master Contract</label>
                </value>
                <value>
                    <fullName>Cancellation Due to Customer Death</fullName>
                </value>
                <value>
                    <fullName>Commercial Input Error</fullName>
                </value>
                <value>
                    <fullName>Customer Cancellation</fullName>
                </value>
                <value>
                    <fullName>Insufficient Loading Balance</fullName>
                </value>
                <value>
                    <fullName>Mosaic’s Failure</fullName>
                </value>
                <value>
                    <fullName>No Digital Signature &gt; 15 Days</fullName>
                </value>
                <value>
                    <fullName>No Physical Signature &gt; 40 Days</fullName>
                    <isActive>false</isActive>
                    <label>No Physical Signature &gt; 40 Days</label>
                </value>
                <value>
                    <fullName>Unapproved Credit Limit</fullName>
                </value>
                <value>
                    <fullName>Unpaid Expired Contracts &gt; 15 Days</fullName>
                    <isActive>false</isActive>
                    <label>Unpaid Expired Contracts &gt; 15 Days</label>
                </value>
                <value>
                    <fullName>Volume Reduction Due to Agronomic Adjustment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_IssueReason__c</fullName>
        <description>Specifies the reason of the issue</description>
        <inlineHelpText>Contract Cancellation, Product request, Credit Request, Financial Solution and Anticipated Billing are for Brazil users ONLY</inlineHelpText>
        <label>Issue Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Account Issues</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Article Request</fullName>
                </value>
                <value>
                    <fullName>Call by Date</fullName>
                </value>
                <value>
                    <fullName>Cambio Exhange</fullName>
                </value>
                <value>
                    <fullName>Change to loading priorities</fullName>
                </value>
                <value>
                    <fullName>Consignment</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                    <label>Contract Cancellation</label>
                </value>
                <value>
                    <fullName>Credit Note Request</fullName>
                </value>
                <value>
                    <fullName>Credit Request</fullName>
                </value>
                <value>
                    <fullName>Data Entry</fullName>
                </value>
                <value>
                    <fullName>Debit Note Request</fullName>
                </value>
                <value>
                    <fullName>Delivery Delay</fullName>
                </value>
                <value>
                    <fullName>Demurrage</fullName>
                </value>
                <value>
                    <fullName>Diversion</fullName>
                </value>
                <value>
                    <fullName>Document Request</fullName>
                </value>
                <value>
                    <fullName>Donation Order/Bonus</fullName>
                </value>
                <value>
                    <fullName>Driver Verification/Change</fullName>
                </value>
                <value>
                    <fullName>Equipment Failure</fullName>
                </value>
                <value>
                    <fullName>Export Documentation</fullName>
                </value>
                <value>
                    <fullName>Export prioritization</fullName>
                </value>
                <value>
                    <fullName>Financial Solution</fullName>
                </value>
                <value>
                    <fullName>Include Script CIF</fullName>
                </value>
                <value>
                    <fullName>Incorrect Destination</fullName>
                </value>
                <value>
                    <fullName>Incorrect Label</fullName>
                </value>
                <value>
                    <fullName>Incorrect Product</fullName>
                </value>
                <value>
                    <fullName>Incorrect UOM</fullName>
                </value>
                <value>
                    <fullName>Incorrect Vehicle ID</fullName>
                </value>
                <value>
                    <fullName>IntelliTrans</fullName>
                </value>
                <value>
                    <fullName>Invoice Adjustments</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_MOT__c</fullName>
        <description>The mode of transportation for a shipping case</description>
        <label>Mode of Transportation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Barge</fullName>
                </value>
                <value>
                    <fullName>Container</fullName>
                </value>
                <value>
                    <fullName>Rail</fullName>
                </value>
                <value>
                    <fullName>Truck</fullName>
                </value>
                <value>
                    <fullName>Vessel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PMC_SS_ClearDependentFieldValues.cls
/**
* @description This class will be used to handle to clear values of Contract mendment type and justification value.
* @author Swakeerth Gadda
* @storynumber GDASF-11118
*/

public with sharing class PMC_SS_ClearDependentFieldValues {
	/**
    * @description This method will be used to clear agreement type and justification values when case type is not transaction or issues reason is not amendment.
    * @param mapOldCases - Triggering case old version
	* @param lstNewCases - Triggering case records.
    */
    public static void clearDependentFieldValues(Map<Id, Case> mapOldCases, List<Case> lstNewCases){
        for(Case objCase : lstNewCases){
            if(
                (mapOldCases.get(objCase.Id).Type == PMC_SS_ConstantClass.CASE_TYPE_TRANSACTIONS && objCase.Type != PMC_SS_ConstantClass.CASE_TYPE_TRANSACTIONS) 
                || (mapOldCases.get(objCase.Id).PMC_SS_IssueReason__c == PMC_SS_ConstantClass.ISSUE_REASON_AMENDMENT && objCase.PMC_SS_IssueReason__c != PMC_SS_ConstantClass.ISSUE_REASON_AMENDMENT))
            	{
                objCase.PMC_SS_ContractAmendmentType__c	= null;
                objCase.PMC_SS_ContractAmendmentJustificationVal__c = null;
         	    }
            if(mapOldCases.get(objCase.Id).PMC_SS_IssueReason__c == PMC_SS_ConstantClass.ISSUE_REASON_ARTICLE_REQ && objCase.PMC_SS_IssueReason__c != mapOldCases.get(objCase.Id).PMC_SS_IssueReason__c) {
                objCase.PMC_SS_ArticleType__c = objCase.PMC_SS_IssueReason__c != PMC_SS_ConstantClass.ISSUE_REASON_ARTICLE_REQ ? '':objCase.PMC_SS_ArticleType__c;
            }
            clearCancellationSubReason(mapOldCases.get(objCase.Id),objCase);
            clearDependentFieldValues(mapOldCases.get(objCase.Id),objCase);
        }
    }
    /**
    * @description This method will be used to clear Contract Cancellation SubReason values.
    * @param objOldCase - Triggering case old version
	* @param objNewCase - Triggering case records.
    */
    private static void clearCancellationSubReason(Case objOldCase, Case objNewCase) {
        if(objOldCase.PMC_SS_ContractCancellation__c != objNewCase.PMC_SS_ContractCancellation__c && (objOldCase.PMC_SS_ContractCancellation__c == PMC_SS_ConstantClass.UNAPPROVED_CREDIT_LIMIT || objOldCase.PMC_SS_ContractCancellation__c == PMC_SS_ConstantClass.MOSAICS_FAILURE))
            {
                objNewCase.PMC_SS_ContractCancellationSubReason__c = objNewCase.PMC_SS_ContractCancellation__c != PMC_SS_ConstantClass.UNAPPROVED_CREDIT_LIMIT || objNewCase.PMC_SS_ContractCancellation__c != PMC_SS_ConstantClass.MOSAICS_FAILURE ? '':objNewCase.PMC_SS_ContractCancellationSubReason__c;
            }
    }
    /**
    * @description This method will be used to clear dependent field values.
    * @param objOldCase - Triggering case old version
	* @param objNewCase - Triggering case records.
    */
    Private static void clearDependentFieldValues(Case objOldCase, Case objNewCase){
            if(objNewCase.PMC_SS_IssueReason__c != objOldCase.PMC_SS_IssueReason__c || objNewCase.PMC_SS_MOT__c != objOldCase.PMC_SS_MOT__c  ) {
                objNewCase.PMC_SS_BadOrder__c =  objNewCase.PMC_SS_MOT__c != PMC_SS_ConstantClass.RAIL ? false:objNewCase.PMC_SS_BadOrder__c;
            }
        }   
}