objects/Case.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_SAP_CustomerNumber__c</fullName>
        <description>Number for Contact stored in SAP</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SAP Customer Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_AbatementContractNumber__c</fullName>
        <description>Only available when Reason is “Bonus/Rebate | 7”</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Abatement Contract Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_Business__c</fullName>
        <description>Business line of Customer</description>
        <label>Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>6</fullName>
                    <label>Bahamas</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>Distribution</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Fospar</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>IFC</label>
                </value>
                <value>
                    <fullName>88</fullName>
                    <label>Jupiter</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>Paraguay Mosaic</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>Potássio Mineração</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Production</label>
                </value>
                <value>
                    <fullName>TBD</fullName>
                    <isActive>false</isActive>
                    <label>TBD</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Terras Brasil</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_CPR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CPR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_CustomerCode__c</fullName>
        <description>7 digit customer code</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_EndorsementValue__c</fullName>
        <description>Field displayed when Warranty Type = &quot;CPR Endorsement&quot;</description>
        <label>Endorsement Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_ExactDateToBePaid__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Exact Date To Be Paid</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_FinancialOperationValue__c</fullName>
        <description>Field displayed when Warranty Type = &quot;CPR Disposal&quot; or &quot;Pledge&quot;</description>
        <label>Financial Operation Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_InitialRequestPeriod__c</fullName>
        <description>Select the initial request period</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Initial Request Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_Mortage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mortage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_MosaicPayingReceivingCompany__c</fullName>
        <label>Mosaic Paying / Receiving Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>4090</fullName>
                    <label>4090 - Mosaic Distribuição</label>
                </value>
                <value>
                    <fullName>4110</fullName>
                    <label>4110 - Fospar</label>
                </value>
                <value>
                    <fullName>4115</fullName>
                    <label>4115 - Bahamas</label>
                </value>
                <value>
                    <fullName>4350</fullName>
                    <label>4350 - Paraguay Mosaic</label>
                </value>
                <value>
                    <fullName>4460</fullName>
                    <label>4460 - IFC</label>
                </value>
                <value>
                    <fullName>4550</fullName>
                    <label>4550 - Mosaic Potássio</label>
                </value>
                <value>
                    <fullName>4560</fullName>
                    <label>4560 - Mosaic P&amp;K</label>
                </value>
                <value>
                    <fullName>4570</fullName>
                    <label>4570 - Terras Brasil</label>
                </value>
                <value>
                    <fullName>4690</fullName>
                    <label>4690 - Jupiter</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_OrderNumberorContractNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Order Number or Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_PayeeName__c</fullName>
        <description>Field displayed when Warranty Type = &quot;CPR Endorsement&quot;</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Payee Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_Program__c</fullName>
        <description>Only available when Reason is “Bonus/Rebate | 7”</description>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Grow Crops</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <label>Others</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>7</fullName>
                    <label>Bonus/Rebate</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Contractual Fine</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>Incident</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Intercompany</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Judicial Proceedings</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>Others</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>Reimbursement of Expenses</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Taxes and Fees</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_RecipientsofCirLetter__c</fullName>
        <description>Field to write the emails that will receive the Letter of Circularization, following the instructions. &quot;Enter the emails of External Customers here to receive information about the completion of this call;
For each e-mail provided, separate it with a comma (&quot;,&quot;), such as: joão@example.com, maria@example.com.&quot;.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Recipients of Circularization Letter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_RequestType__c</fullName>
        <description>Field to select the request type based on the ServiceNow Ticket Type</description>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Advance Reports</fullName>
                </value>
                <value>
                    <fullName>Banking Intervention</fullName>
                </value>
                <value>
                    <fullName>Billed and billable portfolio report</fullName>
                </value>
                <value>
                    <fullName>Closing of Services Exchange</fullName>
                </value>
                <value>
                    <fullName>Compensation reports</fullName>
                </value>
                <value>
                    <fullName>Complementary Note</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Core Registration</label>
                </value>
                <value>
                    <fullName>CRA</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>Credit note</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>Customer Registration</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <label>Debit note</label>
                </value>
                <value>
                    <fullName>Demurrage / Dispatch Closing</fullName>
                </value>
                <value>
                    <fullName>Discharge Receipt</fullName>
                </value>
                <value>
                    <fullName>Empty Factory</fullName>
                </value>
                <value>
                    <fullName>Enlargement of Registration to Another Center</fullName>
                    <label>Enlargement of Registration to Another Centerv</label>
                </value>
                <value>
                    <fullName>Export Exchange Closing</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Generate Billet</label>
                </value>
                <value>
                    <fullName>Import Exchange Closing</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Login and Password Unlock</label>
                </value>
                <value>
                    <fullName>MRO Exchange Closing</fullName>
                </value>
                <value>
                    <fullName>NDA Renewal</fullName>
                </value>
                <value>
                    <fullName>New NDA</fullName>
                </value>
                <value>
                    <fullName>New Product Registration</fullName>
                </value>
                <value>
                    <fullName>Premium Products</fullName>
                </value>
                <value>
                    <fullName>Product Registration in MIC</fullName>
                </value>
                <value>
                    <fullName>Receipt Composition</fullName>
                </value>
                <value>
                    <fullName>Registration Change</fullName>
                </value>
                <value>
                    <fullName>Replan</fullName>
                </value>
                <value>
                    <fullName>Return of Values</fullName>
                </value>
                <value>
                    <fullName>Scrap Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_SegmentManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SNOW_WarrantyType__c</fullName>
        <description>Select the type of warranty</description>
        <label>Warranty Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>1</fullName>
                    <label>Bail</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>CPR</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>CPR Endorsement</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Disposal</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>Fiduciary Sale</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Mortgage</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>Pledge</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_SAP_CustomerNumber__c</fullName>
        <description>Number for Contact stored in SAP</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SAP Customer Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PMC_SS_ServiceNowWrapper.cls
/**
 * @description       : Used to perform JSON for ServiceNow Ticket creation 
 * @author            : Vedashri
 * @last modified on  : 11-01-2023
**/

public  with sharing class PMC_SS_ServiceNowWrapper {
    private String u_customer_name;
    private String u_cod_customer;
    private String callerID ;
    private String u_request_type_paid_contracts;
    private String request_type;
    private String u_request_type; 
    private String u_customer_sap_code;
    private String u_business;
    private String u_due_date_payment;
    private String u_reason;
    private String u_program;
    private String u_abatement_contract;
    private String u_incident_number;
    private String u_email_customer_receipt;
    private String u_order_number_contract_or_invoice;
    private String u_email_client_circularisation_letter;
    private String u_initial_date_circularisation_letter;
    private String u_company_mosaic;
    private String u_client_name;
    private String u_segment_manager;
    private String u_warranty_type;
    private String u_operation_value;
    private String u_payee_name;
    private String u_type_of_warranty_cpr;
    private String u_type_of_warranty_mortage;
    private String u_payment_effective_date;
    private String u_endorsement_value;
    private String comments;
    /**
     * @description - Method used to fetch the Invoice Details related to Account Id
     * @param objCase - Case Object
     * @param strSolutionType -  Selected Soulution Type
     * @param strComments - Comments to send to ServiceNow
     */

    public PMC_SS_ServiceNowWrapper(Case objCase,String strSolutionType, String strComments){
        
        String strRequestTypeKey = label.PMC_SS_SNOW_RequestType_KeyValue;
        Map<String,String> mapRequestType = (Map<String,String>)JSON.deserialize(strRequestTypeKey, Map<String,String>.class);
        u_customer_name = objCase.Contact.Name;
        u_cod_customer = objCase.PMC_SS_SNOW_CustomerCode__c;
        u_warranty_type = objCase.PMC_SS_SNOW_WarrantyType__c;
        u_request_type_paid_contracts = request_type = u_request_type=  mapRequestType.containsKey(objCase.PMC_SS_SNOW_RequestType__c) ? mapRequestType.get(objCase.PMC_SS_SNOW_RequestType__c) :'';
        u_due_date_payment = u_payment_effective_date =  String.valueOf(objCase.PMC_SS_SNOW_ExactDateToBePaid__c);
        u_client_name = objCase.Contact.Name;
        //u_operation_value = objCase.PMC_SS_SNOW_FinancialOperationValue__c;
        u_segment_manager = objCase.PMC_SS_SNOW_SegmentManager__r.FederationIdentifier;
        //u_endorsement_value = objCase.PMC_SS_SNOW_EndorsementValue__c;
        u_payee_name = objCase.PMC_SS_SNOW_PayeeName__c;
        u_email_customer_receipt = objCase.ContactEmail;
        u_order_number_contract_or_invoice = objCase.PMC_SS_SNOW_OrderNumberorContractNumber__c;
        u_type_of_warranty_cpr = String.valueOf(objCase.PMC_SS_SNOW_CPR__c);
        u_type_of_warranty_mortage = String.valueOf(objCase.PMC_SS_SNOW_Mortage__c);
        u_customer_sap_code = objCase.PMC_SS_SAP_CustomerNumber__c;
        u_business = objCase.PMC_SS_SNOW_Business__c;
        u_reason = objCase.PMC_SS_SNOW_Reason__c;
        u_program = objCase.PMC_SS_SNOW_Program__c;
        u_abatement_contract = objCase.PMC_SS_SNOW_AbatementContractNumber__c;
        u_incident_number = objCase.CaseNumber;
       
        u_email_client_circularisation_letter = objCase.PMC_SS_SNOW_RecipientsofCirLetter__c;
        u_initial_date_circularisation_letter = String.valueOf(objCase.PMC_SS_SNOW_InitialRequestPeriod__c);
        u_company_mosaic = objCase.PMC_SS_SNOW_MosaicPayingReceivingCompany__c;
        //String strCustomerSAPCode = String.isBlank(objCase.PMC_SS_SAP_CustomerNumber__c) ? '' :objCase.PMC_SS_SAP_CustomerNumber__c;

        callerID = [SELECT FederationIdentifier FROM User WHERE Id = :UserInfo.getUserId() WITH SYSTEM_MODE].FederationIdentifier;
        comments = strComments;
         /*if(strSolutionType=='Release of Paid Contracts' || strSolutionType == 'Collections Portal')
        {
			
            String strContractNumber = objCase.PMC_SS_NewContract__c == null ? '':objCase.PMC_SS_NewContract__r.ContractNumber;
            Double dbContractValue = objCase.PMC_SS_NewContract__r.SBQQ__Quote__r.SBQQ__CustomerAmount__c == null ? 0:objCase.PMC_SS_NewContract__r.SBQQ__Quote__r.SBQQ__CustomerAmount__c;
            comments = 'Customer SAP Code:'+ strCustomerSAPCode+'\n Contract Number:'+strContractNumber +
                        '\n Contract Value:'+dbContractValue +'\n '+strComments;        
        }
        
       else if(strSolutionType == 'Use of Credits, Return, Receipt of Discharge and Reports')
        {
            String strInitialDate = objCase.PMC_SS_SNOW_InitialDate__c != null ? '\n Initial Date:'+ objCase.PMC_SS_SNOW_InitialDate__c : '';
            String strFinalDate = objCase.PMC_SS_SNOW_FinalDate__c != null ? '\n Final Date:'+ objCase.PMC_SS_SNOW_FinalDate__c : '';
            comments = 'Request Type:'+ objCase.PMC_SS_SNOW_RequestType__c+strInitialDate+strFinalDate+'\nCustomer SAP Code:'+ strCustomerSAPCode+'\n '+strComments;
        }
        else if(strSolutionType == 'Warranty Formalization' || strSolutionType == 'Perform Warranty' || strSolutionType == 'Debit or Credit Notes')
        {
            comments = strComments;
        }
        else if(strSolutionType == 'Customer Credit Analysis')
        {
            comments = 'Currency used in this analysis is:'+objCase.CurrencyIsoCode+'\n'+strComments;
        } 
        else if(strSolutionType == 'Circularization Letters')
        {
            String strCustomerSAPCode = String.isBlank(objCase.PMC_SS_SAP_CustomerNumber__c) ? '' :objCase.PMC_SS_SAP_CustomerNumber__c;
            comments = 'Customer SAP Code:'+ strCustomerSAPCode+'\n '+strComments;
        } */
    }
}