objects/Case.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_ActionReason__c</fullName>
        <label>Action Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
                <value>
                    <fullName>Rebill</fullName>
                </value>
                <value>
                    <fullName>Return</fullName>
                </value>
                <value>
                    <fullName>Reverse Shipment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_CancelAmount__c</fullName>
        <label>Invoice Delta Cancel</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_SS_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>PMC_CPQ_Invoice__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_SS_OrderProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Link to Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_SS_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field stores the look-up to the Order record against which the case is being created</description>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_SS_OriginalInvoiceAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Original Invoice Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_SS_RebillAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Invoice Rebill Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_ShipToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to reference Shipping account.</description>
        <inlineHelpText>Ship To Account for the order.</inlineHelpText>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Ship To Account)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SoldToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture Sold To Account for the Order.</description>
        <inlineHelpText>Sold To Account for the Order.</inlineHelpText>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_ModeofTransportation__c</fullName>
        <description>This field captures the Mode of Transportation value.</description>
        <inlineHelpText>Mode of Transportation for this order line</inlineHelpText>
        <label>Mode of Transportation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_MoT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Location</label>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SoldtoAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Products (Sold to Account)</relationshipLabel>
        <relationshipName>Order_Products1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/PMC_CPQ_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_BillToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Delivery__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Delivery associated to this invoice.</description>
        <label>Delivery</label>
        <referenceTo>Shipment</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_InvoiceId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Invoice Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PMC_CPQ_NetInvoicedQuantity__c</fullName>
        <label>Net Invoiced Quantity</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OriginalAmount__c</fullName>
        <label>Original Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ParentInvoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Invoice</label>
        <referenceTo>PMC_CPQ_Invoice__c</referenceTo>
        <relationshipLabel>Related Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RemainingAmount__c</fullName>
        <label>Remaining Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SoldToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices (Sold To)</relationshipLabel>
        <relationshipName>PMC_CPQ_SoldToInvoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_TotalInvoiceValue__c</fullName>
        <label>Total Invoice Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_CPQ_ProductLocation__c.object
<CustomObject>
    <description>This object is created as a part of  story to capture product and location data.</description>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created  to check the location details.</description>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Product Locations</relationshipLabel>
        <relationshipName>ProductLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Shipment.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_DeliveryItemID__c</fullName>
        <description>This field captures the delivery Item ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Delivery Item ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_DeliveryItemName__c</fullName>
        <description>This field captures the delivery Item Name</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Delivery Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ModeofTransportation__c</fullName>
        <inlineHelpText>Select the appropriate mode from the available options to track and manage logistics effectively.</inlineHelpText>
        <label>MOT</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_MoT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field captures the Order Number.</description>
        <label>Order Number</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PlantID__c</fullName>
        <description>This field captures the  Plant ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Plant ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deliveries (Ship To Account)</relationshipLabel>
        <relationshipName>Deliveries1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShippedDate__c</fullName>
        <description>This field captures the shipped  Date.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipped Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_VehicleID__c</fullName>
        <description>This field captures the vehicle Vehicle ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ShipmentItem.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_DeliveryItemID__c</fullName>
        <description>This field captures the delivery Item ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SAP Delivery Item ID</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PMC_CPQ_DeliveryItemName__c</fullName>
        <description>This field captures the delivery Item Name.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Delivery Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ModeofTransportation__c</fullName>
        <inlineHelpText>Select the appropriate mode from the available options to track and manage logistics effectively</inlineHelpText>
        <label>MOT</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_MoT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field captures the order Order Item.</description>
        <label>Order Item</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Delivery Items</relationshipLabel>
        <relationshipName>Delivery_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PlantID__c</fullName>
        <description>This field captures the  Plant ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Plant ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Location</label>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Delivery Lines</relationshipLabel>
        <relationshipName>Delivery_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShippedDate__c</fullName>
        <description>This field captures the shipped  Date.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipped Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_VehicleID__c</fullName>
        <description>This field captures the vehicle Vehicle ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/PMC_CPQ_MoT.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Barge</fullName>
    </customValue>
    <customValue>
        <fullName>Container</fullName>
    </customValue>
    <customValue>
        <fullName>Rail</fullName>
    </customValue>
    <customValue>
        <fullName>Truck</fullName>
    </customValue>
    <customValue>
        <fullName>Vessel</fullName>
    </customValue>
    <description>This is created to hold mode of Transportation value sets</description>
    <masterLabel>MoT</masterLabel>
</GlobalValueSet>

classes/PMC_SS_CaseRelatedUpdateCtrl.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 08-02-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class PMC_SS_CaseRelatedUpdateCtrl {

    /**
     * @description - Wrapper class to hold the order related details
     */

    public class OrderDetailsWrapper {
        /**
         * @description - holds the account details
         */
        @AuraEnabled
        public ObjectDetailsWrapper objAccountWrapper{get;set;}

        /**
         * @description - holds the contract details
         */
        @AuraEnabled
        public ObjectDetailsWrapper objContractWrapper{get;set;}

        /**
         * @description - holds the ship-to account details
         */
        @AuraEnabled
        public ObjectDetailsWrapper objShipToAccountWrapper{get;set;}

        /**
         * @description - holds the sold-to account details
         */
        @AuraEnabled
        public ObjectDetailsWrapper objSoldToAccountWrapper{get;set;}
        
        /**
         * @description - holds the order object
         */
        @AuraEnabled
        public Order objOrder{get;set;}
        
        /**
         * @description - holds the list of order related order products
         */
        @AuraEnabled
        public List<OrderItem> lstOrderItems{get;set;}

        /**
         * @description - holds the list of order related order products
         */
        @AuraEnabled
        public List<PMC_CPQ_Invoice__c> lstInvoices{get;set;}
    }

    
    /**
     * @description - Generic Wrapper class to hold the object record name & id
     */
    public class ObjectDetailsWrapper {
        /**
         * @description - holds the object Id
         */
        @AuraEnabled
        public Id idRecord{get;set;}

        /**
         * @description - holds the object name
         */
        @AuraEnabled
        public String strRecordName{get;set;}

        /**
         * @description - constructor for wrapper class
         * @param idRecord - Record Id
         * @param strRecordName - Record Name
         */
        public ObjectDetailsWrapper(Id idRecord, String strRecordName) {
            this.idRecord =  idRecord;
            this.strRecordName = strRecordName;
        }
    }

    /**
     * @description - Method used to fetch the Order Details
     * @param strOrderId - Order Id
     * @return OrderDetailsWrapper - Returns Wrapper of type OrderDetailsWrapper
     */

    @AuraEnabled(cacheable=true)
    public static OrderDetailsWrapper getOrderItems(String strOrderId){
        try {
            Order objOrder = [SELECT Id, AccountId, Account.Name, ContractId, Contract.Name, Contract.ContractNumber,
                                    PMC_CPQ_ShipToAccount__c, PMC_CPQ_ShipToAccount__r.Name, PMC_CPQ_SoldToAccount__c, PMC_CPQ_SoldToAccount__r.Name,
                                    (SELECT Id, OrderItemNumber, OrderId, UnitPrice, PMC_CPQ_ProductLocation__r.PMC_CPQ_Location__r.PMC_CPQ_Plant__c FROM OrderItems),
                                    (SELECT Id, Name, PMC_CPQ_InvoiceId__c, PMC_CPQ_Contact__c, PMC_CPQ_NetInvoicedQuantity__c,
                                        PMC_CPQ_Contact__r.Name, PMC_CPQ_OriginalAmount__c, PMC_CPQ_OrderProduct__c,
                                        PMC_CPQ_RemainingAmount__c, PMC_CPQ_TotalInvoiceValue__c
                                        FROM Invoices__r
                                        WHERE PMC_CPQ_Delivery__c IN : [SELECT Id, PMC_CPQ_Order__c FROM Shipment WHERE PMC_CPQ_Order__c =: strOrderId])
                                    FROM Order                                       
                                    WHERE Id =: strOrderId 
                                    WITH SECURITY_ENFORCED];

            if(objOrder != null) {
                OrderDetailsWrapper objOrderDetailsWrapper = new OrderDetailsWrapper();
                objOrderDetailsWrapper.objOrder = objOrder;

                ObjectDetailsWrapper objAccountWrapper = new ObjectDetailsWrapper(objOrder.AccountId, objOrder.Account.Name);
                objOrderDetailsWrapper.objAccountWrapper = objAccountWrapper;

                ObjectDetailsWrapper objContractWrapper = new ObjectDetailsWrapper(objOrder.ContractId, objOrder.Contract.ContractNumber);
                objOrderDetailsWrapper.objContractWrapper = objContractWrapper;

                ObjectDetailsWrapper objShipToAccountWrapper = new ObjectDetailsWrapper(objOrder.PMC_CPQ_ShipToAccount__c, objOrder.PMC_CPQ_ShipToAccount__r.Name);
                objOrderDetailsWrapper.objShipToAccountWrapper = objShipToAccountWrapper;

                ObjectDetailsWrapper objSoldToAccountWrapper = new ObjectDetailsWrapper(objOrder.PMC_CPQ_SoldToAccount__c, objOrder.PMC_CPQ_SoldToAccount__r.Name);
                objOrderDetailsWrapper.objSoldToAccountWrapper = objSoldToAccountWrapper;

                objOrderDetailsWrapper.lstOrderItems = objOrder.OrderItems;
                objOrderDetailsWrapper.lstInvoices = objOrder.Invoices__r;

                return objOrderDetailsWrapper; 
            }
        } 
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        
        return null;
    }

    /**
     * @description - Method used to fetch the delivery item Details
     * @param strOrderItemId - Order Item Id
     * @return List<ShipmentItem> - Returns List of Shipment Items
     */
    @AuraEnabled(cacheable=true)
    public static List<ShipmentItem> getDeliveryItems(String strOrderItemId){
        try {
            return [SELECT Id, PMC_CPQ_OrderProduct__c, ShipmentItemNumber, PMC_CPQ_DeliveryItemName__c,  PMC_CPQ_DeliveryItemID__c,
                    /*PMC_CPQ_ModeofTransportation__c,*/ PMC_CPQ_PlantID__c, PMC_CPQ_VehicleID__c, PMC_CPQ_ShippedDate__c
                    FROM ShipmentItem                                           
                    WHERE PMC_CPQ_OrderProduct__c =: strOrderItemId 
                    WITH SECURITY_ENFORCED];            
        } 
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * @description - Method used to update Case Object
     * @param objCaseDetailsWrapper -Wrapper holding all case details
     * @return Case - Returns Case Object
     */
    @AuraEnabled
    public static Case updateCaseRecord(PMC_SS_CaseDetailsWrapper objCaseDetailsWrapper){
        try {
            Case objCase = [SELECT Id, PMC_SS_ActionReason__c, PMC_SS_Invoice__c, PMC_SS_Order__c,
                            PMC_SS_OrderProduct__c, PMC_SS_OriginalInvoiceAmount__c, PMC_SS_CancelAmount__c, PMC_SS_RebillAmount__c, 
                            PMC_SS_InvoiceDifference__c, AccountId, ContactId, PMC_SS_AtFaultParty__c, PMC_SS_PaymentRequestType__c,
                            PMC_SS_SoldToAccount__c, PMC_SS_ShipToAccount__c, PMC_SS_CreditDebitAmount__c, 
                            PMC_SS_Plant__c, PMC_SS_ReturnQuantity__c, PMC_SS_ReturnAmount__c, PMC_SS_MOT__c,
                            PMC_SS_VehicleId__c, PMC_SS_PGIDate__c, PMC_SS_HyperLink__c
                            FROM Case 
                            WHERE Id =: objCaseDetailsWrapper.caseId WITH SECURITY_ENFORCED LIMIT 1];
                        
            if(objCase != null) {

                objCase.PMC_SS_ActionReason__c = objCaseDetailsWrapper.actionReason;
                objCase.PMC_SS_Order__c = objCaseDetailsWrapper.orderId;
                objCase.PMC_SS_OrderProduct__c = objCaseDetailsWrapper.orderItemId;
                objCase.PMC_SS_Invoice__c = objCaseDetailsWrapper.invoiceId;
                objCase.PMC_SS_OriginalInvoiceAmount__c =  objCaseDetailsWrapper.originalInvoiceAmount;
                objCase.PMC_SS_AtFaultParty__c = objCaseDetailsWrapper.atFaultParty;
                objCase.PMC_SS_PaymentRequestType__c = objCaseDetailsWrapper.paymentRequestType;

                updateActionSpecificFields(objCaseDetailsWrapper, objCase);
            }

            if(Schema.SObjectType.Case.isUpdateable() && Case.SObjectType.getDescribe().isAccessible()) {
                update objCase;
                return objCase;    
            }
        } 
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return null;
    }

     /**
     * @description - Method used to update Case Object details
     * @param objCaseDetailsWrapper -Wrapper holding all case details
     * @param objCase - Case object
     */
    public static void updateActionSpecificFields(PMC_SS_CaseDetailsWrapper objCaseDetailsWrapper, Case objCase) {

        if(objCaseDetailsWrapper.actionReason == PMC_SS_ConstantClass.CANCEL || objCaseDetailsWrapper.actionReason == PMC_SS_ConstantClass.REBILL){
            objCase.AccountId = objCaseDetailsWrapper.accountId;
            objCase.ContactId = objCaseDetailsWrapper.contactId;
            objCase.PMC_SS_InvoiceDifference__c = objCaseDetailsWrapper.invoiceDifference;
            updateAmountValues(objCaseDetailsWrapper, objCase);
        }
        else if(objCaseDetailsWrapper.actionReason == PMC_SS_ConstantClass.CREDIT || objCaseDetailsWrapper.actionReason == PMC_SS_ConstantClass.DEBIT) {
            objCase.PMC_SS_SoldToAccount__c = objCaseDetailsWrapper.soldToAccountId;
            objCase.PMC_SS_ShipToAccount__c = objCaseDetailsWrapper.shipToAccountId;
            objCase.PMC_SS_Plant__c = objCaseDetailsWrapper.plantId;
			objCase.PMC_SS_CreditDebitAmount__c = objCaseDetailsWrapper.creditDebitAmount;
            updateAmountValues(objCaseDetailsWrapper, objCase);
        }
        else {
            objCase.PMC_SS_SoldToAccount__c = objCaseDetailsWrapper.soldToAccountId;
            objCase.PMC_SS_ShipToAccount__c = objCaseDetailsWrapper.shipToAccountId;
            objCase.PMC_SS_Plant__c = objCaseDetailsWrapper.plantId;
            objCase.PMC_SS_MOT__c = objCaseDetailsWrapper.modeOfTransportation;
            objCase.PMC_SS_VehicleId__c = objCaseDetailsWrapper.vehicleId;
            objCase.PMC_SS_PGIDate__c = Date.valueOf(objCaseDetailsWrapper.pgiDate);
            objCase.PMC_SS_ReturnQuantity__c = objCaseDetailsWrapper.returnQuantity;
            objCase.PMC_SS_ReturnAmount__c = objCaseDetailsWrapper.returnAmount;
            objCase.PMC_SS_HyperLink__c = Label.PMC_SS_SAPFioriReturnLink;
        }
    }

     /**
     * @description - Method used to update Case Object details
     * @param objCaseDetailsWrapper -Wrapper holding all case details
     * @param objCase - Case object
     */
    public static void updateAmountValues(PMC_SS_CaseDetailsWrapper objCaseDetailsWrapper, Case objCase) {
        if(objCaseDetailsWrapper.actionReason == PMC_SS_ConstantClass.CANCEL) {
            objCase.PMC_SS_CancelAmount__c = objCaseDetailsWrapper.cancelAmount;
            objCase.PMC_SS_HyperLink__c = Label.PMC_SS_SAPFioriCancelLink;
        }
        else if(objCaseDetailsWrapper.actionReason == PMC_SS_ConstantClass.REBILL){
            objCase.PMC_SS_RebillAmount__c = objCaseDetailsWrapper.rebillAmount;
            objCase.PMC_SS_HyperLink__c = Label.PMC_SS_SAPFioriRebillLink;
        }
        else if(objCaseDetailsWrapper.actionReason == PMC_SS_ConstantClass.CREDIT){
            objCase.PMC_SS_HyperLink__c = Label.PMC_SS_SAPFioriCreditLink;
        }
        else if(objCaseDetailsWrapper.actionReason == PMC_SS_ConstantClass.DEBIT){
            objCase.PMC_SS_HyperLink__c = Label.PMC_SS_SAPFioriDebitLink;
        }
    }

     /**
     * @description - Method used to fetch picklist values Case Object details
     * @param objApiName - Object API Name
     * @param fieldName - Field Name
     * @return List<Map<String, String>> - Map with details
     */
    @AuraEnabled
    public static List<Map<String, String>> getPickListValues(String objApiName, String fieldName) {
        List<Map<String, String>> options = new List <Map<String, String>>();
        Schema.SObjectType objType = Schema.getGlobalDescribe().get(objApiName);
        if (objType == null) {
            return options;
        }
        Schema.DescribeSObjectResult sobjectDescribe = objType.getDescribe();
        Map<String, Schema.SObjectField> fieldMap = sobjectDescribe.fields.getMap();
        if (fieldMap.get(fieldName) == null) {
            return options;
        }
        List <Schema.PicklistEntry> pickListValues = fieldMap.get(fieldName).getDescribe().getPickListValues();
        for (Schema.PicklistEntry f: pickListValues) {
            Map < String, String > values = new Map < String, String > {
                'label' => f.getLabel(),
                'value' => f.getValue()
            };
            options.add(values);
        }
        return options;
    }
}