objects/Case.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_CaseStatus__c</fullName>
        <formula>CASE( Status , &apos;New&apos;, &apos;Open&apos;, &apos;Working&apos;, &apos;In Progress&apos;,&apos;Pending&apos;, &apos;In Progress&apos;,&apos;Escalated&apos;,&apos;In Progress&apos;,&apos;Re-Open&apos;,&apos;In Progress&apos;,&apos;Rejected&apos;,&apos;Closed&apos;,&apos;Closed&apos;,&apos;Closed&apos;,&apos;Closure Pending&apos;,&apos;Closed&apos;,&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SS_IssueReason__c</fullName>
        <description>Specifies the reason of the issue</description>
        <inlineHelpText>Contract Cancellation, Product request, Credit Request, Financial Solution and Anticipated Billing are for Brazil users ONLY</inlineHelpText>
        <label>Issue Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Account Issues</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Article Request</fullName>
                </value>
                <value>
                    <fullName>Call by Date</fullName>
                </value>
                <value>
                    <fullName>Cambio Exhange</fullName>
                </value>
                <value>
                    <fullName>Change to loading priorities</fullName>
                </value>
                <value>
                    <fullName>Consignment</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                    <label>Contract Cancellation</label>
                </value>
                <value>
                    <fullName>Credit Note Request</fullName>
                </value>
                <value>
                    <fullName>Credit Request</fullName>
                </value>
                <value>
                    <fullName>Data Entry</fullName>
                </value>
                <value>
                    <fullName>Debit Note Request</fullName>
                </value>
                <value>
                    <fullName>Delivery Delay</fullName>
                </value>
                <value>
                    <fullName>Demurrage</fullName>
                </value>
                <value>
                    <fullName>Diversion</fullName>
                </value>
                <value>
                    <fullName>Document Request</fullName>
                </value>
                <value>
                    <fullName>Donation Order/Bonus</fullName>
                </value>
                <value>
                    <fullName>Driver Verification/Change</fullName>
                </value>
                <value>
                    <fullName>Equipment Failure</fullName>
                </value>
                <value>
                    <fullName>Export Documentation</fullName>
                </value>
                <value>
                    <fullName>Export prioritization</fullName>
                </value>
                <value>
                    <fullName>Financial Solution</fullName>
                </value>
                <value>
                    <fullName>Include Script CIF</fullName>
                </value>
                <value>
                    <fullName>Incorrect Destination</fullName>
                </value>
                <value>
                    <fullName>Incorrect Label</fullName>
                </value>
                <value>
                    <fullName>Incorrect Product</fullName>
                </value>
                <value>
                    <fullName>Incorrect UOM</fullName>
                </value>
                <value>
                    <fullName>Incorrect Vehicle ID</fullName>
                </value>
                <value>
                    <fullName>IntelliTrans</fullName>
                </value>
                <value>
                    <fullName>Invoice Adjustments</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PMC_DH_CaseListViewController.cls
/**
* @description       : Controller for fetching Case History
* @author            : @Lohitha sai
* Last modified by   : Sugunkar
* @group             : 
* @Created on        : 02-02-2024
**/
//public with sharing class PMC_DH_CaseListViewController {
public with sharing class PMC_DH_CaseListViewController {
    /**
* @description   : Search case records
* @return        : PMC_DH_CaseListWrapper
* @param           caseWrapper
* @param           effAccId
* @author        : @Lohitha Sai
* @date          : 06-28-2023
*/
    @AuraEnabled
    public static PMC_DH_CaseListWrapper searchCaseRecords(PMC_DH_CaseWrapper caseWrapper, Id effAccId){
        PMC_DH_CaseListWrapper caseListWrap = new PMC_DH_CaseListWrapper();
        String query = 'SELECT Id, CaseNumber, CreatedDate, Subject, LastModifiedDate, tolabel(PMC_SS_IssueReason__c), PMC_SS_CaseStatus__c FROM Case WHERE AccountId = :effAccId';
    try{
        if(caseWrapper!=null){
        PMC_DH_DigitalHubB2BUtils.throwTestExceptionForTest();
    if (String.isNotBlank(caseWrapper.strSearchTerm)) {
        String searchPattern = '\'%' + String.escapeSingleQuotes(caseWrapper.strSearchTerm) + '%\'';
        query += ' AND (CaseNumber LIKE ' + searchPattern;
        query += ' OR tolabel(PMC_SS_IssueReason__c) LIKE ' + searchPattern;
        query += ' OR Subject LIKE ' + searchPattern;
        query += ' OR PMC_SS_CaseStatus__c LIKE ' + searchPattern;
        query += ')';
    }

    if (caseWrapper.strFromDate != null && caseWrapper.strToDate != null) {
            query += ' AND';       
            query += ' (CreatedDate >= ' + caseWrapper.strFromDate + PMC_DH_ConstantClass.START_TIME;
            query += ' AND ';
            query += 'CreatedDate <= ' + caseWrapper.strToDate + PMC_DH_ConstantClass.END_TIME;
            query += ')';
    }
    }
        query += ' WITH SECURITY_ENFORCED ORDER BY CreatedDate DESC LIMIT 1000';
        String queryRes = query.replace('\\', '');
        caseListWrap.lstCases = Database.query(queryRes);
        caseListWrap.statusCodeMessage = PMC_DH_DigitalHubB2BUtils.getMessageForStatusCode('000', 'CaseList');
    }catch(Exception ex){
        caseListWrap.statusCodeMessage = PMC_DH_DigitalHubB2BUtils.getMessageForStatusCode('100', 'All');
        PMC_ErrorLogClass.processException(ex); // MDErrorLog
    }   
    return caseListWrap;
}
   
/**
@description Wrapper for searchCase params
**/
public class PMC_DH_CaseWrapper{
    /**
     * @description String to searchTerm
     * @return String
     */
    @AuraEnabled
    public String strSearchTerm{get;set;}
    /**
     * @description String to fromDate
     * @return String
     */
    @AuraEnabled
    public String strFromDate{get;set;}
    /**
     * @description String to toDate
     * @return String
     */
    @AuraEnabled
    public String strToDate{get;set;}
}

/**
@description Wrapper for cases list
**/
    // Main class is with sharing, wrapper is modified to sharing
public with sharing class PMC_DH_CaseListWrapper{
    /**
     * @description List of cases
     * @return List<PMC_DH_CaseWrapper>
     */
    @AuraEnabled
    public List<Case> lstCases{get;set;}
    
    /**
     * @description Status Code and message
     * @return PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper
     */
    @AuraEnabled
    public PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper statusCodeMessage{get;set;}
}
}