objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_CPQ_Cadence__c.object
<CustomObject>
    <description>This object is created to show Product availability information</description>
    <fields>
        <fullName>PMC_CPQ_QuoteLine__c</fullName>
        <description>Determines the Quote line associated to the cadence</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Cadences</relationshipLabel>
        <relationshipName>Cadences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RequestedDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Requested Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RequestedQuantity__c</fullName>
        <label>Requested Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Cadence</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cadence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cadences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CPQ_QuoteOrigin__c</fullName>
        <description>If the Quote is inserted by DH User and the Stage is Request, then the value is &quot;DH Request&quot;, if not the value shall be blank.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Indicates if this originated from Mosaic Direct or not</inlineHelpText>
        <label>Quote Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_QuoteFriendlyName__c</fullName>
        <description>This field is used to capture the quote name desired by the customer</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Customer friendly short name</inlineHelpText>
        <label>Quote Friendly Name</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PMC_DH_CadenceUtilTest.cls
/**
* @description : Test class for PMC_DH_CadenceUtil
* @author      : Ajeet
* @last modified on 
* @last modified by 
**/
@isTest
public without sharing class PMC_DH_CadenceUtilTest {
    /**
* @description Method for getting test data from PMC_DH_TestDataFactoryClass
* @param: none
* @return: void
*/
    @testSetup  static void setup()
    {
        Account acc;
        User user;
        String strContactId;
        User userAdmin=PMC_DH_TestDataFactoryClass.createAdminUser();
        System.runAs(userAdmin){
        acc=PMC_DH_TestDataFactoryClass.createParentTestAccount();
        Profile profile = [SELECT Id FROM Profile WHERE Name =: PMC_DH_ConstantClass.PROFILE_NAME LIMIT 1];
        PMC_DH_TestDataFactoryClass.createTestUser(acc.Id,profile.Id);
        user=[SELECT id FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
         strContactId=[SELECT contactId FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1][0].contactId;
        Id lstPermSet2=[select id from PermissionSet where Name ='PMC_DH_CPQ_PermissionSetLicense'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(user.Id,lstPermSet2);
        Id lstPermSet=[select id from PermissionSet where Name ='SteelBrickDHCPQPartnerUser'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(user.Id,lstPermSet);
        Id lstPermSet1=[select id from PermissionSet where Name ='PMC_DH_SuperBuyer'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(user.Id,lstPermSet1);
        Id lstPermSet3=[select id from PermissionSet where Name ='PMC_DH_AccountCRE'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(user.Id,lstPermSet3);
        }
        system.runAs(user){            
            Product2 prod = PMC_DH_TestDataFactoryClass.createProduct();
            insert prod;
            Opportunity opp=PMC_DH_TestDataFactoryClass.createOpportunity(acc);
            SBQQ__Quote__c testQuote=PMC_DH_TestDataFactoryClass.createQuote(acc,strContactId,opp);
            testQuote.PMC_CPQ_QuoteOrigin__c = 'DH Request';
            update testQuote;
            SBQQ__QuoteLine__c testQuoteLine = PMC_DH_TestDataFactoryClass.creatQuoteLine(testQuote,prod);
            Test.startTest();
            Contract testContract=PMC_DH_TestDataFactoryClass.createContract(testQuote.id,acc.id); 
            testContract.Status='Activated';
            update testContract;
            PMC_CPQ_Cadence__c testCadence = new PMC_CPQ_Cadence__c();
            testCadence.PMC_CPQ_QuoteLine__c = testQuoteLine.Id;
            testCadence.PMC_CPQ_RequestedDate__c = System.today();
            testCadence.PMC_CPQ_RequestedQuantity__c = 25;
            insert testCadence;
            //PMC_DH_TestDataFactoryClass.createCadence(testQuoteLine);
            Test.stopTest();
        }
    }
    

    @isTest
    public static void deleteAndCreateCadenceTest(){
        Test.startTest();
        User user=[SELECT id FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
        String strQuoteId = [SELECT Id FROM SBQQ__Quote__c WHERE PMC_DH_QuoteFriendlyName__c = 'Test Quote' LIMIT 1].id;
        PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper result;
        System.runAs(user){
            result = PMC_DH_CadenceUtil.createCadence(strQuoteId, true);        
        }
        System.assert(result!=null, 'Success');
        Test.stopTest();
    }
    
    @isTest
    public static void createCadenceTest(){
        Test.startTest();
        User user=[SELECT id FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
        String strQuoteId = [SELECT Id FROM SBQQ__Quote__c WHERE PMC_DH_QuoteFriendlyName__c = 'Test Quote' LIMIT 1].id;
        List<PMC_CPQ_Cadence__c> lstCadence = [select id from PMC_CPQ_Cadence__c where PMC_CPQ_QuoteLine__r.SBQQ__Quote__c =: strQuoteId];
        delete lstCadence;
        PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper result;
        System.runAs(user){
            result = PMC_DH_CadenceUtil.createCadence(strQuoteId, true);        
        }
        System.assert(result!=null, 'Success');
        Test.stopTest();
    }

    @isTest
    public static void getCadenceRecordsTest(){
        Test.startTest();
        User user=[SELECT id FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
        String strQuoteId = [SELECT Id FROM SBQQ__Quote__c WHERE PMC_DH_QuoteFriendlyName__c = 'Test Quote' LIMIT 1].id;
        PMC_DH_CadenceUtil.PMC_DH_QuoteAndCadenceLstResponseWrapper result;
        System.runAs(user){
            result = PMC_DH_CadenceUtil.getCadenceRecords(strQuoteId);        
        }
        System.assert(result!=null, 'Success');
        Test.stopTest();
    }

    @isTest
    public static void updateCadenceTest(){
        Test.startTest();
        User user=[SELECT id FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
        PMC_CPQ_Cadence__c cadence = [SELECT Id FROM PMC_CPQ_Cadence__c LIMIT 1];
        List<PMC_DH_CadenceUtil.PMC_DH_CadenceWrapper> lstCadenceWrapper = new List<PMC_DH_CadenceUtil.PMC_DH_CadenceWrapper>();
        PMC_DH_CadenceUtil.PMC_DH_CadenceWrapper cadencewrp1 = new PMC_DH_CadenceUtil.PMC_DH_CadenceWrapper();
        cadencewrp1.strCadenceId = cadence.Id;
        cadencewrp1.strMonth =  String.valueOf(System.today());
        cadencewrp1.intQuantity = 30;
        lstCadenceWrapper.add(cadencewrp1);
        PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper result;
        System.runAs(user){
            result = PMC_DH_CadenceUtil.updateCadence(lstCadenceWrapper);        
        }
        System.assertEquals('000', result.strStatusCode, 'Success');
        Test.stopTest();
    }

    @isTest
    public static void testExceptionCall()
    {
        Boolean boolExc=False;
        Test.startTest();
        User user=[SELECT id FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
        System.runAs(user){
            PMC_DH_DigitalHubB2BUtils.throwTestException = true;
            PMC_DH_CadenceUtil.PMC_DH_QuoteAndCadenceLstResponseWrapper quoteCadenceRecordsWrapper =new PMC_DH_CadenceUtil.PMC_DH_QuoteAndCadenceLstResponseWrapper();
            quoteCadenceRecordsWrapper=PMC_DH_CadenceUtil.getCadenceRecords(''); 
            if(quoteCadenceRecordsWrapper.statusCodeMessage.strStatusCode!='000')
            {
             boolExc=True;   
            } 
            System.assertEquals(True,boolExc, 'Exception not Handled');
            Test.stopTest();  
        }
	
    }
}