objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_CPQ_Integration_Endpoint__mdt.object
<CustomObject>
    <description>This is used to store all External endpoints.</description>
    <fields>
        <fullName>PMC_CPQ_Endpoint__c</fullName>
        <description>This is used to store the Integration endpoint.</description>
        <label>Endpoint</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Integration Endpoint</label>
    <pluralLabel>Integration Endpoints</pluralLabel>
</CustomObject>

objects/PMC_CPQ_TransactionLog__c.object
<CustomObject>
    <description>This object is used to store transactions details based on SF intergation with external systems.</description>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TRL-{0000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PMC_CPQ_ContractUpdateActionClass.cls
/** @description This class will be used to make callouts to the Contract Update interface of CPI. 
 *  @author Shefali Dsouza
 *  @storynumber GDASF-2978
 */
public class PMC_CPQ_ContractUpdateActionClass implements Queueable, Database.AllowsCallouts{   
    public List<SBQQ__Quote__c> lstQuotes;
    public List<Id> lstIds;
    static final String STRING_INTEGRATIONSTATUSERROR = 'Error';
    static final String STRING_INTERFACE = 'SAPContractUpdate';
    static final String STRING_NAMEDCREDENTIALS = 'callout:PMC_CPQ_NamedCredential';
    static final String STRING_METHOD = 'POST';
    static List<PMC_CPQ_TransactionLog__c> lstTransactionLogs = new List<PMC_CPQ_TransactionLog__c>();
     /** 
     * @description Constructor of the class. 
     * @param lstQuotes - list of quotes sent from the flow.
     * @param lstIds - lists of ids
     */
    public PMC_CPQ_ContractUpdateActionClass(List<SBQQ__Quote__c> lstQuotes, List<Id> lstIds)
    {
        this.lstQuotes = lstQuotes; 
        this.lstIds = lstIds;
    }	
    /** 
     * @description This is the apex action that will be invoked from the flow.
     * @param lstQuotes - list of quotes sent from the flow.
     */
	@InvocableMethod(label='Contract Update Remote Action' description='Triggers the CPI Interface to update contract records in SAP' category='SBQQ__Quote__c')
  	public static void postInfoToCPI(List<SBQQ__Quote__c> lstQuotes) {
        List<Id> lstIds = new List<Id>();
        
        for(SBQQ__Quote__c objQuote: lstQuotes)
        {
            lstIds.add(objQuote.Id);
        }
       System.enqueueJob(new PMC_CPQ_ContractUpdateActionClass(lstQuotes,lstIds));
    }    
    /** 
     * @description Makes a rerquest to callout class.
     * @param context - Receives the context of the flow. In this case it is the list of quotes.
     */
    public void execute(QueueableContext context)
    {
        PMC_CPQ_Integration_Endpoint__mdt strIntegrationEndpointRecord = PMC_CPQ_Integration_Endpoint__mdt.getInstance(STRING_INTERFACE); 
        String strEndpoint = strIntegrationEndpointRecord.PMC_CPQ_Endpoint__c;
        String strCalloutEndpoint = STRING_NAMEDCREDENTIALS+strEndpoint;
        
        String strSerializedBody = PMC_CPQ_CPIRemoteCalloutUtilityClass.createMinimalPayload(lstIds);
        HttpResponse response = PMC_CPQ_CPIRemoteCalloutUtilityClass.sendCalloutRequest(STRING_METHOD, strCalloutEndpoint, strSerializedBody);
		if(response != null)
        {
            PMC_CPQ_CPIQuoteContractIntegrationClass.parseJSONQuoteContractInterface(lstQuotes,response,strEndpoint);
        }
        else
        {
            Boolean boolRetry = PMC_CPQ_CPIRemoteCalloutUtilityClass.autoRetryQueueableApex(AsyncInfo.getCurrentQueueableStackDepth(),PMC_CPQ_CPIRemoteCalloutUtilityClass.strExceptionMsg);
            if(boolRetry)
            {
                System.enqueueJob(new PMC_CPQ_ContractUpdateActionClass(lstQuotes,lstIds), 1);
            }
            PMC_CPQ_CPIQuoteContractIntegrationClass.updateQuoteExceptionStatusMsg(lstQuotes,strEndpoint);
        }
    }
}