objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_ConfirmedQuantity__c</fullName>
        <label>Confirmed Quantity</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_FPDPricefromPriceFx__c</fullName>
        <description>Created as part of GDASF-9360. This field captures the FPD price from Price Fx.</description>
        <inlineHelpText>The FPD List Price for the Order Product is only relevant when the contract type of the product is specified as FPD</inlineHelpText>
        <label>FPD List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderLineStatus__c</fullName>
        <label>Order Line Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Placed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Completely Shipped</fullName>
                    <isActive>false</isActive>
                    <label>Completely Shipped</label>
                </value>
                <value>
                    <fullName>Partially Shipped</fullName>
                    <isActive>false</isActive>
                    <label>Partially Shipped</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Location</label>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_DH_CustomerCallPriceDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Call Price Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote line where this order product is created from.</description>
        <inlineHelpText>The quote line where this order product is created from.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>OrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/PMC_CPQ_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_InvoiceNumber__c</fullName>
        <description>This field is to capture the SAP Invoice Id.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SAP Invoice Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_CPQ_InvoiceItem__c.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Invoice__c</fullName>
        <description>The Invoice associated with this Item.</description>
        <label>Invoice</label>
        <referenceTo>PMC_CPQ_Invoice__c</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>InvoiceItems2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>InvoiceItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Location</label>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Invoice Items (Product Location)</relationshipLabel>
        <relationshipName>Invoice_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>INV ITEM-{0000}</displayFormat>
        <label>Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product.This is as per the  US GCPM 1064</description>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <infoMessage>Select Product Location Columns Link to add appropriate Locations</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>CPQ Quotes</relationshipLabel>
        <relationshipName>CPQ_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product.</description>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SBQQ__Product__c</field>
                <operation>equals</operation>
                <valueField>PMC_CPQ_ProductLocation__c.PMC_CPQ_ProductName__c</valueField>
            </filterItems>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Shipment.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_DeliveryStatus__c</fullName>
        <description>This field captures the delivery Delivery Status.</description>
        <label>Delivery Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Shipped</fullName>
                </value>
                <value>
                    <fullName>Partially Shipped</fullName>
                </value>
                <value>
                    <fullName>Completely Shipped</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <isActive>false</isActive>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                    <isActive>false</isActive>
                    <label>Shipped</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field captures the Order Number.</description>
        <label>Order Number</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShippedDate__c</fullName>
        <description>This field captures the shipped  Date.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipped Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_VehicleID__c</fullName>
        <description>This field captures the vehicle Vehicle ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ShipmentItem.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_DeliveryStatus__c</fullName>
        <description>This field captures the delivery Delivery  Status.</description>
        <label>Delivery Line Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Shipped</fullName>
                </value>
                <value>
                    <fullName>Partially Shipped</fullName>
                </value>
                <value>
                    <fullName>Completely Shipped</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                    <isActive>false</isActive>
                    <label>Delivered</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <isActive>false</isActive>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Picked</fullName>
                    <isActive>false</isActive>
                    <label>Picked</label>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                    <isActive>false</isActive>
                    <label>Shipped</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field captures the order Order Item.</description>
        <label>Order Item</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Delivery Items</relationshipLabel>
        <relationshipName>Delivery_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Location</label>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Delivery Lines</relationshipLabel>
        <relationshipName>Delivery_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_VehicleID__c</fullName>
        <description>This field captures the vehicle Vehicle ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PMC_DH_OrderLineDetailsUtilTest.cls
/**
* @description : Test class for PMC_DH_OrderLineDetailsUtil
* @author      : Krishan Jangir
* @userStory   : GDASF-15433
* @last modified by Krishan
* @last modified on 10-26-2023
**/
@isTest
public with sharing class PMC_DH_OrderLineDetailsUtilTest {
/**
* @description Method for getting test data from PMC_DH_TestDataFactoryClass
* @param: none
* @return: void
* @author Rohan
*/
    @testSetup  static void setup()
    {
        // test Classes fixes
        Account acc=PMC_DH_TestDataFactoryClass.createParentTestAccount();
        //Account shipToAcc=PMC_DH_TestDataFactoryClass.createShipToTestAccount(acc);
        Profile profile = [SELECT Id FROM Profile WHERE Name =: PMC_DH_ConstantClass.PROFILE_NAME LIMIT 1];
        PMC_DH_TestDataFactoryClass.createTestUser(acc.Id,profile.Id);
        
        User user=[SELECT id FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
        String strContactId=[SELECT contactId FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1][0].contactId;
        Id lstPermSet2=[select id from PermissionSet where Name ='PMC_DH_CPQ_PermissionSetLicense'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(user.Id,lstPermSet2);
        Id lstPermSet=[select id from PermissionSet where Name ='SteelBrickDHCPQPartnerUser'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(user.Id,lstPermSet);
        Id lstPermSet1=[select id from PermissionSet where Name ='PMC_DH_SuperBuyer'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(user.Id,lstPermSet1);
        Id lstPermSet3=[select id from PermissionSet where Name ='PMC_DH_AccountCRE'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(user.Id,lstPermSet3);
        PMC_DH_TestDataFactoryClass.createTestAccountTeamMember(acc.Id, user.id, PMC_DH_ConstantClass.ACCOUNT_TEAMMEMBERACC);

        
        WebStore webStore=PMC_DH_TestDataFactoryClass.createTestWebStore();
        system.runAs(user){
            WebCart cartObj=PMC_DH_TestDataFactoryClass.buildCart(webStore.Id,acc.Id);
        	insert cartObj;
        	Product2 prod = PMC_DH_TestDataFactoryClass.createProduct();
        	insert prod;
        	CartDeliveryGroup testCartDeliveryGroup=PMC_DH_TestDataFactoryClass.buildCartDeliveryGroup(cartObj.id);
        	insert testCartDeliveryGroup;
        	CartItem cartItem=PMC_DH_TestDataFactoryClass.buildCartItem(cartObj.id, prod.id,testCartDeliveryGroup.Id);
        	cartItem.Quantity = 5;
        	cartItem.TotalLineAmount = 5100;
        	insert cartItem;
        
        	Account shipToAcc=PMC_DH_TestDataFactoryClass.createShipToTestAccount(acc);
        	Schema.Location loc = PMC_DH_TestDataFactoryClass.createLocation();
        	PMC_CPQ_ProductLocation__c prodLocation = PMC_DH_TestDataFactoryClass.createProductLocation(prod, loc);
        	PMC_DH_TestDataFactoryClass.CartItemObject objCartItem=new PMC_DH_TestDataFactoryClass.CartItemObject();
        	objCartItem.strCartId=cartObj.id;
        	objCartItem.strProductId=prod.id;
        	objCartItem.strDeliveryGroupId=testCartDeliveryGroup.id;
        	objCartItem.strShipToAccId=shipToAcc.id;
        	objCartItem.strShipFromId=prodLocation.id;
        	CartItem cartItem1=PMC_DH_TestDataFactoryClass.buildCartItem1(objCartItem);
        	cartItem1.Quantity = 10;
        	cartItem1.TotalLineAmount = 100;
        	insert cartItem1;
            Opportunity opp=PMC_DH_TestDataFactoryClass.createOpportunity(acc);
            
            SBQQ__Quote__c testQuote=PMC_DH_TestDataFactoryClass.createQuote(acc,strContactId,opp);
            SBQQ__QuoteLine__c testQuoteLine = PMC_DH_TestDataFactoryClass.creatQuoteLine(testQuote,prod);
            Test.startTest();
           	Contract testContract=PMC_DH_TestDataFactoryClass.createContract(testQuote.id,acc.id); 
            testContract.Status='Activated';
            update testContract;
            objCartItem.strAccId = acc.Id;
            objCartItem.strContractId = testContract.Id;
            objCartItem.strQuoteLineId = testQuoteLine.Id;
            PMC_DH_TestDataFactoryClass.createSubscription(objCartItem);
            Order testOrder = PMC_DH_TestDataFactoryClass.createOrder(acc, testContract, cartObj.id);
            OrderItem oi1 = PMC_DH_TestDataFactoryClass.creatOrderLine(testOrder, cartItem);
            oi1.PMC_CPQ_ConfirmedQuantity__c = 50;
        	oi1.PMC_CPQ_OrderLineStatus__c='Placed';
            update oi1;
        	Shipment shipmnt = PMC_DH_TestDataFactoryClass.createShipment(testOrder);        	
        	PMC_DH_TestDataFactoryClass.createShipmentItem(oi1,shipmnt);
        	shipmnt.PMC_CPQ_DeliveryStatus__c = 'Completely Shipped';
        	update shipmnt;
            //ShipmentItem si1 = PMC_DH_TestDataFactoryClass.createShipmentItem(oi1,shipmnt);
            //si1.PMC_CPQ_VehicleID__c = 'SA12345';
            //update si1;
            PMC_CPQ_Invoice__c invoice = new PMC_CPQ_Invoice__c();
            invoice.PMC_CPQ_Order__c = testOrder.Id;
            invoice.PMC_CPQ_InvoiceNumber__c = '1234';
            invoice.PMC_CPQ_OrderProduct__c = oi1.Id;
            insert invoice;
            PMC_CPQ_InvoiceItem__c invoiceItem = new PMC_CPQ_InvoiceItem__c();
            invoiceItem.PMC_CPQ_Invoice__c = invoice.Id;
            invoiceItem.PMC_CPQ_OrderProduct__c =  oi1.Id;
            insert invoiceItem;
            Test.stopTest();
        }
    }
    /**
* @description Test Method for getOrderLineDetails method on PMC_DH_OrderLineDetailsController class
* @param: none
* @return: void
* @author Ajeet
*/
    @isTest
    public static void getDeliveryTrackingTest(){
        Test.startTest();
        User user=[SELECT id FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
        System.runAs(user) {
        String orderItemId = [SELECT Id FROM OrderItem WHERE Order.Name = 'Test Order' LIMIT 1][0].Id;
        Shipment shipmnt = [SELECT Id, ShipToName from Shipment WHERE ShipToName = 'Test' LIMIT 1];
        shipmnt.PMC_CPQ_DeliveryStatus__c = 'Completely Shipped';
        shipmnt.PMC_CPQ_CurrentCoordinates__Latitude__s = 23.23;
        shipmnt.PMC_CPQ_CurrentCoordinates__Longitude__s = 23.23;
        shipmnt.PMC_CPQ_VehicleID__c = 'SA1234';
        update shipmnt;
        ShipmentItem objShip = [SELECT Id,PMC_CPQ_VehicleID__c FROM ShipmentItem  WHERE PMC_CPQ_VehicleID__c='SA1234' LIMIT 1];
       
        PMC_DH_OrderLineDetailsWrapper.OrderLineSummaryWrapper wrapOrderLineSummary = new PMC_DH_OrderLineDetailsWrapper.OrderLineSummaryWrapper();
        List<OrderItem> lstOrderItem = [SELECT Id,PMC_DH_CustomerCallPriceDate__c,PMC_CPQ_FPDPricefromPriceFx__c FROM OrderItem LIMIT 1];
        lstOrderItem[0].PMC_DH_CustomerCallPriceDate__c = System.today();
        update lstOrderItem[0];
        Boolean boolValue;
     
            try{
                PMC_DH_DeliveryTrackerWrapper orderLineDetailWrp = PMC_DH_OrderLineDetailsUtil.getDeliveryTracking(orderItemId,objShip.PMC_CPQ_VehicleID__c);
                boolValue = PMC_DH_OrderLineDetailsUtil.getBoolValues(wrapOrderLineSummary, lstOrderItem);
                System.assert(orderLineDetailWrp!=null,'Success');
            }catch(AuraHandledException ex){
                System.assert(ex.getMessage() != null, 'Exception was caught');
            }
           
        }
        Test.stopTest();
    }
    
    @isTest
    public static void getDeliveryTrackingTest1(){
        Test.startTest();
        User user=[SELECT id FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
        System.runAs(user) {
        String orderItemId = [SELECT Id FROM OrderItem WHERE Order.Name = 'Test Order' LIMIT 1][0].Id;
        ShipmentItem objShip = [SELECT Id,PMC_CPQ_VehicleID__c,ShipmentId FROM ShipmentItem  WHERE PMC_CPQ_VehicleID__c='SA1234' LIMIT 1];
        Shipment objShip2 = new Shipment(Id=objShip.ShipmentId);
        objShip2.PMC_CPQ_DeliveryStatus__c = 'Partially Shipped';
        objShip2.PMC_CPQ_VehicleID__c = 'SA1234';
        update objShip2;
        update objShip;
            try{
                PMC_DH_DeliveryTrackerWrapper orderLineDetailWrp = PMC_DH_OrderLineDetailsUtil.getDeliveryTracking(orderItemId,objShip.PMC_CPQ_VehicleID__c);
                System.assert(orderLineDetailWrp!=null,'Success');
            }catch(AuraHandledException ex){
                System.assert(ex.getMessage() != null, 'Exception was caught');
            }
        }
        Test.stopTest();
    }
        @isTest
    public static void getDeliveryTrackingTest2(){
        Test.startTest();
        User user=[SELECT id FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
        System.runAs(user) {
        String orderItemId = [SELECT Id FROM OrderItem WHERE Order.Name = 'Test Order' LIMIT 1][0].Id;        
        ShipmentItem objShip = [SELECT Id,PMC_CPQ_VehicleID__c, ShipmentId FROM ShipmentItem  WHERE PMC_CPQ_VehicleID__c='SA1234' LIMIT 1];
        //objShip.PMC_CPQ_DeliveryStatus__c = 'Partially Shipped';
        objShip.PMC_CPQ_ShippedDate__c = NULL;
        update objShip;
        Shipment objShip2 = new Shipment(Id=objShip.ShipmentId);
        objShip2.PMC_CPQ_DeliveryStatus__c = 'Partially Shipped';
        objShip2.PMC_CPQ_DeliveryPlannedGIDate__c = System.today();
        objShip2.PMC_CPQ_VehicleID__c = 'SA1234';
        update objShip2;
        
            try{
                PMC_DH_DeliveryTrackerWrapper orderLineDetailWrp = PMC_DH_OrderLineDetailsUtil.getDeliveryTracking(orderItemId,objShip.PMC_CPQ_VehicleID__c);
                System.assert(orderLineDetailWrp!=null,'Success');
            }catch(AuraHandledException ex){
                System.assert(ex.getMessage() != null, 'Exception was caught');
            }
        }
        Test.stopTest();
    }
    
    @isTest
    public static void getDeliveryTrackingTest3(){
        Test.startTest();
        User user=[SELECT id FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
        System.runAs(user) {
        String orderItemId = [SELECT Id FROM OrderItem WHERE Order.Name = 'Test Order' LIMIT 1][0].Id;        
        ShipmentItem objShip = [SELECT Id,PMC_CPQ_VehicleID__c, ShipmentId FROM ShipmentItem  WHERE PMC_CPQ_VehicleID__c='SA1234' LIMIT 1];
        objShip.PMC_CPQ_DeliveryStatus__c = 'Partially Shipped';
        objShip.PMC_CPQ_ShippedDate__c = NULL;
        update objShip;
        Shipment objShip2 = new Shipment(Id=objShip.ShipmentId);
        objShip2.PMC_CPQ_DeliveryStatus__c = 'Partially Shipped';
        objShip2.PMC_CPQ_DeliveryPlannedGIDate__c = NULL;
        objShip2.PMC_CPQ_VehicleID__c = 'SA1234';
        update objShip2;
        
            try{
                PMC_DH_DeliveryTrackerWrapper orderLineDetailWrp = PMC_DH_OrderLineDetailsUtil.getDeliveryTracking(orderItemId,objShip.PMC_CPQ_VehicleID__c);
                System.assert(orderLineDetailWrp!=null,'Success');
            }catch(AuraHandledException ex){
                System.assert(ex.getMessage() != null, 'Exception was caught');
            }
        }
        Test.stopTest();
    }
     @isTest
    public static void getOrderLineDetailsTest(){
        Test.startTest();
        User usr=[SELECT id FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
        System.runAs(usr){
            try{
                String orderItemId = [SELECT Id FROM OrderItem WHERE Order.Name = 'Test Order' LIMIT 1][0].Id;
                PMC_DH_OrderLineDetailsWrapper orderLineDetailWrp = PMC_DH_OrderLineDetailsController.getOrderLineDetails(orderItemId,'United States');
                System.assert(orderLineDetailWrp!=null,'Success');
            }catch(AuraHandledException ex){
                System.assert(ex.getMessage() != null, 'Exception was caught');
            }
        }
        Test.stopTest();
    }
}