objects/Contract.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_ContractType__c</fullName>
        <description>This field will be used to indicate the Contract Type wrt to the Mode to Transportation (Rail, Truck, Barge) and FPD/Priced/CCC</description>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Priced Contract Barge</fullName>
                </value>
                <value>
                    <fullName>Priced Contract Truck</fullName>
                </value>
                <value>
                    <fullName>Priced Contract Rail</fullName>
                </value>
                <value>
                    <fullName>FPD Contract Barge</fullName>
                </value>
                <value>
                    <fullName>FPD Contract Rail</fullName>
                </value>
                <value>
                    <fullName>FPD Contract Truck</fullName>
                </value>
                <value>
                    <fullName>CCC Contract Truck</fullName>
                </value>
                <value>
                    <fullName>Third Party Delivery</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_CPQ_ProductLocation__c.object
<CustomObject>
    <description>This object is created as a part of  story to capture product and location data.</description>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created  to check the location details.</description>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Product Locations</relationshipLabel>
        <relationshipName>ProductLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>CPQ Quotes</relationshipLabel>
        <relationshipName>CPQ_Quotes_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product.This is as per the  US GCPM 1064</description>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <infoMessage>Select Product Location Columns Link to add appropriate Locations</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>CPQ Quotes</relationshipLabel>
        <relationshipName>CPQ_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CPQ Quotes (Ship To)</relationshipLabel>
        <relationshipName>CPQ_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_UnitOfMeasure__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_SS_UnitOfMeasure</valueSetName>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product</description>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product.</description>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SBQQ__Product__c</field>
                <operation>equals</operation>
                <valueField>PMC_CPQ_ProductLocation__c.PMC_CPQ_ProductName__c</valueField>
            </filterItems>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created  to check the shipping address value of the line item.</description>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Lines (Ship To)</relationshipLabel>
        <relationshipName>Quote_Lines2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_UnitofMeasure__c</fullName>
        <label>UoM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_SS_UnitOfMeasure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>PMC_CPQ_LatestSubscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as part of XYZ. This will store the value of the latest / newest subscription record created from its current version.</description>
        <label>Latest Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Subscriptions (Latest Subscription)</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product</description>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SBQQ__Product__c</field>
                <operation>equals</operation>
                <valueField>PMC_CPQ_ProductLocation__c.PMC_CPQ_ProductName__c</valueField>
            </filterItems>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_QuoteLineSelfLookupBackend__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as a part of GDASF-9382, to store lookup value of quoteline</description>
        <label>Quote Line (Backend)</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions (Quote Line (Backend))</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to check the shipping address value</description>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions (Ship To)</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_TotalAvailableQuantity__c</fullName>
        <description>This field will store the value corresponding to the quantities available to order for a line item</description>
        <label>Total Available Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_TotalOrderedQuantity__c</fullName>
        <description>This field will store the  summation of quantities of the several order lines created for a particular line item.</description>
        <label>Total Ordered Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_UnitofMeasure__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_SS_UnitOfMeasure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
        <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract that governs this subscription.</description>
        <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity of this subscription product purchased by the customer.</description>
        <inlineHelpText>Quantity of this subscription product purchased by the customer.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this subscription.</description>
        <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__SubscriptionConsumptionSchedule__c.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Consumption Schedules</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subscription Consumption Schedule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Subscription Consumption Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Consumption Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PMC_DH_ContractAmendmentController.cls
/** 
* @description Controller for fetching Contract Details 
* @author Sugunakar Rouhtu
* @last modified on 2024-May-09
* @last modified by Sugunakar Routhu
* Created On       : 2024-May-09
**/
public without sharing class  PMC_DH_ContractAmendmentController {
    
    
    /*************************************************************************
* @method Name  : getProductInfoforAmendment
* @description  : Method to fetch Contract product info for amended contracts
* @param         strCommunityId
* @param         strEffectiveAccountId
* @param         contract
* @return       : PMC_DH_RequestForQuoteWrapper
*****************************************************************************/
    
    public static PMC_DH_RequestForQuoteWrapper getProductInfoforAmendment(String strCommunityId,String strEffectiveAccountId,Contract contract){
        PMC_DH_RequestForQuoteWrapper productInfoWrapper = new PMC_DH_RequestForQuoteWrapper();
        List<PMC_DH_RequestForQuoteWrapper.CartWrapper> lstContractItemsWrapper = new List<PMC_DH_RequestForQuoteWrapper.CartWrapper>();
        PMC_DH_RequestForQuoteWrapper.CartWrapper contractItemsWrapper;
        PMC_DH_DigitalHubB2BUtils.throwTestExceptionForTest();
        // get the latest Quote and line Item details for the amendment
        
        
        Map<String,List<PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper>> mapSubscriptions = getSubscriptionDetailsforAmendment(contract);
        
        Set<String> setSku = mapSubscriptions.keyset();
        List<String> lstSku = new List<String>(setSku);
        //method to get Product Details using connectApi 
        if(!lstSku.isEmpty()){
            Map<String,PMC_DH_RequestForQuoteController.ConnectApiWrapper> mapProductDetail = PMC_DH_QuoteManagementControllerClass.getproductConnectApi(strCommunityId,strEffectiveAccountId,lstSku); 
            
            if(contract.SBQQ__Subscriptions__r != null){
                for(String quoteLineSku : mapSubscriptions.keyset()){
                    contractItemsWrapper = new PMC_DH_RequestForQuoteWrapper.CartWrapper();
                    //method to assign product Details in Wrapper
                    PMC_DH_RequestForQuoteController.ConnectApiWrapper objconnectapiProduct = mapProductDetail.get(quoteLineSku);
                    contractItemsWrapper.strProductName = objconnectapiProduct.strProductName;
                    contractItemsWrapper.strSku = objconnectapiProduct.strSku;
                    contractItemsWrapper.strProductId = objconnectapiProduct.strProductId;
                    contractItemsWrapper.strImgSrc = objconnectapiProduct.strImgSrc;
                    contractItemsWrapper.strProductUOM = mapSubscriptions.get(quoteLineSku)[0].strProductUOM;
                    contractItemsWrapper.strProductUOMLabel = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(SBQQ__QuoteLine__c.PMC_CPQ_UnitofMeasure__c.getDescribe(),contractItemsWrapper.strProductUOM);
                    contractItemsWrapper.lstContractItems = mapSubscriptions.get(quoteLineSku);
                    Double intTotalQty = 0.00;// GDASF-10697 /GPT-ActiveHome
                    for(PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper ciwrp : contractItemsWrapper.lstContractItems)
                    {
                        intTotalQty += ciwrp.intQty;
                    }
                    contractItemsWrapper.strTotalQty = intTotalQty;
                    lstContractItemsWrapper.add(contractItemsWrapper);
                }
                productInfoWrapper.lstCartWrapper = lstContractItemsWrapper;
            }
        }
        return productInfoWrapper;
    }
    
    /*************************************************************************
* @method Name  : getSubscriptionDetailsData
* @description  : Method to get the Subscription Details information 
* @param         subscription
* @return        PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper
*****************************************************************************/
    
    public static PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper  getSubscriptionDetailsData(SBQQ__Subscription__c subscription ){
        
        PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper objSubscriptionWrap = new PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper(); 
        objSubscriptionWrap.strContractItemId = subscription.Id;
        if(subscription.PMC_CPQ_TotalOrderedQuantity__c != null && subscription.PMC_CPQ_TotalAvailableQuantity__c != null){
            objSubscriptionWrap.intOrderedQty = subscription.PMC_CPQ_TotalOrderedQuantity__c.doubleValue();// GDASF-10697
            objSubscriptionWrap.intAvailableQty = subscription.PMC_CPQ_TotalAvailableQuantity__c.DoubleValue();// GDASF-10697
        }
        objSubscriptionWrap.intQty = subscription.SBQQ__QuoteLine__r.SBQQ__Quantity__c.doubleValue();// GDASF-10697
        PMC_DH_PicklistWrapper wrpShipTo = new PMC_DH_PicklistWrapper();
        PMC_DH_PicklistWrapper wrpShipFrom = new PMC_DH_PicklistWrapper();
        wrpShipTo.label = subscription.SBQQ__QuoteLine__r.PMC_CPQ_ShipTo__r.Name + ' ' + subscription.SBQQ__QuoteLine__r.PMC_CPQ_ShipTo__r.ShippingStreet + ', ' + subscription.SBQQ__QuoteLine__r.PMC_CPQ_ShipTo__r.ShippingCity + ', ' + subscription.SBQQ__QuoteLine__r.PMC_CPQ_ShipTo__r.ShippingState + ' ' + subscription.SBQQ__QuoteLine__r.PMC_CPQ_ShipTo__r.ShippingPostalCode;
        wrpShipTo.value = subscription.SBQQ__QuoteLine__r.PMC_CPQ_ShipTo__c;
        wrpShipFrom.label = subscription.SBQQ__QuoteLine__r.PMC_CPQ_ProductLocation__r.PMC_CPQ_Location__r.Name;
        wrpShipFrom.value = subscription.SBQQ__QuoteLine__r.PMC_CPQ_ProductLocation__c;
        objSubscriptionWrap.wrpShipTo = wrpShipTo;
        objSubscriptionWrap.wrpShipFrom = wrpShipFrom;
        objSubscriptionWrap.strContractType = subscription.SBQQ__QuoteLine__r.PMC_CPQ_ContractType__c ;
        objSubscriptionWrap.strDeliveryMode = subscription.SBQQ__QuoteLine__r.PMC_CPQ_ModeofTransportation__c;
        objSubscriptionWrap.strIncoterm = subscription.SBQQ__QuoteLine__r.PMC_CPQ_Incoterms1__c;
        objSubscriptionWrap.strProductUOM= subscription.SBQQ__QuoteLine__r.PMC_CPQ_UnitofMeasure__c;
        objSubscriptionWrap.strPackType = subscription.SBQQ__QuoteLine__r.PMC_CPQ_PackType__c;
        objSubscriptionWrap.strPackageType = subscription.SBQQ__QuoteLine__r.PMC_CPQ_PackageType__c;
        
        //GPT-43943
        objSubscriptionWrap.strDeliveryModeLabel = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(SBQQ__QuoteLine__c.PMC_CPQ_ModeofTransportation__c.getDescribe(),subscription.SBQQ__QuoteLine__r.PMC_CPQ_ModeofTransportation__c);
        objSubscriptionWrap.strIncotermLabel = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(SBQQ__QuoteLine__c.PMC_CPQ_Incoterms1__c.getDescribe(),subscription.SBQQ__QuoteLine__r.PMC_CPQ_Incoterms1__c);
        objSubscriptionWrap.strPackTypeLabel = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(SBQQ__QuoteLine__c.PMC_CPQ_PackType__c.getDescribe(),subscription.SBQQ__QuoteLine__r.PMC_CPQ_PackType__c);
        objSubscriptionWrap.strPackageTypeLabel = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(SBQQ__QuoteLine__c.PMC_CPQ_PackageType__c.getDescribe(),subscription.SBQQ__QuoteLine__r.PMC_CPQ_PackageType__c);
        objSubscriptionWrap.strProductUOMLabel = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(SBQQ__QuoteLine__c.PMC_CPQ_UnitofMeasure__c.getDescribe(),subscription.SBQQ__QuoteLine__r.PMC_CPQ_UnitofMeasure__c);
        objSubscriptionWrap.strContractTypeLabel = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(SBQQ__QuoteLine__c.PMC_CPQ_ContractType__c.getDescribe(),subscription.SBQQ__QuoteLine__r.PMC_CPQ_ContractType__c);
        
        return objSubscriptionWrap;
    }
    
    
    /*************************************************************************
* @method Name  : getQuoteSubscriptionDetailsMap
* @description  : Method to get the Quote Line Details information 
* @param         quoteLine
* @param         subscription
* @param         mapofSubscriptionId
* @return        PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper
*****************************************************************************/
    public static PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper getQuoteSubscriptionDetailsMap(SBQQ__QuoteLine__c quoteLine, SBQQ__Subscription__c subscription , Map<String,Id> mapofSubscriptionId){
        PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper objSubscriptionWrap = new PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper(); 
        objSubscriptionWrap.strContractItemId = mapofSubscriptionId.get(subscription.SBQQ__contract__c + String.ValueOf(subscription.SBQQ__QuoteLine__r.PMC_CLM_QuoteLineNumber__c));
        if(subscription.PMC_CPQ_TotalOrderedQuantity__c != null && subscription.PMC_CPQ_TotalAvailableQuantity__c != null){
            objSubscriptionWrap.intOrderedQty = subscription.PMC_CPQ_TotalOrderedQuantity__c.doubleValue();// GDASF-10697
            objSubscriptionWrap.intAvailableQty = subscription.PMC_CPQ_TotalAvailableQuantity__c.DoubleValue();// GDASF-10697
        }
        objSubscriptionWrap.intQty = subscription.SBQQ__QuoteLine__r.SBQQ__Quantity__c.doubleValue();// GDASF-10697
        
        PMC_DH_PicklistWrapper wrpShipTo = new PMC_DH_PicklistWrapper();
        PMC_DH_PicklistWrapper wrpShipFrom = new PMC_DH_PicklistWrapper();
        wrpShipTo.label = quoteLine.PMC_CPQ_ShipTo__r.Name + ' ' + quoteLine.PMC_CPQ_ShipTo__r.ShippingStreet + ', ' + quoteLine.PMC_CPQ_ShipTo__r.ShippingCity + ', ' + quoteLine.PMC_CPQ_ShipTo__r.ShippingState + ' ' + quoteLine.PMC_CPQ_ShipTo__r.ShippingPostalCode;
        wrpShipTo.value = quoteLine.PMC_CPQ_ShipTo__c;
        wrpShipFrom.label = quoteLine.PMC_CPQ_ProductLocation__r.PMC_CPQ_Location__r.Name;
        wrpShipFrom.value = quoteLine.PMC_CPQ_ProductLocation__c;
        objSubscriptionWrap.wrpShipTo = wrpShipTo;
        objSubscriptionWrap.wrpShipFrom = wrpShipFrom;
        objSubscriptionWrap.strContractType = quoteLine.PMC_CPQ_ContractType__c ;
        objSubscriptionWrap.strDeliveryMode = quoteLine.PMC_CPQ_ModeofTransportation__c;
        objSubscriptionWrap.strIncoterm = quoteLine.PMC_CPQ_Incoterms1__c;
        objSubscriptionWrap.strProductUOM= quoteLine.PMC_CPQ_UnitofMeasure__c;
        objSubscriptionWrap.strPackType = quoteLine.PMC_CPQ_PackType__c;
        objSubscriptionWrap.strPackageType = quoteLine.PMC_CPQ_PackageType__c;
        //objSubscriptionWrap.decNetUnitPrice = subscription.SBQQ__QuoteLine__r.SBQQ__NetPrice__c;
        //Checking if map contains sku and assigning the Subscription Wrapper
        
        //GPT-43943
        objSubscriptionWrap.strDeliveryModeLabel = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(SBQQ__QuoteLine__c.PMC_CPQ_ModeofTransportation__c.getDescribe(),quoteLine.PMC_CPQ_ModeofTransportation__c);
        objSubscriptionWrap.strIncotermLabel = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(SBQQ__QuoteLine__c.PMC_CPQ_Incoterms1__c.getDescribe(),quoteLine.PMC_CPQ_Incoterms1__c);
        objSubscriptionWrap.strPackTypeLabel = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(SBQQ__QuoteLine__c.PMC_CPQ_PackType__c.getDescribe(),quoteLine.PMC_CPQ_PackType__c);
        objSubscriptionWrap.strPackageTypeLabel = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(SBQQ__QuoteLine__c.PMC_CPQ_PackageType__c.getDescribe(),quoteLine.PMC_CPQ_PackageType__c);
        objSubscriptionWrap.strProductUOMLabel = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(SBQQ__QuoteLine__c.PMC_CPQ_UnitofMeasure__c.getDescribe(),quoteLine.PMC_CPQ_UnitofMeasure__c);
        objSubscriptionWrap.strContractTypeLabel = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(SBQQ__QuoteLine__c.PMC_CPQ_ContractType__c.getDescribe(),quoteLine.PMC_CPQ_ContractType__c);
        
        return objSubscriptionWrap;
    }
    
    
    /*************************************************************************
* @method Name  : getSubscriptionDetailsforAmendment
* @description  : Method to get the Subscription Details information 
* @param         contract
* @return        Map<String,List<PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper>>
*************************************************************************/
    
    public static Map<String,List<PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper>> getSubscriptionDetailsforAmendment(Contract contract){
        
        Map<String,List<PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper>> mapSubscriptions = new Map<String,List<PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper>>();
        
        
        Map<String, SBQQ__QuoteLine__c > latestAmenededLineItemsMap = new Map<String, SBQQ__QuoteLine__c >();
        Map<String,Id> mapofSubscriptionId = PMC_DH_ContractManagementController.getMapOfSubscriptionIds(new List<Contract>{contract});
        List<SBQQ__QuoteLine__c> quoteLineList = [SELECT Id, PMC_CLM_QuoteLineNumber__c,SBQQ__Quote__r.Name,SBQQ__Quote__c,SBQQ__Quote__r.SBQQ__Status__c,
                                                  PMC_CPQ_ShipTo__c, PMC_CPQ_ShipTo__r.Name, PMC_CPQ_ShipTo__r.ShippingStreet, SBQQ__Quantity__c,
                                                  PMC_CPQ_ShipTo__r.ShippingCity, PMC_CPQ_ShipTo__r.ShippingState, PMC_CPQ_ShipTo__r.ShippingPostalCode,
                                                  PMC_CPQ_ProductLocation__c,PMC_CPQ_ProductLocation__r.PMC_CPQ_Location__r.Name, 
                                                  //toLabel( PMC_CPQ_Incoterms1__c) labelIncoterm, toLabel( PMC_CPQ_ModeofTransportation__c) labelMOT, toLabel( PMC_CPQ_ContractType__c) labelContractType, toLabel(PMC_CPQ_PackageType__c) labelPackageType, toLabel(PMC_CPQ_PackType__c) labelPackType, toLabel(PMC_CPQ_UnitofMeasure__c) labelUOM,
                                                  PMC_CPQ_Incoterms1__c, PMC_CPQ_ModeofTransportation__c, SBQQ__NetPrice__c, PMC_CPQ_ContractType__c, PMC_CPQ_PackageType__c, PMC_CPQ_PackType__c,  
                                                  PMC_CPQ_UnitofMeasure__c, SBQQ__Product__c,SBQQ__Product__r.StockKeepingUnit
                                                  FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c=:contract.PMC_CPQ_LatestQuote__c 
                                                  WITH SECURITY_ENFORCED];
        
        for( SBQQ__QuoteLine__c qline : quoteLineList){
            latestAmenededLineItemsMap.put(String.ValueOf(qline.PMC_CLM_QuoteLineNumber__c), qline);
        }
        
        for(SBQQ__Subscription__c subscription : contract.SBQQ__Subscriptions__r){
            if((latestAmenededLineItemsMap.containsKey(subscription.SBQQ__QuoteLine__r.PMC_CLM_QuoteLineNumber__c)) && 
               (latestAmenededLineItemsMap.get(subscription.SBQQ__QuoteLine__r.PMC_CLM_QuoteLineNumber__c).SBQQ__Quote__c == subscription.SBQQ__QuoteLine__r.SBQQ__Quote__c)){
                   // need to get the Information from new Quote subcription
                   PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper objSubscriptionWrap = getSubscriptionDetailsData(subscription);
                   
                   if(!mapSubscriptions.containsKey(subscription.SBQQ__Product__r.StockKeepingUnit))
                   {
                       mapSubscriptions.put(subscription.SBQQ__Product__r.StockKeepingUnit, new List<PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper>());
                   }
                   mapSubscriptions.get(subscription.SBQQ__Product__r.StockKeepingUnit).add(objSubscriptionWrap);
               } 
            else{
                
                SBQQ__QuoteLine__c quoteLine = latestAmenededLineItemsMap.get(String.ValueOf(subscription.SBQQ__QuoteLine__r.PMC_CLM_QuoteLineNumber__c));
                PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper objSubscriptionWrap = getQuoteSubscriptionDetailsMap(quoteLine, subscription, mapofSubscriptionId);
                if(!mapSubscriptions.containsKey(quoteLine.SBQQ__Product__r.StockKeepingUnit))
                {
                    mapSubscriptions.put(quoteLine.SBQQ__Product__r.StockKeepingUnit, new List<PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper>());
                }
                mapSubscriptions.get(quoteLine.SBQQ__Product__r.StockKeepingUnit).add(objSubscriptionWrap);
            }
            
        }
        
        return mapSubscriptions;
        
        
    }
    
    /*************************************************************************
* @method Name  : getContractSummarywithAmendment
* @description  : Method to fetch Contract Summary
* @param         contract
* @param         isAmendment
* @return       : PMC_DH_ContractDetailsWrapper.ContractSummaryWrapper
*****************************************************************************/
    public static PMC_DH_ContractDetailsWrapper.ContractSummaryWrapper getContractSummarywithAmendment(Contract contract, Boolean isAmendment){
        PMC_DH_ContractDetailsWrapper.ContractSummaryWrapper contractSummaryWrapper; 
        PMC_DH_DigitalHubB2BUtils.throwTestExceptionForTest();
        contractSummaryWrapper = new PMC_DH_ContractDetailsWrapper.ContractSummaryWrapper();
        //assign contract values in Contract summary wrapper
        if(contract != null){
            if(isAmendment){
                contractSummaryWrapper.strPoNumber = contract.PMC_CPQ_LatestQuote__r.PMC_CPQ_PO__c;
                contractSummaryWrapper.strCustomerName = contract.PMC_CPQ_LatestQuote__r.PMC_CPQ_PrimaryContact__r.Name;
                contractSummaryWrapper.datContractStartDate = contract.PMC_CPQ_LatestQuote__r.SBQQ__StartDate__c; //GPT-35789
                contractSummaryWrapper.datContractEndDate = contract.PMC_CPQ_LatestQuote__r.SBQQ__EndDate__c; //GPT-35789
            }
            else{
                contractSummaryWrapper.strPoNumber = contract.SBQQ__Quote__r.PMC_CPQ_PO__c;
                contractSummaryWrapper.strCustomerName = contract.SBQQ__Quote__r.PMC_CPQ_PrimaryContact__r.Name;
                contractSummaryWrapper.datContractStartDate = contract.StartDate; //GPT-35789
                contractSummaryWrapper.datContractEndDate = contract.EndDate; //GPT-35789
            }
            List<String> lstStatusAndReason = PMC_DH_ContractManagementHelper.getContractStatusAndReason(contract);
            contractSummaryWrapper.strSummaryStatus = lstStatusAndReason[0]; // Active/Inactive
            contractSummaryWrapper.strInactiveReason = lstStatusAndReason[1]; // Completed/Expired if Status = 'Inactive'
        }
        return contractSummaryWrapper;
    }
    
    /*************************************************************************
* @method Name  : getPaymentInfowithAmendment
* @description  : Method to fetch Payment Info
* @param         contract
* @param         isAmendment
* @return       : PMC_DH_QuoteDetailsWrapper.PaymentInformationWrapper
*****************************************************************************/
    public static PMC_DH_QuoteDetailsWrapper.PaymentInformationWrapper getPaymentInfowithAmendment(Contract contract, Boolean isAmendment){
        PMC_DH_QuoteDetailsWrapper.PaymentInformationWrapper paymentInfoWrapper; 
        PMC_DH_DigitalHubB2BUtils.throwTestExceptionForTest();
        paymentInfoWrapper = new PMC_DH_QuoteDetailsWrapper.PaymentInformationWrapper();
        //assign contract values in Payment information wrapper
        if(contract != null){
            if(isAmendment){
                paymentInfoWrapper.strPaymentTermSelected = contract.PMC_CPQ_LatestQuote__r.SBQQ__PaymentTerms__c;
                paymentInfoWrapper.strPaymentMethodSelected = contract.PMC_CPQ_LatestQuote__r.PMC_DH_PaymentMethod__c;
                paymentInfoWrapper.strCurrencySelected = contract.PMC_CPQ_LatestQuote__r.CurrencyIsoCode;
            }
            else{
                paymentInfoWrapper.strPaymentTermSelected = contract.SBQQ__Quote__r.SBQQ__PaymentTerms__c;
                paymentInfoWrapper.strPaymentMethodSelected = contract.SBQQ__Quote__r.PMC_DH_PaymentMethod__c;
                paymentInfoWrapper.strCurrencySelected = contract.SBQQ__Quote__r.CurrencyIsoCode;
            }
            paymentInfoWrapper.boolIsBoletoAvailable = false; //to be changed once Boleto feature is ready
        }
        return paymentInfoWrapper;
    }
    
}