objects/Contract.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_SAPContractReference__c</fullName>
        <formula>SBQQ__Quote__r.PMC_CPQ_SAPContractReference__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Contract Reference</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_SAPContractReference__c</fullName>
        <description>Created as part of GDASF-8818. This field will hold the SAP Contract reference (carried over from quote lines, when order is created)</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SAP Contract Reference #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_CPQ_Integration_Endpoint__mdt.object
<CustomObject>
    <description>This is used to store all External endpoints.</description>
    <fields>
        <fullName>PMC_CPQ_Endpoint__c</fullName>
        <description>This is used to store the Integration endpoint.</description>
        <label>Endpoint</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Integration Endpoint</label>
    <pluralLabel>Integration Endpoints</pluralLabel>
</CustomObject>

objects/PMC_CPQ_TransactionLog__c.object
<CustomObject>
    <description>This object is used to store transactions details based on SF intergation with external systems.</description>
    <fields>
        <fullName>PMC_CPQ_IntegrationStatus__c</fullName>
        <description>This will show the status of the response of the external callout.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_InterfaceURL__c</fullName>
        <description>This is the endpoint that was hit during the transaction.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Interface URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RequestBody__c</fullName>
        <description>This is the request body sent to the external system.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Request Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ResponseBody__c</fullName>
        <description>This field stores the response body of the request made to the external system.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Response Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TRL-{0000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CPQ_IntegrationMessage__c</fullName>
        <description>Created as part of GDASF-5842. This field will capture the integration response message</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>receives the Integration response message</inlineHelpText>
        <label>Integration Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_IntegrationStatus__c</fullName>
        <description>Created as part of GDASF-5842. This field will capture the overall integration status.</description>
        <inlineHelpText>Indicates the over all integration status</inlineHelpText>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SAPContractReference__c</fullName>
        <description>This field stores the Contract Number generated on SAP.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SAP Contract Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PMC_CPQ_CPIQuoteContractIntegrationClass.cls
/** @description This is a utility class for external callouts.
 *  @author Shefali Dsouza
 *  @storynumber GDASF-2983
 */
public without sharing class PMC_CPQ_CPIQuoteContractIntegrationClass implements Database.AllowsCallouts {
    static HttpRequest request = new HttpRequest();
    static HttpResponse response;
    static Boolean boolTransLogSuccess = false;
    static Boolean boolTransLogError = false;
    static String strTransactionLogStatus;
    static final String STRING_INTEGRATIONSTATUSERROR = 'Error'; 
    static final String STRING_INTEGRATIONSTATUSSUCCESS = 'Success';
    static final String STRING_INTEGRATIONSTATUSPARTIALSUCCESS = 'Partial Success';
    static final string STRING_OBJECTNUMBER = 'OBJECT_NUMBER';
    static final string STRING_SFRECORDID = 'SFRecordId';
    static final string STRING_OBJECTNAME = 'ObjectName';
    static final string STRING_STATUSCODE = 'statusCode';
    static final string STRING_RESPONSEMESSAGE = 'responsetext';
    static final string STRING_OBJECTNAMEQUOTE = 'Quote';
    static final string STRING_OBJECTNAMECONTRACT = 'Contract';
    static final string STRING_OBJECT_CREATE = 'Creation';
    static final string STRING_OBJECT_UPDATE = 'Update';
    static final Integer INT_STATUSCODE200 = 200;
    static final Integer INT_STATUSCODE201 = 201;
    static Exception objException;
    static final List<Integer> LISTINT_SUCCESSCODES = new List<Integer>{INT_STATUSCODE200,INT_STATUSCODE201};
    static List<PMC_CPQ_TransactionLog__c> lstTransactionLogs;

    /** 
     * @description Returns a filtered list of values by parsing through the payload received
     * @param lstObjContainer - Entire payload
     * @return lstFilteredList - Filtered payload
     */
    public static List<Object> getFilteredList(List<Object> lstObjContainer)
    {
        List<Object> lstFilteredList = new List<Object>();
        Set<Object> setFilteredSet = new Set<Object>();

        for(Object objContainer: lstObjContainer)//remove records with duplicate values and keep only values required for futher processing.
        { 
            Map<String,Object> mapCurRecord = (Map<String,Object>) objContainer;
            Map<String,Object> mapNewRecord = new Map<String,Object>();
            mapNewRecord.put(STRING_OBJECTNUMBER,mapCurRecord.get(STRING_OBJECTNUMBER));
            mapNewRecord.put(STRING_SFRECORDID,mapCurRecord.get(STRING_SFRECORDID));
            mapNewRecord.put(STRING_OBJECTNAME,mapCurRecord.get(STRING_OBJECTNAME));
            mapNewRecord.put(STRING_STATUSCODE,mapCurRecord.get(STRING_STATUSCODE));
            mapNewRecord.put(STRING_RESPONSEMESSAGE,mapCurRecord.get(STRING_RESPONSEMESSAGE));
            setFilteredSet.add(mapNewRecord);
        }
        lstFilteredList.addAll(setFilteredSet);
        return lstFilteredList;
    }
    public static void getFilteredErrorList(List<Object> lstObjContainer,List<SBQQ__Quote__c> lstQuotes,list<SBQQ__QuoteLine__c> QuoteItemUpdate,String strEndpoint)
    {
        map<String,String> lstFilteredList = new map<String,String>();
        Set<Object> setFilteredSet = new Set<Object>();
        map<String,String> QuoteErrorList = New  map<String,String>();
        map<String,String> QuoteItemErrorList = New  map<String,String>();
        Set<Id> LstQuoteId = new Set<Id>();
        list<SBQQ__QuoteLine__c> QuoteItemList= new list<SBQQ__QuoteLine__c>();
        
        
        for(Object objContainer: lstObjContainer)
        { 
            Map<String,Object> mapCurRecord = (Map<String,Object>) objContainer;
            String sfdcitem = (String)mapCurRecord.get('SFDC_ITEM'); 
            String sfrecordid = (String)mapCurRecord.get(STRING_SFRECORDID); 
                                  
            if(mapCurRecord.get('TYPE')=='E'){
                Boolean containsQuote = QuoteErrorList.containsKey(sfrecordid);
                if(!containsQuote){
                    QuoteErrorList.put(sfrecordid,(String)mapCurRecord.get('MESSAGE'));
                }
                LstQuoteId.add(sfrecordid);
                
                Integer charLength = sfdcitem.length();
                
                if(sfdcitem.length()>0){
                    if(!QuoteItemErrorList.containsKey(sfdcitem)){                    
                        QuoteItemErrorList.put(sfdcitem,(String)mapCurRecord.get('MESSAGE'));
                    }
                }
               
            
               
            }
        }

        
        If(!QuoteErrorList.isEmpty()){
             for(SBQQ__Quote__c objQuote: lstQuotes){
                //objQuote.PMC_CPQ_IntegrationStatus__c = STRING_INTEGRATIONSTATUSERROR;
                objQuote.PMC_CPQ_IntegrationMessage__c = getPrefix(strEndpoint)+QuoteErrorList.get(objQuote.Id).abbreviate(225);
            }
        }
        
        
    }
    
    /** 
     * @description Parses through the quote and payload.
     * @param lstQuotes - list of quotes
     * @param lstFilteredList - Filtered payload
     * @param strEndpoint - Interface Endpoint
     */
    public static void parseQuoteContractFilteredList(List<SBQQ__Quote__c> lstQuotes, List<Object> lstFilteredList, String strEndpoint)
    {
        for(SBQQ__Quote__c curQuote: lstQuotes)//parse through filtered list
        {
            Integer intResponseCode;
            String strSAPRefId;
            Integer intCountResponseCodes;
            Set<Integer> setResponseCodes = new Set<Integer>();
            Set<String> setSAPContracts = new Set<String>();
            
            for(Object curObjContainer: lstFilteredList)//parse through filtered list 
            {
                Map<String,Object> mapRecord = (Map<String,Object>)curObjContainer;
                Boolean boolIsCurrentQuote = mapRecord.get(STRING_OBJECTNAME) == STRING_OBJECTNAMEQUOTE && mapRecord.get(STRING_SFRECORDID) == curQuote.Id;
                Boolean boolIsCurrentContract = mapRecord.get(STRING_OBJECTNAME) == STRING_OBJECTNAMECONTRACT && mapRecord.get(STRING_SFRECORDID) == curQuote.Id;
                if(boolIsCurrentQuote)
                {
                    intResponseCode = (Integer) mapRecord.get(STRING_STATUSCODE);
                    setResponseCodes.add(intResponseCode); 
                }
                else if(boolIsCurrentContract)
                {
                    intResponseCode = (Integer) mapRecord.get(STRING_STATUSCODE);
                    setResponseCodes.add(intResponseCode);
                    strSAPRefId = (String) mapRecord.get(STRING_OBJECTNUMBER);
                    setSAPContracts.add(strSAPRefId);   
                } 
            }

            setSAPContracts.remove('');
            String strSAPContracts = string.join(setSAPContracts,',');
            curQuote.PMC_CPQ_SAPContractReference__c = strSAPContracts;
            intCountResponseCodes = setResponseCodes.size();
            setResponseCodes.removeAll(LISTINT_SUCCESSCODES);
            if(setResponseCodes.isEmpty()) //Success Scenario
           {
                curQuote.PMC_CPQ_IntegrationStatus__c = STRING_INTEGRATIONSTATUSSUCCESS;
                curQuote.PMC_CPQ_IntegrationMessage__c = getPrefix(strEndpoint)+STRING_INTEGRATIONSTATUSSUCCESS;
            }
            else //Error Scenario
            {
                boolTransLogError = true;
                curQuote.PMC_CPQ_IntegrationStatus__c = STRING_INTEGRATIONSTATUSERROR;
                curQuote.PMC_CPQ_IntegrationMessage__c = getPrefix(strEndpoint) + getQuoteErrorStatus(intCountResponseCodes,setResponseCodes.size());
            }
        }
           }
            
    /** 
     * @description Returns whether the quote is Partial Success or Error
     * @param intCountResponseCodes - Count of Response Codes
     * @param intCurCountResponseCodes - Count of Response Codes after removing successful response codes
     * @return STRING_INTEGRATIONSTATUSPARTIALSUCCESS = Partial Success
     * @return STRING_INTEGRATIONSTATUSERROR = Error
     */
    public static String getQuoteErrorStatus(Integer intCountResponseCodes, Integer intCurCountResponseCodes)
    {
        if(intCountResponseCodes != intCurCountResponseCodes)
        {
            return STRING_INTEGRATIONSTATUSPARTIALSUCCESS;
        }
        return STRING_INTEGRATIONSTATUSERROR;
    }
    
     /** 
     * @description Returns overall order status
     * @return strIntegrationStatusError - Status = Error
     * @return strIntegrationStatusWarning - Status = Warning
     * @return strIntegrationStatusSuccess - Status = Success 
     */
    public static String getOverallTransactionStatus()
    {
        if(boolTransLogError)
        {
            return (STRING_INTEGRATIONSTATUSERROR);
        }
        return (STRING_INTEGRATIONSTATUSSUCCESS);
    }
    
    /** 
     * @description It returns the prefix for integration message.
     * @param strEndpoint - Integration Endpoint.
     * @return strPrefix - Prefix of Integration Message.
     */
    public Static String getPrefix(String strEndpoint)
    {
        String strPrefix;
        String strInterface = 'SAPQuoteandContractCreate';
        PMC_CPQ_Integration_Endpoint__mdt strIntegrationEndpointRecord = PMC_CPQ_Integration_Endpoint__mdt.getInstance(strInterface); 
        String strQuoteAndContractReplicationEndpoint = strIntegrationEndpointRecord.PMC_CPQ_Endpoint__c;
        
        if(strEndpoint == strQuoteAndContractReplicationEndpoint)
        {
            strPrefix = 'Quote/Contract Creation: ';
        }
        else
        {
            strPrefix = 'Contract Update: ';
        }
        return strPrefix;
    }
    
    /** 
     * @description Parses through the response body and populates Integration fields on the quote.
     * @param lstQuotes - List of quotes.
     * @param response - Response received from the endpoint.
     * @param strEndpoint - Endpoint that the HttpRequest will hit.
     */
    public static void parseJSONQuoteContractInterface(List<SBQQ__Quote__c> lstQuotes, HttpResponse response, String strEndpoint)
    {    
        List<Object> lstFilteredList = new List<Object>();
        List<Object> lstObjContainer= new List<Object>();
        String strJSONResponseBody = response.getBody();
        list<SBQQ__QuoteLine__c> QuoteItemUpdate=new list<SBQQ__QuoteLine__c>();
        
        

        if(LISTINT_SUCCESSCODES.contains(response.getStatusCode()))//status code returned is 200
        {   
            try
            {
                lstObjContainer= (List<Object>) JSON.deserializeUntyped(response.getBody());
                lstFilteredList = getFilteredList(lstObjContainer);//removes duplicate records and non essential values
                parseQuoteContractFilteredList(lstQuotes, lstFilteredList, strEndpoint);
                strTransactionLogStatus = getOverallTransactionStatus();
                if(boolTransLogError){
                       getFilteredErrorList(lstObjContainer,lstQuotes,QuoteItemUpdate,strEndpoint);
                    
                }
            }
            catch(Exception e)//Exception caused due to inablitiy to parse through response.
            {
                strTransactionLogStatus = STRING_INTEGRATIONSTATUSERROR;
                for(SBQQ__Quote__c objQuote: lstQuotes)
                {
                    objQuote.PMC_CPQ_IntegrationStatus__c = STRING_INTEGRATIONSTATUSERROR;
                    objQuote.PMC_CPQ_IntegrationMessage__c = getPrefix(strEndpoint)+e.getMessage().abbreviate(225);
                }
            }
        }
        else //status code returned is not 200
        {
            strTransactionLogStatus = STRING_INTEGRATIONSTATUSERROR;
            for(SBQQ__Quote__c objQuote: lstQuotes)
            {
                objQuote.PMC_CPQ_IntegrationStatus__c = STRING_INTEGRATIONSTATUSERROR;
                objQuote.PMC_CPQ_IntegrationMessage__c = getPrefix(strEndpoint)+response.getBody().abbreviate(225);
            }
        }
        
        SObjectAccessDecision securityDecisionQuote = Security.stripInaccessible(AccessType.UPDATABLE, lstQuotes);
        Database.update(securityDecisionQuote.getRecords(),false);
        
        
        Map<String, String> mapTransactionLogFields = new Map<String,String>();
        mapTransactionLogFields.put('PMC_CPQ_IntegrationStatus__c',strTransactionLogStatus);
        mapTransactionLogFields.put('PMC_CPQ_InterfaceURL__c',strEndpoint);
        mapTransactionLogFields.put('PMC_CPQ_RequestBody__c',PMC_CPQ_CPIRemoteCalloutUtilityClass.request.getBody());
        mapTransactionLogFields.put('PMC_CPQ_ResponseBody__c',strJSONResponseBody);

        lstTransactionLogs = PMC_CPQ_TransactionLogUtilityClass.addTransactionLog(mapTransactionLogFields);
        PMC_CPQ_TransactionLogUtilityClass.insertTransactionLogs(lstTransactionLogs);
    
    }
    /** 
     * @description Updates the status and message for quotes 
     * @param lstQuotes - List of quotes.
     * @param strEndpoint - Integration Endpoint.
     */
    public static void updateQuoteExceptionStatusMsg(List<SBQQ__Quote__c> lstQuotes, String strEndpoint)
    {
        for(SBQQ__Quote__c objQuote: lstQuotes)
        {
            objQuote.PMC_CPQ_IntegrationStatus__c = STRING_INTEGRATIONSTATUSERROR;
            objQuote.PMC_CPQ_IntegrationMessage__c = getPrefix(strEndpoint)+PMC_CPQ_CPIRemoteCalloutUtilityClass.strExceptionMsg.abbreviate(225);
        }
        SObjectAccessDecision securityDecisionQuote = Security.stripInaccessible(AccessType.UPDATABLE, lstQuotes);
        Database.update(securityDecisionQuote.getRecords(),false);
    }
}