objects/Contract.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_ContractNumberIdentifier__c</fullName>
        <description>This field will store the contract number(AutoNumber) which will be used as an External Id for 066I.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Contract Number Identifier</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_SAPOrderNumber__c</fullName>
        <description>This field captures the order number in SAP.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Reference Order Number in SAP.</inlineHelpText>
        <label>SAP Order Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <label>Approval Flow Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Under Revision</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                    <isActive>false</isActive>
                    <label>Recalled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_FPDPricefromPriceFx__c</fullName>
        <description>Created as part of GDASF-9360. This field captures the FPD price from Price Fx.</description>
        <inlineHelpText>The FPD List Price for the Order Product is only relevant when the contract type of the product is specified as FPD</inlineHelpText>
        <label>FPD List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_FinalAgreedPrice__c</fullName>
        <description>This field is will store the Final Agreed Price and send it back to SAP after the Order is placed.</description>
        <label>Final Agreed Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_LinePONumber__c</fullName>
        <description>This field will be used to capture the PO Number at a order line level - leveraged in the Contract Document forms for North America</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Purchase Order #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderItemIntegrationMessage__c</fullName>
        <description>The Integration message of external callout.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderItemIntegrationStatus__c</fullName>
        <description>This field captures the integration status of the Order product</description>
        <inlineHelpText>This field captures the integration status of the Order product</inlineHelpText>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderLineStatus__c</fullName>
        <label>Order Line Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Placed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Completely Shipped</fullName>
                    <isActive>false</isActive>
                    <label>Completely Shipped</label>
                </value>
                <value>
                    <fullName>Partially Shipped</fullName>
                    <isActive>false</isActive>
                    <label>Partially Shipped</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PricingDate__c</fullName>
        <description>This field captures Pricing date.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field captures the pricing date</inlineHelpText>
        <label>Price by Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Products (Ship To)</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contract of the subscription that is created from this order product.</description>
        <inlineHelpText>The contract of the subscription that is created from this order product.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>OrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/PMC_TriggerSwitches__mdt.object
<CustomObject>
    <description>This custom metadata is used to bypass trigger operations.</description>
    <fields>
        <fullName>PMC_AfterUpdate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Update</label>
        <type>Checkbox</type>
    </fields>
    <label>PMC Trigger Switches</label>
    <pluralLabel>PMC Trigger Switches</pluralLabel>
</CustomObject>

classes/OrderItemTriggerHandler.cls
/**
* @description This class will be used to handle all trigger operations of OrderItem object
* @author Raphael Soares
* @storynumber GCPM-2396 - FPD I - PM Approval Workflow and Approvers
*/
public without sharing class OrderItemTriggerHandler extends PMC_TriggerHandler  {
    
    /**
    * These boolean variables are used to bypass the trigger operations
    */
    private static final Boolean BOOL_BYPASS_AFTER_UPDATE;
    
    @testVisible
    public static Boolean boolBypassTriggerLogic = false;
    
    /**
	* These variables will hold the copy of trigger variables
	*/
    private List<OrderItem> newOrderItems;
    private Map<Id,OrderItem> oldOrderItems;
    
    /**
    * @description This static block initializes the trigger switches when the class is invoked
    */
    static{
        
        PMC_TriggerSwitches__mdt operationSwitches = PMC_TriggerSwitches__mdt.getInstance('OrderItem');
        BOOL_BYPASS_AFTER_UPDATE = operationSwitches.PMC_AfterUpdate__c;
        
    }
    
    /**
    * @description Constructor method to initialize class level variables and store the trigger collections and add the max loop count of trigger
    */

    public OrderItemTriggerHandler(){    
        
        //Instantiating local class variables from trigger variables
        this.newOrderItems = Trigger.new;
        this.oldOrderItems = (Map<Id, OrderItem>)Trigger.oldMap;
        //Set the maximum calls allowed for the class
        this.setMaxLoopCount(8);
    }
    
    public override void afterUpdate(){
        if(BOOL_BYPASS_AFTER_UPDATE  || boolBypassTriggerLogic){
            return;
        }
        Set<Id> oItemIds = new Set<Id>();
        for(OrderItem item: newOrderItems){
            if(item.ApprovalStatus__c == 'Approved' && item.ApprovalStatus__c != oldOrderItems.get(item.Id).ApprovalStatus__c){
                oItemIds.add(item.Id);
            }
        }
        if(!oItemIds.isEmpty()){
            List<OrderItem> orderItems = [SELECT Id, OrderItemNumber, Order.OrderNumber, SBQQ__Contract__r.PMC_CPQ_ContractNumberIdentifier__c, PMC_CPQ_LinePONumber__c, PMC_CPQ_ShipTo__r.Name, Order.Account.Name, Product2.Name, Quantity, PMC_CPQ_PricingDate__c,  PMC_CPQ_FPDPricefromPriceFx__c, PMC_CPQ_FinalAgreedPrice__c, PMC_CPQ_OrderLineStatus__c, PMC_CPQ_OrderItemIntegrationStatus__c,PMC_CPQ_OrderItemIntegrationMessage__c,Order.PMC_CPQ_SAPOrderNumber__c
            FROM OrderItem
            WHERE Id IN :oItemIds];
            System.enqueueJob(new PMC_CPQ_FPDActionClass(orderItems,true));
        }

    }
}