objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_CPQ_Cadence__c.object
<CustomObject>
    <description>This object is created to show Product availability information</description>
    <fields>
        <fullName>PMC_CPQ_QuoteLine__c</fullName>
        <description>Determines the Quote line associated to the cadence</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Cadences</relationshipLabel>
        <relationshipName>Cadences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RequestedDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Requested Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RequestedQuantity__c</fullName>
        <label>Requested Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Cadence</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cadence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cadences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PMC_CPQ_ProductLocation__c.object
<CustomObject>
    <description>This object is created as a part of  story to capture product and location data.</description>
    <label>Product Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CPQ_ContractEnd__c</fullName>
        <description>If Master contract exists - then formula to pull the date from Contract reference</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Quote End Date</inlineHelpText>
        <label>Contract Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ContractPeriod__c</fullName>
        <description>This field calculate number of months between contract start and end date.</description>
        <formula>((YEAR(PMC_CPQ_ContractEnd__c) - YEAR(PMC_CPQ_ContractStart__c))*12) + (MONTH(PMC_CPQ_ContractEnd__c) - MONTH(PMC_CPQ_ContractStart__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ContractStart__c</fullName>
        <description>If Master contract exists - then formula to pull the date from Contract reference</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Quote Start Date</inlineHelpText>
        <label>Contract Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_IsContractPeriodChanged__c</fullName>
        <formula>(PMC_CPQ_ContractStart__c &lt;&gt; PMC_CPQ_LastContractStart__c)  || ( PMC_CPQ_ContractEnd__c  &lt;&gt;  PMC_CPQ_LastContractEnd__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Contract Period Changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_LastContractEnd__c</fullName>
        <description>This field will hold the last value of Contract Valid To sent to SAP.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Contract Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_LastContractStart__c</fullName>
        <description>This field will hold last value of Contract Valid From sent to SAP.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Contract Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ModeOfTransportation__c</fullName>
        <label>Mode of Transportation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_MoT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product.This is as per the  US GCPM 1064</description>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <infoMessage>Select Product Location Columns Link to add appropriate Locations</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>CPQ Quotes</relationshipLabel>
        <relationshipName>CPQ_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_QuantityChangedCount__c</fullName>
        <description>This field will track count of QLE&apos;s where quantity is changed.</description>
        <label>Quantity Changed Count</label>
        <summaryFilterItems>
            <field>SBQQ__QuoteLine__c.PMC_CPQ_IsQuantityUpdated__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>SBQQ__QuoteLine__c.SBQQ__Quote__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CPQ Quotes (Ship To)</relationshipLabel>
        <relationshipName>CPQ_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__DocumentStatus__c</fullName>
        <description>Indicates the status of your Document.</description>
        <inlineHelpText>Indicates the Status of the generated quote document.</inlineHelpText>
        <label>Document Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>PMC_CPQ_Incoterms1__c</fullName>
        <description>This field is created  to check incoterms data of line item record</description>
        <label>Incoterms</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PMC_CPQ_QuoteRecordSubType__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_Incoterms1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_IsQuantityUpdated__c</fullName>
        <formula>SBQQ__Quantity__c  &lt;&gt;   PMC_CPQ_Last_Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Quantity Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ModeofTransportation__c</fullName>
        <description>This field is created  to check The mode of transportation</description>
        <inlineHelpText>Select the appropriate mode from the available options to track and manage logistics effectively</inlineHelpText>
        <label>MoT</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PMC_CPQ_QuoteRecordType__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_MoT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product.</description>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SBQQ__Product__c</field>
                <operation>equals</operation>
                <valueField>PMC_CPQ_ProductLocation__c.PMC_CPQ_ProductName__c</valueField>
            </filterItems>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created  to check the shipping address value of the line item.</description>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Lines (Ship To)</relationshipLabel>
        <relationshipName>Quote_Lines2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/PMC_CPQ_Incoterms1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CFR</fullName>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
    </customValue>
    <customValue>
        <fullName>DAP</fullName>
    </customValue>
    <customValue>
        <fullName>DAT</fullName>
    </customValue>
    <customValue>
        <fullName>FCA</fullName>
    </customValue>
    <customValue>
        <fullName>FOB</fullName>
    </customValue>
    <customValue>
        <fullName>FOB/CIFADO</fullName>
    </customValue>
    <customValue>
        <fullName>CPT</fullName>
    </customValue>
    <customValue>
        <fullName>CIFFOB</fullName>
        <isActive>false</isActive>
        <label>CIFFOB</label>
    </customValue>
    <masterLabel>Incoterms 1</masterLabel>
</GlobalValueSet>

globalValueSets/PMC_CPQ_MoT.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Barge</fullName>
    </customValue>
    <customValue>
        <fullName>Container</fullName>
    </customValue>
    <customValue>
        <fullName>Rail</fullName>
    </customValue>
    <customValue>
        <fullName>Truck</fullName>
    </customValue>
    <customValue>
        <fullName>Vessel</fullName>
    </customValue>
    <description>This is created to hold mode of Transportation value sets</description>
    <masterLabel>MoT</masterLabel>
</GlobalValueSet>

classes/PMC_DH_CadenceUtil.cls
/** 
* @description Class for get Cadence Records
* @author Ajeet
* @last modified on 
* @last modified by 
* Created On       :2023-Nov-16
**/
public without sharing class PMC_DH_CadenceUtil {
    /*************************************************************************
* @method Name  : createCadence
* @description  : Method to create cadence record
* @param 		  strQuoteId
* @param 		  boolIsContractPeriodChanged
* @return         PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper 
*****************************************************************************/
    @AuraEnabled
    public static PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper createCadence(String strQuoteId, Boolean boolIsContractPeriodChanged){
        PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper statusCodeMessage = new PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper();
        try{
            List<SBQQ__QuoteLine__c> lstQuoteLine = [select id,SBQQ__Quote__c,PMC_CPQ_IsQuantityUpdated__c, SBQQ__Quantity__c, SBQQ__Quote__r.PMC_CPQ_IsContractPeriodChanged__c, SBQQ__Quote__r.name, SBQQ__Quote__r.PMC_CPQ_LastContractStart__c, 
                                                    SBQQ__Quote__r.PMC_CPQ_LastContractEnd__c, SBQQ__Quote__r.PMC_CPQ_QuantityChangedCount__c, SBQQ__Quote__r.PMC_CPQ_ContractPeriod__c, SBQQ__Quote__r.PMC_CPQ_ContractStart__c, SBQQ__Quote__r.PMC_CPQ_ContractEnd__c   
                                                    from SBQQ__QuoteLine__c where SBQQ__Quote__c=: strQuoteId WITH SECURITY_ENFORCED];
            
            // added by Nikhilesh as part of GDASF-19031
            List<PMC_CPQ_Cadence__c> lstCadence = [select id, PMC_CPQ_QuoteLine__c from PMC_CPQ_Cadence__c where PMC_CPQ_QuoteLine__r.SBQQ__Quote__c =: strQuoteId WITH SECURITY_ENFORCED];
            // condition 1: contract period has changed and cadence records exist
            // action: delete existing cadence records, create new ones based on date range
            if(boolIsContractPeriodChanged && !lstCadence.isEmpty()){
                PMC_CPQ_CadenceController.deleteCadenceRecord(lstCadence);
                PMC_CPQ_CadenceController.createCadenceRecord(lstQuoteLine);
            }
            // condition 2: no cadence record exists
            // action: create cadence records based on date range
            // end of changes as part of GDASF-19031
            else if(lstCadence.isEmpty()){
                PMC_CPQ_CadenceController.createCadenceRecord(lstQuoteLine); 
            }
            statusCodeMessage = PMC_DH_DigitalHubB2BUtils.getMessageForStatusCode(PMC_DH_ConstantClass.SUCCESS_STATUS_CODE, PMC_DH_ConstantClass.CADENCE);
        }catch(Exception ex){
            PMC_ErrorLogClass.processException(ex); // MDErrorLog
            statusCodeMessage = PMC_DH_DigitalHubB2BUtils.getMessageForStatusCode(PMC_DH_ConstantClass.TECHNICAL_ERR_STATUS_CODE, PMC_DH_ConstantClass.ALL); 
        }
        return statusCodeMessage;
    }	
    
    /*************************************************************************
* @method Name  : getCadenceRecords
* @description  : Method to get cadence record along with their quoteId
* @param 		  strQuoteId
* @return         PMC_DH_QuoteAndCadenceLstResponseWrapper
*****************************************************************************/
    @AuraEnabled
    public static PMC_DH_QuoteAndCadenceLstResponseWrapper getCadenceRecords(String strQuoteId){
        PMC_DH_QuoteAndCadenceLstResponseWrapper quoteCadenceRecordsWrapper = new PMC_DH_QuoteAndCadenceLstResponseWrapper();
        List<PMC_DH_QuoteAndCadenceWrapper> lstQuoteAndCadenceWrapper = new List<PMC_DH_QuoteAndCadenceWrapper>();
        try{
            PMC_DH_DigitalHubB2BUtils.throwTestExceptionForTest();
            List<SBQQ__QuoteLine__c> lstQuoteLine = [SELECT Id, Name, SBQQ__Quote__c, SBQQ__Product__r.Name, PMC_CPQ_ShipTo__r.Name, 
                                                    PMC_CPQ_ShipTo__r.ShippingStreet, PMC_CPQ_ShipTo__r.ShippingCity, PMC_CPQ_ShipTo__r.ShippingState, 
                                                    PMC_CPQ_ShipTo__r.ShippingCountry, toLabel(PMC_CPQ_ModeofTransportation__c), toLabel(PMC_CPQ_Incoterms1__c), 
                                                    PMC_CPQ_ProductLocation__r.Name,  SBQQ__Quantity__c, SBQQ__Quote__r.SBQQ__DocumentStatus__c, SBQQ__Quote__r.PMC_CPQ_ContractStart__c, SBQQ__Quote__r.PMC_CPQ_ContractEnd__c, 
                                                    (SELECT Id, PMC_CPQ_RequestedDate__c, PMC_CPQ_RequestedQuantity__c FROM Cadences__r ORDER BY PMC_CPQ_RequestedDate__c) 
                                                    from SBQQ__QuoteLine__c where SBQQ__Quote__c = :strQuoteId WITH SECURITY_ENFORCED];
            if(!lstQuoteLine.isEmpty()){
                for(SBQQ__QuoteLine__c quoteLine:lstQuoteLine){
                    PMC_DH_QuoteAndCadenceWrapper quoteAndCadenceWrapper = new PMC_DH_QuoteAndCadenceWrapper();
                    quoteAndCadenceWrapper.strQuoteLineId = quoteLine.Id;
                    quoteAndCadenceWrapper.strProductName = quoteLine.SBQQ__Product__r.Name;
                    quoteAndCadenceWrapper.strShipTo = quoteLine.PMC_CPQ_ShipTo__r.Name + ' ' + quoteLine.PMC_CPQ_ShipTo__r.ShippingStreet + ' ' + quoteLine.PMC_CPQ_ShipTo__r.ShippingCity + ' ' + quoteLine.PMC_CPQ_ShipTo__r.ShippingState + ' ' + quoteLine.PMC_CPQ_ShipTo__r.ShippingCountry;
                    quoteAndCadenceWrapper.strDeliveryInfo = quoteLine.PMC_CPQ_ModeofTransportation__c + '-' + quoteLine.PMC_CPQ_Incoterms1__c;
                    quoteAndCadenceWrapper.strShipFrom = quoteLine.PMC_CPQ_ProductLocation__r.Name;
                    quoteAndCadenceWrapper.intTotalQuantity = quoteLine.SBQQ__Quantity__c != null?quoteLine.SBQQ__Quantity__c.longValue():0;//GDASF-10697 - Integer.valueOf()
                    quoteAndCadenceWrapper.strStartDate = String.valueOf(quoteLine.SBQQ__Quote__r.PMC_CPQ_ContractStart__c);
                    quoteAndCadenceWrapper.strEndDate = String.valueOf(quoteLine.SBQQ__Quote__r.PMC_CPQ_ContractEnd__c);
                    List<PMC_DH_CadenceWrapper> lstCadenceWrapper = new List<PMC_DH_CadenceWrapper>();
                    getCadenceData(quoteLine.Cadences__r,lstCadenceWrapper);
                    quoteAndCadenceWrapper.lstCadence = lstCadenceWrapper;
                    quoteAndCadenceWrapper.boolCadenceAvailable = false;
                    if(!lstCadenceWrapper.isEmpty()){
                        quoteAndCadenceWrapper.boolCadenceAvailable = true;
                    }
                    lstQuoteAndCadenceWrapper.add(quoteAndCadenceWrapper);
                }
            }
            quoteCadenceRecordsWrapper.lstQuoteCadenceRecords = lstQuoteAndCadenceWrapper;
            quoteCadenceRecordsWrapper.statusCodeMessage = PMC_DH_DigitalHubB2BUtils.getMessageForStatusCode(PMC_DH_ConstantClass.SUCCESS_STATUS_CODE, PMC_DH_ConstantClass.CADENCE);
        }catch(Exception ex){
            PMC_ErrorLogClass.processException(ex); // MDErrorLog
            quoteCadenceRecordsWrapper.statusCodeMessage = PMC_DH_DigitalHubB2BUtils.getMessageForStatusCode(PMC_DH_ConstantClass.FAILURE_STATUS_CODE, PMC_DH_ConstantClass.ALL); 
            //throw new AuraHandledException(ex.getMessage());
        }
        return quoteCadenceRecordsWrapper;
        //return lstQuoteAndCadenceWrapper;
    }
    /*************************************************************************
* @method Name  : getCadenceData
* @description  : Method to get cadence record
* @param 		  lstCadence
* @param          lstCadenceWrapper
*****************************************************************************/
    private static void getCadenceData(List<PMC_CPQ_Cadence__c> lstCadence, List<PMC_DH_CadenceWrapper> lstCadenceWrapper){
        if(!lstCadence.isEmpty()){
            for(PMC_CPQ_Cadence__c cadence:lstCadence){
                PMC_DH_CadenceWrapper cadenceWrapper = new PMC_DH_CadenceWrapper();
                cadenceWrapper.strCadenceId = cadence.Id;
                cadenceWrapper.intQuantity = cadence.PMC_CPQ_RequestedQuantity__c != null?cadence.PMC_CPQ_RequestedQuantity__c.longValue():0;//GDASF-10697 - Integer.valueOf()
                cadenceWrapper.strMonth = String.valueOf(cadence.PMC_CPQ_RequestedDate__c.month()+'/'+cadence.PMC_CPQ_RequestedDate__c.year());
                lstCadenceWrapper.add(cadenceWrapper);
            }
        }
    }
    /*************************************************************************
* @method Name  : updateCadence
* @description  : Method to update cadence record
* @param          lstCadenceWrapper
* @return         PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper
*****************************************************************************/
    @AuraEnabled
    public static PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper updateCadence(List<PMC_DH_CadenceWrapper> lstCadenceWrapper){
        PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper statusCodeMessage = new PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper();
        try{
            if(!lstCadenceWrapper.isEmpty()){
                List<PMC_CPQ_Cadence__c> lstCadence = new List<PMC_CPQ_Cadence__c>();
                for(PMC_DH_CadenceWrapper cadenceWrp: lstCadenceWrapper){
                    PMC_CPQ_Cadence__c cadence = new PMC_CPQ_Cadence__c();
                    cadence.Id = cadenceWrp.strCadenceId;
                    cadence.PMC_CPQ_RequestedQuantity__c = cadenceWrp.intQuantity;
                    lstCadence.add(cadence);
                }
                if(Schema.sObjectType.PMC_CPQ_Cadence__c.isUpdateable()){
                    update lstCadence;
                }
            }
            statusCodeMessage = PMC_DH_DigitalHubB2BUtils.getMessageForStatusCode(PMC_DH_ConstantClass.SUCCESS_STATUS_CODE, PMC_DH_ConstantClass.CADENCE);
        }catch(Exception ex){
            PMC_ErrorLogClass.processException(ex); // MDErrorLog
            statusCodeMessage = PMC_DH_DigitalHubB2BUtils.getMessageForStatusCode(PMC_DH_ConstantClass.FAILURE_STATUS_CODE, PMC_DH_ConstantClass.ALL); 
            return statusCodeMessage;
        }
        return statusCodeMessage;
    }

/**
* @description       : Wrapper for Quote and Cadence Records List and response status
* @author            : @manishasingh9
* @Created on        : 2023-Dec-23
**/
// added with sharing
public with sharing class PMC_DH_QuoteAndCadenceLstResponseWrapper{
    /**
    * @description List of Quote and Cadence Records
    * @return List<PMC_DH_QuoteAndCadenceWrapper>
    */
    @AuraEnabled
    public List<PMC_DH_QuoteAndCadenceWrapper> lstQuoteCadenceRecords { get; set; }

    /**
     * @description Status Code and message
     * @return PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper
     */
    @AuraEnabled
    public PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper statusCodeMessage{get;set;}

}
    /**
* @description       : Wrapper for Quote and Cadence Records
* @author            : @Ajeet
* @Created on        : 2023-Nov-16
**/
// added with sharing
    public with sharing class PMC_DH_QuoteAndCadenceWrapper{
        /**
* @description QuoteLine Id
* @return String
*/
        @AuraEnabled
        public String strQuoteLineId { get; set; }
        /**
* @description Product on QuoteLine
* @return String
*/
        @AuraEnabled
        public String strProductName { get; set; }
        /**
* @description Ship to Address
* @return String
*/
        @AuraEnabled
        public String strShipTo { get; set; }
        /**
* @description Delivery information
* @return String
*/
        @AuraEnabled
        public String strDeliveryInfo { get; set; }
        /**
* @description Ship From loaction
* @return String
*/
        @AuraEnabled
        public String strShipFrom { get; set; }
        /**
* @description Quantity of quote line item
* @return Long
*/
        @AuraEnabled
        public Long intTotalQuantity { get; set; }
        /**
* @description Ship From loaction
* @return String
*/
        @AuraEnabled
        public String strStartDate { get; set; }
        /**
* @description Ship From loaction
* @return String
*/
        @AuraEnabled
        public String strEndDate { get; set; }
        /**
* @description Flag for Cadence present or not
* @return Boolean
*/
        @AuraEnabled
        public Boolean boolCadenceAvailable { get; set; }
        /**
* @description List of Cadence
* @return List<PMC_DH_CadenceWrapper>
*/
        @AuraEnabled
        public List<PMC_DH_CadenceWrapper> lstCadence { get; set; }
    }
    
    /**
* @description       : Wrapper for Quote and Cadence Records
* @author            : @Ajeet
* @Created on        : 2023-Nov-16
**/
// added with sharing
    public with sharing class PMC_DH_CadenceWrapper{
        /**
* @description Cadence Id
* @return String
*/
        @AuraEnabled
        public String strCadenceId { get; set; }
        /**
* @description Cadence Month
* @return String
*/
        @AuraEnabled
        public String strMonth { get; set; }
        /**
* @description Cadence quantity
* @return Long
*/
        @AuraEnabled
        public Long intQuantity { get; set; }
    }
}