objects/Contract.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_AccountManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__AmendmentRenewalBehavior__c</fullName>
        <description>The basis for which a Renewal Start Date and Amendment End Date are calculated.</description>
        <inlineHelpText>The basis for which a Renewal Start Date and Amendment End Date are calculated.</inlineHelpText>
        <label>Amendment &amp; Renewal Behavior</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Latest End Date</fullName>
                    <default>true</default>
                    <label>Latest End Date</label>
                </value>
                <value>
                    <fullName>Earliest End Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity from which this Contract was created.</description>
        <inlineHelpText>The Opportunity from which this Contract was created.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionQuantitiesCombined__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select to combine quantities of Subscriptions for the same product into one line on Renewal Quotes and Legacy Amendments.</description>
        <inlineHelpText>Select to combine quantities of Subscriptions for the same product into one line on Renewal Quotes and Legacy Amendments.</inlineHelpText>
        <label>Combine Subscription Quantities</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CLM_ContractCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_AccountManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field captures the Account manager for each quote</description>
        <inlineHelpText>Indicates the Account manager for the Quote</inlineHelpText>
        <label>Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ContractEnd__c</fullName>
        <description>If Master contract exists - then formula to pull the date from Contract reference</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Quote End Date</inlineHelpText>
        <label>Contract Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ContractStart__c</fullName>
        <description>If Master contract exists - then formula to pull the date from Contract reference</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Quote Start Date</inlineHelpText>
        <label>Contract Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to capture the Primary Contact associated with the quote.</description>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.SBQQ__Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CPQ Quotes (Primary Contact1)</relationshipLabel>
        <relationshipName>CPQ_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_QuoteNumberIdentifier__c</fullName>
        <description>This field will store the quote number with prefix removed which will serve as an external id for integration.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Quote Number Identifier</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>Account for which this quote has been created.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__PaymentTerms__c</fullName>
        <description>Terms that govern payment of the items in this quote.</description>
        <inlineHelpText>Indicates the Terms that govern payment of the items in this quote.</inlineHelpText>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash Against Documents</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 5 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 7 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 10 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 15 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 30 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 45 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Doc - 60 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 90 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 120 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 180 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Prepayment</fullName>
                </value>
                <value>
                    <fullName>Net 1 Day - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 2 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 3 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>05 Days - Document Lock Date</fullName>
                </value>
                <value>
                    <fullName>Net 7 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 10 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 14 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 15 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 17 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 21 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 28 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 29 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 30 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 31 Days - From Invoicing Date</fullName>
                    <label>Net 31 Days -  From Invoicing Date</label>
                </value>
                <value>
                    <fullName>Net 35 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 42 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 45 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 60 Days - From Invoicing Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__PricebookId__c</fullName>
        <description>ID of the Price Book used by this quote.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>ID of the Price Book used by this quote.</inlineHelpText>
        <label>Pricebook ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PMC_DM_CreateContractFromQuoteBatch.cls
/**
* @description       : Batch Class to create Contract for the Quotes created by Data Migration User
* @author            : Preethi J
**/
public with sharing class PMC_DM_CreateContractFromQuoteBatch implements Database.Batchable<sObject> {
    Id userId;
    List<Id> listQuoteIds = new List<Id>();
    List<Contract> lstContract = new List<Contract>();
    List<SBQQ__Quote__c> quoUpdate = new List<SBQQ__Quote__c>();
    /**
* @description constructor of the class
* @param userId - the id of the user
*/
    public PMC_DM_CreateContractFromQuoteBatch(Id userId) {
        this.userId = userId;
    }
    /**
* @description constructor of the class
* @param userId - the id of the user
* @param lstQuoteIds - list of Quotes
*/
    public PMC_DM_CreateContractFromQuoteBatch(Id userId, List<Id> lstQuoteIds){
        this.userId = userId;
        this.listQuoteIds = lstQuoteIds;
    }
    /**
* @description start method of batchable class
* @param objBC
* @return  Database.QueryLocator
*/
    public Database.QueryLocator start(Database.BatchableContext objBC) {
        String query;
        if(!listQuoteIds.isEmpty()){
            query = 'select Id, CurrencyIsoCode,PMC_CPQ_QuoteNumberIdentifier__c, PMC_CPQ_ContractEnd__c, PMC_CPQ_ContractStart__c, SBQQ__PricebookId__c, PMC_CPQ_AccountManager__c, PMC_CPQ_PrimaryContact__c, SBQQ__Opportunity2__c, SBQQ__PaymentTerms__c, SBQQ__Account__c, SBQQ__Account__r.OwnerId from SBQQ__Quote__c where CreatedById =: userId AND PMC_CLM_ContractCreated__c = false AND id in : listQuoteIds';
        }
        else{
            query = 'select Id, CurrencyIsoCode,PMC_CPQ_QuoteNumberIdentifier__c, PMC_CPQ_ContractEnd__c, PMC_CPQ_ContractStart__c, SBQQ__PricebookId__c, PMC_CPQ_AccountManager__c, PMC_CPQ_PrimaryContact__c, SBQQ__Opportunity2__c, SBQQ__PaymentTerms__c, SBQQ__Account__c, SBQQ__Account__r.OwnerId from SBQQ__Quote__c where CreatedById =: userId AND PMC_CLM_ContractCreated__c = false';
        }
        return Database.getQueryLocator(query);
    }
    /**
* @description execute method of batchable class
* @param objBC
* @param  lstQuotes - list of quotes
*/
    public void execute(Database.BatchableContext objBC, List<SBQQ__Quote__c> lstQuotes) {
        //List<Contract> lstContract = new List<Contract>();
        //List<SBQQ__Quote__c> quoUpdate = new List<SBQQ__Quote__c>();
        try {
            contractCreate(lstQuotes);
            // Insert the created contracts
            if (!lstContract.isEmpty()) {
                SObjectAccessDecision decision = Security.stripInaccessible(AccessType.CREATABLE, lstContract);
                Database.insert(decision.getRecords());
            }
            if(!quoUpdate.isEmpty()){
                SObjectAccessDecision decision = Security.stripInaccessible(AccessType.UPDATABLE, quoUpdate);
                Database.update(decision.getRecords());
            }
        } catch (Exception e) {
            PMC_ErrorLogClass.processException(e);
        }
    }
    /**
* @description method which creates the contract by assigning the respective fields
* @param lstQuotes
*/
    public void contractCreate(List<SBQQ__Quote__c> lstQuotes){
        // Iterate through the quotes and create contracts
        for (SBQQ__Quote__c q : lstQuotes) {
            Contract objContract = new Contract();
            objContract.CurrencyIsoCode = q.CurrencyIsoCode;
            objContract.EndDate = q.PMC_CPQ_ContractEnd__c;
            objContract.StartDate = q.PMC_CPQ_ContractStart__c;
            objContract.Pricebook2Id = q.SBQQ__PricebookId__c!=null?q.SBQQ__PricebookId__c:null;
            objContract.Status = 'Draft';
            //objContract.PMC_CPQ_AccountManager__c = q.PMC_CPQ_AccountManager__c;
            objContract.SBQQ__AmendmentRenewalBehavior__c = 'Latest End Date';
            objContract.SBQQ__SubscriptionQuantitiesCombined__c = false;
            objContract.PMC_CPQ_PrimaryContact__c = q.PMC_CPQ_PrimaryContact__c!=null?q.PMC_CPQ_PrimaryContact__c:null;
            objContract.SBQQ__Opportunity__c = q.SBQQ__Opportunity2__c!=null?q.SBQQ__Opportunity2__c:null;
            objContract.PMC_CPQ_PaymentTerms__c  = q.SBQQ__PaymentTerms__c;
            objContract.SBQQ__Quote__c = q.Id;
            objContract.PMC_CPQ_LatestQuote__c = q.Id;
            objContract.AccountId = q.SBQQ__Account__c!=null?q.SBQQ__Account__c:null;
            objContract.OwnerId = q.SBQQ__Account__r.OwnerId;
            objContract.PMC_CPQ_ContractNumberIdentifier__c = q.PMC_CPQ_QuoteNumberIdentifier__c;
            objContract.ContractTerm = objContract.StartDate.monthsBetween(objContract.EndDate)==0?1:objContract.StartDate.monthsBetween(objContract.EndDate);
            lstContract.add(objContract);
            q.PMC_CLM_ContractCreated__c = true;
            quoUpdate.add(q);
        }
    }
    /**
* @description finish method of batchable class
* @param objBC
*/
    public void finish(Database.BatchableContext objBC) {
        System.assertEquals('Success','Success');
    }
}