objects/Contract.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_PO__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Purchase Order #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_PO__c</fullName>
        <description>This field is used to capture the user input for Purchase order number.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Purchase Order number for this order.</inlineHelpText>
        <label>Customer Purchase Order #</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SAPOrderNumber__c</fullName>
        <description>This field captures the order number in SAP.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Reference Order Number in SAP.</inlineHelpText>
        <label>SAP Order Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_FPDPricefromPriceFx__c</fullName>
        <description>Created as part of GDASF-9360. This field captures the FPD price from Price Fx.</description>
        <inlineHelpText>The FPD List Price for the Order Product is only relevant when the contract type of the product is specified as FPD</inlineHelpText>
        <label>FPD List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_FinalAgreedPrice__c</fullName>
        <description>This field is will store the Final Agreed Price and send it back to SAP after the Order is placed.</description>
        <label>Final Agreed Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderItemIntegrationMessage__c</fullName>
        <description>The Integration message of external callout.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderLineStatus__c</fullName>
        <label>Order Line Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Placed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Completely Shipped</fullName>
                    <isActive>false</isActive>
                    <label>Completely Shipped</label>
                </value>
                <value>
                    <fullName>Partially Shipped</fullName>
                    <isActive>false</isActive>
                    <label>Partially Shipped</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PricingDate__c</fullName>
        <description>This field captures Pricing date.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field captures the pricing date</inlineHelpText>
        <label>Price by Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Products (Ship To)</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/PMC_CPQ_QLApprovalReqEmailTempClass.cls
/**
* @description This class will be used to fetch the data from the org to be used in Email Template.
* @author Azmir Ali
* @storynumber GCPM-2397
*/
public with sharing class PMC_CPQ_QLApprovalReqEmailTempClass {
   
    private OrderItem orderItemInfo;
    
/**
* @description orderitemId -to store the quoteid rendering from the email template 
*/
    public string orderItemId {get;set;}

/**
* @description This method is used to Query only the Orders which is related to the Order Line id passed
* @description qLines -  to store the Orders which have RawMaterials in the related list
* @return qLines 
*/
	public List<OrderItem> oLines{
        get{
            if(orderItemId!=null){ 
                oLines= [SELECT id,OrderItemNumber, Order.OrderNumber, Order.PMC_CPQ_SAPOrderNumber__c, Order.Contract.ContractNumber, Order.Contract.PMC_CPQ_PO__c,
                             PMC_CPQ_ShipTo__r.Name, Order.Account.Name, Product2.Name, Quantity, PMC_CPQ_PricingDate__c,PMC_CPQ_FPDPricefromPriceFx__c,
                             PMC_CPQ_FinalAgreedPrice__c, PMC_CPQ_OrderLineStatus__c, PMC_CPQ_OrderItemIntegrationMessage__c  from OrderItem WHERE ID = :orderItemId WITH SECURITY_ENFORCED];
            }
            return oLines;            
        }set;
    }         
}