objects/Contract.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_LatestQuote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts (Latest Quote)</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__MasterContract__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select to designate this contract as the master contract for this account. Upon renewal, all contracts will be rolled into this one.</description>
        <inlineHelpText>Select to designate this contract as the master contract for this account. Upon renewal, all contracts will be rolled into this one.</inlineHelpText>
        <label>Master Contract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_TriggerSwitches__mdt.object
<CustomObject>
    <description>This custom metadata is used to bypass trigger operations.</description>
    <fields>
        <fullName>PMC_AfterDelete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_AfterInsert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_AfterUndelete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Undelete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_AfterUpdate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_BeforeDelete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_BeforeInsert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before Insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_BeforeUpdate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before Update</label>
        <type>Checkbox</type>
    </fields>
    <label>PMC Trigger Switches</label>
    <pluralLabel>PMC Trigger Switches</pluralLabel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CPQ_ContractEnd__c</fullName>
        <description>If Master contract exists - then formula to pull the date from Contract reference</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Quote End Date</inlineHelpText>
        <label>Contract Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ContractStageName__c</fullName>
        <description>This field helps to denote the current stage of the contract document</description>
        <label>Contract Document Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Pending Signature</fullName>
                </value>
                <value>
                    <fullName>Partially Executed</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Accept</fullName>
                    <isActive>false</isActive>
                    <label>Accept</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <isActive>false</isActive>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Pending Signatures</fullName>
                    <isActive>false</isActive>
                    <label>Pending Signatures</label>
                </value>
                <value>
                    <fullName>Signed</fullName>
                    <isActive>false</isActive>
                    <label>Signed</label>
                </value>
                <value>
                    <fullName>hello</fullName>
                    <isActive>false</isActive>
                    <label>hello</label>
                </value>
                <value>
                    <fullName>yfgfgfc</fullName>
                    <isActive>false</isActive>
                    <label>yfgfgfc</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ContractStart__c</fullName>
        <description>If Master contract exists - then formula to pull the date from Contract reference</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Quote Start Date</inlineHelpText>
        <label>Contract Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_LegacyQuoteID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SAP Original Contract</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__MasterContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master contract with which subscription products in this quote are to be co-terminated.</description>
        <inlineHelpText>Master contract with which subscription products in this quote are to be co-terminated.</inlineHelpText>
        <label>Master Contract</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contract.SBQQ__Evergreen__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Co-Terminated Quotes</relationshipLabel>
        <relationshipName>CoTerminatedQuotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Type__c</fullName>
        <description>Indicates the type of quote.</description>
        <inlineHelpText>Indicates the type of quote.(New,Amend,Renew)</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                    <default>true</default>
                    <label>Quote</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Re-Quote</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PMC_CPQ_QuoteTriggerHandler.cls
/**
* @description This class will be used to handle all trigger operations of Quote (SBQQ_Quote__c) object
* @author Lalit Sharma
* @storynumber GDASF-8944
*/
public without sharing class PMC_CPQ_QuoteTriggerHandler extends PMC_TriggerHandler{
    /**
* These boolean variables are used to bypass the trigger operations
*/
    private static final Boolean BOOL_BYPASS_BEFORE_INSERT;
    private static final Boolean BOOL_BYPASS_BEFORE_UPDATE;
    private static final Boolean BOOL_BYPASS_BEFORE_DELETE;
    private static final Boolean BOOL_BYPASS_AFTER_INSERT;
    private static final Boolean BOOL_BYPASS_AFTER_UPDATE;
    private static final Boolean BOOL_BYPASS_AFTER_DELETE;
    private static final Boolean BOOL_BYPASS_AFTER_UNDELETE;
    
    @testVisible
    public static Boolean boolBypassTriggerLogic = false;
    
    /**
* These variables will hold the copy of trigger variables
*/
    private List<SBQQ__Quote__c> lstNewQuotes;
    private Map<Id,SBQQ__Quote__c> mapNewQuotes;
    private List<SBQQ__Quote__c> lstOldQuotes;
    private Map<Id,SBQQ__Quote__c> mapOldQuotes;
    
    
    /**
* @description This static block initializes the trigger switches when the class is invoked
*/
    static{
        
        PMC_TriggerSwitches__mdt operationSwitches = PMC_TriggerSwitches__mdt.getInstance('Quote');
        
        BOOL_BYPASS_BEFORE_INSERT = operationSwitches.PMC_BeforeInsert__c;
        BOOL_BYPASS_BEFORE_UPDATE = operationSwitches.PMC_BeforeUpdate__c;
        BOOL_BYPASS_BEFORE_DELETE = operationSwitches.PMC_BeforeDelete__c;
        BOOL_BYPASS_AFTER_INSERT = operationSwitches.PMC_AfterInsert__c;
        BOOL_BYPASS_AFTER_UPDATE = operationSwitches.PMC_AfterUpdate__c;
        BOOL_BYPASS_AFTER_DELETE = operationSwitches.PMC_AfterDelete__c;
        BOOL_BYPASS_AFTER_UNDELETE = operationSwitches.PMC_AfterUndelete__c;
        
    }
    
    /**
* @description Constructor method to initialize class level variables and store the trigger collections and add the max loop count of trigger
*/
    public PMC_CPQ_QuoteTriggerHandler(){    
        
        //Instantiating local class variables from trigger variables
        this.lstNewQuotes = Trigger.new;
        this.mapNewQuotes = (Map<Id, SBQQ__Quote__c>) Trigger.newMap;
        this.lstOldQuotes = Trigger.old;
        this.mapOldQuotes = (Map<Id, SBQQ__Quote__c>) Trigger.oldMap;
        
        //Set the maximum calls allowed for the class
        //this.setMaxLoopCount(32);
        //GCPM-1751 - Start
        for(SBQQ__Quote__c objquote:this.lstNewQuotes){
            if(objquote.PMC_CPQ_LegacyQuoteID__c != null){
        			this.setMaxLoopCount(150);        
            }
            else
            {
                this.setMaxLoopCount(32);
            }
        }
        //GCPM-1751 - End
    }
    
    /**
    * @description This method will perform the operation for before insert trigger
    */
    public override void beforeInsert(){
        if(BOOL_BYPASS_BEFORE_INSERT  || boolBypassTriggerLogic){
            return;
        }
        // PMC_CPQ_QuoteTriggerHelper.clearLegacyQuoteIdWhileClonning(this.lstNewQuotes);
    }
    
    /**
* @description This method will perform the operation for before update trigger
*/
    public override void beforeUpdate(){
        if(BOOL_BYPASS_BEFORE_UPDATE  || boolBypassTriggerLogic){
            return;
        }
        
        
             PMC_CPQ_QuoteTriggerHelper.validateQuoteExpiration(lstNewQuotes, mapOldQuotes);
    }
    
    /**
* @description This method will perform the operation for before delete trigger
*/
    public override void beforeDelete(){
        if(BOOL_BYPASS_BEFORE_DELETE  || boolBypassTriggerLogic){
            return;
        }
       
    }
    
    /**
* @description This method will perform the operation for after insert trigger
*/
    public override void afterInsert(){
        if(BOOL_BYPASS_AFTER_INSERT  || boolBypassTriggerLogic){
            return;
        }
    }
    
    /**
* @description This method will perform the operation for after update trigger
*/
    public override void afterUpdate(){
        if(BOOL_BYPASS_AFTER_UPDATE || boolBypassTriggerLogic){
            return;
        }
        /* GSMD-384  */
       /* Set<ID> SetOfContractID=new  Set<ID>();
        for(SBQQ__Quote__c objquote:this.lstNewQuotes){
            if(objquote.SBQQ__Type__c=='Amendment' && objquote.PMC_CPQ_ContractStageName__c=='Accepted' && 
               objquote.SBQQ__MasterContract__c!=null && objquote.PMC_CPQ_ContractEnd__c!=null && objquote.PMC_CPQ_ContractStart__c!=null){
                SetOfContractID.add(objquote.SBQQ__MasterContract__c);
            }
        }
    if(SetOfContractID.size()>0){
    List<Contract> enddateupdate=new  List<Contract> ();
    for(Contract obj:[Select id,PMC_CPQ_LatestQuote__c,PMC_CPQ_LatestQuote__r.PMC_CPQ_ContractEnd__c,EndDate,
    PMC_CPQ_LatestQuote__r.PMC_CPQ_ContractStart__c ,StartDate
                        from Contract where id in:SetOfContractID]){ 
    if(obj.PMC_CPQ_LatestQuote__r.PMC_CPQ_ContractEnd__c !=obj.EndDate){
    obj.EndDate=obj.PMC_CPQ_LatestQuote__r.PMC_CPQ_ContractEnd__c;        
    }  
    if(obj.PMC_CPQ_LatestQuote__r.PMC_CPQ_ContractStart__c !=obj.StartDate){
    obj.StartDate=obj.PMC_CPQ_LatestQuote__r.PMC_CPQ_ContractStart__c ;        
    }       
    enddateupdate.add(obj);
    }
    
    if(enddateupdate.size()>0){
    update enddateupdate;
    }
    }*/
        
    }
    
    /**
* @description This method will perform the operation for after delete trigger
*/
    public override void afterDelete(){
        if(BOOL_BYPASS_AFTER_DELETE || boolBypassTriggerLogic){
            return;
        }
        
    }
    
    /**
* @description This method will perform the operation for after undelete trigger
*/
    public override void afterUndelete(){
        if(BOOL_BYPASS_AFTER_UNDELETE || boolBypassTriggerLogic){
            return;
        }        
    }
    
}