objects/Contract.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_AccountManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CLM_ContractCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_AccountManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field captures the Account manager for each quote</description>
        <inlineHelpText>Indicates the Account manager for the Quote</inlineHelpText>
        <label>Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ContractEnd__c</fullName>
        <description>If Master contract exists - then formula to pull the date from Contract reference</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Quote End Date</inlineHelpText>
        <label>Contract Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ContractStart__c</fullName>
        <description>If Master contract exists - then formula to pull the date from Contract reference</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Quote Start Date</inlineHelpText>
        <label>Contract Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>Account for which this quote has been created.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__PaymentTerms__c</fullName>
        <description>Terms that govern payment of the items in this quote.</description>
        <inlineHelpText>Indicates the Terms that govern payment of the items in this quote.</inlineHelpText>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash Against Documents</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 5 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 7 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 10 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 15 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 30 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 45 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Doc - 60 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 90 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 120 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Cash Against Documents - 180 Days From BL</fullName>
                </value>
                <value>
                    <fullName>Prepayment</fullName>
                </value>
                <value>
                    <fullName>Net 1 Day - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 2 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 3 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>05 Days - Document Lock Date</fullName>
                </value>
                <value>
                    <fullName>Net 7 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 10 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 14 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 15 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 17 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 21 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 28 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 29 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 30 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 31 Days - From Invoicing Date</fullName>
                    <label>Net 31 Days -  From Invoicing Date</label>
                </value>
                <value>
                    <fullName>Net 35 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 42 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 45 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Net 60 Days - From Invoicing Date</fullName>
                </value>
                <value>
                    <fullName>Fixed Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__PriceBook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Price Book associated with this Quote.</description>
        <inlineHelpText>Price Book associated with this Quote.</inlineHelpText>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PMC_DM_CreateContractFromQuoteBatchTest.cls
/**
* @description This test class will be used to cover all the methods of PMC_DM_CreateContractFromQuoteBatchTest
* @author Preethi J
*/
@isTest
public class PMC_DM_CreateContractFromQuoteBatchTest {
    public Static List<Id> lstQuoteId = new List<Id>();
    public Static List<Opportunity> lstOpty = new List<Opportunity>();
    public Static List<Contact> lstContact = new List<Contact>();
    public static Id userId;
    public static List<SBQQ__Quote__c> lstQuotes;
    public static Account objAccount;
    
    /*
     * @description This is the test setup method which creates the data required
*/
    @TestSetup
    private static void testSetup(){
        List<String>lstProfileNames = New List<String>{'System Administrator','Sales User'};
        List<String>lstPermissionNames = New List<String>{'PMC_Administrator_Permission_Set_Group','PMC_SLS_Permission_Set_Group'};
        Map<String,Id>mapOfProfiles = PMC_TestUtilityClass.getProfiles(lstProfileNames);
        Map<String,PermissionSetGroup>mapOfPermissionGrp = PMC_TestUtilityClass.getPemissionsetGroups(lstPermissionNames);
        Integer intuserCount =0;
        User objSystemAdminUser;  
        User objSalesUser;
        List<User> lstUser = PMC_TestUtilityClass.createUser(2);
        for(User objUser : lstUser) {
            If(intuserCount==0){
                objUser.LastName = 'Admin User Test';
                objUser.ProfileId = mapOfProfiles.get('System Administrator'); 
                objUser.FederationIdentifier = objUser.Username + 'Admin';
            }else if(intuserCount==1){
                objUser.LastName = 'Sales User Test';
                objUser.ProfileId = mapOfProfiles.get('Sales User'); 
                objUser.FederationIdentifier = objUser.Username + 'Sales';
            }
            objUser.isActive = true;                
            objUser.MobilePhone = '1234567890';
            objUser.UserPermissionsKnowledgeUser =true;
            objUser.LanguageLocaleKey = 'en_US';
            intuserCount = intuserCount + 1;
        }            
        insert lstUser;
        objSystemAdminUser = lstUser[0];
        objSalesUser =lstUser[1];
        PMC_TestUtilityClass.assignPermissionSetGroupToUsers(new List<User>{objSystemAdminUser}, mapOfPermissionGrp.get('PMC_Administrator_Permission_Set_Group'));
        PMC_TestUtilityClass.assignPermissionSetGroupToUsers(new List<User>{objSalesUser}, mapOfPermissionGrp.get('PMC_SLS_Permission_Set_Group'));
        System.runas(objSystemAdminUser){
            lstOpty = PMC_TestUtilityClass.createOpportunity(3,'Master');
            lstContact = PMC_TestUtilityClass.createContact(3,'Master');
            lstQuotes = PMC_TestUtilityClass.createCPQQuotes(3,lstOpty , lstContact);
            for(Integer i=0; i<lstQuotes.size();i++){
                lstQuoteId.add(lstQuotes[i].Id);
            }
        }
    }
    /*
     * @description This method will run the Execute method for Months between less than 1
*/
    @isTest
    public static void testBatchExecution(){
        List<User> lstUser = [SELECT Id FROM User WHERE LastName ='Admin User Test' WITH SECURITY_ENFORCED LIMIT 1];
        System.runAs(lstUser.get(0)){
        List<SBQQ__Quote__c> lstQuote = [select OwnerId,SBQQ__Opportunity2__r.AccountId,PMC_CPQ_AccountManager__c,CurrencyIsoCode,SBQQ__PriceBook__c,SBQQ__PaymentTerms__c,SBQQ__Account__c,PMC_CLM_ContractCreated__c,PMC_CPQ_ContractStart__c,PMC_CPQ_ContractEnd__c, Id from SBQQ__Quote__c LIMIT 3];
        for(SBQQ__Quote__c obj : lstQuote){
            lstQuoteId.add(obj.Id);
            obj.CurrencyIsoCode = 'USD';
            obj.SBQQ__PriceBook__c = Test.getStandardPricebookId();
            obj.SBQQ__PaymentTerms__c = 'Fixed Date';
            obj.SBQQ__Account__c = obj.SBQQ__Opportunity2__r.AccountId;
            obj.PMC_CLM_ContractCreated__c = false;
            obj.PMC_CPQ_ContractEnd__c = obj.PMC_CPQ_ContractStart__c.addDays(2);
        }
        update lstQuote;
        userId = lstQuote[0].OwnerId;
        Test.startTest();
        PMC_DM_CreateContractFromQuoteBatch batch = new PMC_DM_CreateContractFromQuoteBatch(userId);
        Database.executeBatch(batch);
        Test.stopTest();
        List<SBQQ__Quote__c> updatedQuotes = [SELECT Id, PMC_CLM_ContractCreated__c FROM SBQQ__Quote__c WHERE PMC_CLM_ContractCreated__c =: true];
        System.assertEquals(3, updatedQuotes.size(),'Contract not created');
        }
    }
    /*
     * @description This method will run the Execute method for Months between greater than 1
*/
    @isTest
    public static void testBatchExecution1(){
        List<User> lstUser = [SELECT Id FROM User WHERE LastName ='Admin User Test' WITH SECURITY_ENFORCED LIMIT 1];
        System.runAs(lstUser.get(0)){
        List<SBQQ__Quote__c> lstQuote = [select OwnerId,SBQQ__Opportunity2__r.AccountId,PMC_CPQ_AccountManager__c,CurrencyIsoCode,SBQQ__PriceBook__c,SBQQ__PaymentTerms__c,SBQQ__Account__c,PMC_CLM_ContractCreated__c,PMC_CPQ_ContractStart__c,PMC_CPQ_ContractEnd__c, Id from SBQQ__Quote__c LIMIT 3];
        for(SBQQ__Quote__c obj : lstQuote){
            lstQuoteId.add(obj.Id);
            obj.CurrencyIsoCode = 'USD';
            obj.SBQQ__PriceBook__c = Test.getStandardPricebookId();
            obj.SBQQ__PaymentTerms__c = 'Fixed Date';
            obj.SBQQ__Account__c = obj.SBQQ__Opportunity2__r.AccountId;
            obj.PMC_CLM_ContractCreated__c = false;
            obj.PMC_CPQ_ContractEnd__c = obj.PMC_CPQ_ContractStart__c.addDays(50);
        }
        update lstQuote;
        userId = lstQuote[0].OwnerId;
        Test.startTest();
        PMC_DM_CreateContractFromQuoteBatch batch1 = new PMC_DM_CreateContractFromQuoteBatch(userId,lstQuoteId);
        Database.executeBatch(batch1);
        Test.stopTest();
        List<SBQQ__Quote__c> updatedQuotes = [SELECT Id, PMC_CLM_ContractCreated__c FROM SBQQ__Quote__c WHERE PMC_CLM_ContractCreated__c =: true];
        System.assertEquals(3, updatedQuotes.size(),'Contract not created');
        }
    }
}