objects/Contract.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Contract_Blocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If new contract created by Block/Replace Button then this field will be checked</description>
        <label>Contract Blocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Contract_Blocked__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To check the Contract Blocked</description>
        <label>Contract Blocked</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>CPQ Quotes (Contract Blocked)</relationshipLabel>
        <relationshipName>CPQ_Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/QuoteTriggerUpdateTest.cls
@isTest
public class QuoteTriggerUpdateTest {
    @isTest
    static void testQuoteTrigger() {
        // Start test context
        Test.startTest();
        User testUser = [SELECT Id FROM User WHERE IsActive = true LIMIT 1];
        
        // Create a Contract record to be ussed in the test
        Contract testContract = new Contract(
            Name = 'Test Contract',
            Status = 'Draft',OwnerId = testUser.Id
        );
        insert testContract;
 
        // Verify the PMC_CPQ_Contract_Blocked__c field is false by default
        testContract = [SELECT Id, PMC_CPQ_Contract_Blocked__c FROM Contract WHERE Id = :testContract.Id];
        System.assertEquals(false, testContract.PMC_CPQ_Contract_Blocked__c, 'Initial value of PMC_CPQ_Contract_Blocked__c should be false.');
 
        // Create a Quote record and associate it with the Contract
        SBQQ__Quote__c testQuote = new SBQQ__Quote__c( 
            SBQQ__Opportunity2__c = '006Ot000009JijKIAS',
            Contract_Blocked__c = testContract.Id,
            RecordTypeId = '012DT000003pPmoYAE');
        insert testQuote;
 
        // Verify that the Contract was updated by the trigger
        testContract = [SELECT Id, PMC_CPQ_Contract_Blocked__c FROM Contract WHERE Id = :testContract.Id];
        System.assertEquals(true, testContract.PMC_CPQ_Contract_Blocked__c, 'PMC_CPQ_Contract_Blocked__c should be updated to true.');
 
        // End test context
        Test.stopTest();
    }
}