objects/Contract.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_ContractNumberIdentifier__c</fullName>
        <description>This field will store the contract number(AutoNumber) which will be used as an External Id for 066I.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Contract Number Identifier</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_SAPOrderNumber__c</fullName>
        <description>This field captures the order number in SAP.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Reference Order Number in SAP.</inlineHelpText>
        <label>SAP Order Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <label>Approval Flow Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Under Revision</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                    <isActive>false</isActive>
                    <label>Recalled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_FPDPricefromPriceFx__c</fullName>
        <description>Created as part of GDASF-9360. This field captures the FPD price from Price Fx.</description>
        <inlineHelpText>The FPD List Price for the Order Product is only relevant when the contract type of the product is specified as FPD</inlineHelpText>
        <label>FPD List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_FinalAgreedPrice__c</fullName>
        <description>This field is will store the Final Agreed Price and send it back to SAP after the Order is placed.</description>
        <label>Final Agreed Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_LinePONumber__c</fullName>
        <description>This field will be used to capture the PO Number at a order line level - leveraged in the Contract Document forms for North America</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Purchase Order #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderItemIntegrationMessage__c</fullName>
        <description>The Integration message of external callout.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderItemIntegrationStatus__c</fullName>
        <description>This field captures the integration status of the Order product</description>
        <inlineHelpText>This field captures the integration status of the Order product</inlineHelpText>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderLineStatus__c</fullName>
        <label>Order Line Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Placed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Completely Shipped</fullName>
                    <isActive>false</isActive>
                    <label>Completely Shipped</label>
                </value>
                <value>
                    <fullName>Partially Shipped</fullName>
                    <isActive>false</isActive>
                    <label>Partially Shipped</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PricingDate__c</fullName>
        <description>This field captures Pricing date.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field captures the pricing date</inlineHelpText>
        <label>Price by Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Products (Ship To)</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contract of the subscription that is created from this order product.</description>
        <inlineHelpText>The contract of the subscription that is created from this order product.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>OrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/PMC_CPQ_Integration_Endpoint__mdt.object
<CustomObject>
    <description>This is used to store all External endpoints.</description>
    <fields>
        <fullName>PMC_CPQ_Endpoint__c</fullName>
        <description>This is used to store the Integration endpoint.</description>
        <label>Endpoint</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Integration Endpoint</label>
    <pluralLabel>Integration Endpoints</pluralLabel>
</CustomObject>

classes/PMC_CPQ_sendFPDOrderProductsSAPClass.cls
/**
* @description This class will be used to receive order products from fpdMassUpdate lightning web component and process it and send to SAP or receive
* price from PriceFX
* @storynumber GDASF-9421
*/
public with sharing class PMC_CPQ_sendFPDOrderProductsSAPClass {
    
    /**
* @description Common method to fetch OrderItems based on a list of IDs
* @param idOps - List of id for which the OrderItem record is to be returned
* @return - the result of the SOQL query
*/
    private static List<OrderItem> fetchOrderItems(List<Id> idOps) {
        return [SELECT Id, OrderItemNumber, Order.OrderNumber, SBQQ__Contract__r.PMC_CPQ_ContractNumberIdentifier__c, PMC_CPQ_LinePONumber__c, PMC_CPQ_ShipTo__r.Name, Order.Account.Name, Product2.Name, Quantity, PMC_CPQ_PricingDate__c,  PMC_CPQ_FPDPricefromPriceFx__c, PMC_CPQ_FinalAgreedPrice__c, PMC_CPQ_OrderLineStatus__c, PMC_CPQ_OrderItemIntegrationStatus__c,PMC_CPQ_OrderItemIntegrationMessage__c,Order.PMC_CPQ_SAPOrderNumber__c
                FROM OrderItem
                WHERE Id IN :idOps WITH SECURITY_ENFORCED];
    }
    
    /**
* @description This method will be used to send Order products to SAP with negotiated Final Agreed Price
* @param lstOlines - String of List of Order Products sent from LWC component
*/
    @AuraEnabled
    public static String saveOPFromUI(String lstOlines) {
        List<PMC_CPQ_OrderProductDetailsWrapperClass> params = (List<PMC_CPQ_OrderProductDetailsWrapperClass>)JSON.deserialize(lstOlines,List<PMC_CPQ_OrderProductDetailsWrapperClass>.class);
        List<Id> idOps = new List<Id>();
        for (PMC_CPQ_OrderProductDetailsWrapperClass wrapper : params) {
            idOps.add(wrapper.customId);
        }
        List<OrderItem> lstOP = fetchOrderItems(idOps);
        for (Integer i = 0; i < params.size(); i++) {
            lstOP[i].PMC_CPQ_FinalAgreedPrice__c = params[i].finalAgreedPrice;
        }
        
        try {
            if (Schema.sObjectType.OrderItem.isAccessible() &&
                Schema.sObjectType.OrderItem.isUpdateable() &&
                Schema.SObjectType.OrderItem.fields.PMC_CPQ_FinalAgreedPrice__c.isUpdateable()) {
                    update lstOP;
                }
        } catch (DmlException objException) {
            PMC_ErrorLogClass.processException(objException);
            return 'Error saving Order Products : ' + objException.getMessage();
        }
       return  sendOrderProductsToSAP(lstOP);
    }
    
    /**
* @description This method will be used to send Order products to SAP with negotiated Final Agreed Price and this function will block to send to SAP if Order products status is Under Revision and Rejected
* @param lstOP - List of Order Products
*/
    @AuraEnabled
    public static String sendOrderProductsToSAP(List<OrderItem> lstOP) {
        //GCPM-2008 - SAA Start
        PMC_CPQ_FPDActionClass objRef = new PMC_CPQ_FPDActionClass(lstOP,true);
        List<OrderItem> lstOrdItemApp = [Select id,ApprovalStatus__c,PMC_CPQ_OrderItemIntegrationMessage__c from OrderItem where ID IN :lstOP];
        List<OrderItem> lstToUpdateIntegration = new List<OrderItem>();
        String message = '';
        for(OrderItem lstOrdItem : lstOrdItemApp){
            String test = lstOrdItem.ApprovalStatus__c;
            {
                if(lstOrdItem.ApprovalStatus__c != 'Under Revision' && lstOrdItem.ApprovalStatus__c != 'Rejected')
                {
                    objRef.bulkSendFPDtoSAPRequest(lstOP);
                }
                else
                {
                    lstOrdItem.PMC_CPQ_OrderItemIntegrationMessage__c = 'Approval Require';
                    lstToUpdateIntegration.add(lstOrdItem);
                }
            }
        }
        try{
            if(!lstToUpdateIntegration.isEmpty())
            {
                update lstToUpdateIntegration;
                message = 'Some Selected Orders have been sent to PM for approval.';
            }
        }
        catch (DmlException e){
            message = 'Error Updating Order Item : ' + e.getMessage();
            PMC_ErrorLogClass.processException(e);
        }
        return message;
        
        //GCPM-2008 - SAA End
    }
    
    /**
* @description This method will be used to receive the latest price of selected order products from the Price FPD Order Line tab
* @param lstOlines - String of List of Order Products sent from LWC component
*/
    @AuraEnabled
    public static void getPriceFromPriceFX(String lstOlines) {
        List<PMC_CPQ_OrderProductDetailsWrapperClass> params = (List<PMC_CPQ_OrderProductDetailsWrapperClass>)JSON.deserialize(lstOlines,List<PMC_CPQ_OrderProductDetailsWrapperClass>.class);
        List<Id> idOps = new List<Id>();
        for (PMC_CPQ_OrderProductDetailsWrapperClass wrapper : params) {
            idOps.add(wrapper.customId);
        }
        List<OrderItem> lstOP = fetchOrderItems(idOps);
        PMC_CPQ_GetFPDController objRef1 = new PMC_CPQ_GetFPDController(lstOP,true);
        objRef1.bulkGetFPDRequest(lstOP);
    }
    
    /**
* @description This method will retrieve the interface url from the PMC_CPQ_Integration_Endpoint__mdt
* @return endpoint- the interface URL string
*/
   @AuraEnabled(cacheable = true)
    public static string sendFPDPriceFXURL(){
        String strInterface = 'SendFPD';
        PMC_CPQ_Integration_Endpoint__mdt strIntegrationEndpointRecord = PMC_CPQ_Integration_Endpoint__mdt.getInstance(strInterface); 
        String endpoint = JSON.serialize(strIntegrationEndpointRecord.PMC_CPQ_Endpoint__c);
        return endpoint;
    }
}