objects/CustomSalesAgreement__c.object
<CustomObject>
    <fields>
        <fullName>SalesAgreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Agreement</label>
        <referenceTo>SalesAgreement</referenceTo>
        <relationshipLabel>Custom Sales Agreements</relationshipLabel>
        <relationshipName>Custom_Sales_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Custom Sales Agreement</label>
    <nameField>
        <displayFormat>CSA-{0000}</displayFormat>
        <label>Sales Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Sales Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IncentiveData__c.object
<CustomObject>
    <fields>
        <fullName>CustomSalesAgreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Custom Sales Agreement</label>
        <referenceTo>CustomSalesAgreement__c</referenceTo>
        <relationshipLabel>Incentive Data</relationshipLabel>
        <relationshipName>Incentive_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ForecastTons__c</fullName>
        <label>Forecast Tons</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IndividualIncentive__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Individual Incentive $/ST</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PortfolioIncentives__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Portfolio Incentives $/ST</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_SS_ProductFamilies</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Threshold__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Threshold</label>
        <type>TextArea</type>
    </fields>
    <label>Incentive Data</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Incentive Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incentive Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProgramRebateType.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ZRS6</fullName>
                    <label>Blended</label>
                </value>
                <value>
                    <fullName>Cultivar - Performa</fullName>
                </value>
                <value>
                    <fullName>Cultivar - Performa Bio</fullName>
                </value>
                <value>
                    <fullName>Cultivar - Performance</fullName>
                </value>
                <value>
                    <fullName>Cultivar - Volume</fullName>
                </value>
                <value>
                    <fullName>ZRS3</fullName>
                    <label>Growth</label>
                </value>
                <value>
                    <fullName>ZRS1</fullName>
                    <label>Individual</label>
                </value>
                <value>
                    <fullName>ZRS2</fullName>
                    <label>Portfolio</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RebateProgram.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_SalesAgreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Sales Agreement</description>
        <label>Sales Agreement</label>
        <referenceTo>SalesAgreement</referenceTo>
        <relationshipLabel>Rebate Programs</relationshipLabel>
        <relationshipName>Rebate_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/PMC_SS_ProductFamilies.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ASPIRE</fullName>
    </customValue>
    <customValue>
        <fullName>ATHOS</fullName>
    </customValue>
    <customValue>
        <fullName>BASICA</fullName>
    </customValue>
    <customValue>
        <fullName>BIOSCIENCE</fullName>
    </customValue>
    <customValue>
        <fullName>BLENDS</fullName>
    </customValue>
    <customValue>
        <fullName>BORON</fullName>
    </customValue>
    <customValue>
        <fullName>CO-PRODUCT</fullName>
    </customValue>
    <customValue>
        <fullName>DAP-MAP</fullName>
    </customValue>
    <customValue>
        <fullName>EXCELLEN</fullName>
    </customValue>
    <customValue>
        <fullName>FEED</fullName>
    </customValue>
    <customValue>
        <fullName>FLUOSILIC ACID</fullName>
    </customValue>
    <customValue>
        <fullName>GRAVEL</fullName>
    </customValue>
    <customValue>
        <fullName>GYPSUM</fullName>
    </customValue>
    <customValue>
        <fullName>K-MAG</fullName>
    </customValue>
    <customValue>
        <fullName>LIMESTONE</fullName>
    </customValue>
    <customValue>
        <fullName>LIQUID FERT</fullName>
    </customValue>
    <customValue>
        <fullName>MES</fullName>
    </customValue>
    <customValue>
        <fullName>MES BLENDS</fullName>
    </customValue>
    <customValue>
        <fullName>MICRO</fullName>
    </customValue>
    <customValue>
        <fullName>MKP</fullName>
    </customValue>
    <customValue>
        <fullName>MOP</fullName>
    </customValue>
    <customValue>
        <fullName>MPASTO</fullName>
    </customValue>
    <customValue>
        <fullName>N BLENDS</fullName>
    </customValue>
    <customValue>
        <fullName>NITROGEN</fullName>
    </customValue>
    <customValue>
        <fullName>NPK</fullName>
    </customValue>
    <customValue>
        <fullName>NPK BLENDS</fullName>
    </customValue>
    <customValue>
        <fullName>P BLENDS</fullName>
    </customValue>
    <customValue>
        <fullName>PERFORMA BIO</fullName>
    </customValue>
    <customValue>
        <fullName>PERFORMA BLENDS</fullName>
    </customValue>
    <customValue>
        <fullName>P FERTILIZER</fullName>
    </customValue>
    <masterLabel>Product Families</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/CreateCustomSalesAgreement.cls
public class CreateCustomSalesAgreement {
    
    public static void createCustomSalesAgreement(Id salesAgreementId){
        //SalesAgreement sa = [Select name, account.name , StartDate, EndDate From SalesAgreement WHERE id =:salesAgreementId];
        CustomSalesAgreement__c csa = new CustomSalesAgreement__c();
        csa.SalesAgreement__c = salesAgreementId;
        insert csa;
        SalesAgreementProduct sap = [SELECT Product.PMC_CPQ_ProductFamily__c,TotalForecastedQuantity from  SalesAgreementProduct where SalesAgreementId = :salesAgreementId];
		IncentiveData__c incData =  new IncentiveData__c();
        incData.CustomSalesAgreement__c = csa.id;
        incData.Product_Family__c = sap.Product.PMC_CPQ_ProductFamily__c;
        incData.ForecastTons__c = sap.TotalForecastedQuantity;
        RebateProgram rp = [SELECT name,id from RebateProgram where PMC_SS_SalesAgreement__c = :salesAgreementId];
        List<ProgramRebateType> programRebateTypeRecs = [select id,PMC_SS_Type__c from ProgramRebateType where RebateProgramId = :rp.id];
        Set<ID> programRebateTypeIDs = new Set<Id>();
        for(ProgramRebateType prt: programRebateTypeRecs){
            programRebateTypeIDs.add(prt.id);
        }
        System.debug('programRebateTypeIDs:: '+programRebateTypeIDs);
        List<Decimal> thresholdValues = new List<Decimal>();
        Map<Decimal,Decimal> threshold_IndvIncentiveValues = new Map<Decimal,Decimal>();
        Map<Decimal,Decimal> threshold_PortfolioIncentiveValues = new Map<Decimal,Decimal>();
        List<ProgramRebateTypeBenefit> rbtb = [Select id,MinimumQualifyingValue,BenefitValue,ProgramRebateType.PMC_SS_Type__c from ProgramRebateTypeBenefit where ProgramRebateTypeId in :programRebateTypeIDs];  
        for(ProgramRebateTypeBenefit prtbrec: rbtb){
            
            if(prtbrec.ProgramRebateType.PMC_SS_Type__c == 'Individual'){
               thresholdValues.add(prtbrec.MinimumQualifyingValue);
                threshold_IndvIncentiveValues.put(prtbrec.MinimumQualifyingValue,prtbrec.BenefitValue);
            }
            if(prtbrec.ProgramRebateType.PMC_SS_Type__c == 'Portfolio'){
                threshold_PortfolioIncentiveValues.put(prtbrec.MinimumQualifyingValue,prtbrec.BenefitValue);
            } 
            
        }
        thresholdValues.sort();
        String thresholdFinal='';
        String indvIncentiveValues = '';
        String portIncentiveValues = '';
        for(Integer i = thresholdValues.size()-1 ; i>=0;i-- ){
            thresholdFinal = thresholdFinal+ '\n'+thresholdValues[i]+'+';
            indvIncentiveValues = indvIncentiveValues+'\n$'+threshold_IndvIncentiveValues.get(thresholdValues[i]);
            portIncentiveValues = portIncentiveValues+'\n$'+threshold_PortfolioIncentiveValues.get(thresholdValues[i]);
        }
        System.debug('thresholdFinal:: '+thresholdFinal);
        incData.Threshold__c = thresholdFinal;
        incData.IndividualIncentive__c = indvIncentiveValues;
        incData.PortfolioIncentives__c = portIncentiveValues;
		insert incData;    
    }
        

}