objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>PMC_SS_EndDate__c</fullName>
        <formula>IF( ISPICKVAL( PublishStatus , &apos;Online&apos;) , LastPublishedDate +  PMC_SS_NumberOfDisplayDays__c
, null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_SS_Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
    <recordTypes>
        <fullName>PMC_SS_TechnicalBulletinNotice</fullName>
        <active>true</active>
        <description>Technical document informing users about important events (e.g. System Issues, Planned down times).</description>
        <label>Technical Bulletin/Notice</label>
    </recordTypes>
</CustomObject>

classes/PMC_SS_ArchiveKnowledgeArticleBatch.cls
/**
* @description This class will be used archive Bulletin article post end date.
* @author Vedashri
* @storynumber GDASF-2189
*/
public with sharing class PMC_SS_ArchiveKnowledgeArticleBatch implements Database.Batchable<SObject> {
    //variable for article query
    public String strDynamicQuery;
    private final String techBulletinRecordType = 'PMC_SS_TechnicalBulletinNotice';
    private final String onlineStatus = 'Online';
    private final String draftStatus = 'Draft';

    /**
    * @description This is constructor to set query string
    */
    public PMC_SS_ArchiveKnowledgeArticleBatch() {
        strDynamicQuery ='SELECT KnowledgeArticleId,Id,PMC_SS_Region__c, PublishStatus FROM Knowledge__kav WHERE RecordType.DeveloperName=\''+techBulletinRecordType+'\' and PublishStatus =\''+onlineStatus+'\'';
        strDynamicQuery = Test.isRunningTest() ? strDynamicQuery : strDynamicQuery+ ' AND PMC_SS_EndDate__c < TODAY';
       
    }

    /**
    * @description This is start method of batch to archive article
    * @param objBtachContext - this object is used to track batch process 
    * @return Database.QueryLocator - This will send article to execute method
    */
    public Database.QueryLocator start(Database.BatchableContext objBtachContext){
        User usr=[Select Id,Name from User where Id =:UserInfo.getuserId()];
        system.debug('Logged in User'+usr);
         return Database.getQueryLocator(strDynamicQuery);
    }

    /**
    * @description  This is executable method of batch to archive article
    * @param objBtachContext - this object is used to track batch process 
    * @param lstKnowledgeToArchive - List of article to be archived
    */
    public void execute(Database.BatchableContext objBtachContext, List<Knowledge__kav> lstKnowledgeToArchive) {
        
        Map<Id,Knowledge__kav> mapArticleToArchive = new Map<Id,Knowledge__kav>();

        for(Knowledge__kav objKnowledge :lstKnowledgeToArchive ) {
            mapArticleToArchive.put(objKnowledge.KnowledgeArticleId,objKnowledge);                                 
        }
        
        for(Knowledge__kav objKnowledge : [SELECT KnowledgeArticleId FROM Knowledge__kav WHERE KnowledgeArticleId IN : mapArticleToArchive.keyset() AND PublishStatus =: draftStatus] ) {
    
            mapArticleToArchive.remove(objKnowledge.KnowledgeArticleId);                               
        }

        if(!mapArticleToArchive.isEmpty()) {
            for(Knowledge__kav objKnowledge :mapArticleToArchive.values()) {
            
                KbManagement.PublishingService.archiveOnlineArticle(objKnowledge.KnowledgeArticleId,null);
            }
        }
    }
    /**
    * @description  This is finish method of batch to archive article
    * @param objBtachContext - this object is used to track batch process 
    */
    public void finish(Database.BatchableContext objBtachContext){
        Boolean isBatchSuccess = true;
        if(Test.isRunningTest())
        {
            isBatchSuccess = false;
        }
    }


}