objects/Location.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Plant__c</fullName>
        <description>Indicates Plant Number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Plant</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to store the Ship to Account</description>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations (Ship To Account)</relationshipLabel>
        <relationshipName>Locations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SoldToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to store the Sold to Account</description>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations(Sold To Account)</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_ShipToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to reference Shipping account.</description>
        <inlineHelpText>Ship To Account for the order.</inlineHelpText>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Ship To Account)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SoldToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture Sold To Account for the Order.</description>
        <inlineHelpText>Sold To Account for the Order.</inlineHelpText>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_CPQ_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_BillToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Delivery__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Delivery associated to this invoice.</description>
        <label>Delivery</label>
        <referenceTo>Shipment</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ParentInvoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Invoice</label>
        <referenceTo>PMC_CPQ_Invoice__c</referenceTo>
        <relationshipLabel>Related Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SoldToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices (Sold To)</relationshipLabel>
        <relationshipName>PMC_CPQ_SoldToInvoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_TotalInvoiceValue__c</fullName>
        <label>Total Invoice Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_CPQ_ProductLocation__c.object
<CustomObject>
    <description>This object is created as a part of  story to capture product and location data.</description>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created  to check the location details.</description>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Product Locations</relationshipLabel>
        <relationshipName>ProductLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipment.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ContractNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Number</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_DeliveryItemID__c</fullName>
        <description>This field captures the delivery Item ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Delivery Item ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_DeliveryItemName__c</fullName>
        <description>This field captures the delivery Item Name</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Delivery Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_DeliveryQuantity__c</fullName>
        <description>This field captures the delivery Delivery Quantity.</description>
        <label>Delivery Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ModeofTransportation__c</fullName>
        <inlineHelpText>Select the appropriate mode from the available options to track and manage logistics effectively.</inlineHelpText>
        <label>MOT</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_MoT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field captures the Order Number.</description>
        <label>Order Number</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OriginLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The plant location associated to this delivery</description>
        <label>Origin Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PlantID__c</fullName>
        <description>This field captures the  Plant ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Plant ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deliveries (Ship To Account)</relationshipLabel>
        <relationshipName>Deliveries1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deliveries (Ship To)</relationshipLabel>
        <relationshipName>Deliveries2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShippedDate__c</fullName>
        <description>This field captures the shipped  Date.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipped Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_UoMUnitofMeasure__c</fullName>
        <description>This field captures the uom of Measure.</description>
        <inlineHelpText>Specify the unit in which the value of this field will be measured</inlineHelpText>
        <label>UoM Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_SS_UnitOfMeasure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_VehicleID__c</fullName>
        <description>This field captures the vehicle Vehicle ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ShipmentItem.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_DeliveryItemID__c</fullName>
        <description>This field captures the delivery Item ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SAP Delivery Item ID</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PMC_CPQ_DeliveryItemName__c</fullName>
        <description>This field captures the delivery Item Name.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Delivery Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_DeliveryQuantity__c</fullName>
        <description>This field captures the delivery Delivery Quantity.</description>
        <label>Delivery Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ModeofTransportation__c</fullName>
        <inlineHelpText>Select the appropriate mode from the available options to track and manage logistics effectively</inlineHelpText>
        <label>MOT</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_MoT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field captures the order Order Item.</description>
        <label>Order Item</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Delivery Items</relationshipLabel>
        <relationshipName>Delivery_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PlantID__c</fullName>
        <description>This field captures the  Plant ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Plant ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Location</label>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Delivery Lines</relationshipLabel>
        <relationshipName>Delivery_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShippedDate__c</fullName>
        <description>This field captures the shipped  Date.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipped Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_UnitofMeasure__c</fullName>
        <description>This field captures the uom of Measure.</description>
        <inlineHelpText>Specify the unit in which the value of this field will be measured.</inlineHelpText>
        <label>UoM Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_SS_UnitOfMeasure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_VehicleID__c</fullName>
        <description>This field captures the vehicle Vehicle ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/PMC_CPQ_MoT.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Barge</fullName>
    </customValue>
    <customValue>
        <fullName>Container</fullName>
    </customValue>
    <customValue>
        <fullName>Rail</fullName>
    </customValue>
    <customValue>
        <fullName>Truck</fullName>
    </customValue>
    <customValue>
        <fullName>Vessel</fullName>
    </customValue>
    <description>This is created to hold mode of Transportation value sets</description>
    <masterLabel>MoT</masterLabel>
</GlobalValueSet>

classes/PMC_SS_CaseDisputeManagementCtrl.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 08-28-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class PMC_SS_CaseDisputeManagementCtrl {

    /**
     * @description - Method used to fetch the Order Details
     * @param strOrderId - Order Id
     * @return OrderDetailsWrapper - Returns Wrapper of type OrderDetailsWrapper
     */

    @AuraEnabled(cacheable=true)
    public static PMC_SS_CaseDisputeManagementWrappers.OrderDetailsWrapper getOrderItems(String strOrderId){
        try {
            Order objOrder = [SELECT Id, AccountId, Account.Name, ContractId, Contract.ContractNumber,BillToContactId,BillToContact.Name,
                                    PMC_CPQ_ShipToAccount__c, PMC_CPQ_ShipToAccount__r.Name, PMC_CPQ_SoldToAccount__c, PMC_CPQ_SoldToAccount__r.Name,
                                    (SELECT Id, OrderItemNumber, OrderId, UnitPrice, PMC_CPQ_ProductLocation__c,PMC_CPQ_ShipTo__c,PMC_CPQ_ShipTo__r.Name, PMC_CPQ_ProductLocation__r.PMC_CPQ_Location__c, 
                                     PMC_CPQ_ProductLocation__r.PMC_CPQ_Location__r.PMC_CPQ_Plant__c, Product2.Name, Product2Id
                                     FROM OrderItems),
                                    (SELECT Id, ShipmentNumber,PMC_CPQ_UoMUnitofMeasure__c, PMC_CPQ_DeliveryQuantity__c, PMC_CPQ_OriginLocation__c,
                                     	PMC_CPQ_OriginLocation__r.Name, DestinationLocationId, DestinationLocation.Name, PMC_CPQ_ShippedDate__c,
                                     	PMC_CPQ_VehicleID__c
                                     	FROM Deliveries__r),
                                    (SELECT Id, Name, PMC_CPQ_Contact__c, PMC_CPQ_Contact__r.Name, PMC_CPQ_TotalInvoiceValue__c, PMC_CPQ_OrderProduct__c
                                       FROM Invoices__r)
                                    FROM Order                                       
                                    WHERE Id =: strOrderId 
                                    WITH SECURITY_ENFORCED];

            if(objOrder != null) {
                PMC_SS_CaseDisputeManagementWrappers.OrderDetailsWrapper objOrderDetailsWrapper = new PMC_SS_CaseDisputeManagementWrappers.OrderDetailsWrapper();
                objOrderDetailsWrapper.objOrder = objOrder;

                PMC_SS_ObjectDetailsWrapper objAccountWrapper = new PMC_SS_ObjectDetailsWrapper(objOrder.AccountId, objOrder.Account.Name);
                objOrderDetailsWrapper.objAccountWrapper = objAccountWrapper;

                PMC_SS_ObjectDetailsWrapper objContractWrapper = new PMC_SS_ObjectDetailsWrapper(objOrder.ContractId, objOrder.Contract.ContractNumber);
                objOrderDetailsWrapper.objContractWrapper = objContractWrapper;

                
                PMC_SS_ObjectDetailsWrapper objSoldToAccountWrapper = new PMC_SS_ObjectDetailsWrapper(objOrder.PMC_CPQ_SoldToAccount__c, objOrder.PMC_CPQ_SoldToAccount__r.Name);
                objOrderDetailsWrapper.objSoldToAccountWrapper = objSoldToAccountWrapper;
                
                //PMC_SS_ObjectDetailsWrapper objShipToAccountWrapper = new PMC_SS_ObjectDetailsWrapper(objOrder.PMC_CPQ_ShipToAccount__c, objOrder.PMC_CPQ_ShipToAccount__r.Name);
                //objOrderDetailsWrapper.objShipToAccountWrapper = objShipToAccountWrapper;

                objOrderDetailsWrapper.lstOrderItems = objOrder.OrderItems;
                objOrderDetailsWrapper.lstInvoices = objOrder.Invoices__r;
                objOrderDetailsWrapper.lstDeliveries = objOrder.Deliveries__r;

                return objOrderDetailsWrapper; 
            }
        } 
        catch (Exception e) {
        //throw new AuraHandledException(e.getMessage());
        system.debug('Exception occured'+e);
        }
        
        return null;
    }

    /**
     * @description - Method used to fetch the delivery item Details
     * @param strOrderItemId - Order Item Id
     * @return List<ShipmentItem> - Returns List of Shipment Items
     */
    @AuraEnabled(cacheable=true)
    public static List<ShipmentItem> getDeliveryItems(String strOrderItemId){
        
            return [SELECT Id, PMC_CPQ_OrderProduct__c, ShipmentItemNumber, PMC_CPQ_DeliveryItemName__c,  PMC_CPQ_DeliveryItemID__c,
                    PMC_CPQ_ModeofTransportation__c, PMC_CPQ_PlantID__c, PMC_CPQ_VehicleID__c, PMC_CPQ_ShippedDate__c, Product2.Name,
                    PMC_CPQ_UnitofMeasure__c,PMC_CPQ_DeliveryQuantity__c,ShipmentId
                    FROM ShipmentItem                                           
                    WHERE PMC_CPQ_OrderProduct__c =: strOrderItemId 
                    WITH SECURITY_ENFORCED];                    
    }
    
    
    /**
     * @description - Method used to fetch the contract Details
     * @param strAccountId - Account Id
     * @return List<Contract> - Returns List of Contract
     */
    @AuraEnabled(cacheable=true) 
    public static List<Contract> getContracts(String strAccountId) {
        try {
            Account objAccount = [SELECT Id, (SELECT Id, ContractNumber FROM Contracts) FROM Account WHERE Id =: strAccountId WITH SECURITY_ENFORCED LIMIT 1];
            return objAccount.Contracts;
        }
        catch(Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

     /**
     * @description - Method used to fetch picklist values Case Object details
     * @param strObjApiName - Object API Name
     * @param strFieldName - Field Name
     * @return List<Map<String, String>> - Map with details
     */
    @AuraEnabled
    public static List<Map<String, String>> getPickListValues(String strObjApiName, String strFieldName) {
        List<Map<String, String>> lstOptions = new List <Map<String, String>>();
        Schema.SObjectType objType = Schema.getGlobalDescribe().get(strObjApiName);
        if (objType == null) {
            return lstOptions;
        }
        Schema.DescribeSObjectResult sobjectDescribe = objType.getDescribe(SObjectDescribeOptions.DEFERRED);
        Map<String, Schema.SObjectField> mapField = sobjectDescribe.fields.getMap();
        if (mapField.get(strFieldName) == null) {
            return lstOptions;
        }
        List <Schema.PicklistEntry> pickListValues = mapField.get(strFieldName).getDescribe().getPickListValues();
        for (Schema.PicklistEntry f: pickListValues) {
            Map<String, String> mapValues = new Map<String, String> {
                'label' => f.getLabel(),
                'value' => f.getValue()
            };
            lstOptions.add(mapValues);
        }
        return lstOptions;
    }

    /**
     * @description - Method used to upload a document on Case
     * @param strBase64 - File Data
     * @param strFilename - File Name
     * @param strRecordId - Case Record Idd
     * @return String - Returns content document id
     */ 
    @AuraEnabled
    public static String uploadFile(String strBase64, String strFilename, String strRecordId) {
        ContentVersion objContentVersion = createContentVersion(strBase64, strFilename);
        ContentDocumentLink objContentDocLink = createContentLink(objContentVersion.Id, strRecordId);
        if (objContentVersion == null || objContentDocLink == null) {
            return null; 
        }
        return objContentDocLink.Id;
    } 
    
    /**
     * @description - Method used to prepare ContentVersion
     * @param strBase64 - File Data
     * @param strFilename - File Name
     * @return ContentVersion - Returns content document id
     */
    private static ContentVersion createContentVersion(String strBase64, String strFilename) {
        ContentVersion objContentVersion = new ContentVersion();
        objContentVersion.VersionData = EncodingUtil.base64Decode(strBase64);
        objContentVersion.Title = strFilename;
        objContentVersion.PathOnClient = strFilename;
        try {
            if(ContentVersion.sObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).isCreateable()) {
                insert objContentVersion;
                return objContentVersion;

            }
        } 
        catch(DMLException e) {
            throw new AuraHandledException(e.getMessage());
        }
        
        return null;
    }
    
    /**
     * @description - Method used to prepare ContentDocumentLink
     * @param strContentVersionId - Content Version Id
     * @param strRecordId - Case Record Idd
     * @return ContentDocumentLink - Returns content document Link id
     */
    private static ContentDocumentLink createContentLink(String strContentVersionId, String strRecordId) {
        if (strContentVersionId == null || strRecordId == null) { 
            return null; 
        }
        
        ContentDocumentLink objContentDocLink = new ContentDocumentLink();
            
        objContentDocLink.ContentDocumentId = [SELECT ContentDocumentId 
                                 FROM ContentVersion 
                                 WHERE Id =: strContentVersionId WITH SECURITY_ENFORCED
            					].ContentDocumentId;
        
        objContentDocLink.LinkedEntityId = strRecordId;
        objContentDocLink.ShareType = 'V';
        try {
            if(ContentDocumentLink.sObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).isCreateable()) {
                insert objContentDocLink;
                return objContentDocLink;
            }
        } 
        catch(DMLException e) { throw new AuraHandledException(e.getMessage());
        }
        return null;
    }
}