objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Budget_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Budget Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Discovery_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Discovery Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_SS_AccountManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Main point-of-contact/Account Manager working the Opportunity</description>
        <label>Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_SS_ActualCloseDate__c</fullName>
        <description>This field tracks the date on which the opportunity is won or not won.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Actual Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_SS_DaysOpen__c</fullName>
        <description>This field contains the days an opportunity has been opened.</description>
        <formula>TODAY() - DATEVALUE( CreatedDate)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Open</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_SS_Details__c</fullName>
        <description>Additional details that Sales team can be provide</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Additional Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PMC_SS_LeadType__c</fullName>
        <description>Type of leads available</description>
        <label>Lead Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Crop Consultant</fullName>
                </value>
                <value>
                    <fullName>Grower</fullName>
                </value>
                <value>
                    <fullName>Retailer - Agrnomist</fullName>
                </value>
                <value>
                    <fullName>Retailer - Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_MainCompetitors__c</fullName>
        <description>This field stores the main competitor(s) of the company for this opportunity.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Main Competitor(s)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SS_NeedsEndsDate__c</fullName>
        <description>Timeline in which customer needs products ends</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Needs End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_SS_NeedsStartDate__c</fullName>
        <description>Timeline in which customer needs products starts</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Needs Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_SS_OpportunitySource__c</fullName>
        <description>This is the source of the Opportunity to indicate where the Opportunity comes from.</description>
        <label>Opportunity Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cold Call</fullName>
                </value>
                <value>
                    <fullName>Company Inbox</fullName>
                </value>
                <value>
                    <fullName>Cross-Selling - Aftermarket</fullName>
                </value>
                <value>
                    <fullName>Cross-Sellin - Rental</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Personal Visit</fullName>
                </value>
                <value>
                    <fullName>Phone Call</fullName>
                </value>
                <value>
                    <fullName>Public Relation</fullName>
                </value>
                <value>
                    <fullName>Recommendation</fullName>
                </value>
                <value>
                    <fullName>Trade Show</fullName>
                </value>
                <value>
                    <fullName>Web</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Main point-of-contact at the Customer</description>
        <inlineHelpText>This field will only show ACTIVE contacts. Inactive contacts can be accessed from Global Search.</inlineHelpText>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.PMC_SS_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_SS_ProductFamilies__c</fullName>
        <description>Indicates the product families of the Opportunity</description>
        <label>Product Families</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_SS_ProductFamilies</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_ReasonLost__c</fullName>
        <description>This is the reason why the Opportunity was lost.</description>
        <label>Reason Lost</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery Timing</fullName>
                </value>
                <value>
                    <fullName>Desired Product Unavailable</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>Incorrect Season</fullName>
                </value>
                <value>
                    <fullName>Insufficient Customer Credit</fullName>
                </value>
                <value>
                    <fullName>Lost to Competitor</fullName>
                </value>
                <value>
                    <fullName>Misexecution</fullName>
                </value>
                <value>
                    <fullName>No Budget / Lost Funding</fullName>
                </value>
                <value>
                    <fullName>No Decision / Non-Responsive</fullName>
                </value>
                <value>
                    <fullName>No Longer Interested</fullName>
                </value>
                <value>
                    <fullName>No Quotation</fullName>
                </value>
                <value>
                    <fullName>Not Ready For Purchase</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Product Unable to Meet Customer Needs</fullName>
                </value>
                <value>
                    <fullName>Will Consider Next Season</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__AmendedContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the relationship to your Amended Contract.</description>
        <inlineHelpText>Lookup to your Amended Contract.</inlineHelpText>
        <label>Amended Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Amendment Opportunities</relationshipLabel>
        <relationshipName>AmendmentOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Contracted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal flag used to kick off automatic asset and subscription conversion.</description>
        <inlineHelpText>Salesforce CPQ uses this field to automatically convert assets and subscriptions.</inlineHelpText>
        <label>Contracted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__CreateContractedPrices__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select this checkbox to create Contracted Prices without creating a Contract.</description>
        <inlineHelpText>Select this checkbox to create Contracted Prices without creating a Contract.</inlineHelpText>
        <label>Create Contracted Prices</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__OrderGroupID__c</fullName>
        <description>The unique identifier for the Amend:Re-Quote transaction, which is the original primary quote&apos;s ID. This is not a reference.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The unique identifier for the Amend:Re-Quote transaction, which is the original primary quote&apos;s ID.</inlineHelpText>
        <label>Order Group ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal flag that drives automatic order creation.</description>
        <inlineHelpText>Select this checkbox to automatically create an order from the primary quote.</inlineHelpText>
        <label>Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryQuote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points to primary quote on this opportunity.</description>
        <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
        <label>Primary Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>PrimaryOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuotePricebookId__c</fullName>
        <description>Custom pricebook ID field that updates the standard Pricebook2Id field. Use to automatically drive pricebook selection from workflow rules.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Quote Pricebook Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates this opportunity is a renewal opportunity.</description>
        <inlineHelpText>Indicates this opportunity is a renewal opportunity.</inlineHelpText>
        <label>Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewedContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract being renewed by this renewal opportunity. In case opportunity rolls up several contracts this points at the master contract.</description>
        <inlineHelpText>Contract being renewed by this renewal opportunity. If the several contracts roll up to this opportunity, this points at the master contract.</inlineHelpText>
        <label>Renewed Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>RenewalOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sbaa__ApprovalStatus__c</fullName>
        <description>Overall Approval Status for this Opportunity</description>
        <inlineHelpText>Overall Approval Status for this Opportunity</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sbaa__ApprovalStep__c</fullName>
        <description>Used with Native Approvals to indicate the step in the approval process this Opportunity is in</description>
        <inlineHelpText>Used with Native Approvals to indicate the step in the approval process this Opportunity is in</inlineHelpText>
        <label>Approval Step</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sbaa__Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used with Native Approvers; indicates which Approver is responsible for approving the Opportunity.</description>
        <inlineHelpText>Used with Native Approvers; indicates which Approver is responsible for approving the Opportunity.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/PMC_SS_ProductFamilies.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ASPIRE</fullName>
    </customValue>
    <customValue>
        <fullName>ATHOS</fullName>
    </customValue>
    <customValue>
        <fullName>BASICA</fullName>
    </customValue>
    <customValue>
        <fullName>BIOSCIENCE</fullName>
    </customValue>
    <customValue>
        <fullName>BLENDS</fullName>
    </customValue>
    <customValue>
        <fullName>BORON</fullName>
    </customValue>
    <customValue>
        <fullName>CO-PRODUCT</fullName>
    </customValue>
    <customValue>
        <fullName>DAP-MAP</fullName>
    </customValue>
    <customValue>
        <fullName>EXCELLEN</fullName>
    </customValue>
    <customValue>
        <fullName>FEED</fullName>
    </customValue>
    <customValue>
        <fullName>FLUOSILIC ACID</fullName>
    </customValue>
    <customValue>
        <fullName>GRAVEL</fullName>
    </customValue>
    <customValue>
        <fullName>GYPSUM</fullName>
    </customValue>
    <customValue>
        <fullName>K-MAG</fullName>
    </customValue>
    <customValue>
        <fullName>LIMESTONE</fullName>
    </customValue>
    <customValue>
        <fullName>LIQUID FERT</fullName>
    </customValue>
    <customValue>
        <fullName>MES</fullName>
    </customValue>
    <customValue>
        <fullName>MES BLENDS</fullName>
    </customValue>
    <customValue>
        <fullName>MICRO</fullName>
    </customValue>
    <customValue>
        <fullName>MKP</fullName>
    </customValue>
    <customValue>
        <fullName>MOP</fullName>
    </customValue>
    <customValue>
        <fullName>MPASTO</fullName>
    </customValue>
    <customValue>
        <fullName>N BLENDS</fullName>
    </customValue>
    <customValue>
        <fullName>NITROGEN</fullName>
    </customValue>
    <customValue>
        <fullName>NPK</fullName>
    </customValue>
    <customValue>
        <fullName>NPK BLENDS</fullName>
    </customValue>
    <customValue>
        <fullName>P BLENDS</fullName>
    </customValue>
    <customValue>
        <fullName>PERFORMA BIO</fullName>
    </customValue>
    <customValue>
        <fullName>PERFORMA BLENDS</fullName>
    </customValue>
    <customValue>
        <fullName>P FERTILIZER</fullName>
    </customValue>
    <masterLabel>Product Families</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/PMC_SS_CloneOpportunityRecordClass.cls
/**
* @description This class will be used to clone the Opportunity Record and its related lists.
* @author Aditya R Achar
* @storynumber GPSSM-236
*/

public with sharing class PMC_SS_CloneOpportunityRecordClass {
    
    
    /**
* @description This method is invoked from the flow - PMC SS Clone Opportunity Record Flow.
* @param lstSelectedOpportunity - list of the selected opportunity records sent from the flow.
* @return This Method will return list of string used to check if the cloning was successful.
*/    
    @InvocableMethod
    public static List<String> cloneOpportunityRecords(List<Id> lstSelectedOpportunity){
        String strCheck = PMC_SS_CloneOpportunityRecordClass.cloneOpportunityDetails(lstSelectedOpportunity);
        return new List<String>{strCheck};
            }
    
    /**
* @description This method is used to clone the Details of the Opportunity record.
* @param lstSelectedOpportunity - list of the selected Opportunity records.
* @return This method will return a string that checks whether successfully cloned or not.
*/   
    public static String cloneOpportunityDetails(List<Id> lstSelectedOpportunity){
        Boolean boolCheck0 = false;
        Boolean relatedListInserted = false;
        String strMessage = 'Error';
        try {
            Opportunity objOpportunity = [SELECT PMC_SS_AccountManager__c, AccountId, PMC_SS_ActualCloseDate__c, PMC_SS_Details__c, SBQQ__AmendedContract__c, Amount, sbaa__ApprovalStatus__c, sbaa__ApprovalStep__c, sbaa__Approver__c, Budget_Confirmed__c, CloseDate, ContractId, SBQQ__Contracted__c, 
                                          SBQQ__CreateContractedPrices__c, CreatedById, PMC_SS_DaysOpen__c, Description, Discovery_Completed__c, ExpectedRevenue, ForecastCategoryName, LastModifiedById, LeadSource, PMC_SS_LeadType__c, PMC_SS_MainCompetitors__c, PMC_SS_NeedsEndsDate__c, 
                                          PMC_SS_NeedsStartDate__c, NextStep, CurrencyIsoCode, Name, OwnerId, PMC_SS_OpportunitySource__c, SBQQ__OrderGroupID__c, SBQQ__Ordered__c, PartnerAccountId, Pricebook2Id, CampaignId, PMC_SS_PrimaryContact__c, SBQQ__PrimaryQuote__c, IsPrivate, Probability, 
                                          PMC_SS_ProductFamilies__c, TotalOpportunityQuantity, SBQQ__QuotePricebookId__c, PMC_SS_ReasonLost__c, SBQQ__Renewal__c, SBQQ__RenewedContract__c, ROI_Analysis_Completed__c, PMC_SS_SMSOptOut__c, StageName, sbaa__StepApproved__c, sbaa__SubmittedDate__c, 
                                          sbaa__SubmittedUser__c, SyncedQuoteId, Type
                                          FROM Opportunity 
                                          WHERE Id IN :lstSelectedOpportunity WITH SECURITY_ENFORCED];
            if(Test.isRunningTest() && objOpportunity.name == 'test Opportunity Name1') {
                throw new DMLException('DML Exception');
            }
            Savepoint sp = Database.setSavepoint();
            //clone the selected opportunity record details with deep clone attribute as true.
            Opportunity objClonedOpportunity = objOpportunity.clone(false, true, false, false);
            Database.SaveResult sr = Database.insert(objClonedOpportunity,false);
            
            if(sr.isSuccess()){
                boolCheck0 = true;
                relatedListInserted = PMC_SS_CloneOpportunityRecordClass.cloneOpportunityRelatedLists(objOpportunity, objClonedOpportunity);
            }
            if(boolCheck0 && relatedListInserted){
                strMessage = 'Success';
            }else{
                Database.rollback(sp);
            }
            
        }catch(QueryException objQueryException) {
            PMC_ErrorLogClass.processException(objQueryException);
        }catch(DmlException objDmlException) {
            PMC_ErrorLogClass.processException(objDmlException);
        }
        return strMessage;
    }
    
    /** @description This method is used to clone the Opportunity related lists.
* @param objOpportunity - selected Opportunity record.
* @param objClonedOpportunity - cloned Opportunity object created in method cloneOpportunityDetails.
* @return This method returns a boolean that used to check for successfull cloning of Opportunity related lists.
*/  
    public static Boolean cloneOpportunityRelatedLists(Opportunity objOpportunity, Opportunity objClonedOpportunity){
        Boolean boolCheck1;
        Boolean boolCheck2;
        Boolean boolCheck3;
        Boolean boolCheck4;
        Boolean boolCheck5; 
        if (Test.isRunningTest()){
            PMC_SS_CloneOpportunityRecordHelperClass.boolTest = true;
        }
        boolCheck1 = PMC_SS_CloneOpportunityRecordHelperClass.cloneOpportunityContact(objOpportunity, objClonedOpportunity);
        boolCheck2 = PMC_SS_CloneOpportunityRecordHelperClass.cloneOpportunityTeamMember(objOpportunity, objClonedOpportunity);
        boolCheck3 = PMC_SS_CloneOpportunityRecordHelperClass.cloneOpportunityLineItem(objOpportunity, objClonedOpportunity);
        boolCheck4 = PMC_SS_CloneOpportunityRecordHelperClass.cloneContracts(objOpportunity, objClonedOpportunity);
        boolCheck5 = PMC_SS_CloneOpportunityRecordHelperClass.cloneQuotes(objOpportunity, objClonedOpportunity);
        if(boolCheck1 && boolCheck2 && boolCheck3 && boolCheck4 && boolCheck5){
            return true;
        }else{
            return false;
        }
    }
    
    
}