objects/Order.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Incoterms__c</fullName>
        <description>This field captures the user input for Incoterms.</description>
        <inlineHelpText>The rules and terms used in international and domestic trade contracts.</inlineHelpText>
        <label>Incoterms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_Incoterms1</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Incoterms__c</fullName>
        <description>This field captures the user input for Incoterms.</description>
        <label>Incoterms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_Incoterms1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ModeofTransportation__c</fullName>
        <description>This field captures the Mode of Transportation value.</description>
        <inlineHelpText>Mode of Transportation for this order line</inlineHelpText>
        <label>Mode of Transportation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_MoT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderLineStatus__c</fullName>
        <label>Order Line Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Placed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Completely Shipped</fullName>
                    <isActive>false</isActive>
                    <label>Completely Shipped</label>
                </value>
                <value>
                    <fullName>Partially Shipped</fullName>
                    <isActive>false</isActive>
                    <label>Partially Shipped</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PackageType__c</fullName>
        <description>The Packaging Type of the Product added to the quote.</description>
        <label>Packaging Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_PackagingType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ReasonOfRejectionOfItem__c</fullName>
        <description>This field indicates the Reason of Rejection of the Order</description>
        <label>Reason Of Rejection Of Item</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cust Initiated - Ordering Error</fullName>
                </value>
                <value>
                    <fullName>Cancellation Contract Expired</fullName>
                </value>
                <value>
                    <fullName>Supply/Availability</fullName>
                </value>
                <value>
                    <fullName>Rejected by workflow</fullName>
                </value>
                <value>
                    <fullName>Cust Initiated - Price Dispute</fullName>
                </value>
                <value>
                    <fullName>Volume low by Agronomic adjustments</fullName>
                </value>
                <value>
                    <fullName>CSR Initiated - Order Entry Error</fullName>
                </value>
                <value>
                    <fullName>Credit Management</fullName>
                </value>
                <value>
                    <fullName>Open Acct. vs Pre-Pay</fullName>
                </value>
                <value>
                    <fullName>Contract Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Shipment Diverted - Mosaic Request</fullName>
                </value>
                <value>
                    <fullName>Shipment Diverted - Customer Request</fullName>
                </value>
                <value>
                    <fullName>Carrier change</fullName>
                </value>
                <value>
                    <fullName>DH Cancellation</fullName>
                </value>
                <value>
                    <fullName>B2B Order Rejected</fullName>
                </value>
                <value>
                    <fullName>Canpotex Rejection</fullName>
                </value>
                <value>
                    <fullName>Order cannot be fulfilled</fullName>
                </value>
                <value>
                    <fullName>Reshipment</fullName>
                </value>
                <value>
                    <fullName>Diversion to New Customer</fullName>
                </value>
                <value>
                    <fullName>Deleted from SFDC via Amendment</fullName>
                </value>
                <value>
                    <fullName>Due to Complementary Invoice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_UnitOfMeasure__c</fullName>
        <label>Unit Of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_SS_UnitOfMeasure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote line where this order product is created from.</description>
        <inlineHelpText>The quote line where this order product is created from.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>OrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subscription created from this order product</description>
        <inlineHelpText>Subscription created from this order product</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>SubscriptionOrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/PMC_DH_DocumentType__mdt.object
<CustomObject>
    <description>Metadata for Document types</description>
    <fields>
        <fullName>PMC_DH_DocumentCode__c</fullName>
        <label>Document Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Digital Hub Document Type</label>
    <pluralLabel>Digital Hub Document Types</pluralLabel>
</CustomObject>

objects/PMC_DH_Quote_Management_Status__mdt.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_StatusLabel__c</fullName>
        <label>PMC_DH_StatusLabel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Quote Management Status</label>
    <pluralLabel>Quote Management Statuses</pluralLabel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_PackType__c</fullName>
        <description>This field is to display the pack type of the product</description>
        <label>Pack Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Packed</fullName>
                </value>
                <value>
                    <fullName>Bulk</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PackageType__c</fullName>
        <description>This field captures the package type for each product record</description>
        <inlineHelpText>This field captures the package type for each product record</inlineHelpText>
        <label>Packaging Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_PackagingType</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>PMC_CPQ_ModeofTransportation__c</fullName>
        <description>This field is created  to check The mode of transportation</description>
        <inlineHelpText>Select the appropriate mode from the available options to track and manage logistics effectively</inlineHelpText>
        <label>MoT</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PMC_CPQ_QuoteRecordType__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_MoT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PackType__c</fullName>
        <description>This field captures the Pack type of the product associated.</description>
        <label>Pack Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Packed</fullName>
                </value>
                <value>
                    <fullName>Bulk</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PackageType__c</fullName>
        <description>This field captures the package type for the product associated.</description>
        <label>Packaging Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_PackagingType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_UnitofMeasure__c</fullName>
        <label>UoM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_SS_UnitOfMeasure</valueSetName>
        </valueSet>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>PMC_CPQ_ModeofTransportation__c</fullName>
        <description>This field is created to check the mode of transportation.</description>
        <label>MoT</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_MoT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PackType__c</fullName>
        <label>Pack Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_PackType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PackageType__c</fullName>
        <description>The Packaging Type of the Product added to the quote.</description>
        <label>Packaging Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_PackagingType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_UnitofMeasure__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_SS_UnitOfMeasure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this subscription.</description>
        <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipment.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_ModeofTransportation__c</fullName>
        <inlineHelpText>Select the appropriate mode from the available options to track and manage logistics effectively.</inlineHelpText>
        <label>MOT</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_MoT</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ShipmentItem.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_ModeofTransportation__c</fullName>
        <inlineHelpText>Select the appropriate mode from the available options to track and manage logistics effectively</inlineHelpText>
        <label>MOT</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_MoT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field captures the order Order Item.</description>
        <label>Order Item</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Delivery Items</relationshipLabel>
        <relationshipName>Delivery_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_UnitofMeasure__c</fullName>
        <description>This field captures the uom of Measure.</description>
        <inlineHelpText>Specify the unit in which the value of this field will be measured.</inlineHelpText>
        <label>UoM Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_SS_UnitOfMeasure</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/PMC_CPQ_Incoterms1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CFR</fullName>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
    </customValue>
    <customValue>
        <fullName>DAP</fullName>
    </customValue>
    <customValue>
        <fullName>DAT</fullName>
    </customValue>
    <customValue>
        <fullName>FCA</fullName>
    </customValue>
    <customValue>
        <fullName>FOB</fullName>
    </customValue>
    <customValue>
        <fullName>FOB/CIFADO</fullName>
    </customValue>
    <customValue>
        <fullName>CPT</fullName>
    </customValue>
    <customValue>
        <fullName>CIFFOB</fullName>
        <isActive>false</isActive>
        <label>CIFFOB</label>
    </customValue>
    <masterLabel>Incoterms 1</masterLabel>
</GlobalValueSet>

globalValueSets/PMC_CPQ_MoT.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Barge</fullName>
    </customValue>
    <customValue>
        <fullName>Container</fullName>
    </customValue>
    <customValue>
        <fullName>Rail</fullName>
    </customValue>
    <customValue>
        <fullName>Truck</fullName>
    </customValue>
    <customValue>
        <fullName>Vessel</fullName>
    </customValue>
    <description>This is created to hold mode of Transportation value sets</description>
    <masterLabel>MoT</masterLabel>
</GlobalValueSet>

globalValueSets/PMC_CPQ_PackagingType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Big Bag 1500 Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Saco 50 Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Saco 50 Kg - Paletizado</fullName>
    </customValue>
    <customValue>
        <fullName>Big Bag 1000 Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Saco 30 Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Saco 25 Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Big Bag 1350 Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Saco 25 Kg - Paletizado</fullName>
    </customValue>
    <customValue>
        <fullName>Transp. Valved NPK</fullName>
    </customValue>
    <customValue>
        <fullName>Transp. Valved Urea</fullName>
    </customValue>
    <customValue>
        <fullName>Braided   Valved</fullName>
    </customValue>
    <customValue>
        <fullName>BagOneWay 90x90x1,30</fullName>
    </customValue>
    <customValue>
        <fullName>BagOneWay 500Kg</fullName>
    </customValue>
    <customValue>
        <fullName>BagOneWay Liner 1,40</fullName>
    </customValue>
    <customValue>
        <fullName>Bag ONE-Way-Liner Urea 99x99x1,40</fullName>
    </customValue>
    <customValue>
        <fullName>Bag One Way Liner 500kg Liner 90X</fullName>
    </customValue>
    <customValue>
        <fullName>Tranç. Nitrog. Laminated</fullName>
    </customValue>
    <customValue>
        <fullName>Tranç. Urea Laminated</fullName>
    </customValue>
    <customValue>
        <fullName>BagOneWayLiner 750kg</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk</fullName>
    </customValue>
    <customValue>
        <fullName>Sifted Bulk</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk - Mosiac Production</fullName>
        <label>Bulk - Mosaic Production</label>
    </customValue>
    <customValue>
        <fullName>Big BagOneWay Liner</fullName>
    </customValue>
    <customValue>
        <fullName>Saco 30 Kg - Paletizado</fullName>
    </customValue>
    <customValue>
        <fullName>1000 KG Bags</fullName>
    </customValue>
    <customValue>
        <fullName>25KG Bags</fullName>
    </customValue>
    <customValue>
        <fullName>50KG Bags</fullName>
    </customValue>
    <customValue>
        <fullName>Trançada com Liner</fullName>
    </customValue>
    <customValue>
        <fullName>test</fullName>
        <isActive>false</isActive>
        <label>test</label>
    </customValue>
    <customValue>
        <fullName>saco 50kg</fullName>
        <isActive>false</isActive>
        <label>saco 50kg</label>
    </customValue>
    <description>The Packaging Type of the Product added to the quote.</description>
    <masterLabel>Packaging Type</masterLabel>
</GlobalValueSet>

classes/PMC_DH_OrderUtilHelper.cls
/** 
* @description Helper class for PMC_DH_OrderUtil
* @author Mosaic Direct Dev
* Created On       :2023-Nov-29
**/

public without sharing class PMC_DH_OrderUtilHelper {

    /*************************************************************************
    * @method Name  : getTotalOrderItems
    * @description : Method to get Total OrderItems
    * @param lstOrderItems
    * @return Map<String, OrderItem> 
    *****************************************************************************/
    public static Map<String, OrderItem> getTotalOrderItems(List<OrderItem> lstOrderItems){
        Map<String, OrderItem> mapOrderItems = new Map<String, OrderItem>();
        if(!lstOrderItems.isEmpty()){
            for(OrderItem objOrderItem : lstOrderItems){
                mapOrderItems.put(objOrderItem.Id, objOrderItem);
            }
        }
        return mapOrderItems;
    }
    /*************************************************************************
    * @method Name  : getShipmentOrderItems
    * @description : Method to get Shipment related OrderItems
    * @param mapOrderItems
    * @param lstShipmentOrderIds
    * @return List<OrderItem> 
    *****************************************************************************/
    public static List<OrderItem> getShipmentOrderItems(Map<String, OrderItem> mapOrderItems, List<String> lstShipmentOrderIds){
        List<OrderItem> lstShipmentOrderItems = new List<OrderItem>();
        for(String strOrderItemId : lstShipmentOrderIds){
            if(mapOrderItems.containsKey(strOrderItemId)){
                lstShipmentOrderItems.add(mapOrderItems.get(strOrderItemId));
            }
        }
        return lstShipmentOrderItems;
    }

    /**
    * @description getStatusOrdLine
    * @author Hemant Giri Goswami | hegoswami@deloitte.com | 12-12-2023 
    * @param strStatus 
    * @return String 
    **/
    public static String getStatusOrdLine(String strStatus)
    {   
        String strFieldDev='';
        String strReturn='';
        String strTransStatus='';
        if(!String.isBlank(strStatus))
        {
        strFieldDev=strStatus.replace(' ','_');
        strTransStatus= PMC_DH_Quote_Management_Status__mdt.getInstance(strFieldDev).PMC_DH_StatusLabel__c;
        strReturn=System.label.get(null,strTransStatus,userinfo.getLocale());
        }
        return strReturn;
    }

    /**
    * @description Set Order Line Status
    * @param oi 
    * @return String 
    **/
    public static String setDeliveryStatus(OrderItem oi) {
        String strDeliveryStatus = System.label.pmc_orderDetails_statusPlaced;

        if(!String.isBlank(oi.PMC_CPQ_OrderLineStatus__c) && String.isBlank(oi.PMC_CPQ_ReasonOfRejectionOfItem__c) ) {
            strDeliveryStatus = getStatusOrdLine(oi.PMC_CPQ_OrderLineStatus__c);
        }
        else if(!String.isBlank(oi.PMC_CPQ_ReasonOfRejectionOfItem__c)){
            strDeliveryStatus = System.label.PMC_DH_Cancelled;

        }
        
        return strDeliveryStatus;
    }

    /**
     * @description Check if set contains the value
     * @param parentSet
     * @param val
     * @return boolean
     */
    public static Boolean checkIfSetContainsValue(Set<String> parentSet, String val) {
        if(String.isNotBlank(val) && !parentSet.contains(val)){
            return true;
        }
        return false;
    }

     /**
* @description formatting shipment date
* @author  Mosaic Direct Dev 
* @param strReqdeldate
* @return  String
**/
public static String formatShipmentDate(String strReqdeldate) {
    String strDelDate;
    if(strReqdeldate.contains('.')){
        List<String> lstDelDate = strReqdeldate.split('\\.');
        if(lstDelDate.size()==3) {
            strDelDate = lstDelDate[2]+'-'+lstDelDate[1] +'-'+ lstDelDate[0];
        }
    }
    if(strReqdeldate.contains('-')){
        List<String> lstDelDate = strReqdeldate.split('-');
        if(lstDelDate.size()==3) {
            strDelDate = lstDelDate[0]+'-'+lstDelDate[1] +'-'+ lstDelDate[2];
        }
    }
    return strDelDate;
}

 /**
* @description  getProductNames
* @param lstProducts 
* @return Map<String, String> 
**/ 
    
public static Map<String, String> getProductNames(List<Product2> lstProducts){
    Map<String, String> mapOfProdSKUName = new Map<String, String>();
    for (Product2 prod : lstProducts){
        mapOfProdSKUName.put(prod.StockKeepingUnit, prod.Name);
    }
    return mapOfProdSKUName;
}


/*************************************************************************
* @method Name  : createFieldSetmap
* @description  : Method to create a field set map
* @return       : Map<String, Schema.DescribeFieldResult>
*****************************************************************************/
public static Map<String, Schema.DescribeFieldResult> createFieldSetmap() {
    Schema.DescribeFieldResult mot = OrderItem.PMC_CPQ_ModeofTransportation__c.getDescribe();
    Schema.DescribeFieldResult incoterms = OrderItem.PMC_CPQ_Incoterms__c.getDescribe();     
    Schema.DescribeFieldResult packType = SBQQ__QuoteLine__c.PMC_CPQ_PackType__c.getDescribe();     
    Schema.DescribeFieldResult packagingType = OrderItem.PMC_CPQ_PackageType__c.getDescribe();     
    Schema.DescribeFieldResult uom = SBQQ__QuoteLine__c.PMC_CPQ_UnitOfMeasure__c.getDescribe(); 
    Map<String, Schema.DescribeFieldResult> mapOfFieldSet = new Map<String, Schema.DescribeFieldResult>{'mot' => mot, 'incoterms' => incoterms, 'packType' => packType, 'packagingType' => packagingType, 'uom' => uom};
    return mapOfFieldSet;
}


/*************************************************************************
* @method Name  : setTranslatedValuesForPicklist
* @description  : Method to set translated fields
* @param         objShipmentItemWrap
* @param         oi
* @param         mapOfFieldSet
*****************************************************************************/
public static void setTranslatedValuesForPicklist(PMC_DH_OrderDetailsWrapper.ShipmentItemsWrapper objShipmentItemWrap, OrderItem oi,Map<String, Schema.DescribeFieldResult> mapOfFieldSet) {
    objShipmentItemWrap.strDeliveryModeLabel = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(mapOfFieldSet.get('mot'),oi.PMC_CPQ_ModeofTransportation__c);
    objShipmentItemWrap.strIncotermLabel = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(mapOfFieldSet.get('incoterms'),oi.PMC_CPQ_Incoterms__c);
    objShipmentItemWrap.strPackageTypeLabel = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(mapOfFieldSet.get('packagingType'),oi.PMC_CPQ_PackageType__c);
    objShipmentItemWrap.strPackTypeLabel = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(mapOfFieldSet.get('packType'),objShipmentItemWrap.strPackType);
    objShipmentItemWrap.strProductUOMLabel = PMC_DH_CommonSystemUtils.getTranslatedValForPicklist(mapOfFieldSet.get('uom'),oi.SBQQ__Subscription__r.SBQQ__QuoteLine__r.PMC_CPQ_UnitOfMeasure__c);
}

   /**
    * @description 
    * @author Hemant Giri Goswami | hegoswami@deloitte.com | 06-04-2024 
    * @param docType 
    * @param orderItem 
    * @param lstWrp 
    * @return Map<String, Map<String, String>> 
    **/
    public static Map<String,Map<String,String>> generateMaps(PMC_DH_DocumentType__mdt docType,OrderItem orderItem,PMC_DH_OrderLineDetailsController.ListWrapper lstWrp)
    {
        for(ShipmentItem shipItem: orderItem.Delivery_Items__r){
            if(docType.PMC_DH_DocumentCode__c == PMC_DH_ConstantClass.BOL && shipItem.Shipment.PMC_CPQ_SAPDeliveryID__c!=null && lstWrp.lstRegions.contains(lstWrp.strRegion)){ //GPT-44509
                Map<String,String> mapString = new Map<String,String>();
                mapString.put(docType.PMC_DH_Identifier__c,shipItem.Shipment.PMC_CPQ_SAPDeliveryID__c);
                lstWrp.mapResult.put(docType.PMC_DH_DocumentCode__c,mapString);
            }
            if(docType.PMC_DH_DocumentCode__c == PMC_DH_ConstantClass.COA && shipItem.Shipment.PMC_CPQ_SAPDeliveryID__c!=null && shipItem.PMC_CPQ_DeliveryItemID__c!=null && lstWrp.lstRegions.contains(lstWrp.strRegion) && lstWrp.lstProductionPlants.contains('PDPL_' + orderItem?.PMC_CPQ_ProductLocation__r?.PMC_CPQ_SAPOriginID__c )){ //GPT-44509
                Map<String,String> mapString = new Map<String,String>();
                mapString.put(lstWrp.lstString[0],shipItem.Shipment.PMC_CPQ_SAPDeliveryID__c);
                mapString.put(lstWrp.lstString[1],shipItem.PMC_CPQ_DeliveryItemID__c);
                lstWrp.mapResult.put(docType.PMC_DH_DocumentCode__c,mapString);
            }
        }
        return lstWrp.mapResult;
    }
}