objects/Order.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_PO__c</fullName>
        <description>This field is used to capture the user input for Purchase order number.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Purchase Order number for this order.</inlineHelpText>
        <label>Customer Purchase Order #</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SAPOrderNumber__c</fullName>
        <description>This field captures the order number in SAP.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Reference Order Number in SAP.</inlineHelpText>
        <label>SAP Order Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_Shipment_Data__c.object
<CustomObject>
    <fields>
        <fullName>PMC_BOLNUMBER__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>BOLNUMBER</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_BOL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>BOL</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_COMMENTS__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>COMMENTS</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_CurrentCoordinates__c</fullName>
        <label>CurrentCoordinates</label>
        <scale>6</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SAPDeliveryID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Delivery Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipmentNumber__c</fullName>
        <label>Shipment Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Shipment_PO__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Shipment PO</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PMC_CURRENTCARRIER__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CURRENTCARRIER</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CURRENTLOCATION__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CURRENTLOCATION</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CUSTORDERNO__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CUSTORDERNO</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DELIVERYNUMBER__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DELIVERYNUMBER</label>
        <length>252</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DESTINATIONCARRIER__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DESTINATIONCARRIER</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DESTINATIONMM__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DESTINATIONMM</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_Deliveries_Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deliveries Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_EQUIPMENTID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>EQUIPMENTID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_ETA__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ETA</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PMC_FLEETTOWNAME__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>FLEETTOWNAME</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_LATESTINTERNALCOMMENT__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>LATESTINTERNALCOMMENT</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_LATESTTRIPSIGHTINGID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>LATESTTRIPSIGHTINGID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_PONUMBER__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PONUMBER</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SHIPMENTNUMBER_CNTORDER__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SHIPMENTNUMBER_CNTORDER</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SIGHTINGDESTINATION__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SIGHTINGDESTINATION</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SIGHTINGLOADOREMPTY__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SIGHTINGLOADOREMPTY</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Shipment Data</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipment Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipment.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Carrier__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_CurrentCarrier__c</fullName>
        <description>This is used in intellitrans integration</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Current Carrier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_CurrentCoordinates__c</fullName>
        <description>This field is used in intellitrans integration</description>
        <label>Current Coordinates</label>
        <scale>6</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_CurrentLocation__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Current Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ETA__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ETA</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field captures the Order Number.</description>
        <label>Order Number</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PO__c</fullName>
        <description>This field is used to capture the user input for Purchase order number.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Purchase Order #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SAPDeliveryID__c</fullName>
        <description>This field captures the sap Delivery ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SAP Delivery ID</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PMC_CPQ_TowName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tow Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_VehicleID__c</fullName>
        <description>This field captures the vehicle Vehicle ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PMC_IntellitransShipmentBatchUpdate.cls
public class PMC_IntellitransShipmentBatchUpdate implements Database.Batchable<SObject>, Database.AllowsCallouts, Schedulable  {

   
    public Database.QueryLocator start(Database.BatchableContext BC) {
        
        return Database.getQueryLocator([ select Id,PMC_BOL__c, PMC_BOLNUMBER__c, PMC_COMMENTS__c, PMC_CPQ_CurrentCoordinates__c, PMC_CPQ_CurrentCoordinates__Latitude__s, PMC_CPQ_CurrentCoordinates__Longitude__s, PMC_CPQ_SAPDeliveryID__c, PMC_CPQ_Shipment_PO__c, PMC_CPQ_ShipmentNumber__c, PMC_CURRENTCARRIER__c, PMC_CURRENTLOCATION__c, PMC_CUSTORDERNO__c, PMC_DELIVERYNUMBER__c, PMC_DESTINATIONCARRIER__c, PMC_DESTINATIONMM__c, PMC_EQUIPMENTID__c, PMC_ETA__c, PMC_FLEETTOWNAME__c, PMC_LATESTINTERNALCOMMENT__c, PMC_LATESTTRIPSIGHTINGID__c, PMC_PONUMBER__c, PMC_SHIPMENTNUMBER_CNTORDER__c, PMC_SIGHTINGDESTINATION__c, PMC_SIGHTINGLOADOREMPTY__c,PMC_Deliveries_Updated__c  from PMC_Shipment_Data__c where PMC_CUSTORDERNO__c != null and PMC_EQUIPMENTID__c !=null and PMC_Deliveries_Updated__c = FALSE ]);
    }

    public void execute(SchedulableContext objSchedulableContext){
        
        Database.executeBatch(new PMC_IntellitransShipmentBatchUpdate(), 200);
    }

    public void execute(Database.BatchableContext BC, List<PMC_Shipment_Data__c> scope) {
        // Maps to hold 
        Map<String, PMC_Shipment_Data__c> IntellitransmapPO = new Map<String, PMC_Shipment_Data__c>();
        Map<String, PMC_Shipment_Data__c> IntellitransmapVID = new Map<String, PMC_Shipment_Data__c>();
         Map<String, PMC_Shipment_Data__c> IntellitransmapConcat = new Map<String, PMC_Shipment_Data__c>();
        
        // Populate the maps with Itelli trans
        for (PMC_Shipment_Data__c ls : scope) {
            if (ls.PMC_CUSTORDERNO__c != null) {
                IntellitransmapPO.put(ls.PMC_CUSTORDERNO__c, ls);
            }
            if (ls.PMC_EQUIPMENTID__c != null) {
                IntellitransmapVID.put(ls.PMC_EQUIPMENTID__c, ls);
            }
            IntellitransmapConcat.put(ls.PMC_CUSTORDERNO__c+ls.PMC_EQUIPMENTID__c,ls);
        }

       
        List<shipment> shiplst = [select id,PMC_CPQ_Order__r.PMC_CPQ_SAPOrderNumber__c,PMC_CPQ_SAPDeliveryID__c,PMC_CPQ_ETA__c,PMC_CPQ_PO__c,PMC_CPQ_VehicleID__c,PMC_CPQ_CurrentCarrier__c,PMC_CPQ_Carrier__c,PMC_CPQ_TowName__c,PMC_CPQ_CurrentLocation__c,PMC_CPQ_CurrentCoordinates__Latitude__s, PMC_CPQ_CurrentCoordinates__Longitude__s 


  from shipment where PMC_CPQ_Order__r.PMC_CPQ_SAPOrderNumber__c  IN :IntellitransmapPO.keySet() 
                                          OR PMC_CPQ_VehicleID__c IN :IntellitransmapVID.keySet()];
                                          
                                          list<PMC_Shipment_Data__c> lstUpdateProcessedRecords = new list<PMC_Shipment_Data__c>();

        

        for (shipment ship : shiplst) {
            PMC_Shipment_Data__c matchedIntellitrans;
          

            
            if (IntellitransmapPO.containsKey(ship.PMC_CPQ_Order__r.PMC_CPQ_SAPOrderNumber__c) && IntellitransmapVID.containsKey(ship.PMC_CPQ_VehicleID__c)) {
                if(IntellitransmapConcat.containsKey(ship.PMC_CPQ_Order__r.PMC_CPQ_SAPOrderNumber__c+ship.PMC_CPQ_VehicleID__c)){
                    matchedIntellitrans = IntellitransmapConcat.get(ship.PMC_CPQ_Order__r.PMC_CPQ_SAPOrderNumber__c+ship.PMC_CPQ_VehicleID__c);
                    PMC_Shipment_Data__c IntelliTrans = new PMC_Shipment_Data__c(Id = matchedIntellitrans.Id, PMC_Deliveries_Updated__c = True);
                    lstUpdateProcessedRecords.add(IntelliTrans);
                }
                
            }
            
            if (matchedIntellitrans != null) {
                //ship.Id = matchedIntellitrans.Id;
                //ship.PMC_CPQ_SAPDeliveryID__c = matchedIntellitrans.PMC_CPQ_SAPDeliveryID__c;
               if(matchedIntellitrans.PMC_ETA__c!=null){
                	Date currentDate = matchedIntellitrans.PMC_ETA__c.date();
                	ship.PMC_CPQ_ETA__c = date.valueof(currentDate);
                }
                //ship.PMC_CPQ_PO__c = matchedIntellitrans.PMC_CPQ_SAPDeliveryID__c;
                //ship.PMC_CPQ_VehicleID__c = matchedIntellitrans.PMC_CPQ_SAPDeliveryID__c;
                ship.PMC_CPQ_CurrentCarrier__c = matchedIntellitrans.PMC_CURRENTCARRIER__c;
                //ship.PMC_CPQ_Carrier__c = matchedIntellitrans.PMC_CPQ_SAPDeliveryID__c;
                ship.PMC_CPQ_TowName__c = matchedIntellitrans.PMC_FLEETTOWNAME__c;
                ship.PMC_CPQ_CurrentLocation__c = matchedIntellitrans.PMC_CURRENTLOCATION__c;
                ship.PMC_CPQ_Carrier__c = matchedIntellitrans.PMC_DESTINATIONCARRIER__c;
                ship.PMC_CPQ_CurrentCoordinates__Latitude__s = matchedIntellitrans.PMC_CPQ_CurrentCoordinates__Latitude__s;
                ship.PMC_CPQ_CurrentCoordinates__Longitude__s = matchedIntellitrans.PMC_CPQ_CurrentCoordinates__Longitude__s;
               
            }
        }


        // Perform the update
        if (!shiplst.isEmpty()) {
            map<id,shipment> mp1 = new map<id,shipment>();
            mp1.putall(shiplst);
            Database.update(mp1.values(),false);
            
        }
         if (!lstUpdateProcessedRecords.isEmpty()) {
            map<id,PMC_Shipment_Data__c> mp = new map<id,PMC_Shipment_Data__c>();
            mp.putall(lstUpdateProcessedRecords);
            Database.update(mp.values(),false);
            
        }
    }

    public void finish(Database.BatchableContext BC) {
        System.debug('Batch processing finished.');
    }
}