objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_FinalAgreedPrice__c</fullName>
        <description>This field is will store the Final Agreed Price and send it back to SAP after the Order is placed.</description>
        <label>Final Agreed Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ListPrice__c</fullName>
        <description>This field is to capture the List Price from SAP and Store it in the standard List Price field using flow on Create.</description>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_ProductSKUCode__c</fullName>
        <description>This field is to store SKU Code of the Product associated</description>
        <formula>Product2.StockKeepingUnit</formula>
        <label>Product SKU Code</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_SAPProductCode__c</fullName>
        <description>This field captures the product code in SAP system for the product.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Product code in SAP system.</inlineHelpText>
        <label>SAP Product Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>PMC_CPQ_Brazil</fullName>
        <active>true</active>
        <description>This Record Type was created as a part of story to have different functionalities for different Record Types</description>
        <label>Brazil</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PMC_CPQ_QLApprovalReqEmailTempTest.cls
@isTest
public class PMC_CPQ_QLApprovalReqEmailTempTest {

    @testSetup  
    static void setup(){
        List<Order> lstOrders = PMC_CPQ_OrderIntegrationTest.createOrders(1);
        User objUser = [select Id from User where LastName = 'System Administrator Test' LIMIT 1 ];
 		System.runAs(objUser){  
            List<Product2> prod = PMC_TestUtilityClass.createProduct(1,'PMC_CPQ_Brazil');
            prod[0].PMC_CPQ_SAPProductCode__c = '';
            update prod[0];
            //Instantiate the Pricebook2 record with StandardPricebookId
            Pricebook2 standardPricebook = new Pricebook2(
                Id = Test.getStandardPricebookId(),
                IsActive = true
            );
            
            //Execute an update DML on the Pricebook2 record, to make IsStandard to true
            Update standardPricebook;
            
            lstOrders[0].Pricebook2Id = standardPricebook.Id;
            lstOrders[0].CurrencyIsoCode = 'USD';
            update lstOrders;
            //Create the PricebookEntry
            PricebookEntry pbe = new PricebookEntry(
                Pricebook2Id = standardPricebook.Id,
                Product2Id = prod[0].Id,
                UnitPrice = 0,
                // PMC_CPQ_ProductSKUCode__c = prod[0].PMC_CPQ_SAPProductCode__c,
                CurrencyIsoCode = lstOrders[0].CurrencyIsoCode,
                IsActive = true
            );
            Insert pbe;
            OrderItem objOrderProducts = new OrderItem();
            
            objOrderProducts.Product2Id = prod[0].id;
            objOrderProducts.OrderId = lstOrders[0].id;
            objOrderProducts.Quantity = 2;
            //objOrderProducts.PMC_CPQ_ListPrice__c = 180;
            objOrderProducts.UnitPrice = 0;
            objOrderProducts.ListPrice = 0;
            objOrderProducts.PMC_CPQ_FinalAgreedPrice__c = 1;
            objOrderProducts.PricebookEntryId = pbe.Id;
            insert objOrderProducts;
        }
    }
    
    @isTest
    static void testGetOLines() {
        // Retrieve the OrderItem created in the setup
        OrderItem testOrderItem = [SELECT Id FROM OrderItem LIMIT 1];

        // Instantiate the class to be tested
        PMC_CPQ_QLApprovalReqEmailTempClass emailTempClass = new PMC_CPQ_QLApprovalReqEmailTempClass();
        emailTempClass.orderItemId = testOrderItem.Id;

        // Call the oLines property to trigger the query
        List<OrderItem> oLines = emailTempClass.oLines;

        // Assert that the oLines list is not null and contains the expected OrderItem
        System.assertNotEquals(null, oLines, 'oLines should not be null');
        System.assertEquals(1, oLines.size(), 'oLines should contain one OrderItem');
        System.assertEquals(testOrderItem.Id, oLines[0].Id, 'The OrderItem Id should match the one created in setup');
    }

    @isTest
    static void testGetOLinesWithNullOrderItemId() {
        // Instantiate the class to be tested without setting orderItemId
        PMC_CPQ_QLApprovalReqEmailTempClass emailTempClass = new PMC_CPQ_QLApprovalReqEmailTempClass();

        // Call the oLines property to trigger the query
        List<OrderItem> oLines = emailTempClass.oLines;

        // Assert that the oLines list is null since orderItemId is not set
        System.assertEquals(null, oLines, 'oLines should be null when orderItemId is not set');
    }
}