objects/Order.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_SAPOrderNumber__c</fullName>
        <description>This field captures the order number in SAP.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Reference Order Number in SAP.</inlineHelpText>
        <label>SAP Order Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PMC_DH_OrderTypeCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Order Type Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Destination__c</fullName>
        <description>This field captures destination</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field captures the destination for the order</inlineHelpText>
        <label>Destination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_LinePONumber__c</fullName>
        <description>This field will be used to capture the PO Number at a order line level - leveraged in the Contract Document forms for North America</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Purchase Order #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Location</label>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Products (Ship To)</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/PMC_CPQ_Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PMC_CPQ_InvoiceItem__c.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_DeliveryItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Item</label>
        <referenceTo>ShipmentItem</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>InvoiceItems1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Invoice__c</fullName>
        <description>The Invoice associated with this Item.</description>
        <label>Invoice</label>
        <referenceTo>PMC_CPQ_Invoice__c</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>InvoiceItems2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_LinePONumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Purchase Order #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>InvoiceItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Location</label>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Invoice Items (Product Location)</relationshipLabel>
        <relationshipName>Invoice_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SAPDeliveryID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SAP Delivery ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>Invoice_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>INV ITEM-{0000}</displayFormat>
        <label>Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PMC_CPQ_ProductLocation__c.object
<CustomObject>
    <description>This object is created as a part of  story to capture product and location data.</description>
    <fields>
        <fullName>PMC_CPQ_SAPOriginID__c</fullName>
        <description>This field is created  to check SAP Origin ID</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SAP Origin ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Product Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Shipment.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_CurrentLocation__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Current Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_DeliveryItemID__c</fullName>
        <description>This field captures the delivery Item ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Delivery Item ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_DeliveryPlannedGIDate__c</fullName>
        <description>Planned date for good to be released.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Delivery Planned GI Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_DeliveryQuantity__c</fullName>
        <description>This field captures the delivery Delivery Quantity.</description>
        <label>Delivery Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Destination__c</fullName>
        <label>Destination</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_DestinationCountry</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ETA__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ETA</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SAPDeliveryID__c</fullName>
        <description>This field captures the sap Delivery ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SAP Delivery ID</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deliveries (Ship To)</relationshipLabel>
        <relationshipName>Deliveries2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShippedDate__c</fullName>
        <description>This field captures the shipped  Date.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipped Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_VehicleID__c</fullName>
        <description>This field captures the vehicle Vehicle ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ShipmentItem.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_CurrentLocation__c</fullName>
        <description>This field captures the current Current Location.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Current Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_DeliveryItemID__c</fullName>
        <description>This field captures the delivery Item ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SAP Delivery Item ID</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PMC_CPQ_DeliveryLineStatus__c</fullName>
        <description>This field is to capture the status of the Line Item</description>
        <label>Delivery Line Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Shipped</fullName>
                </value>
                <value>
                    <fullName>Partially Shipped</fullName>
                </value>
                <value>
                    <fullName>Completely Shipped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_DeliveryQuantity__c</fullName>
        <description>This field captures the delivery Delivery Quantity.</description>
        <label>Delivery Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Destination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Delivery Items</relationshipLabel>
        <relationshipName>Delivery_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ETA__c</fullName>
        <description>Estimated Time of Arrival date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>ETA</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_LinePONumber__c</fullName>
        <formula>PMC_CPQ_OrderProduct__r.PMC_CPQ_LinePONumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Purchase Order #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_OrderProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field captures the order Order Item.</description>
        <label>Order Item</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Delivery Items</relationshipLabel>
        <relationshipName>Delivery_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Location</label>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Delivery Lines</relationshipLabel>
        <relationshipName>Delivery_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SAPDeliveryID__c</fullName>
        <description>This field captures the sap Delivery ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SAP Delivery ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ShippedDate__c</fullName>
        <description>This field captures the shipped  Date.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipped Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_VehicleID__c</fullName>
        <description>This field captures the vehicle Vehicle ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PMC_DH_ShipmentHistoryListHelper.cls
/** 
* @description Helper Class for PMC_DH_ShipmentHistoryList class
* @author Mosaic Direct Dev
* Created On       :2023-Nov-08
**/
public without sharing class PMC_DH_ShipmentHistoryListHelper {
    private static final String SCHEDULED_STATUS = 'Scheduled';
    private static final String IN_TRANSIT_STATUS = 'In Transit';
/*************************************************************************
* @method Name  : getShipmentQuery
* @description  : Method for querying the Shipment Records
* @param 		  searchParams
* @param 		  effAccountId
* @return       : String
*****************************************************************************/    
    public static String getShipmentQuery(PMC_DH_ShipmentHistoryList.PMC_DH_ShipmentSearchParameterWrapper searchParams,String effAccountId){

            String strQuery = 'SELECT Id, OrderId, PMC_CPQ_ShipTo__c, PMC_CPQ_ShipTo__r.Name, PMC_CPQ_ProductLocation__r.PMC_CPQ_SAPOriginID__c,';
            strQuery += ' (SELECT Id, ShipmentId, shipment.ActualDeliveryDate, PMC_CPQ_OrderProduct__r.Order.PMC_CPQ_SAPOrderNumber__c, PMC_CPQ_OrderProduct__c,Product2.Name,PMC_CPQ_LinePONumber__c, PMC_CPQ_ShippedDate__c, ExpectedDeliveryDate, PMC_CPQ_DeliveryQuantity__c,PMC_CPQ_DeliveryLineStatus__c, PMC_CPQ_Destination__c, ShipmentItemNumber,PMC_CPQ_DeliveryItemID__c,Shipment.PMC_CPQ_SAPDeliveryID__c, Shipment.ShipmentNumber, Shipment.PMC_CPQ_DeliveryPlannedGIDate__c, Shipment.PMC_CPQ_ShippedDate__c, Shipment.PMC_CPQ_VehicleID__c,Shipment.PMC_CPQ_ETA__c,Shipment.PMC_CPQ_CurrentLocation__c, PMC_CPQ_OrderProduct__r.PMC_CPQ_ProductLocation__r.PMC_CPQ_SAPOriginID__c FROM Delivery_Items__r '; // GDASF-20651
            if(String.isNotBlank(searchParams.strSearchTerm)){
                String strSearchPattern = '\'%' + String.escapeSingleQuotes(searchParams.strSearchTerm) + '%\'';
                strQuery += 'WHERE (PMC_CPQ_OrderProduct__r.PMC_CPQ_ShipTo__r.Name LIKE '+ strSearchPattern +' OR PMC_CPQ_OrderProduct__r.Order.PMC_CPQ_SAPOrderNumber__c LIKE '+ strSearchPattern +' OR PMC_CPQ_LinePONumber__c LIKE '+ strSearchPattern +' OR Product2.Name LIKE '+ strSearchPattern +' OR Shipment.PMC_CPQ_VehicleID__c LIKE '+ strSearchPattern +' OR PMC_CPQ_DeliveryLineStatus__c LIKE '+ strSearchPattern +')';// Vehicle Id change part of GDASF-20651
            }
            strQuery = getDateFilters(searchParams,strQuery);
            if(String.isNotBlank(searchParams.strSearchTerm) && searchParams.datFromDate != NULL && searchParams.datToDate != NULL){
                if(String.isNotBlank(searchParams.strStatus) && searchParams.strStatus == SCHEDULED_STATUS){
                	strQuery += 'AND (Shipment.PMC_CPQ_DeliveryPlannedGIDate__c >='+ String.valueOf(searchParams.datFromDate) +' AND Shipment.PMC_CPQ_DeliveryPlannedGIDate__c <= '+ String.valueOf(searchParams.datToDate)+')';
                }
                else if(String.isNotBlank(searchParams.strStatus) && searchParams.strStatus == IN_TRANSIT_STATUS){
                	strQuery += 'AND (PMC_CPQ_ShippedDate__c >='+ String.valueOf(searchParams.datFromDate) +' AND PMC_CPQ_ShippedDate__c <= '+ String.valueOf(searchParams.datToDate)+')'; 
                }
            }
            strQuery +='),';
            strQuery += '(SELECT id, PMC_CPQ_Invoice__r.PMC_CPQ_InvoiceNumber__c, PMC_CPQ_DeliveryItem__c FROM InvoiceItems__r)';
            strQuery += ' FROM OrderItem  WHERE Order.AccountId =: effAccountId';
            strQuery += ' AND Order.PMC_CPQ_SAPOrderNumber__c != null';
        
            //strQuery += ' AND (Order.Type = \'Standard Sales Order\' OR Order.Type = \'Pre-pay Sales Order\')';
            // added as part of GPT-28211 and Updated as part of GDASF-20299
        	strQuery += ' AND Order.PMC_DH_OrderTypeCode__c IN ';
        	strQuery += Label.PMC_DH_OrderTypesforShipment;
            strQuery += ' WITH SYSTEM_MODE ORDER BY Order.CreatedDate DESC LIMIT 1001';
        return strQuery;
    }
    
/*************************************************************************
* @method Name  : getDateFilters
* @description  : Method for Filtering the shipment records
* @param 		  searchParams
* @param 		  strQuery
* @return       : String
*****************************************************************************/
    public static String getDateFilters(PMC_DH_ShipmentHistoryList.PMC_DH_ShipmentSearchParameterWrapper searchParams, String strQuery){

        if(searchParams.datFromDate != NULL && searchParams.datToDate != NULL && !(String.isNotBlank(searchParams.strSearchTerm))){
            if(String.isNotBlank(searchParams.strStatus) && searchParams.strStatus == SCHEDULED_STATUS){
                strQuery += 'WHERE Shipment.PMC_CPQ_DeliveryPlannedGIDate__c >='+ String.valueOf(searchParams.datFromDate) +' AND Shipment.PMC_CPQ_DeliveryPlannedGIDate__c <= '+ String.valueOf(searchParams.datToDate);
            }
            else if(String.isNotBlank(searchParams.strStatus) && searchParams.strStatus == IN_TRANSIT_STATUS){
                strQuery += 'WHERE PMC_CPQ_ShippedDate__c >='+ String.valueOf(searchParams.datFromDate) +' AND PMC_CPQ_ShippedDate__c <= '+ String.valueOf(searchParams.datToDate); 
            }
        }
        return strQuery;
    }
    
    //GPT-44509
    /*************************************************************************
* @method Name  : getUserRegion
* @description  : Method to get the user's region (NA/BR)
* @return       : String
*****************************************************************************/
    public static String getUserRegion(){
        String strCountry = [SELECT Id, Country FROM User WHere Id =: UserInfo.getUserId() WITH USER_MODE LIMIT 1].Country;
        String strRegion = PMC_DH_CommonSystemUtils.getUserRegion(strCountry);
        return strRegion;
    }
}