objects/PMC_SalesAgreementSalesAreaRelation__c.object
<CustomObject>
    <description>Junction object to link Sales Agreement with Sales Area.</description>
    <fields>
        <fullName>PMC_SS_SalesAgreement__c</fullName>
        <description>Sales Agreement Master-Detail field</description>
        <label>Sales Agreement</label>
        <referenceTo>SalesAgreement</referenceTo>
        <relationshipLabel>Sales Area</relationshipLabel>
        <relationshipName>PMC_SS_SalesAgreementSalesAreaRel</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SalesArea__c</fullName>
        <description>Sales Area Master-Detail field</description>
        <label>Sales Area</label>
        <referenceTo>PMC_SS_SalesArea__c</referenceTo>
        <relationshipLabel>Sales Agreement Sales Area Relation</relationshipLabel>
        <relationshipName>PMC_SS_SalesAgreementSalesAreaRelation</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Agreement Sales Area Relation</label>
    <nameField>
        <displayFormat>SAR-{00000}</displayFormat>
        <label>Sales Agreement Sales Area Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Agreement Sales Area Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PMC_SS_AccountSalesAreaRelationship__c.object
<CustomObject>
    <description>Junction Object to relate Account and Sales Areas</description>
    <fields>
        <fullName>PMC_SS_Account__c</fullName>
        <description>Master Detail relationship between Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>AccountSalesAreRelationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PMC_SS_SalesArea__c</fullName>
        <description>Master Detail relationship to Sales Area</description>
        <label>Sales Area</label>
        <referenceTo>PMC_SS_SalesArea__c</referenceTo>
        <relationshipName>AccountSalesAreRelationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Sales Area Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Sales Area Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PMC_SS_SalesArea__c.object
<CustomObject>
    <description>Sales Area Object</description>
    <label>Sales Area</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PMC_SS_SalesAgreeSalesAreaRelHelper.cls
/**
* @description This class will be used to handle all triggers on Sales Agreement Sales Area Relation object.
* @author Swakeerth Gadda
* @storynumber GDASF-9729
*/

public with sharing class PMC_SS_SalesAgreeSalesAreaRelHelper {
    /**
    * @description This method will be used to validate if sales area matches on sales agreement sales area relation object from account sales area junction.
    * @param listSalesAgreeSalesAreaRel - Triggering sales agreement sales area relation records.
    */
    public static void salesAgreementToSalesAreaValidation(List<PMC_SalesAgreementSalesAreaRelation__c> listSalesAgreeSalesAreaRel){
		Map<Id, Id> mapSalesAgreementAccountId = new Map<Id, Id>();
		Set<Id> setSalesAgreementId = new Set<Id>();
		Map<Id, Set<Id>> mapAccountSalesArea = new Map<Id, Set<Id>>();
        Map<Id, Set<Id>> mapSalesAgreementSalesArea = new Map<Id, Set<Id>>();
        list<PMC_SalesAgreementSalesAreaRelation__c> listNewSalesAgreeSalesAreaRel = new list<PMC_SalesAgreementSalesAreaRelation__c>();
        for(PMC_SalesAgreementSalesAreaRelation__c salesAgreeSalesAreaRel : listSalesAgreeSalesAreaRel){
            If(salesAgreeSalesAreaRel.PMC_SS_SalesArea__c != null && salesAgreeSalesAreaRel.PMC_SS_SalesAgreement__c != null){
                //Get Sales Agreement ID's for relevant Sales Agreement Sales Area Relation Junction
                setSalesAgreementId.add(salesAgreeSalesAreaRel.PMC_SS_SalesAgreement__c);
                //Get relavent Sales Agreement Sales Area Relation to loop and add validation if necessary
                listNewSalesAgreeSalesAreaRel.add(salesAgreeSalesAreaRel);
            }
        }
        mapSalesAgreementAccountId = createSalesAgreementAccountIdMap(setSalesAgreementId);
        mapAccountSalesArea = createAccountIdAccountSalesAreaRelationshipMap(mapSalesAgreementAccountId);
        mapSalesAgreementSalesArea = createSalesAgreeIdSalesAreaRelMap(mapSalesAgreementAccountId, mapAccountSalesArea);
		//Loop to check Account - Sales Area relations for all relavent sales agreement sales area relationship
        for(PMC_SalesAgreementSalesAreaRelation__c salesAgreeSalesAreaRel : listNewSalesAgreeSalesAreaRel){
            If(!mapSalesAgreementSalesArea.containsKey(salesAgreeSalesAreaRel.PMC_SS_SalesAgreement__c) || (mapSalesAgreementSalesArea.containsKey(salesAgreeSalesAreaRel.PMC_SS_SalesAgreement__c) && !mapSalesAgreementSalesArea.get(salesAgreeSalesAreaRel.PMC_SS_SalesAgreement__c).contains(salesAgreeSalesAreaRel.PMC_SS_SalesArea__c))){
                salesAgreeSalesAreaRel.addError(Label.PMC_SS_SalesAgreementtoSalesAreaValidationMessage);
            }
        }
    }
    /**
     * @description this method is used to create a map of account id vs set of related sales area ids
     * @param mapSalesAgreementAccountId map of accountIds linked to Sales Agreement
     * @return Map<Id, Set<Id>> map of <accId, Set<SalesAreaId>>
     */
	private static Map<Id, Set<Id>> createAccountIdAccountSalesAreaRelationshipMap(Map<Id, Id> mapSalesAgreementAccountId){
		Map<Id, Set<Id>> mapAccountSalesArea = new Map<Id, Set<Id>>();
        If(mapSalesAgreementAccountId.KeySet().size() > 0 && PMC_SS_AccountSalesAreaRelationship__c.sObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).isAccessible() && Schema.sObjectType.PMC_SS_AccountSalesAreaRelationship__c.fields.PMC_SS_Account__c.isAccessible() && Schema.sObjectType.PMC_SS_AccountSalesAreaRelationship__c.fields.PMC_SS_SalesArea__c.isAccessible()){
            //Loop to map Account - Sales Area relations for all related Accounts      
            for(PMC_SS_AccountSalesAreaRelationship__c accountSalesArea : [Select PMC_SS_Account__c, PMC_SS_SalesArea__c From PMC_SS_AccountSalesAreaRelationship__c Where PMC_SS_Account__c In : mapSalesAgreementAccountId.values()]){
                If(!mapAccountSalesArea.containsKey(accountSalesArea.PMC_SS_Account__c)){
                    mapAccountSalesArea.put(accountSalesArea.PMC_SS_Account__c, new Set<Id>{accountSalesArea.PMC_SS_SalesArea__c});
                }
                else{
                    Set<Id> existingSalesAreaSet = mapAccountSalesArea.get(accountSalesArea.PMC_SS_Account__c);
                    existingSalesAreaSet.add(accountSalesArea.PMC_SS_SalesArea__c);
                    mapAccountSalesArea.put(accountSalesArea.PMC_SS_Account__c, existingSalesAreaSet);
                }
            }
        }
        return mapAccountSalesArea;
    }
    
    /**
     * @description this method is used to create a map of sales agreement ids vs sales area ids
     * @param setSalesAgreementId set of Sales Agreement Ids
     * @return Map<Id, Id> map of <salesAgreementId, accountId>
     */
    private static Map<Id, Id> createSalesAgreementAccountIdMap(Set<Id> setSalesAgreementId){
        Map<Id, Id> mapSalesAgreementAccountId = new Map<Id, Id>();
        If(setSalesAgreementId.size() > 0 && SalesAgreement.sObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).isAccessible() && Schema.sObjectType.SalesAgreement.fields.AccountId.isAccessible()){
            for(SalesAgreement salesAgreement : [Select Id, AccountId from SalesAgreement Where Id IN: setSalesAgreementId]){
                mapSalesAgreementAccountId.put(salesAgreement.Id, salesAgreement.AccountId);           
            }
        }
        return mapSalesAgreementAccountId;
    }
    
    /**
     * @description this method is used to create a map of sales agreement id vs set of related sales area ids
     * @param mapSalesAgreementAccountId map of accountIds linked to Sales Agreement
     * @param mapAccountSalesArea map of sales area ids linked to account Ids
     * @return Map<Id, Set<Id>> map of <salesAgreementId, Set<SalesAreaId>>
     */
    private static Map<Id, Set<Id>> createSalesAgreeIdSalesAreaRelMap(Map<Id, Id> mapSalesAgreementAccountId, Map<Id, Set<Id>> mapAccountSalesArea){
		Map<Id, Set<Id>> mapSalesAgreementSalesArea = new Map<Id, Set<Id>>();
        for(Id salesAgreementId: mapSalesAgreementAccountId.KeySet()){
            Id accountId = mapSalesAgreementAccountId.get(salesAgreementId);
            if(mapAccountSalesArea.containsKey(accountId) && mapAccountSalesArea.get(accountId).size() > 0){
                mapSalesAgreementSalesArea.put(salesAgreementId, mapAccountSalesArea.get(accountId));
            }
        }
		return mapSalesAgreementSalesArea;
    }
}