objects/PMC_SS_Allocation__c.object
<CustomObject>
    <description>Custom object to store the quota allocation data from O9</description>
    <fields>
        <fullName>PMC_SS_AllocationPeriod__c</fullName>
        <description>Specifies the Allocation Period</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Allocation Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_SS_AllocationSummary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Specifies the Allocation Summary</description>
        <label>Allocation Summary</label>
        <referenceTo>PMC_SS_AllocationSummary__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_SS_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Specifies the Plant Location</description>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Location.PMC_CPQ_SAPLocationId__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Quota_Allocation_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_SS_ProductLocationAllocationKey__c</fullName>
        <description>Specifies the Product Location Allocation Period Key</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Location Allocation Period Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Specifies the Product</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.PMC_CPQ_SAPProductCode__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>PMC_SS_QuotaAllocationData</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PMC_SS_AllocationSummary__c.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_AllocationPeriod__c</fullName>
        <description>Specifies the Allocation Period</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Allocation Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_SS_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Specifies the Product plant Location</description>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Location.PMC_CPQ_SAPLocationId__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Allocation Summaries</relationshipLabel>
        <relationshipName>Allocation_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_SS_ProductLocationAllocationKey__c</fullName>
        <description>Specifies the Product Location Allocation Period Key</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Product Location Allocation Period Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PMC_SS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Specifies the Product</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.PMC_CPQ_SAPProductCode__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Allocation Summaries</relationshipLabel>
        <relationshipName>Allocation_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Allocation Summary</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Allocation Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocation Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PMC_SS_AllocationTriggerHelperExtension.cls
/**
* @description This class will be used to handle all trigger operations on PMC_SS_Allocation__c object
* @author Aravind Chaganti
* @storynumber : GDASF-16609 
* Test Class: PMC_SS_AllocationTriggerHandlerTest
*/
public with sharing class PMC_SS_AllocationTriggerHelperExtension {
    /**
     * @description This populates the Product, Location, Allocation Period on Allocation from Allocation Summary
     * @param lstAllocations List of Allocation records
    */
    public static void populateFieldsOnAllocation(List<PMC_SS_Allocation__c> lstAllocations){
        Set<Id> setAllocationSummaryIds= new Set<Id>();
        Map<Id,PMC_SS_AllocationSummary__c> mapAllocationSummary=new Map<Id,PMC_SS_AllocationSummary__c>();
        for(PMC_SS_Allocation__c alloc:lstAllocations){
            if(alloc.PMC_SS_AllocationSummary__c!=null){
                setAllocationSummaryIds.add(alloc.PMC_SS_AllocationSummary__c);
            }
        }
        for(PMC_SS_AllocationSummary__c allocSummary:[SELECT ID, PMC_SS_Product__c, PMC_SS_Location__c,PMC_SS_AllocationPeriod__c FROM PMC_SS_AllocationSummary__c WHERE ID IN :setAllocationSummaryIds WITH SECURITY_ENFORCED]){
            mapAllocationSummary.put(allocSummary.Id,allocSummary);
        }
        //Map<Id,PMC_SS_AllocationSummary__c> mapAllocationSummary=new Map<Id,PMC_SS_AllocationSummary__c>([SELECT ID, PMC_SS_Product__c, PMC_SS_Location__c, PMC_SS_AllocationPeriod__c FROM PMC_SS_AllocationSummary__c WITH SECURITY_ENFORCED WHERE ID IN :setAllocationSummaryIds]);
        for (PMC_SS_Allocation__c alloc:lstAllocations){
            if(alloc.PMC_SS_AllocationSummary__c!=null){
                alloc.PMC_SS_AllocationPeriod__c=mapAllocationSummary.get(alloc.PMC_SS_AllocationSummary__c).PMC_SS_AllocationPeriod__c;
                alloc.PMC_SS_Product__c=mapAllocationSummary.get(alloc.PMC_SS_AllocationSummary__c).PMC_SS_Product__c;
                alloc.PMC_SS_Location__c=mapAllocationSummary.get(alloc.PMC_SS_AllocationSummary__c).PMC_SS_Location__c;
            }
        }
    }
    
    /**
     * @description Creates a map of product location and period keys of allocations.
     * @param lstAllocations List of Allocation records
     * @return Set<String>
    */
    public static Set<String> createProductLocationKeySet(List<PMC_SS_Allocation__c> lstAllocations){
        Set<String>setProductLocationMonthKeys=new Set<String>();
        
        for(PMC_SS_Allocation__c alloc:lstAllocations){
            if(alloc.PMC_SS_ProductLocationAllocationKey__c!=null){
                setProductLocationMonthKeys.add(alloc.PMC_SS_ProductLocationAllocationKey__c);
            }    
        }
        
        return setProductLocationMonthKeys;
    }
    
}