objects/PMC_DH_Store_Configuration__mdt.object
<CustomObject>
    <fields>
        <fullName>PMC_DH_FieldsAPIName__c</fullName>
        <label>Field API Names</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>PMC DH Store Configuration</label>
    <pluralLabel>PMC DH Store Configurations</pluralLabel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_Nitrogen__c</fullName>
        <description>This field captures the Nitrogen % for the product.</description>
        <inlineHelpText>This field captures the Nitrogen % for the product.</inlineHelpText>
        <label>Nitrogen %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductFamily__c</fullName>
        <description>This field captures the product family for the product.</description>
        <inlineHelpText>This field captures the product family for the product.</inlineHelpText>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ATHOS</fullName>
                </value>
                <value>
                    <fullName>BASICA</fullName>
                </value>
                <value>
                    <fullName>BLENDS</fullName>
                </value>
                <value>
                    <fullName>BORON</fullName>
                </value>
                <value>
                    <fullName>Co-Product</fullName>
                    <label>CO-PRODUCT</label>
                </value>
                <value>
                    <fullName>DAP-MAP</fullName>
                </value>
                <value>
                    <fullName>EXCELLEN</fullName>
                </value>
                <value>
                    <fullName>FEED</fullName>
                </value>
                <value>
                    <fullName>Fluosilic Acid</fullName>
                </value>
                <value>
                    <fullName>GRAVEL</fullName>
                </value>
                <value>
                    <fullName>Gypsum</fullName>
                </value>
                <value>
                    <fullName>K-MAG</fullName>
                </value>
                <value>
                    <fullName>Limestone</fullName>
                </value>
                <value>
                    <fullName>Liquid Fert</fullName>
                </value>
                <value>
                    <fullName>MES</fullName>
                </value>
                <value>
                    <fullName>MES BLENDS</fullName>
                </value>
                <value>
                    <fullName>MICRO</fullName>
                </value>
                <value>
                    <fullName>MKP</fullName>
                </value>
                <value>
                    <fullName>MOP</fullName>
                </value>
                <value>
                    <fullName>MPASTO</fullName>
                </value>
                <value>
                    <fullName>N Blends</fullName>
                </value>
                <value>
                    <fullName>Nitrogen</fullName>
                </value>
                <value>
                    <fullName>NPK</fullName>
                </value>
                <value>
                    <fullName>NPK Blends</fullName>
                </value>
                <value>
                    <fullName>P Blends</fullName>
                </value>
                <value>
                    <fullName>PERFORMA BIO</fullName>
                </value>
                <value>
                    <fullName>PERFORMA BLENDS</fullName>
                </value>
                <value>
                    <fullName>P FERTILIZER</fullName>
                </value>
                <value>
                    <fullName>Phosphoric Acid</fullName>
                </value>
                <value>
                    <fullName>Rock</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductSegment__c</fullName>
        <label>Product Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BIOSCIENCE</fullName>
                </value>
                <value>
                    <fullName>Co-Product</fullName>
                </value>
                <value>
                    <fullName>Feed</fullName>
                </value>
                <value>
                    <fullName>Fertilizer</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductSubFamily__c</fullName>
        <description>This field captures the product sub family for the product</description>
        <inlineHelpText>This field captures the product sub family for the product.</inlineHelpText>
        <label>Product Sub Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMMONIA</fullName>
                </value>
                <value>
                    <fullName>APATITE</fullName>
                </value>
                <value>
                    <fullName>ASPIRE</fullName>
                </value>
                <value>
                    <fullName>ASPIRE FINE</fullName>
                </value>
                <value>
                    <fullName>ATHOS</fullName>
                </value>
                <value>
                    <fullName>BASICA</fullName>
                </value>
                <value>
                    <fullName>BORON</fullName>
                </value>
                <value>
                    <fullName>CFL ROCK</fullName>
                </value>
                <value>
                    <fullName>DAP</fullName>
                </value>
                <value>
                    <fullName>DAP-MAP</fullName>
                </value>
                <value>
                    <fullName>EXCELLEN</fullName>
                </value>
                <value>
                    <fullName>FEED</fullName>
                </value>
                <value>
                    <fullName>FLUOSILIC ACID</fullName>
                </value>
                <value>
                    <fullName>GRAVEL</fullName>
                </value>
                <value>
                    <fullName>GYPSUM</fullName>
                </value>
                <value>
                    <fullName>GYPSUM (AGRICULTURAL)</fullName>
                </value>
                <value>
                    <fullName>GYPSUM (CHEMICAL)</fullName>
                </value>
                <value>
                    <fullName>GYPSUM (CONSTRUCTION)</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>K BLENDS</fullName>
                </value>
                <value>
                    <fullName>KMAG BLENDS</fullName>
                </value>
                <value>
                    <fullName>KMAG GRANULAR</fullName>
                </value>
                <value>
                    <fullName>KMAG PREMIUM</fullName>
                </value>
                <value>
                    <fullName>KMAG SPECIAL</fullName>
                </value>
                <value>
                    <fullName>KMAG STANDARD</fullName>
                </value>
                <value>
                    <fullName>LIMESTONE</fullName>
                </value>
                <value>
                    <fullName>LIQUID FERT</fullName>
                </value>
                <value>
                    <fullName>MAGNETITE</fullName>
                </value>
                <value>
                    <fullName>MAP</fullName>
                </value>
                <value>
                    <fullName>MES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductTypes__c</fullName>
        <description>This will be used to store Product Hiearchy Informaiton.</description>
        <label>Product Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commodity</fullName>
                </value>
                <value>
                    <fullName>Co-Product</fullName>
                </value>
                <value>
                    <fullName>Intermediary</fullName>
                </value>
                <value>
                    <fullName>Performance</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                    <label>SERVICES</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_Micronutrients__c</fullName>
        <description>This field was created as part of story to handle/manage value for Micronutrient</description>
        <label>Micronutrient</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Boron</fullName>
                </value>
                <value>
                    <fullName>Chlorine</fullName>
                </value>
                <value>
                    <fullName>Cobalt</fullName>
                </value>
                <value>
                    <fullName>Copper</fullName>
                </value>
                <value>
                    <fullName>Iron</fullName>
                </value>
                <value>
                    <fullName>Manganese</fullName>
                </value>
                <value>
                    <fullName>Molybdenum</fullName>
                </value>
                <value>
                    <fullName>Silicone</fullName>
                </value>
                <value>
                    <fullName>Zinc</fullName>
                </value>
                <value>
                    <fullName>Calcium</fullName>
                </value>
                <value>
                    <fullName>Magnesium</fullName>
                </value>
                <value>
                    <fullName>Sulfur</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_Nitrogen__c</fullName>
        <label>Nitrogen(N)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0-5%</fullName>
                </value>
                <value>
                    <fullName>06-10%</fullName>
                </value>
                <value>
                    <fullName>11-15%</fullName>
                </value>
                <value>
                    <fullName>16-20%</fullName>
                </value>
                <value>
                    <fullName>21-25%</fullName>
                </value>
                <value>
                    <fullName>26-30%</fullName>
                </value>
                <value>
                    <fullName>31-35%</fullName>
                </value>
                <value>
                    <fullName>36-40%</fullName>
                </value>
                <value>
                    <fullName>41-45%</fullName>
                </value>
                <value>
                    <fullName>46-50%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_Phosphorous__c</fullName>
        <label>Phosphorous (P)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0-5%</fullName>
                </value>
                <value>
                    <fullName>06-10%</fullName>
                </value>
                <value>
                    <fullName>11-15%</fullName>
                </value>
                <value>
                    <fullName>16-20%</fullName>
                </value>
                <value>
                    <fullName>21-25%</fullName>
                </value>
                <value>
                    <fullName>26-30%</fullName>
                </value>
                <value>
                    <fullName>31-35%</fullName>
                </value>
                <value>
                    <fullName>36-40%</fullName>
                </value>
                <value>
                    <fullName>41-45%</fullName>
                </value>
                <value>
                    <fullName>46-50%</fullName>
                </value>
                <value>
                    <fullName>51-55%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_Potassium__c</fullName>
        <label>Potassium (K)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0-5%</fullName>
                </value>
                <value>
                    <fullName>06-10%</fullName>
                </value>
                <value>
                    <fullName>11-15%</fullName>
                </value>
                <value>
                    <fullName>16-20%</fullName>
                </value>
                <value>
                    <fullName>21-25%</fullName>
                </value>
                <value>
                    <fullName>26-30%</fullName>
                </value>
                <value>
                    <fullName>31-35%</fullName>
                </value>
                <value>
                    <fullName>36-40%</fullName>
                </value>
                <value>
                    <fullName>41-45%</fullName>
                </value>
                <value>
                    <fullName>46-50%</fullName>
                </value>
                <value>
                    <fullName>51-55%</fullName>
                </value>
                <value>
                    <fullName>56-60%</fullName>
                </value>
                <value>
                    <fullName>61-65%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_isProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a flag field, which will indicate if this product record is already processed or not</description>
        <label>Is Processed</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PMC_DH_ProductOnboardingBatch.cls
/**
 * @description       : Batch Class for Product Onboarding
 * @author            : Rohan Undale
 * @last modified on  : 01-08-2024
 * @last modified by  : Hemant Giri Goswami | hegoswami@deloitte.com
**/
public with sharing class PMC_DH_ProductOnboardingBatch implements Database.Batchable<sObject> {
    private final static string PRODUCT_MICRONUTRIENTS_FIELDS = 'PRODUCT_MICRONUTRIENTS_FIELDS';
    /**
     * @description method to store Product Ids
     * @return Set<String> 
     */
    //public static Set<String> setProdIdsChunk;
    /**
    * @description Start method of batchable
    * @param objBatchableContext
    * @return  Database.QueryLocator
    * @date 10-20-2023
    */
    public Database.QueryLocator start(Database.BatchableContext objBatchableContext) {
        
        PMC_DH_Store_Configuration__mdt micorNutriConfig = [SELECT Id,PMC_DH_FieldsAPIName__c, DeveloperName from PMC_DH_Store_Configuration__mdt Where DeveloperName=:PRODUCT_MICRONUTRIENTS_FIELDS];
        Map<String,String> mpdata= (Map<String,String>)JSON.deserialize(micorNutriConfig.PMC_DH_FieldsAPIName__c, Map<String,String>.Class);
        
        String query='SELECT Id, Name, PMC_DH_isProcessed__c, PMC_CPQ_ProductSegment__c,PMC_CPQ_ProductTypes__c,PMC_CPQ_ProductFamily__c, PMC_CPQ_ProductSubFamily__c,';
            query+=' PMC_DH_Micronutrients__c, PMC_DH_Nitrogen__c, PMC_DH_Phosphorous__c, PMC_DH_Potassium__c, PMC_CPQ_Nitrogen__c, PMC_CPQ_Phosphorous__c, PMC_CPQ_Potassium__c';
        if(!mpdata.isEmpty()){
            query += ', '+String.join(mpdata.KeySet(), ', ');
        }
        query+=' FROM Product2 WHERE PMC_DH_isProcessed__c=FALSE AND (PMC_CPQ_ProductSegment__c!=NULL AND PMC_CPQ_ProductTypes__c!=NULL AND PMC_CPQ_ProductFamily__c!=NULL AND PMC_CPQ_ProductSubFamily__c!=NULL ) WITH SYSTEM_MODE';
        
        
        return Database.getQueryLocator(query);
        /*return Database.getQueryLocator(
            [SELECT Id, Name, PMC_DH_isProcessed__c, 
            PMC_CPQ_ProductSegment__c,PMC_CPQ_ProductTypes__c,PMC_CPQ_ProductFamily__c,PMC_CPQ_ProductSubFamily__c,
            PMC_DH_Nitrogen__c, PMC_DH_Phosphorous__c, PMC_DH_Potassium__c, PMC_CPQ_Nitrogen__c, PMC_CPQ_Phosphorous__c, PMC_CPQ_Potassium__c
            FROM Product2 
            WHERE PMC_DH_isProcessed__c=FALSE and (PMC_CPQ_ProductSegment__c!=null 
            and PMC_CPQ_ProductTypes__c!=null and PMC_CPQ_ProductFamily__c!=null and PMC_CPQ_ProductSubFamily__c!=null ) //for proper data-alignment
            WITH SYSTEM_MODE
            ]);*/
    }
    /**
    * @description execute method of batchable
    * @param objBatchableContext
    * @param lstProduct
    * @date 10-20-2023
    */
    public void execute(Database.BatchableContext objBatchableContext , List<Product2> lstProduct){
        PMC_DH_ProductOnboardingBatchHelper.executeHelper(lstProduct);
    }
    /**
    * @description finish method of batchable
    * @param objBatchableContext
    * @date 10-20-2023
    */
    public void finish(Database.BatchableContext objBatchableContext){
       // here it will call the batch indexing Job
       Database.executeBatch(new PMC_DH_UpdateEntitlementPolicyBatch());
    }


    
    /**
    * @description execute method of Schedulable
    * @param objSchedulableContext
    * @date 10-20-2023
    *
    public void execute(SchedulableContext objSchedulableContext){
        PMC_DH_Store_Configuration__mdt config = PMC_DH_Store_Configuration__mdt.getInstance('Batch_Size');
        Database.executeBatch(new PMC_DH_ProductOnboardingBatch(), Integer.Valueof(config.PMC_DH_Batch_Size__c));
    }*/

     /**
    * @description method to get the All Micro Nutrinets 
    * @param pro
    * @return String
    * @author Sugunakar ROuthu
    * @date 05-03-2024
    */
    
    public static String populateMicroNutrinents(Product2 pro){
        List<String> lsteligibleNutirents = new List<String>();
        PMC_DH_Store_Configuration__mdt micorNutriConfig = [SELECT Id,PMC_DH_FieldsAPIName__c, DeveloperName from PMC_DH_Store_Configuration__mdt Where DeveloperName=:PRODUCT_MICRONUTRIENTS_FIELDS WITH USER_MODE];
        Map<String,String> mpdata= (Map<String,String>)JSON.deserialize(micorNutriConfig.PMC_DH_FieldsAPIName__c, Map<String,String>.Class);
        for(String mn : mpdata.KeySet()){
            Decimal decPercentage = (Decimal)pro.get(mn);
            if( decPercentage > 0){
                lsteligibleNutirents.add(mpdata.get(mn));
            }
        }
        return String.join(lsteligibleNutirents,';');
    } 

}