objects/PMC_CPQ_ProductLocation__c.object
<CustomObject>
    <description>This object is created as a part of  story to capture product and location data.</description>
    <label>Product Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>PMC_CPQ_PackType__c</fullName>
        <description>This field captures the Pack type of the product associated.</description>
        <label>Pack Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Packed</fullName>
                </value>
                <value>
                    <fullName>Bulk</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_PackageType__c</fullName>
        <description>This field captures the package type for the product associated.</description>
        <label>Packaging Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_PackagingType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field captures the Location of the product.</description>
        <label>Product Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SBQQ__Product__c</field>
                <operation>equals</operation>
                <valueField>PMC_CPQ_ProductLocation__c.PMC_CPQ_ProductName__c</valueField>
            </filterItems>
            <filterItems>
                <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Origin Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductPackTypeIndicator__c</fullName>
        <formula>IF(!ISPICKVAL(  SBQQ__Product__r.PMC_CPQ_PackType__c  , &apos;&apos;) , true , false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product PackType Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductPackageTypeIndicator__c</fullName>
        <description>This field is to indicate if the Package Type on Product is loaded or not.</description>
        <formula>IF(!ISPICKVAL( SBQQ__Product__r.PMC_CPQ_PackageType__c , &apos;&apos;) ,  true , false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product PackageType Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProductLocation_Location__c</fullName>
        <formula>PMC_CPQ_ProductLocation__r.PMC_CPQ_Location__c</formula>
        <label>ProductLocation-Location(Backend)Formula</label>
        <type>Text</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/PMC_CPQ_PackagingType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Big Bag 1500 Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Saco 50 Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Saco 50 Kg - Paletizado</fullName>
    </customValue>
    <customValue>
        <fullName>Big Bag 1000 Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Saco 30 Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Saco 25 Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Big Bag 1350 Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Saco 25 Kg - Paletizado</fullName>
    </customValue>
    <customValue>
        <fullName>Transp. Valved NPK</fullName>
    </customValue>
    <customValue>
        <fullName>Transp. Valved Urea</fullName>
    </customValue>
    <customValue>
        <fullName>Braided   Valved</fullName>
    </customValue>
    <customValue>
        <fullName>BagOneWay 90x90x1,30</fullName>
    </customValue>
    <customValue>
        <fullName>BagOneWay 500Kg</fullName>
    </customValue>
    <customValue>
        <fullName>BagOneWay Liner 1,40</fullName>
    </customValue>
    <customValue>
        <fullName>Bag ONE-Way-Liner Urea 99x99x1,40</fullName>
    </customValue>
    <customValue>
        <fullName>Bag One Way Liner 500kg Liner 90X</fullName>
    </customValue>
    <customValue>
        <fullName>Tranç. Nitrog. Laminated</fullName>
    </customValue>
    <customValue>
        <fullName>Tranç. Urea Laminated</fullName>
    </customValue>
    <customValue>
        <fullName>BagOneWayLiner 750kg</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk</fullName>
    </customValue>
    <customValue>
        <fullName>Sifted Bulk</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk - Mosiac Production</fullName>
        <label>Bulk - Mosaic Production</label>
    </customValue>
    <customValue>
        <fullName>Big BagOneWay Liner</fullName>
    </customValue>
    <customValue>
        <fullName>Saco 30 Kg - Paletizado</fullName>
    </customValue>
    <customValue>
        <fullName>1000 KG Bags</fullName>
    </customValue>
    <customValue>
        <fullName>25KG Bags</fullName>
    </customValue>
    <customValue>
        <fullName>50KG Bags</fullName>
    </customValue>
    <customValue>
        <fullName>Trançada com Liner</fullName>
    </customValue>
    <customValue>
        <fullName>test</fullName>
        <isActive>false</isActive>
        <label>test</label>
    </customValue>
    <customValue>
        <fullName>saco 50kg</fullName>
        <isActive>false</isActive>
        <label>saco 50kg</label>
    </customValue>
    <description>The Packaging Type of the Product added to the quote.</description>
    <masterLabel>Packaging Type</masterLabel>
</GlobalValueSet>

classes/MassUpdateQuoteLinesHandler.cls
/**
* @File Name : MassUpdateQuoteLinesHandler.cls
* @Description :
* @Author : Kaushik  Gohain
* @Last Modified By :
* @Last Modified On : March 3 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | March 3, 2025 |   | Initial Version
**/

public class MassUpdateQuoteLinesHandler {
    
    public static void massUpdateQuoteLines(List<SBQQ__QuoteLine__c> quoteLineItemNewList, Map<Id,SBQQ__QuoteLine__c> quoteLineItemoldMap) {
        for(SBQQ__QuoteLine__c quoteLine : quoteLineItemNewList) {
           /* if(quoteLine.PMC_CPQ_ProductPackTypeIndicator__c )   
            {
                quoteLine.PMC_CPQ_PackType__c = quoteLineItemoldMap.get(quoteLine.Id).PMC_CPQ_PackType__c; 
            }
            if(quoteLine.PMC_CPQ_ProductPackageTypeIndicator__c || quoteline.PMC_CPQ_PackType__c =='Bulk')  {
                quoteLine.PMC_CPQ_PackageType__c = quoteLineItemoldMap.get(quoteLine.Id).PMC_CPQ_PackageType__c; 
            } */
            
            if(quoteLine.ProductLocation_Location__c != null) {
                quoteLine.PMC_CPQ_ProductLocation__c = quoteLineItemoldMap.get(quoteLine.Id).PMC_CPQ_ProductLocation__c; 
            }
        }
    }
}