objects/PMC_CPQ_TransactionLog__c.object
<CustomObject>
    <description>This object is used to store transactions details based on SF intergation with external systems.</description>
    <fields>
        <fullName>PMC_CPQ_IntegrationStatus__c</fullName>
        <description>This will show the status of the response of the external callout.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_InterfaceURL__c</fullName>
        <description>This is the endpoint that was hit during the transaction.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Interface URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RequestBody__c</fullName>
        <description>This is the request body sent to the external system.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Request Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ResponseBody__c</fullName>
        <description>This field stores the response body of the request made to the external system.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Response Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TRL-{0000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PMC_CPQ_TransactionLogUtilityClass.cls
/** @description This is a utility class for transaction logs.
 *  @author Shefali Dsouza
 *  @storynumber GDASF-2983
 */
public without sharing class PMC_CPQ_TransactionLogUtilityClass {
    
    public static List<PMC_CPQ_TransactionLog__c> lstTransactionLogs = new List<PMC_CPQ_TransactionLog__c>();
    /** 
     * @description This class is used to add a trasaction log to the list of transaction logs.
     * @param mapTransactionLogFields - Send integration fields. 
     * @return lstTransactionLogs - Add to list of transaction logs.
     */
    public static List<PMC_CPQ_TransactionLog__c> addTransactionLog(Map<String, String> mapTransactionLogFields)
    {
        PMC_CPQ_TransactionLog__c trl = new PMC_CPQ_TransactionLog__c();
        trl.PMC_CPQ_IntegrationStatus__c = mapTransactionLogFields.get('PMC_CPQ_IntegrationStatus__c');
        trl.PMC_CPQ_InterfaceURL__c = mapTransactionLogFields.get('PMC_CPQ_InterfaceURL__c');
        trl.PMC_CPQ_RequestBody__c = mapTransactionLogFields.get('PMC_CPQ_RequestBody__c');
        trl.PMC_CPQ_ResponseBody__c = mapTransactionLogFields.get('PMC_CPQ_ResponseBody__c').abbreviate(131065);
        lstTransactionLogs.add(trl);
        return lstTransactionLogs;
    }
     /** 
     * @description This class is used to insert the transaction log.
     * @param lstTransactionLogs - List of transaction logs
     */
    public static void insertTransactionLogs(List<PMC_CPQ_TransactionLog__c> lstTransactionLogs)
    {
        SObjectAccessDecision securityDecisionTrl = Security.stripInaccessible(AccessType.CREATABLE, lstTransactionLogs);
        Database.insert(securityDecisionTrl.getRecords(),false);
    }   
}