objects/PMC_CPQ_RawMaterial__c.object
<CustomObject>
    <description>This Object is to store the details of the Blended Components.</description>
    <fields>
        <fullName>PMC_CPQ_ListCFR__c</fullName>
        <description>This field is to store the List CFR amount.</description>
        <label>List CFR (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductSKU__c</fullName>
        <description>This field is to show the SKU of the Product.</description>
        <formula>PMC_CPQ_Product__r.StockKeepingUnit</formula>
        <label>Product SKU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Raw Materials</relationshipLabel>
        <relationshipName>Raw_Materials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_QuantityTons__c</fullName>
        <formula>( PMC_CPQ_Quantity__c ) * PMC_CPQ_QuoteLine__r.SBQQ__Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quantity Tons</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Quantity__c</fullName>
        <description>This field is to store the returned quantity from the blend optimizer for that component.</description>
        <label>Quantity</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to store the respective Quote Line.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Raw Materials</relationshipLabel>
        <relationshipName>Raw_Materials1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SoldCFR__c</fullName>
        <description>This field is to store the Sold CFR</description>
        <label>Sold CFR (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Raw Material</label>
    <nameField>
        <displayFormat>RM-{0000000000}</displayFormat>
        <label>Raw Material Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Raw Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sbaa__Approval__c.object
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <fields>
        <fullName>PMC_CPQ_Product__c</fullName>
        <formula>OrderItem__r.Product2.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Quantity__c</fullName>
        <formula>OrderItem__r.Quantity</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Approvals (Quote)</relationshipLabel>
        <relationshipName>Approvals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CPQ_AccountCountry__c</fullName>
        <description>Field to store Account Country</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ContractEnd__c</fullName>
        <description>If Master contract exists - then formula to pull the date from Contract reference</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Quote End Date</inlineHelpText>
        <label>Contract Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_QuoteShortNameDescription__c</fullName>
        <description>Based on the stanadardized Quote description across all quotes</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Quote Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RawMaterial1ListCFR__c</fullName>
        <description>This field is for Raw Material 1 List CFR</description>
        <label>Raw Material 1 Average List CFR (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RawMaterial1SoldCFR__c</fullName>
        <label>Raw Material 1 Average Sold CFR (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RawMaterial2ListCFR__c</fullName>
        <label>Raw Material 2 Average List CFR (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RawMaterial2SoldCFR__c</fullName>
        <label>Raw Material 2 Average Sold CFR (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RawMaterialName1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Raw Material 1 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RawMaterialName2__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Raw Material 2 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RawMaterialQuantity1__c</fullName>
        <label>Raw Material 1 Quantity</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RawMaterialQuantity2__c</fullName>
        <label>Raw Material 2 Quantity</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>Account for which this quote has been created.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>PMC_CPQ_ListCFR__c</fullName>
        <label>List CFR (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RawMaterial1ListCFR__c</fullName>
        <label>Raw Material 1 List CFR</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RawMaterial1SoldCFR__c</fullName>
        <label>Raw Material 1 Sold CFR</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RawMaterial2ListCFR__c</fullName>
        <label>Raw Material 2 List CFR</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RawMaterial2SoldCFR__c</fullName>
        <label>Raw Material 2 Sold CFR</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RawMaterialName1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Raw Material Name 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RawMaterialName2__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Raw Material Name 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RawMaterialQuantity1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Raw Material Quantity 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RawMaterialQuantity2__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Raw Material Quantity 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SoldCFR__c</fullName>
        <label>Sold CFR (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductName__c</fullName>
        <description>Name for the product referenced by this line item.</description>
        <formula>SBQQ__Product__r.Name</formula>
        <inlineHelpText>Name for the product referenced by this line item.</inlineHelpText>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PMC_CPQ_RawMaterialSummary.cls
/**
* @description This class will be used to Update the Rawmaterial Summary Information to the Quote Record..
* @author Jeyanthi Muthaiah
* @storynumber : GDASF-7851,GDASF-18765
*/

public with sharing class PMC_CPQ_RawMaterialSummary {
    

    /**
* @description rawMaterialQuantitySum -to store the Sum of Quantity Tons of Same Raw Materilas which have same Product SKU
**/
    
    public static Map<String, Decimal> rawMaterialQuantitySum=new Map<String,Decimal>();
 
    /**
* @description rawMaterialListCFRAvg -to store the Avg ListCFR of Same Raw Materilas which have same Product SKU
*/ 
    
    public static Map<String, Decimal> rawMaterialListCFRAvg = new Map<String,Decimal>();

    /**
* @description rawMaterialSoldCFRAvg -to store the Avg SoldCFR of Same Raw Materilas which have same Product SKU
*/
    
    public static Map<String, Decimal> rawMaterialSoldCFRAvg = new Map<String,Decimal>(); 

    /**
* @description rawMaterialName -to store the Names of Raw Materilas which have same Product SKU
*/
    
    public static Map<String, String> rawMaterialName=new Map<String,String>(); 

    /**
* @description rawMaterialSumsKey -to store the Unique Raw Materials in a List
*/
    
    public static Set<String> rawMaterialSumsKey= new Set<String>();
    
    
    /**
* @description This method will be used get the Rawmaterial information of the Quote.
* @param recordid - holds the current quote ID
*/
    
    public static void rawMaterialInfo(Id recordid) {
        
        SBQQ__Quote__c quoteInfo= new SBQQ__Quote__c();
        List<SBQQ__QuoteLine__c> qLines= new List<SBQQ__QuoteLine__c>();
        List<SBQQ__QuoteLine__c> blendedProducts = new List<SBQQ__QuoteLine__c>();
        
        // Get Quote Info
        quoteInfo = [SELECT id,PMC_CPQ_RawMaterialName1__c,PMC_CPQ_RawMaterialName2__c,PMC_CPQ_RawMaterialQuantity1__c,PMC_CPQ_RawMaterialQuantity2__c,PMC_CPQ_RawMaterial2ListCFR__c,PMC_CPQ_RawMaterial1SoldCFR__c,PMC_CPQ_RawMaterial2SoldCFR__c,PMC_CPQ_RawMaterial1ListCFR__c,PMC_CPQ_QuoteShortNameDescription__c,CurrencyIsoCode,PMC_CPQ_ContractEnd__c,CreatedDate,PMC_CPQ_AccountCountry__c,SBQQ__Account__r.Name,                        
                     (select CreatedDate from Approvals1__r) from SBQQ__Quote__c where ID =: recordid WITH SECURITY_ENFORCED];
        
        //Get Quote line Info
        qLines = [SELECT id,SBQQ__ProductName__c,(select PMC_CPQ_Product__r.Name, PMC_CPQ_ListCFR__c,PMC_CPQ_SoldCFR__c,PMC_CPQ_Quantity__c,PMC_CPQ_QuantityTons__c,PMC_CPQ_ProductSKU__c from Raw_Materials1__r)
                  from SBQQ__QuoteLine__c where SBQQ__Quote__c =: recordid WITH SECURITY_ENFORCED];
        // Get blended products among quotelines
        for (SBQQ__QuoteLine__c blendedProduct : qLines) {
            if (blendedProduct.Raw_Materials1__r.size() > 0) {
                
                blendedProducts.add(blendedProduct);
            }
        }
        
        calculateRawMaterialSummary(blendedProducts,quoteInfo);
        
    }

    /**
* @description This method will be used Calculate RM Summary Information on Quote.
* @param blendedProducts - holds the blended product records.
* @param quoteInfo - holds the Quote info.
*/ 
    
    public static void calculateRawMaterialSummary(List<SBQQ__QuoteLine__c> blendedProducts,SBQQ__Quote__c quoteInfo) {
     
        Map<String, Decimal> rawMaterialListCFRSum=new Map<String,Decimal>(); 
        Map<String, Decimal> rawMaterialSoldCFRSum=new Map<String,Decimal>(); 
    
        
        for (SBQQ__QuoteLine__c blendedProduct : blendedProducts) {
            for (PMC_CPQ_RawMaterial__c blendedProductInfo : blendedProduct.Raw_Materials1__r) {
                String rawMaterialSKU = blendedProductInfo.PMC_CPQ_ProductSKU__c;
                Decimal quantity = blendedProductInfo.PMC_CPQ_QuantityTons__c;
                Decimal listCFR = blendedProductInfo.PMC_CPQ_ListCFR__c;
                Decimal soldCFR = blendedProductInfo.PMC_CPQ_SoldCFR__c;
                Decimal totalListCFR = quantity*listCFR;
                Decimal totalSoldCFR = quantity*soldCFR;
                String nameofRM = blendedProductInfo.PMC_CPQ_Product__r.Name;
                
                
                if (rawMaterialQuantitySum.containsKey(rawMaterialSKU)) {
                    rawMaterialQuantitySum.put(rawMaterialSKU, rawMaterialQuantitySum.get(rawMaterialSKU) + quantity);
                    rawMaterialListCFRSum.put(rawMaterialSKU, rawMaterialListCFRSum.get(rawMaterialSKU) + totalListCFR);
                    rawMaterialSoldCFRSum.put(rawMaterialSKU, rawMaterialSoldCFRSum.get(rawMaterialSKU) + totalSoldCFR);
                } else {
                    rawMaterialQuantitySum.put(rawMaterialSKU, quantity);
                    rawMaterialListCFRSum.put(rawMaterialSKU, totalListCFR);
                    rawMaterialSoldCFRSum.put(rawMaterialSKU, totalSoldCFR);
                }
                rawMaterialName.put(rawMaterialSKU,nameofRM) ;
            }
        }
        
        rawMaterialSumsKey = rawMaterialQuantitySum.keySet();        
        for(String keys :rawMaterialSumsKey){           
            rawMaterialListCFRAvg.put(keys,rawMaterialListCFRSum.get(keys)/rawMaterialQuantitySum.get(keys));
            rawMaterialSoldCFRAvg.put(keys,rawMaterialSoldCFRSum.get(keys)/rawMaterialQuantitySum.get(keys));          
        }
       
        updateRawMaterialSummary(quoteInfo);
        
    }

   /**
* @description This method will be used  Update RM Summary Information on Quote.
* @param quoteInfo - holds the Quote info.
*/ 
    
    public static void updateRawMaterialSummary(SBQQ__Quote__c quoteInfo){
        try{
            SBQQ__Quote__c quotetoUpadte= new SBQQ__Quote__c();
            
            //Reset Rawmaterial Summary Fields
            decimal j=1;  
            for(j=1;j<=10;j++){
                String rawMaterialNames= 'PMC_CPQ_RawMaterialName'+j+'__c';
                String rawMaterialQuantitys= 'PMC_CPQ_RawMaterialQuantity'+j+'__c'; 
                String rawMaterialListCFR= 'PMC_CPQ_RawMaterial'+j+'ListCFR'+'__c';
                String rawMaterialSoldCFR= 'PMC_CPQ_RawMaterial'+j+'SoldCFR'+'__c';
                quotetoUpadte.put(RawMaterialNames,null);
                quotetoUpadte.put(RawMaterialQuantitys,null);
                quotetoUpadte.put(RawMaterialListCFR,null);  
                quotetoUpadte.put(RawMaterialSoldCFR,null);
                
            }
            // Update the Calculated Vaues to the Raw Material Field
            decimal i=1;         
            for(String keys :rawMaterialSumsKey){
                if(i<=10){
                    String rawMaterialNames= 'PMC_CPQ_RawMaterialName'+i+'__c';
                    String rawMaterialQuantitys= 'PMC_CPQ_RawMaterialQuantity'+i+'__c'; 
                    String rawMaterialListCFR= 'PMC_CPQ_RawMaterial'+i+'ListCFR'+'__c';
                    String rawMaterialSoldCFR= 'PMC_CPQ_RawMaterial'+i+'SoldCFR'+'__c';
                    quotetoUpadte.id=quoteInfo.id;               
                    quotetoUpadte.put(RawMaterialNames,rawMaterialName.get(keys));
                    quotetoUpadte.put(RawMaterialQuantitys,rawMaterialQuantitySum.get(keys));
                    quotetoUpadte.put(RawMaterialListCFR,rawMaterialListCFRAvg.get(keys));  
                    quotetoUpadte.put(RawMaterialSoldCFR,rawMaterialSoldCFRAvg.get(keys));
                    i++;
                }
            }
            //System.Debug(quotetoUpadte);
            if(Schema.sObjectType.SBQQ__Quote__c.isAccessible() 
               && Schema.sObjectType.SBQQ__Quote__c.isUpdateable()
              )
            {
                update quotetoUpadte;
            }
            
        }
        catch(DmlException objException){
            PMC_ErrorLogClass.processException(objException);
        } 
    }
    
    
  
    
}