objects/PMC_SS_CasePriorityAssignment__mdt.object
<CustomObject>
    <description>This metadata is used to set the Case priority based on Case Type And Account Segmentation.</description>
    <fields>
        <fullName>PMC_SS_Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                    <default>true</default>
                    <label>High</label>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_Segmentation__c</fullName>
        <label>Segmentation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Strategic</fullName>
                    <default>true</default>
                    <label>Strategic</label>
                </value>
                <value>
                    <fullName>Core</fullName>
                </value>
                <value>
                    <fullName>Base</fullName>
                </value>
                <value>
                    <fullName>Prime</fullName>
                </value>
                <value>
                    <fullName>Ultra</fullName>
                </value>
                <value>
                    <fullName>Grow</fullName>
                </value>
                <value>
                    <fullName>Basic</fullName>
                </value>
                <value>
                    <fullName>Mega Farmers</fullName>
                </value>
                <value>
                    <fullName>Top Farmers</fullName>
                </value>
                <value>
                    <fullName>Farmers</fullName>
                </value>
                <value>
                    <fullName>Mid Farmers</fullName>
                </value>
                <value>
                    <fullName>Small Farmers</fullName>
                </value>
                <value>
                    <fullName>Key</fullName>
                </value>
                <value>
                    <fullName>Canal KAM</fullName>
                    <label>Canal - KAM</label>
                </value>
                <value>
                    <fullName>Trader KAM</fullName>
                    <label>Trader - KAM</label>
                </value>
                <value>
                    <fullName>Mega Farmer KAM</fullName>
                    <label>EU - KAM Mega Farmer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Shipping</fullName>
                    <default>true</default>
                    <label>Shipping</label>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Mosaic Direct</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Transactions</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                    <isActive>false</isActive>
                    <label>Billing</label>
                </value>
                <value>
                    <fullName>Internal Request</fullName>
                    <isActive>false</isActive>
                    <label>Internal Request</label>
                </value>
                <value>
                    <fullName>NPK Blend Request</fullName>
                    <isActive>false</isActive>
                    <label>NPK Blend Request</label>
                </value>
                <value>
                    <fullName>New Product Registration</fullName>
                    <isActive>false</isActive>
                    <label>New Product Registration</label>
                </value>
                <value>
                    <fullName>Order</fullName>
                    <isActive>false</isActive>
                    <label>Order</label>
                </value>
                <value>
                    <fullName>Technical</fullName>
                    <isActive>false</isActive>
                    <label>Technical</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PMC SS Case Priority Assignment</label>
    <pluralLabel>PMC SS Case Priority Assignments</pluralLabel>
</CustomObject>

classes/PMC_CasePriorityAssignmentSelector.cls
/**
* @description This class will be used to handle all the PMC_SS_CasePriorityAssignment__mdt related queries.
* @author Sayali Shinde
*/

public class PMC_CasePriorityAssignmentSelector extends fflib_SObjectSelector implements PMC_ICasePriorityAssignmentSelector {

    /** 
     * @description Application Selector Factory Instance for PMC_SS_CasePriorityAssignment__mdt Object
     */
    
	public static final fflib_Application.SelectorFactory objSelector = new fflib_Application.SelectorFactory(new Map<SObjectType, Type> {
																		PMC_SS_CasePriorityAssignment__mdt.SObjectType => PMC_CasePriorityAssignmentSelector.class });
	
    
	/** 
     * @description Instance for PMC_CasePriorityAssignmentSelector
    */
    
    public static PMC_CasePriorityAssignmentSelector newInstance() {
        return (PMC_CasePriorityAssignmentSelector) objSelector.newInstance(PMC_SS_CasePriorityAssignment__mdt.SObjectType);
    }
    
    /**
     * @description This is a mandatory method of fflib Selector layer. 
     * Indicating which SObject the selector is for
     */
    
	public Schema.SObjectType getSObjectType() {
		return PMC_SS_CasePriorityAssignment__mdt.SObjectType;
	}  
    
    
    /**
     * @description This is a mandatory method of fflib Selector layer. 
     * Indicating which fields should be selected from current SObject.
     */
	
	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			PMC_SS_CasePriorityAssignment__mdt.MasterLabel,
			PMC_SS_CasePriorityAssignment__mdt.PMC_SS_Priority__c,
            PMC_SS_CasePriorityAssignment__mdt.PMC_SS_Segmentation__c,
            PMC_SS_CasePriorityAssignment__mdt.PMC_SS_Type__c
		};
	}
    

  	/**
     * @description This method is used to retrieve all PMC_SS_CasePriorityAssignment__mdt records. 
     */   
    
    public List<PMC_SS_CasePriorityAssignment__mdt> getCasePriorityAssignmentMetadata() {
        fflib_QueryFactory objQueryFactory = newQueryFactory();
        return (List<PMC_SS_CasePriorityAssignment__mdt>) Database.query(objQueryFactory.toSOQL());    
    }
}