objects/PMC_DH_IntegrationSettings__mdt.object
<CustomObject>
    <description>Configuration for Digital Hub ( Mosaic Direct ) to store all the API related configurations</description>
    <fields>
        <fullName>PMC_DH_Accept__c</fullName>
        <label>Accept</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_Authorization__c</fullName>
        <label>Authorization</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PMC_DH_CachedTime__c</fullName>
        <inlineHelpText>Maximum allowed cached time : 172800 secs</inlineHelpText>
        <label>Cached Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_DH_CalloutMethod__c</fullName>
        <label>Callout Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GET</fullName>
                    <default>true</default>
                    <label>GET</label>
                </value>
                <value>
                    <fullName>PATCH</fullName>
                </value>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_ClientId__c</fullName>
        <label>ClientId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_ClientSecret__c</fullName>
        <label>ClientSecret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_ContentType__c</fullName>
        <label>Content Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_EndpointURL__c</fullName>
        <label>Endpoint URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_RefreshToken__c</fullName>
        <label>Refresh Token</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PMC_DH_RetryCount__c</fullName>
        <label>Retry Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_DH_RetryTimeout__c</fullName>
        <inlineHelpText>The time is in seconds</inlineHelpText>
        <label>Retry Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_DH_Timeout__c</fullName>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Digital Hub Integration</label>
    <pluralLabel>Digital Hub Integrations</pluralLabel>
</CustomObject>

objects/PMC_Shipment_Data__c.object
<CustomObject>
    <fields>
        <fullName>PMC_BOLNUMBER__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>BOLNUMBER</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_BOL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>BOL</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_COMMENTS__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>COMMENTS</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SAPDeliveryID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Delivery Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_Shipment_PO__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Shipment PO</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PMC_CURRENTCARRIER__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CURRENTCARRIER</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_CUSTORDERNO__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CUSTORDERNO</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DELIVERYNUMBER__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DELIVERYNUMBER</label>
        <length>252</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DESTINATIONCARRIER__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DESTINATIONCARRIER</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DESTINATIONMM__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DESTINATIONMM</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_Deliveries_Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deliveries Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMC_EQUIPMENTID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>EQUIPMENTID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_ETA__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ETA</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PMC_FLEETTOWNAME__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>FLEETTOWNAME</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_LATESTINTERNALCOMMENT__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>LATESTINTERNALCOMMENT</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_LATESTTRIPSIGHTINGID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>LATESTTRIPSIGHTINGID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_PONUMBER__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PONUMBER</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SHIPMENTNUMBER_CNTORDER__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SHIPMENTNUMBER_CNTORDER</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SIGHTINGDESTINATION__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SIGHTINGDESTINATION</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_SIGHTINGLOADOREMPTY__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SIGHTINGLOADOREMPTY</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Shipment Data</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipment Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipment.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_SAPDeliveryID__c</fullName>
        <description>This field captures the sap Delivery ID.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SAP Delivery ID</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PMC_CPQ_FetchAndStoreData.cls
public class PMC_CPQ_FetchAndStoreData implements Schedulable {

    public void execute(SchedulableContext sc) {
        // Make callouts to API, process data, and insert records in intellitrans shipment
        fetchAndInsertData();
        //Database.executeBatch(new PMC_IntellitransShipmentBatchUpdate(), 200);
    }
    private static final String GETTOKENNAME = 'IntelliTransGetToken';
    private static final String GETSHIPPMENTNAME = 'IntelliTransGetShipmentData';
    
    
    
    
    public static PMC_DH_IntegrationSettings__mdt getIntegrationSettings(String developerName) {
        PMC_DH_IntegrationSettings__mdt integrationSettings = [
            SELECT 
                Id, 
                DeveloperName,
                PMC_DH_CalloutMethod__c,
                PMC_DH_ContentType__c,
                PMC_DH_EndpointURL__c,
                PMC_DH_RefreshToken__c,
                PMC_DH_Accept__c,
                PMC_DH_RetryCount__c, 
                PMC_DH_RetryTimeout__c,
                PMC_DH_Timeout__c,
                PMC_DH_Authorization__c,
                PMC_DH_CachedTime__c,
                PMC_DH_ClientId__c,
                PMC_DH_ClientSecret__c
            FROM
                PMC_DH_IntegrationSettings__mdt 
            WHERE 
                DeveloperName =: developerName 
            WITH USER_MODE
            LIMIT 1
        ];

        return integrationSettings;
    }

    public class ShipmentData {
        @AuraEnabled public String DELIVERYNUMBER { get; set; }
        @AuraEnabled public String EQUIPMENTID { get; set; }
        @AuraEnabled public Datetime ETA { get; set; }
        @AuraEnabled public String BOL { get; set; }
        @AuraEnabled public String BOLNUMBER { get; set; }
        @AuraEnabled public String CUSTORDERNO { get; set; }
        @AuraEnabled public String SHIPMENTNUMBER_CNTORDER { get; set; }
        @AuraEnabled public String PONUMBER { get; set; }
        @AuraEnabled public String CURRENTCARRIER { get; set; }
        @AuraEnabled public String DESTINATIONCARRIER { get; set; }
        @AuraEnabled public String FLEETTOWNAME { get; set; }
        @AuraEnabled public String COMMENTS { get; set; }
        @AuraEnabled public String SIGHTINGLOADOREMPTY { get; set; }
        @AuraEnabled public String CURRENTLOCATION { get; set; }
        @AuraEnabled public String DESTINATIONMM { get; set; }
        @AuraEnabled public String LATESTTRIPSIGHTINGID { get; set; }
        @AuraEnabled public String LATESTINTERNALCOMMENT { get; set; }
        @AuraEnabled public String SIGHTINGDESTINATION { get; set; }
        @AuraEnabled public Double LATITUDE { get; set; }
        @AuraEnabled public Double LONGITUDE { get; set; }
    }
    
    @future(callout=true)
    public static void fetchAndInsertData() {
         String token;
        PMC_DH_IntegrationSettings__mdt getTokenIntegrationSettings = getIntegrationSettings(GETTOKENNAME);
         
        Map<String,Object> mapResponse;
       
        Map<String,String> headersMap = new Map<String,String>();
        List<PMC_CPQ_FetchAndStoreData.ShipmentData> shipmentDataList;
        Map<String, String> bodyMap = new Map<String, String>();
        HttpRequest request = new HttpRequest();
         Http http = new Http();
        HttpResponse response = new HttpResponse();

       
		
		Integer intTimeoutValue = 120000;
        
        request.setMethod('GET');
        request.setTimeout(intTimeoutValue);
        request.setEndpoint(getTokenIntegrationSettings.PMC_DH_EndpointURL__c);
        request.setHeader('loginid',getTokenIntegrationSettings.PMC_DH_ClientId__c);
		request.setHeader('pwd',getTokenIntegrationSettings.PMC_DH_ClientSecret__c);		
        request.setHeader('Content-Type',getTokenIntegrationSettings.PMC_DH_ContentType__c);
        
          try {
         response = http.send(request);
			 if(response.getStatusCode() == 200) {
                
                token = (String)JSON.deserializeUntyped(response.getBody());
            }
            else {
                token = '';
            }}
        catch(PMC_DH_Validation.CustomException ex){
            throw new PMC_DH_Validation.CustomException('Callout Failed');
        }
        catch (Exception ex) {
            throw  new AuraHandledException(ex.getMessage());
        }


        request = new HttpRequest();
        http = new Http();
        response = new HttpResponse();



        getTokenIntegrationSettings = getIntegrationSettings(GETSHIPPMENTNAME);
        bodyMap.put('equipmentNumbers', '');
        bodyMap.put('shipDateFrom', '');
        bodyMap.put('shipDateTo', '');
        bodyMap.put('searchTemplateName', 'Salesforce API');
        bodyMap.put('resultTemplateName', 'Salesforce API');
        bodyMap.put('loginId', 'Salesforce_API');
        bodyMap.put('shipmentType', 'Current');
        String body = JSON.serialize(bodyMap);        
       
        
        request.setMethod('GET');
        request.setTimeout(intTimeoutValue);
        request.setEndpoint(getTokenIntegrationSettings.PMC_DH_EndpointURL__c);
        request.setBody(body);
        request.setHeader('TokenID',token);
        request.setHeader('Content-Type',getTokenIntegrationSettings.PMC_DH_ContentType__c);
      
       
        try{
            response = http.send(request);
            if (response.getStatusCode() == 200) {       
                 
                shipmentDataList = (List<PMC_CPQ_FetchAndStoreData.ShipmentData>) JSON.deserialize(
                    response.getBody(),
                    List<PMC_CPQ_FetchAndStoreData.ShipmentData>.class
                );
                List<PMC_Shipment_Data__c> recordsToInsert = new List<PMC_Shipment_Data__c>();
                for (Integer i=0;i<shipmentDataList.size();i++) {
                     PMC_Shipment_Data__c customObj = new PMC_Shipment_Data__c();
                        customObj.PMC_CPQ_SAPDeliveryID__c = shipmentDataList[i].DELIVERYNUMBER;
                        customObj.PMC_DELIVERYNUMBER__c = shipmentDataList[i].DELIVERYNUMBER;
                        customObj.PMC_EQUIPMENTID__c = shipmentDataList[i].EQUIPMENTID;
                        customObj.PMC_ETA__c = shipmentDataList[i].ETA;
                        customObj.PMC_BOL__c = shipmentDataList[i].BOL;
                        customObj.PMC_BOLNUMBER__c = shipmentDataList[i].BOLNUMBER;
                        string custOrdNumber = shipmentDataList[i].CUSTORDERNO;
                        
                        If(custOrdNumber!=null){
                              customObj.PMC_CUSTORDERNO__c = custOrdNumber.removeStart('00');
                              
                        }else{
                            
                            customObj.PMC_CUSTORDERNO__c = shipmentDataList[i].CUSTORDERNO;
                        }
						customObj.PMC_SHIPMENTNUMBER_CNTORDER__c = shipmentDataList[i].SHIPMENTNUMBER_CNTORDER;
						customObj.PMC_PONUMBER__c = shipmentDataList[i].PONUMBER;
						customObj.PMC_CURRENTCARRIER__c = shipmentDataList[i].CURRENTCARRIER;
						customObj.PMC_DESTINATIONCARRIER__c = shipmentDataList[i].DESTINATIONCARRIER;
						customObj.PMC_FLEETTOWNAME__c = shipmentDataList[i].FLEETTOWNAME;
						customObj.PMC_COMMENTS__c = shipmentDataList[i].COMMENTS;
						customObj.PMC_SIGHTINGLOADOREMPTY__c = shipmentDataList[i].SIGHTINGLOADOREMPTY;
						customObj.PMC_DESTINATIONMM__c = shipmentDataList[i].DESTINATIONMM;
						customObj.PMC_LATESTTRIPSIGHTINGID__c = shipmentDataList[i].LATESTTRIPSIGHTINGID;
						customObj.PMC_LATESTINTERNALCOMMENT__c = shipmentDataList[i].LATESTINTERNALCOMMENT;
						customObj.PMC_SIGHTINGDESTINATION__c = shipmentDataList[i].SIGHTINGDESTINATION;
                        customObj.PMC_CPQ_CurrentCoordinates__latitude__s = shipmentDataList[i].LATITUDE;
                        customObj.PMC_CPQ_CurrentCoordinates__longitude__s = shipmentDataList[i].LONGITUDE;
                        customObj.PMC_CPQ_Shipment_PO__c =shipmentDataList[i].CUSTORDERNO+shipmentDataList[i].EQUIPMENTID;
                        customObj.Name = shipmentDataList[i].CUSTORDERNO;
                        customObj.PMC_Deliveries_Updated__c =FALSE;
                      recordsToInsert.add(customObj);
                  
                }
                PMC_DH_LoggingUtils.createDHTransactionLogs(
                request,
                response,
                getTokenIntegrationSettings.PMC_DH_EndpointURL__c
           );
                 if (!recordsToInsert.isEmpty()) {
                    try {
                        Schema.SObjectField ExtId = PMC_Shipment_Data__c.Fields.PMC_CPQ_Shipment_PO__c;
                        Database.upsert(recordsToInsert,ExtId,false);
                        System.debug('Records inserted successfully: ' + recordsToInsert.size());
                        
                        } catch (DMLException e) {
                             System.debug('Error inserting records: ' + e.getMessage());
                              
                        }
                }
            }
         else {
                System.debug('HTTP Error: ' + response.getStatusCode() + ' - ' + response.getStatus());
                 System.debug('HTTP Error: ' + request + ' - ' + response);
                  PMC_DH_LoggingUtils.createDHTransactionLogs(
                request,
                response,
                getTokenIntegrationSettings.PMC_DH_EndpointURL__c
            );
        }
        }
             catch(PMC_DH_Validation.CustomException ex){
            throw new PMC_DH_Validation.CustomException('Callout Failed');
        }
        catch (Exception ex) {
            throw  new AuraHandledException(ex.getMessage());
        }finally{
            //Database.executeBatch(new PMC_IntellitransShipmentBatchUpdate(), 200);
        }
        
      

    
            
       
    }
}