objects/PMC_ErrorLog__c.object
<CustomObject>
    <fields>
        <fullName>PMC_ClassName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_Message__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PMC_MethodName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_Type__c</fullName>
        <description>Field to store Type of Error.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Apex</fullName>
                </value>
                <value>
                    <fullName>Flow</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Error Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProgramRebateType.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_ProductFamily__c</fullName>
        <description>Captures Product Family to cater towards the SAP integration</description>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_SS_ProductFamilies</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_SS_Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ZRS6</fullName>
                    <label>Blended</label>
                </value>
                <value>
                    <fullName>Cultivar - Performa</fullName>
                </value>
                <value>
                    <fullName>Cultivar - Performa Bio</fullName>
                </value>
                <value>
                    <fullName>Cultivar - Performance</fullName>
                </value>
                <value>
                    <fullName>Cultivar - Volume</fullName>
                </value>
                <value>
                    <fullName>ZRS3</fullName>
                    <label>Growth</label>
                </value>
                <value>
                    <fullName>ZRS1</fullName>
                    <label>Individual</label>
                </value>
                <value>
                    <fullName>ZRS2</fullName>
                    <label>Portfolio</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ProgramRebateTypeBenefit.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_ActualIncentives__c</fullName>
        <description>Stores the Actual Incentives</description>
        <label>Actual Incentives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMC_SS_InvoiceQuantity__c</fullName>
        <description>Captures the Invoice Quantity from a specific Product Family</description>
        <label>Invoice Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PMC_SS_ProductFamily__c</fullName>
        <description>Captures Product Family to cater towards the SAP integration</description>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_SS_ProductFamilies</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RebateProgram.object
<CustomObject>
    <fields>
        <fullName>PMC_SS_SalesAgreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Sales Agreement</description>
        <label>Sales Agreement</label>
        <referenceTo>SalesAgreement</referenceTo>
        <relationshipLabel>Rebate Programs</relationshipLabel>
        <relationshipName>Rebate_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/PMC_SS_ProductFamilies.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ASPIRE</fullName>
    </customValue>
    <customValue>
        <fullName>ATHOS</fullName>
    </customValue>
    <customValue>
        <fullName>BASICA</fullName>
    </customValue>
    <customValue>
        <fullName>BIOSCIENCE</fullName>
    </customValue>
    <customValue>
        <fullName>BLENDS</fullName>
    </customValue>
    <customValue>
        <fullName>BORON</fullName>
    </customValue>
    <customValue>
        <fullName>CO-PRODUCT</fullName>
    </customValue>
    <customValue>
        <fullName>DAP-MAP</fullName>
    </customValue>
    <customValue>
        <fullName>EXCELLEN</fullName>
    </customValue>
    <customValue>
        <fullName>FEED</fullName>
    </customValue>
    <customValue>
        <fullName>FLUOSILIC ACID</fullName>
    </customValue>
    <customValue>
        <fullName>GRAVEL</fullName>
    </customValue>
    <customValue>
        <fullName>GYPSUM</fullName>
    </customValue>
    <customValue>
        <fullName>K-MAG</fullName>
    </customValue>
    <customValue>
        <fullName>LIMESTONE</fullName>
    </customValue>
    <customValue>
        <fullName>LIQUID FERT</fullName>
    </customValue>
    <customValue>
        <fullName>MES</fullName>
    </customValue>
    <customValue>
        <fullName>MES BLENDS</fullName>
    </customValue>
    <customValue>
        <fullName>MICRO</fullName>
    </customValue>
    <customValue>
        <fullName>MKP</fullName>
    </customValue>
    <customValue>
        <fullName>MOP</fullName>
    </customValue>
    <customValue>
        <fullName>MPASTO</fullName>
    </customValue>
    <customValue>
        <fullName>N BLENDS</fullName>
    </customValue>
    <customValue>
        <fullName>NITROGEN</fullName>
    </customValue>
    <customValue>
        <fullName>NPK</fullName>
    </customValue>
    <customValue>
        <fullName>NPK BLENDS</fullName>
    </customValue>
    <customValue>
        <fullName>P BLENDS</fullName>
    </customValue>
    <customValue>
        <fullName>PERFORMA BIO</fullName>
    </customValue>
    <customValue>
        <fullName>PERFORMA BLENDS</fullName>
    </customValue>
    <customValue>
        <fullName>P FERTILIZER</fullName>
    </customValue>
    <masterLabel>Product Families</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/PMC_SS_PopulateInvoiceQtyOnBenefitsBatch.cls
/**
* @description       : Batch Class to populate Invoice Quantity and Actual Incentives of Rebate Type Benefits
* @author            : Aravind Chaganti
* @last modified on  : 03-11-2024
* @last modified by  : Aravind Chaganti
**/
public with sharing class PMC_SS_PopulateInvoiceQtyOnBenefitsBatch implements Database.Batchable<sObject>,Database.stateful {
    private static final String GROWTH_TYPE = 'ZRS3'; //'Growth';
    private Integer intFailureRecordCount = 0 ;
    private final String strErrorMessage = 'Actual Quantity on Sales Agreement Product Schedules were not updated';
    /**
	* @description Start method of batchable
    * @param objBC
    * @return  Database.QueryLocator
  */
    public Database.QueryLocator start(Database.BatchableContext objBC){
        /*String query;
        if(!Test.isRunningTest()){
            query = 'Select AccountId,Id FROM SalesAgreement WHERE Status = \'Activated\'';
          }else{
            query = 'Select AccountId,Id FROM SalesAgreement Status = \'Activated\' LIMIT 1'; 
        }*/
        return Database.getQueryLocator([SELECT Id, AccountId,Name FROM SalesAgreement WHERE Status = 'Activated' WITH SECURITY_ENFORCED]);
    }
    
    /**
    * @description execute method of batchable
    * @param objBC
    * @param lstSalesAgreement
    */    
    public void execute(Database.BatchableContext objBC, List<SalesAgreement> lstSalesAgreement)
    {
        Database.SaveResult[] lstUpdationResult;
        List<RebateProgram>lstRebatePrograms=new List<RebateProgram>();
        List<ProgramRebateTypeBenefit> lstProgramRebateTypeBenefits=new List<ProgramRebateTypeBenefit>();
        List<ProgramRebateTypeBenefit> lstProgramRebateTypeBenefitsUpdate=new List<ProgramRebateTypeBenefit>();
        lstRebatePrograms=[SELECT ID,StartDate,EndDate,Status,PMC_SS_SalesAgreement__c FROM RebateProgram WHERE Status='Active' AND PMC_SS_SalesAgreement__c!=null AND PMC_SS_SalesAgreement__c IN:lstSalesAgreement ORDER BY PMC_SS_SalesAgreement__c];
        lstProgramRebateTypeBenefits=[SELECT Id,BenefitValue,MaximumQualifyingValue,MinimumQualifyingValue,PMC_SS_ProductFamily__c,ProgramRebateType.PMC_SS_Type__c,ProgramRebateType.RebateProgram.PMC_SS_SalesAgreement__c,ProgramRebateType.RebateProgram.StartDate,ProgramRebateType.RebateProgram.EndDate FROM ProgramRebateTypeBenefit WHERE PMC_SS_ProductFamily__c!=null AND ProgramRebateType.RebateProgramId=:lstRebatePrograms ORDER BY ProgramRebateType.RebateProgramId];
        if(!lstProgramRebateTypeBenefits.isEmpty()){
            for(ProgramRebateTypeBenefit prtypeBenefit:lstProgramRebateTypeBenefits){
                Map<String,Integer> mapProductFamilyInvoiceQty=getInvoiceQtyFromSchedules(prtypeBenefit.ProgramRebateType.RebateProgram.PMC_SS_SalesAgreement__c,prtypeBenefit.ProgramRebateType.RebateProgram.StartDate,prtypeBenefit.ProgramRebateType.RebateProgram.EndDate);
                Integer invoiceQtyValue=mapProductFamilyInvoiceQty!=null?mapProductFamilyInvoiceQty.get(prtypeBenefit.PMC_SS_ProductFamily__c):null;
                //prtypeBenefit.PMC_SS_InvoiceQuantity__c=(prtypeBenefit.MaximumQualifyingValue!=0 && invoiceQtyValue>=prtypeBenefit.MinimumQualifyingValue && invoiceQtyValue<=prtypeBenefit.MaximumQualifyingValue)||(prtypeBenefit.MaximumQualifyingValue==null && invoiceQtyValue>= prtypeBenefit.MinimumQualifyingValue)?invoiceQtyValue:null;
                prtypeBenefit.PMC_SS_InvoiceQuantity__c=getInvoiceQuantity(prtypeBenefit,invoiceQtyValue);
                prtypeBenefit.PMC_SS_ActualIncentives__c=getIncentives(prtypeBenefit,invoiceQtyValue);
                lstProgramRebateTypeBenefitsUpdate.add(prtypeBenefit);
            }
            
            lstUpdationResult=Database.Update(lstProgramRebateTypeBenefitsUpdate,false); 
            for(Database.SaveResult updationResult: lstUpdationResult){
                if(!updationResult.isSuccess()){
                    intFailureRecordCount++;
                }
            }
        }
   	}
    
    /**
   * @description finish method of batchable
   * @param salesAgreementId
   * @param rebateProgramStartDate
   * @param rebateProgramEndDate
   * @return mapProductFamilyInvoiceQuantity
  */    
    public static Map<String,Integer> getInvoiceQtyFromSchedules(Id salesAgreementId,Date rebateProgramStartDate, Date rebateProgramEndDate){
        Map<String,Integer>mapProductFamilyInvoiceQuantity=new Map<String,Integer>();
        List<SalesAgreementProductSchedule>lstSalesAgreementProductSchedules = new List<SalesAgreementProductSchedule>();
        lstSalesAgreementProductSchedules =[SELECT SalesAgreementProductId,ActualQuantity,SalesAgreementProduct.Product.PMC_CPQ_ProductFamily__c 
                     FROM SalesAgreementProductSchedule
                     WHERE SalesAgreementProduct.SalesAgreementId=:salesAgreementId
                     AND SalesAgreementProduct.Product.PMC_CPQ_ProductFamily__c != NULL
                     AND ((StartDate >= :rebateProgramStartDate AND EndDate <= :rebateProgramEndDate)
                     OR (StartDate < :rebateProgramStartDate AND EndDate > :rebateProgramStartDate)
                     OR (StartDate < :rebateProgramEndDate AND EndDate > :rebateProgramEndDate))];
        for(SalesAgreementProductSchedule saps:lstSalesAgreementProductSchedules){
            String productFamily=saps.SalesAgreementProduct.Product.PMC_CPQ_ProductFamily__c;
            if(!mapProductFamilyInvoiceQuantity.containsKey(productFamily.toUpperCase())){
                mapProductFamilyInvoiceQuantity.put(productFamily.toUpperCase(),saps.ActualQuantity);
            }
            else{
                Integer totalPlannedQuantity=mapProductFamilyInvoiceQuantity.get(productFamily.toUpperCase())+saps.ActualQuantity;
                mapProductFamilyInvoiceQuantity.put(productFamily.toUpperCase(),totalPlannedQuantity);
            }     
        }
        return mapProductFamilyInvoiceQuantity;
    }
    
     /**
   * @description To calculate incentives depending on Program Rebate Type
   * @param prtb
   * @param invoiceQtyValue
   * @return incentive
  */    
    public static Decimal getIncentives(ProgramRebateTypeBenefit prtb,Integer invoiceQtyValue){
        Decimal incentive=0;
        if(prtb.ProgramRebateType.PMC_SS_Type__c!=GROWTH_TYPE){
            incentive=(prtb.MaximumQualifyingValue!=0 && invoiceQtyValue>=prtb.MinimumQualifyingValue && invoiceQtyValue<=prtb.MaximumQualifyingValue)||(prtb.MaximumQualifyingValue==null && invoiceQtyValue>= prtb.MinimumQualifyingValue)?invoiceQtyValue*prtb.BenefitValue:null;
        }
        else if (prtb.ProgramRebateType.PMC_SS_Type__c==GROWTH_TYPE){
            incentive=(invoiceQtyValue>= prtb.MinimumQualifyingValue)?(invoiceQtyValue-prtb.MinimumQualifyingValue)*prtb.BenefitValue:null;
        }
        return incentive;
    }
    
     /**
    * @description finish method of batchable
    * @param prtypeBenefit
    * @param invoiceQtyValue
    * @return Decimal - Return the Invoice Quantity
    */    
    public static Decimal getInvoiceQuantity(ProgramRebateTypeBenefit prtypeBenefit,Integer invoiceQtyValue){
        
        return (prtypeBenefit.MaximumQualifyingValue!=0 && invoiceQtyValue>=prtypeBenefit.MinimumQualifyingValue && invoiceQtyValue<=prtypeBenefit.MaximumQualifyingValue)||(prtypeBenefit.MaximumQualifyingValue==null && invoiceQtyValue>= prtypeBenefit.MinimumQualifyingValue)?invoiceQtyValue:null;
        
    }
    
    /**
    * @description finish method of batchable
    * @param objBC
    */    
   public void finish(Database.BatchableContext objBC){
     PMC_ErrorLog__c objErrorLog;
       if (Test.isRunningTest()){
             intFailureRecordCount = 1;
        }
        if(intFailureRecordCount != 0 ) {
            objErrorLog = new PMC_ErrorLog__c();
        	objErrorLog.PMC_Message__c = intFailureRecordCount + strErrorMessage;
            objErrorLog.PMC_Type__c = 'Apex';
        	objErrorLog.PMC_MethodName__c = 'finish';
        	objErrorLog.PMC_ClassName__c = PMC_SS_PopulateInvoiceQtyOnBenefitsBatch.class.getName();
        	Database.insert(objErrorLog, false);
   	}
   }
}