objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_BusinessApplication__c</fullName>
        <label>Business Application</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Water Treatment</fullName>
                </value>
                <value>
                    <fullName>Crop Nutrition</fullName>
                </value>
                <value>
                    <fullName>Animal Nutrition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_GranularType__c</fullName>
        <description>This field captures the Granular Type value for each product record</description>
        <inlineHelpText>This field captures the Granular Type value for each product record</inlineHelpText>
        <label>Granular Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TBD</fullName>
                </value>
                <value>
                    <fullName>Granular</fullName>
                </value>
                <value>
                    <fullName>Fine</fullName>
                </value>
                <value>
                    <fullName>Premium</fullName>
                </value>
                <value>
                    <fullName>Powder</fullName>
                </value>
                <value>
                    <fullName>Pellets</fullName>
                </value>
                <value>
                    <fullName>Coarse</fullName>
                </value>
                <value>
                    <fullName>Rock</fullName>
                </value>
                <value>
                    <fullName>Wet Rock</fullName>
                </value>
                <value>
                    <fullName>Liquid</fullName>
                </value>
                <value>
                    <fullName>Microgranulated</fullName>
                </value>
                <value>
                    <fullName>Farelado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ProductClassification__c</fullName>
        <description>This field captures the product classification</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field captures the product classification</inlineHelpText>
        <label>Product Classification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_DH_CropType__c</fullName>
        <label>Crop Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cotton</fullName>
                </value>
                <value>
                    <fullName>Potato</fullName>
                </value>
                <value>
                    <fullName>Sugarcane</fullName>
                </value>
                <value>
                    <fullName>Rice</fullName>
                </value>
                <value>
                    <fullName>Corn (Winter)</fullName>
                </value>
                <value>
                    <fullName>Coffee</fullName>
                </value>
                <value>
                    <fullName>Corn (Summer)</fullName>
                </value>
                <value>
                    <fullName>HF</fullName>
                </value>
                <value>
                    <fullName>Soy</fullName>
                </value>
                <value>
                    <fullName>Beans</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Citrus</fullName>
                </value>
                <value>
                    <fullName>Pasture</fullName>
                </value>
                <value>
                    <fullName>Wheat</fullName>
                </value>
                <value>
                    <fullName>Reforestation</fullName>
                </value>
                <value>
                    <fullName>Alfalfa</fullName>
                </value>
                <value>
                    <fullName>Artichoke</fullName>
                </value>
                <value>
                    <fullName>Banana</fullName>
                </value>
                <value>
                    <fullName>Barley</fullName>
                </value>
                <value>
                    <fullName>Bean</fullName>
                </value>
                <value>
                    <fullName>Beans Safrinha</fullName>
                </value>
                <value>
                    <fullName>Cane</fullName>
                </value>
                <value>
                    <fullName>Carrot</fullName>
                </value>
                <value>
                    <fullName>Cassava</fullName>
                </value>
                <value>
                    <fullName>Castor bean</fullName>
                </value>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Coconut</fullName>
                </value>
                <value>
                    <fullName>Coffee-Irrigant</fullName>
                </value>
                <value>
                    <fullName>Corn</fullName>
                </value>
                <value>
                    <fullName>Corn Safrinha</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_DH_Micronutrients__c</fullName>
        <description>This field was created as part of story to handle/manage value for Micronutrient</description>
        <label>Micronutrient</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Boron</fullName>
                </value>
                <value>
                    <fullName>Chlorine</fullName>
                </value>
                <value>
                    <fullName>Cobalt</fullName>
                </value>
                <value>
                    <fullName>Copper</fullName>
                </value>
                <value>
                    <fullName>Iron</fullName>
                </value>
                <value>
                    <fullName>Manganese</fullName>
                </value>
                <value>
                    <fullName>Molybdenum</fullName>
                </value>
                <value>
                    <fullName>Silicone</fullName>
                </value>
                <value>
                    <fullName>Zinc</fullName>
                </value>
                <value>
                    <fullName>Calcium</fullName>
                </value>
                <value>
                    <fullName>Magnesium</fullName>
                </value>
                <value>
                    <fullName>Sulfur</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>PMC_CPQ_PrimaryBusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PMC_CPQ_SalesRegion__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_QuoteBusinessType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SalesArea__c</fullName>
        <description>The Sales Areas associated with the user from which the record type and product will be configured.</description>
        <label>Sales Area</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMC_CPQ_SalesAreaUser</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_SalesRegion__c</fullName>
        <label>Sales Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/PMC_CPQ_QuoteBusinessType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Feed</fullName>
    </customValue>
    <customValue>
        <fullName>Fertilizer</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial</fullName>
    </customValue>
    <customValue>
        <fullName>Raw Material</fullName>
    </customValue>
    <customValue>
        <fullName>Co-Products</fullName>
    </customValue>
    <customValue>
        <fullName>B2C - Fertilizer</fullName>
    </customValue>
    <customValue>
        <fullName>B2B - Feed</fullName>
    </customValue>
    <customValue>
        <fullName>B2B - Fertilizer</fullName>
    </customValue>
    <customValue>
        <fullName>B2B - Specialties</fullName>
    </customValue>
    <customValue>
        <fullName>B2C - Paraguay</fullName>
    </customValue>
    <customValue>
        <fullName>B2B - Potash</fullName>
    </customValue>
    <customValue>
        <fullName>International</fullName>
    </customValue>
    <masterLabel>Quote Business Type</masterLabel>
</GlobalValueSet>

classes/PMC_DH_ProductManagementClassTest.cls
@IsTest
public with Sharing class PMC_DH_ProductManagementClassTest {
    
    @testSetup  static void setup()
    {
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Digital Hub Product Merchandiser' LIMIT 1];
        
        User testUser = new User(
                FederationIdentifier = 'emailtesting10101x@gmail.com',
                MobilePhone = '+1 9876543210',
                FirstName = 'DemoUserRequest',
                LastName = 'Bush',
                Email = 'demouser@test.com',
                Username = 'demouser@test.com.testuser',
                //UserRole = role,
                Alias = 'abctest',
                isActive = true,
                TimeZoneSidKey = 'America/New_York',
                LocaleSidKey = 'en_US',
                ProfileId = profile.Id,
                PMC_CPQ_SalesRegion__c = 'North America',
                PMC_CPQ_PrimaryBusinessType__c = 'Feed',
                //PMC_CPQ_SalesArea__c = 'Mosaic Fertilizer Export Common',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                CurrencyIsoCode = 'USD',
                Country='United States'
            );
            if(Schema.sObjectType.User.isCreateable()){
            insert testUser;
            }
        
        User userR=[SELECT id FROM User WHERE Email = 'demouser@test.com' limit 1];
        
          System.runAs(userR)
        {
            Product2 prod = PMC_DH_TestDataFactoryClass.createProduct();
            prod.PMC_DH_CropType__c='Cotton';
            insert prod;
        }
    }
    
    @isTest
    public static void testProductData(){
        Product2 objProduct = [SELECT Id, PMC_CPQ_ProductClassification__c, PMC_DH_CropType__c, PMC_CPQ_GranularType__c, PMC_CPQ_BusinessApplication__c,PMC_DH_Micronutrients__c  FROM Product2 LIMIT 1];
        PMC_DH_ProductManagementClass.PMC_DH_ProdcutData objProDataWrapper = new PMC_DH_ProductManagementClass.PMC_DH_ProdcutData();
        objProDataWrapper.strProductId = objProduct.Id;
        objProDataWrapper.strProductClassification = objProduct.PMC_CPQ_ProductClassification__c;
        objProDataWrapper.strCropType = objProduct.PMC_DH_CropType__c ;
        objProDataWrapper.strGranuleType = objProduct.PMC_CPQ_GranularType__c;
        objProDataWrapper.strBusinessApplication = objProduct.PMC_CPQ_BusinessApplication__c;
        objProDataWrapper.strMicronutrient = objProduct.PMC_DH_Micronutrients__c;
        User userR=[SELECT id FROM User WHERE Email = 'demouser@test.com' limit 1];
        
          System.runAs(userR)
        {
            PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper  result = new PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper ();
            result = PMC_DH_ProductManagementClass.updateProdutDetails(objProDataWrapper);
            System.assertEquals(result.strStatusCode , '000', 'Failure');
            
        }
    }
    
    @isTest
    public static void testProductDataException(){
        Product2 objProduct = [SELECT Id, PMC_CPQ_ProductClassification__c, PMC_DH_CropType__c, PMC_CPQ_GranularType__c, PMC_CPQ_BusinessApplication__c, PMC_DH_Micronutrients__c FROM Product2 LIMIT 1]; 
        PMC_DH_ProductManagementClass.PMC_DH_ProdcutData objProDataWrapper = new PMC_DH_ProductManagementClass.PMC_DH_ProdcutData();
        objProDataWrapper.strProductId = 'test' + objProduct.Id ;
        objProDataWrapper.strProductClassification = objProduct.PMC_CPQ_ProductClassification__c;
        objProDataWrapper.strCropType = objProduct.PMC_DH_CropType__c ;
        objProDataWrapper.strGranuleType = objProduct.PMC_CPQ_GranularType__c;
        objProDataWrapper.strBusinessApplication = objProduct.PMC_CPQ_BusinessApplication__c;
        objProDataWrapper.strMicronutrient = objProduct.PMC_DH_Micronutrients__c;
        User userR=[SELECT id FROM User WHERE Email = 'demouser@test.com' limit 1];
        
          System.runAs(userR)
        {
            PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper  result = new PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper ();
            result = PMC_DH_ProductManagementClass.updateProdutDetails(objProDataWrapper);
            System.assertEquals(result.strStatusCode , '100', 'Failure');
        }
    }
        
}