objects/sbaa__Approval__c.object
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <fields>
        <fullName>sbaa__Status__c</fullName>
        <description>Status of this approval.</description>
        <inlineHelpText>Status of this approval.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                    <default>true</default>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MassApprovalVFController.cls
public with sharing class MassApprovalVFController {
    public List<SBAA__Approval__c> approvals { get; set; }
    public Boolean processing { get; set; }
    public Boolean redirect { get; set; }

    public MassApprovalVFController(ApexPages.StandardSetController controller) {
        this.approvals = (List<SBAA__Approval__c>) controller.getSelected();
        this.processing = true;
        this.redirect = false;

        approveSelected();
    }

    public PageReference approveSelected() {
        for (SBAA__Approval__c app : approvals) {
            app.sbaa__Status__c = 'Approved';
        }

        update approvals;
        processing = false;
        redirect = true; // ativa o redirecionamento

        return null;
    }

    public String getRedirectUrl() {
        // Exemplo: redireciona para a list view padrão do objeto
        return URL.getOrgDomainUrl().toExternalForm() + '/lightning/o/SBAA__Approval__c/list?filterName=Recent';
    }
}