objects/sbaa__Approval__c.object
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Approvals (Quote)</relationshipLabel>
        <relationshipName>Approvals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sbaa__ApprovalStep__c</fullName>
        <description>Step (level) at which this approval is required.</description>
        <inlineHelpText>Step (level) at which this approval is required.</inlineHelpText>
        <label>Approval Step</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sbaa__Approver__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the Approver associated with this Approval.</description>
        <inlineHelpText>Lookup to the Approver associated with this Approval.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>sbaa__Approver__c</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sbaa__RecordField__c</fullName>
        <description>API Name of the Approval field looking up to the record being approved</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>API Name of the Approval field looking up to the record being approved</inlineHelpText>
        <label>Record Field</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sbaa__Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Approval rule that generated this approval.</description>
        <inlineHelpText>Approval rule that generated this approval.</inlineHelpText>
        <label>Rule</label>
        <referenceTo>sbaa__ApprovalRule__c</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sbaa__ApprovalRule__c.object
<CustomObject>
    <customHelpPage>sbaa__ApprovalRuleHelp</customHelpPage>
    <description>This is the Rule associated with an Approval.</description>
    <fields>
        <fullName>sbaa__ApprovalStep__c</fullName>
        <description>Step at which this Approval Rule is evaluated</description>
        <inlineHelpText>Step at which this Approval Rule is evaluated</inlineHelpText>
        <label>Approval Step</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sbaa__ApprovalTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Email Template associated with approval for this Rule</description>
        <inlineHelpText>Lookup to the Email Template associated with approval for this Rule</inlineHelpText>
        <label>Approval Template</label>
        <referenceTo>sbaa__EmailTemplate__c</referenceTo>
        <relationshipLabel>Approved Approval Rules</relationshipLabel>
        <relationshipName>ApprovedApprovalRules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sbaa__Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Approver associated with this Approval Rule.</description>
        <inlineHelpText>Approver associated with this Approval Rule.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>sbaa__Approver__c</referenceTo>
        <relationshipLabel>Approval Rules</relationshipLabel>
        <relationshipName>ApprovalRules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sbaa__TargetObject__c</fullName>
        <description>API Name of the object to which this Rule applies</description>
        <inlineHelpText>API Name of the object to which this Rule applies</inlineHelpText>
        <label>Target Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>SBQQ__Quote__c</fullName>
                </value>
                <value>
                    <fullName>SBQQ__QuoteLine__c</fullName>
                </value>
                <value>
                    <fullName>Order_Line_Approval__c</fullName>
                </value>
                <value>
                    <fullName>OrderItem</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval Rule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Rules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/sbaa__Approver__c.object
<CustomObject>
    <customHelpPage>sbaa__ApproverHelp</customHelpPage>
    <description>Approvers are associated with the Approval Rule, driving what occurs on the Approval itself.</description>
    <fields>
        <fullName>sbaa__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If Approver is a single User, lookup to that User</description>
        <inlineHelpText>If Approver is a single User, lookup to that User</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approver</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/sbaa__EmailTemplate__c.object
<CustomObject>
    <customHelpPage>sbaa__EmailTemplateHelp</customHelpPage>
    <fields>
        <fullName>sbaa__TemplateId__c</fullName>
        <description>Salesforce Email Template ID</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Salesforce Email Template ID</inlineHelpText>
        <label>Template Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Email Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Email Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PMC_CPQ_ApprovalGroupEmailSenderTest.cls
/*
* This class is the test class for PMC_CPQ_ApprovalGroupEmailSenderClass.
* @author Jeyanthi Muthaiah
* @storynumber GDASF-10718 S14
*/
@isTest(seeAllData=false)
public with sharing class PMC_CPQ_ApprovalGroupEmailSenderTest  {
    
 /**
    * @description This Method will be used to setup the test data for the test class execution.
   */
     @testsetup
    private static void setup() {
        
        List<String>lstProfileNames = New List<String>{'System Administrator','Sales User'};
        List<userRole> userRoleName= [SELECT Id FROM userRole WHERE Name = 'Service Director'];
        List<String>lstPermissionNames = New List<String>{'PMC_Administrator_Permission_Set_Group','PMC_SLS_Permission_Set_Group'};
        Map<String,Id>mapOfProfiles = PMC_TestUtilityClass.getProfiles(lstProfileNames);
        Map<String,PermissionSetGroup>mapOfPermissionGrp = PMC_TestUtilityClass.getPemissionsetGroups(lstPermissionNames);
        Integer intuserCount =0;
        User objSystemAdminUser;  
        User objSalesUser;
        List<User> lstUser = PMC_TestUtilityClass.createUser(2);
            for(User objUser : lstUser) {
                If(intuserCount==0){
                   objUser.LastName = 'Admin User Test';
                   objUser.ProfileId = mapOfProfiles.get('System Administrator'); 
                   objUser.FederationIdentifier = objUser.Username + 'Admin';
                   objUser.UserRoleId=userRoleName[0].id;
                }else if(intuserCount==1){
                    objUser.LastName = 'Sales User Test';
                    objUser.ProfileId = mapOfProfiles.get('Sales User'); 
                   objUser.FederationIdentifier = objUser.Username + 'Sales';
                }
                objUser.isActive = true;                
                objUser.MobilePhone = '1234567890';
                objUser.UserPermissionsKnowledgeUser =true;
                objUser.LanguageLocaleKey = 'en_US';
                intuserCount = intuserCount + 1;
            }            
            insert lstUser;
            objSystemAdminUser = lstUser[0];
            objSalesUser = lstUser[1];
        PMC_TestUtilityClass.assignPermissionSetGroupToUsers(new List<User>{objSystemAdminUser}, mapOfPermissionGrp.get('PMC_Administrator_Permission_Set_Group'));
        PMC_TestUtilityClass.assignPermissionSetGroupToUsers(new List<User>{objSalesUser}, mapOfPermissionGrp.get('PMC_SLS_Permission_Set_Group'));    
        }
    /* 
* This method will be used to cover qLines and sendApprovalGroupEmail method of the PMC_CPQ_ApprovalGroupEmailSenderClass.
* 
*/ 
  @isTest
    public static void testSendApprovalGroupEmail() {
        Test.startTest();
        User testUser = [SELECT Id, Name FROM User Where LastName='Admin User Test' WITH SECURITY_ENFORCED LIMIT 1];
        System.runAs(testUser) {
       
            //Create Approver
            sbaa__Approver__c testApprover = new sbaa__Approver__c(
                Name = testUser.Name,
                sbaa__User__c= testUser.id
            );
            
            insert testApprover;
            
            //Email Tempalte 
            EmailTemplate validEmailTemplate = new EmailTemplate(
                isActive = true,
                Name = 'GroupEmailTemp',
                DeveloperName = 'Group_Email_Temp',
                TemplateType = 'text',
                FolderId = UserInfo.getUserId()
            );
            insert validEmailTemplate;        
            
            //Insert Created Email Templte id to the template
            sbaa__EmailTemplate__c testEmailTemplate = new sbaa__EmailTemplate__c(
                Name = 'TestTemplate',
                sbaa__TemplateId__c=validEmailTemplate.id
            );
            insert testEmailTemplate;
            
            // Craete Approval Rule
            sbaa__ApprovalRule__c testApprovalRule = new sbaa__ApprovalRule__c(
                Name='TestApprovalRule',
                sbaa__ApprovalTemplate__c=testEmailTemplate.id,
                sbaa__TargetObject__c='SBQQ__Quote__c'
                
            );
            insert testApprovalRule;
            
            //Create Approval Record  
            sbaa__Approval__c testApproval = new sbaa__Approval__c(
                sbaa__Approver__c = testApprover.Id,
                sbaa__ApprovalStep__c=1,
                sbaa__RecordField__c='Quote__c',
                sbaa__Rule__c=testApprovalRule.id
                
            );
            insert testApproval;
            
            
            // Call the method under test
            Boolean testRunning=true;
            List<Id> recordIds = new List<Id>{ testApproval.Id };
                
            PMC_CPQ_ApprovalGroupEmailSenderClass.testRunning = true;
            PMC_CPQ_ApprovalGroupEmailSenderClass.sendApprovalGroupEmail(recordIds);
            
            List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            
            email.setTemplateId(testEmailTemplate.id);
            if(!TestRunning){
                email.setWhatId( testApproval.Id );
                
            }           
            email.setTargetObjectId(testUser.id);
            email.setSaveAsActivity(false);
            emailMessages.add(email); 
            System.assertEquals(1, emailMessages.size(), 'Expected 1 email to be sent');  
        }
        Test.stopTest();
    }
}