objects/sbaa__Approval__c.object
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <fields>
        <fullName>sbaa__Approver__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the Approver associated with this Approval.</description>
        <inlineHelpText>Lookup to the Approver associated with this Approval.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>sbaa__Approver__c</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sbaa__Approver__c.object
<CustomObject>
    <customHelpPage>sbaa__ApproverHelp</customHelpPage>
    <description>Approvers are associated with the Approval Rule, driving what occurs on the Approval itself.</description>
    <fields>
        <fullName>sbaa__GroupId__c</fullName>
        <description>If Approver is a Group instead of a single User, populate with the Group ID</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>If Approver is a Group instead of a single User, populate with the Group ID</inlineHelpText>
        <label>Group ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Approver</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PMC_CPQ_GroupEmailClass.cls
public without sharing class PMC_CPQ_GroupEmailClass {
    @InvocableMethod(label='send Approval Group Email2')
    public static void sendApprovalGroupEmail(List<Id> recordid) {
        // Query for the approval group members
        String groupid;
        List<Id> groupIDList = new List<Id>();
        List<sbaa__Approval__c> Groupids = [SELECT id,sbaa__Approver__r.sbaa__GroupId__c from sbaa__Approval__c WHERE id IN: recordid limit 1];
        
        if(Groupids[0].sbaa__Approver__r.sbaa__GroupId__c != null){
            groupid = Groupids[0].sbaa__Approver__r.sbaa__GroupId__c;
            groupIDList.add(groupid);
        }
        List<GroupMember> groupMembers = [SELECT GroupId,UserOrGroupId FROM GroupMember WHERE GroupId IN: groupIDList];
        
        List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();
             
        // Iterate through the group members and send an email to each
        for (GroupMember groupMember : groupMembers) {
            
            Messaging.SingleEmailMessage email = Messaging.renderStoredEmailTemplate('00XDT000003qjWO',groupMember.UserOrGroupId , recordid[0]);
            
      		email.setTargetObjectId(groupMember.UserOrGroupId);
			email.setSaveAsActivity(false);
            emailMessages.add(email);
            
            

        }
           // Send the emails
        Messaging.sendEmail(emailMessages);
    }
}