objects/sbaa__Approval__c.object
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <fields>
        <fullName>sbaa__CommentsLong__c</fullName>
        <description>Approver&apos;s Comments</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Approver&apos;s Comments</inlineHelpText>
        <label>Comments</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CommentExtension.cls
public class CommentExtension {
    public String comment { get; set; }
    private sbaa__Approval__c approvalRequest;

    public CommentExtension(ApexPages.StandardController controller) {
        approvalRequest = (sbaa__Approval__c)controller.getRecord();
    }

     public void submitComment() {
        approvalRequest.sbaa__CommentsLong__c = comment;
        update approvalRequest;
    }
        // Additional logic or actions after submitting the comment can be added here
    
}