objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <description>This field is created to enable Quote Line object for Advance Approval</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QuoteLineExtControllerTests.cls
@isTest
private class QuoteLineExtControllerTests {
    
    testMethod static void testSubmit() {
        SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c();
        insert quoteLine;
        
        Test.startTest();
        QuoteLineExtController con = new QuoteLineExtController(new ApexPages.StandardController(quoteLine));
        con.onSubmit();
        quoteLine = [SELECT ApprovalStatus__c FROM SBQQ__QuoteLine__c WHERE Id = :quoteLine.Id LIMIT 1];
        Test.stopTest();
        
        System.assertEquals('Approved', quoteLine.ApprovalStatus__c);
    }
    
    testMethod static void testRecall() {
        SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c();
        insert quoteLine;
        
        Test.startTest();
        QuoteLineExtController con = new QuoteLineExtController(new ApexPages.StandardController(quoteLine));
        con.onRecall();
        quoteLine = [SELECT ApprovalStatus__c FROM SBQQ__QuoteLine__c WHERE Id = :quoteLine.Id LIMIT 1];
        Test.stopTest();
        
        System.assertEquals('Recalled', quoteLine.ApprovalStatus__c);
    }
}