objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CPQ_CustomCreatedDate__c</fullName>
        <description>This field is to use when a custom created date is required.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Custom Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ExpirationDate__c</fullName>
        <description>This field is to store Expiration date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ExpirationTime__c</fullName>
        <description>This field is to store Expiration Time</description>
        <label>Expiration Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_ExpiresOn__c</fullName>
        <description>This field captures the Date and Time this quote will be expired</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Indicates the Date and Time this Quote will expire</inlineHelpText>
        <label>Expiration Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PMC_CPQ_RequestedExpirationDateTime__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Requested Expiration Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SubmittedUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to enable Advanced Approvals for quote object</description>
        <label>Submitted User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PMC_CPQ_UpdateQuoteForExpirationHelper.cls
/**
* @description This class is the helper class of PMC_CPQ_UpdateQuoteForExpirationClass
* @author Ridhu Varshini M
* @storynumber GPT-42302
*/
public with sharing class PMC_CPQ_UpdateQuoteForExpirationHelper {
    /**
* @description This method is to assign Expiration date and expiration time when requested expiration is populated.
* @param lstQuotes - list of quotes.
*/    
    @TestVisible private static Boolean testExceptionRequestedExpiration = false;
    @TestVisible private static Boolean testExceptionCalculateDateTime= false;
    public static void updateExpirationDateAndTimeOnRequestedExpiration(List<SBQQ__Quote__c> lstQuotes){
        
        DateTime reqExp = lstQuotes.get(0).PMC_CPQ_RequestedExpirationDateTime__c; 
        lstQuotes.get(0).PMC_CPQ_ExpirationDate__c = null;
        lstQuotes.get(0).PMC_CPQ_ExpirationTime__c = null;
        lstQuotes.get(0).PMC_CPQ_ExpiresOn__c = null;
        String userTZ = [select TimeZoneSidKey from User where Id =: lstQuotes.get(0).SubmittedUser__c ][0].TimeZoneSidKey;
        Timezone tz = Timezone.getTimeZone(userTZ);
        Integer offset = tz.getOffset(reqExp);
        DateTime amLocal =  reqExp.addSeconds(offset/1000);
        lstQuotes.get(0).PMC_CPQ_ExpirationDate__c = amLocal.dateGmt();
        lstQuotes.get(0).PMC_CPQ_ExpirationTime__c = amLocal.timeGmt();
        lstQuotes.get(0).PMC_CPQ_ExpiresOn__c = reqExp;
        try{
            exceptionCheckRequestedExpiration();
            if(Schema.sObjectType.SBQQ__Quote__c.isAccessible() 
               && Schema.sObjectType.SBQQ__Quote__c.isUpdateable()
               && Schema.SObjectType.SBQQ__Quote__c.fields.PMC_CPQ_ExpiresOn__c.isUpdateable()
               && Schema.SObjectType.SBQQ__Quote__c.fields.PMC_CPQ_ExpirationDate__c.isUpdateable()
               && Schema.SObjectType.SBQQ__Quote__c.fields.PMC_CPQ_ExpirationTime__c.isUpdateable())
            {
                update lstQuotes;
            }
        }
        catch(DmlException objException){
            PMC_ErrorLogClass.processException(objException);
        }
    }
      /**
* @description This method is to check exception triggered from test class to cover DML Exception on updateExpirationDateAndTimeOnRequestedExpiration method
*/
    private static void exceptionCheckRequestedExpiration(){
        if(testExceptionRequestedExpiration){
            throw new DmlException();
        }
    }
    /**
* @description This method is to calculate date Time for BR quotes and update it
* @param lstQuotes - list of quotes.
* @param intDays - the days to add
* @param timeConsidered - the hour to set
*/
   
    public static void calculateDateTime(List<SBQQ__Quote__c> lstQuotes, Integer intDays, Time timeConsidered){
        try{
            exceptionCheckCalculateDateTime();
            DateTime datTCreatedDate;
            if(test.isRunningTest()){
                datTCreatedDate = lstQuotes.get(0).PMC_CPQ_CustomCreatedDate__c;
            }
            else{
                datTCreatedDate = system.now();
            }
            Date datTRequiredDate = datTCreatedDate.date() + intDays;
            lstQuotes.get(0).PMC_CPQ_ExpiresOn__c = null;
            lstQuotes.get(0).PMC_CPQ_ExpirationDate__c = null;
            lstQuotes.get(0).PMC_CPQ_ExpirationTime__c = null;
            lstQuotes.get(0).PMC_CPQ_ExpirationDate__c = datTRequiredDate;
            lstQuotes.get(0).PMC_CPQ_ExpirationTime__c = timeConsidered;
            DateTime datTConverted = Datetime.newInstanceGmt(lstQuotes.get(0).PMC_CPQ_ExpirationDate__c, lstQuotes.get(0).PMC_CPQ_ExpirationTime__c);
            System.debug('datTConverted' +datTConverted);
            String userTZ = [select TimeZoneSidKey from User where Id =: lstQuotes.get(0).SubmittedUser__c ][0].TimeZoneSidKey;
            System.debug('userTZ' +userTZ);
            Timezone tz = Timezone.getTimeZone(userTZ);
            Integer offset = tz.getOffset(datTConverted);
            System.debug('offset' +offset);
            Integer finalOffset = offset*(-1);
            System.debug('finalOffset' +finalOffset);
            DateTime amLocal =  datTConverted.addSeconds(finalOffset/1000);
            System.debug('amLocal' +amLocal);
            lstQuotes.get(0).PMC_CPQ_ExpiresOn__c = amLocal;
            
            if(Schema.sObjectType.SBQQ__Quote__c.isAccessible() 
               && Schema.sObjectType.SBQQ__Quote__c.isUpdateable()
               && Schema.SObjectType.SBQQ__Quote__c.fields.PMC_CPQ_ExpiresOn__c.isUpdateable()
               && Schema.SObjectType.SBQQ__Quote__c.fields.PMC_CPQ_ExpirationDate__c.isUpdateable()
               && Schema.SObjectType.SBQQ__Quote__c.fields.PMC_CPQ_ExpirationTime__c.isUpdateable())
            {
                update lstQuotes;
            }
        }
        catch(DmlException objException){
            PMC_ErrorLogClass.processException(objException);
        }
    }
     /**
* @description This method is to check exception triggered from testclass to cover DML exception on calculateDateTime method
*/
    private static void exceptionCheckCalculateDateTime(){
        if(testExceptionCalculateDateTime){
                throw new DmlException();
            }
    }
}