objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>PMC_CPQ_ContractStageName__c</fullName>
        <description>This field helps to denote the current stage of the contract document</description>
        <label>Contract Document Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Pending Signature</fullName>
                </value>
                <value>
                    <fullName>Partially Executed</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Accept</fullName>
                    <isActive>false</isActive>
                    <label>Accept</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <isActive>false</isActive>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Pending Signatures</fullName>
                    <isActive>false</isActive>
                    <label>Pending Signatures</label>
                </value>
                <value>
                    <fullName>Signed</fullName>
                    <isActive>false</isActive>
                    <label>Signed</label>
                </value>
                <value>
                    <fullName>hello</fullName>
                    <isActive>false</isActive>
                    <label>hello</label>
                </value>
                <value>
                    <fullName>yfgfgfc</fullName>
                    <isActive>false</isActive>
                    <label>yfgfgfc</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_CPQ_QuoteShortNameDescription__c</fullName>
        <description>Based on the stanadardized Quote description across all quotes</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Quote Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PMC_DH_QuoteReviewEmaillTest.cls
/**
 * @description Test Class for PMC_DH_QuoteReviewEmailController
 * @author hemant giri
 * @since  09-11-2023
 */
@isTest
public with sharing class PMC_DH_QuoteReviewEmaillTest {
    @TestSetup
    static void dataSetup(){
        Account acc=PMC_DH_TestDataFactoryClass.createParentTestAccount();
        //Account shipToAcc=PMC_DH_TestDataFactoryClass.createShipToTestAccount(acc);
        Profile profile = [SELECT Id FROM Profile WHERE Name =: PMC_DH_ConstantClass.PROFILE_NAME LIMIT 1];
        PMC_DH_TestDataFactoryClass.createTestUser(acc.Id,profile.Id);
        
        User user=[SELECT id FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
        String strContactId=[SELECT contactId FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1][0].contactId;
        
        Id lstPermSet2=[select id from PermissionSet where Name ='PMC_DH_CPQ_PermissionSetLicense'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(user.Id,lstPermSet2);
        Id lstPermSet=[select id from PermissionSet where Name ='SteelBrickDHCPQPartnerUser'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(user.Id,lstPermSet);
        Id lstPermSet1=[select id from PermissionSet where Name ='PMC_DH_SuperBuyer'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(user.Id,lstPermSet1);
        Id lstPermSet3=[select id from PermissionSet where Name ='PMC_DH_AccountCRE'][0].id;
        PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(user.Id,lstPermSet3);
        
        PMC_DH_TestDataFactoryClass.createTestWebStore();
        system.runAs(user){
            Test.startTest();
            PMC_DH_TestDataFactoryClass.createShipToTestAccount(acc);
            Product2 prod = PMC_DH_TestDataFactoryClass.createProduct();
            insert prod;
            Opportunity opp=PMC_DH_TestDataFactoryClass.createOpportunity(acc);
            SBQQ__Quote__c testQuote=PMC_DH_TestDataFactoryClass.createQuote(acc,strContactId,opp);
            testQuote.PMC_CPQ_ContractStageName__c='Draft';
            update testquote;
            Schema.Location loc = PMC_DH_TestDataFactoryClass.createLocation();
            PMC_DH_TestDataFactoryClass.createProductLocation(prod, loc);
            PMC_DH_TestDataFactoryClass.creatQuoteLine(testQuote,prod);
            Test.stopTest();
        }
    }


    
    @isTest
    public static void sendEmailforQuoteReviewTest()
    {
        Test.startTest();
        User user=[SELECT id, ContactId, Contact.FirstName, Contact.LastName FROM User WHERE UserName = 'demouser@test.com.testuser' limit 1];
        Id conId = user.ContactId;
        Contact con = [SELECT Id, IndividualId FROM Contact WHERE Id =: conId LIMIT 1];
        //if(con.IndividualId == null){
            Individual ind = PMC_DH_TestDataFactoryClass.createIndividual(user);
            con.IndividualId = ind.Id;
            update con;
            DataUseLegalBasis dulb = new DataUseLegalBasis(Name = 'Quotes');
            insert dulb;
            DataUsePurpose dup = new DataUsePurpose(Name = 'Ready for Review', LegalBasisId = dulb.Id);
            insert dup;
            ContactPointTypeConsent cptc = new ContactPointTypeConsent(ContactPointType = 'Email', 
                                                                       PrivacyConsentStatus = 'OptIn',
                                                                       Name = dup.Name,
                                                                       DataUsePurposeId = dup.Id,
                                                                       PartyId = con.IndividualId);
            insert cptc;
        //} 
        system.runAs(user){
            String strQuoteId=[SELECT ID FROM SBQQ__Quote__c WHERE PMC_CPQ_QuoteShortNameDescription__c='TestDH Quote'][0].ID;
            List<Id> testIds = new List<Id>();
            testIds.add(strQuoteId);
            List<Boolean> result = PMC_DH_QuoteReviewEmailController.sendEmailforQuoteReview(testIds);
            System.assert(result != null, 'Success');
        }
        Test.stopTest();
    }
}